### ISSUE TITLE
[DOCS] [Detections] Clarify usage of field overrides with Threshold Rules

### ISSUE THREAD

**Issue by spong** [elastic/security-docs#1011]
Threshold rules/alerts are unique since the fields from the source events that get copied over to the alert are the fields that are aggregated on. This means that these are the only fields available within the field overrides (Severity/Risk Score/Rule Name) and actions context. 

We call out this behavior for the actions context [here](https://www.elastic.co/guide/en/security/current/rules-ui-create.html#create-threshold-rule):

> If you wish to create an Action based on a threshold rule, **you can obtain values of the fields that were aggregated over** by entering the following:

However we don't mention this for the field overrides. This was recently raised as a potential issue from QA, so perhaps we can add an additional callout for clarifying this behavior for the field overrides as well? Additionally, from the UI/UX perspective we shouldn't let users select fields that aren't available, so I'll open a [Kibana issue](https://github.com/elastic/kibana/issues/111214) for that as well.

Using fields not aggregated over:
<p align="center">
  <img width="400" src="https://user-images.githubusercontent.com/2946766/132024040-27b2acd6-6c21-4596-b825-52ebb6c633f6.png" /><img width="400" src="https://user-images.githubusercontent.com/2946766/132024049-d68d9305-8a83-4a25-8dd1-8da372772e19.png" />
</p>

Using fields aggregated over:
<p align="center">
  <img width="500" src="https://user-images.githubusercontent.com/2946766/132024064-94e1c20c-61eb-4545-8671-ae3c3506e4f7.png" />
</p>

**Comment by joepeeples** [comment]
Merged #1124.
