### ISSUE TITLE
[DOCS] Document which supported Linux OSes support host isolation

### ISSUE THREAD

**Issue by ferullo** [elastic/security-docs#1013]
## Description 

Elastic Endpoint is adding host isolation for 7.15. Host isolation is not supported all Linux distributions. For supported OSes, it  works on
* CentOS/RHEL 8
* Ubuntu 18.04
* Ubuntu 20.04

It is not supported on CentOS/RHEL 7.

@stanek-michal will comment whether AWS Linux 2 is supported.

## Acceptance Test Criteria

N/A

## Notes

No notes

cc @nfritts @softengchick @bradenlpreston @caitlinbetz @kevinlog

**Comment by stanek-michal** [comment]
I tested host isolation with the BC5 release on Amazon Linux 2 and I confirm that it works.

**Comment by jmikell821** [comment]
#1054 merged.
