### ISSUE TITLE
[DOCS] Add more context to indicator match rule restrictions

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#1014]
Topic to update: [here](https://www.elastic.co/guide/en/security/current/detection-engine-overview.html#support-indicator-rules). 

Related issue comment [here](https://github.com/elastic/security-team/issues/1682#issuecomment-911495528). 

Let's expand the text on tightening up search queries to limit unwanted data. 

> Indicator match rules provide a powerful capability to search your security data; however, their queries can consume significant deployment resources. When creating an <<create-indicator-rule, indicator match rule>>, it is recommended to limit queries to a specific time range to avoid results that return more indicators than necessary for the desired rule coverage. For example, entering a query such as `@timestamp > "now-30d"` will return results from the past 30 days only. 

Hi @rylnd if there's anything else we need to add to this blurb here ^ please let us know. Also, please review for accuracy. Thank you!

**Comment by nastasha-solomon** [comment]
Merged #1025.
