### ISSUE TITLE
[DOCS] Clarify multi-tenancy behavior of rules being isolated per space

### ISSUE THREAD

**Issue by spong** [elastic/security-docs#1023]
A support issue came in recently that was asking for clarification around how Rule/Alert data is shared between spaces and if rules could be in one space but managed in another. In looking through the docs it looks like while we mention spaces around [setup](https://www.elastic.co/guide/en/security/current/detections-permissions-section.html) and [rule creation](https://www.elastic.co/guide/en/security/current/rules-ui-create.html), we don't explicitly call out this behavior for rules (but can be deduced for alerts).

Opening this issue to see if it's worth having a section detailing that Rules are isolated per spaces, do not share data between spaces, and perhaps some recommendations around architecting their systems when users want administrators that can view all rules across a system (perhaps a blog post would be best for the latter).

**Comment by jmikell821** [comment]
Hey @spong, agree that we should have a section about isolated spaces in rules. If you or someone from the team can detail the specifics here, we can add it to our docs. I wasn't aware of the limitations surrounding this. 

Also +1 for the blog post, I can bring this up in our content working group meeting, and, on the same wavelength, I'd like to start pulling together a FAQs/Best Practice Guide for rule management. 

Thanks for opening this issue!

**Comment by spong** [comment]
> Hey @spong, agree that we should have a section about isolated spaces in rules. If you or someone from the team can detail the specifics here, we can add it to our docs. I wasn't aware of the limitations surrounding this.

Would be happy to! 🙂 


----

The Security Solution supports the organization of your Detection Rules/Alerts and other Security Entities (SO's mostly) like Cases/Timelines via the [Kibana Spaces feature](https://www.elastic.co/guide/en/kibana/master/xpack-spaces.html). Each Security Entity created within a Kibana Space will only be accessible to other users of that space with the appropriate access privileges as defined in the `Kibana privileges` of their roles..

For example, if you create a `SIEM` space (configuring ES privileges for that space as described in the [setup docs](https://www.elastic.co/guide/en/security/current/detections-permissions-section.html)), and install/enable all the available prepackaged Detection Rules, these rules and any generated Alerts will only be visible when visiting the Security Solution in the `SIEM` space. If you create a new `Endpoint` space, you'll notice no Detection Rules or Alerts are present, and any new Rules created here will be isolated and run independently of those in the `SIEM` space.


cc @MikePaquette @jethr0null as I'm sure they'll have better language for the above 😅

**Comment by MikePaquette** [comment]
Yes, I like this idea for a section clarifying the space implications.  I don't think we've used the terms "security entity"  in this context (although it would be useful to have a term for this), so for now I think we should list them explicitly in this new section.

I like Garrett's writeup, and I've added a few tweaks/modifications to it in the draft below:

The Security Solution supports the organization of your security operations into logical instances via the [Kibana Spaces feature](https://www.elastic.co/guide/en/kibana/master/xpack-spaces.html).  Each Kibana Space represents a logical instance of the security solution in which detection rules, rule exceptions, value lists, alerts, timelines, cases, and Kibana advanced settings, are private to the space, accessible only by users assigned to roles that have privileges to access the space.  Please see the [setup docs](https://www.elastic.co/guide/en/security/current/detections-permissions-section.html) for details about configuring Elasticsearch and Kibana privileges.

For example, if you create a `SOC_prod` space in which you load and activate all the Elastic prebuilt Detection Rules, these rules and any Alerts they generate, will be accessible only when visiting the Security Solution in the `SOC_prod` space.  If you then create a new `SOC_dev` space, you'll notice that no Detection Rules or Alerts are present. Any rules subsequently loaded or created here will be private to the `SOC_dev` space, and will run independently of those in the `SOC_prod` space.

**Special Note about Alerts:**  By default, alerts created by detection rules are stored in Elasticsearch indices under the `.siem-signals-<spacename>-*` index pattern, and may be accessed by any user assigned to a role with privileges to access those Elasticsearch indices.  In our example above, any user with Elasticsearch privileges to access `.siem-signals-SOC_prod-*` will be able to view `SOC_prod` alerts from within Elasticsearch and other Kibana apps such as Discover and Lens.  To ensure that Alert data remains private to the space in which it was created, ensure that the roles to which your security solution users are assigned include Elasticsearch privileges that limit their access to only alerts within their space alerts index.

cc:  @jethronull

**Comment by joepeeples** [comment]
Merged #1072.
