### ISSUE TITLE
[DOCS] Review docs and UI mock-ups for SN app 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#1024]
The Cases team is working on a new Elastic application that’ll improve the ServiceNow connector and will be stored in the ServiceNow store. To get certified by ServiceNow, they’ll need to send ServiceNow their application code and the following documents:

- Scoped Application Installation and Configuration Guide 
- Scoped Application Design Document 
- Scope Application Test Plan 

The certification process takes about 3-5 weeks and the team is trying to get this application into 7.16, so they’d like to start reviewing the docs and UI mock-ups ASAP. 

The GH issue tracking all of this work is https://github.com/elastic/security-team/issues/1454

cc: @cnasikas

**Comment by cnasikas** [comment]
Thank you @nastasha-solomon for opening this issue. The most important document is the Scoped Application Installation and Configuration Guide and this will be public and be seen by our users. If you go to the [ServiceNow Store](https://store.servicenow.com/sn_appstore_store.do) and select an application on the left you will see a sidebar. In the sidebar there is a link called Installation Guide. This will link to our Installation guide. The other documents are for internal use.

**Comment by alexfrancoeur** [comment]
@cnasikas do we also need to update the Elastic documentation? It feels like there are a few steps that are different, and we may also need to call out migration steps.

**Comment by cnasikas** [comment]
Hi @alexfrancoeur! Yes, I think we should add to the documents all changes that will be introduced. Specifically:

1. New connectors user flow (need of the Elastic for ITSM application).
2. Link to our app in the ServiceNow store.
3. Instruction on how to create an integration user (section 4 of the Scoped Application Installation and Configuration Guide document)
4. Update from an old connector to the new connector user flow.
5. Elastic for ITSM application dependencies
