### ISSUE TITLE
[DOCS] Clarify alert de-duplication logic around configured 'additional look-back time'

### ISSUE THREAD

**Issue by spong** [elastic/security-docs#1030]
There was a recent user inquiry with regards to how the Detection Engine manages alert de-duplication and in exploring the docs it doesn't look like we currently mention how duplicates are managed when configuring an `additional look-back time` on a Rule, so this issue is for adding additional details around this functionality. Perhaps the [rule tuning documentation](https://www.elastic.co/guide/en/security/current/alerts-ui-monitor.html#troubleshoot-gaps) is the best place for this as we do go into detail about gaps and missed alerts in that section.

At the moment (7.15, pre-RAC), each Security Rule type contains some logic for ensuring we don't create duplicate alerts when a Rule overlaps with a daterange in which alerts were previously generated (by means of the [additional look-back](https://www.elastic.co/guide/en/security/current/alerts-ui-monitor.html#troubleshoot-gaps) scheduling setting). For non-agg based rules it's fairly straightforward and we generate a unique ID for the alert from a combination of the source doc ID, index, and timestamp iirc, then rely on ES to reject inserting docs with duplicate ID's.

There is a bug with this method of handling dupes though as large additional lookbacks can result in detecting alerts between index rollovers/upgrades, and then result in duplicate alerts. Please see this issue/comment for details (https://github.com/elastic/kibana/issues/94071).

That said, it is probably sufficient to just mention that when configuring a lookback, the Rule will try and determine if it has already create an alert for the matching source documents, and not create another except in the above mentioned corner case.

**Comment by spong** [comment]
Was discussing with @joepeeples and he pointed out we do indeed call this out within the [schedule section of the create rules docs](https://www.elastic.co/guide/en/security/current/rules-ui-create.html#rule-schedule) -- so can probably use this copy in any additional spots it makes sense.

> The Elastic Security app prevents duplication. Any duplicate alerts that are discovered during the Additional look-back time are not created.

**Comment by joepeeples** [comment]
Merged #1125.
