### ISSUE TITLE
[DOCS]Old modal for add alert to existing case showing in Elastic Security Solution doc

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1050]
**Describe the bug**
Old modal for add alert to existing case showing in Elastic Security Solution doc

**Guide Link**
https://security-docs_1028.docs-preview.app.elstc.co/guide/en/security/master/alerts-ui-manage.html

**Steps**
- Go to above mentioned guide link
- Scroll down and found "Add alert to existing cases" section
- Old modal for select case is shown , Status column should not show

**Note:** Now user cant change case status hence drop-down arrow should not shown in Case Status column

### Reference issue : https://github.com/elastic/kibana/issues/110931#issuecomment-911891866

**Screen-Shoot**

- Actual
![image](https://user-images.githubusercontent.com/59917825/133584947-69c9abf1-16b1-4736-84e8-137a3762542c.png)

- Expected
![image](https://user-images.githubusercontent.com/59917825/133585056-56866230-4f33-4e17-93e1-72e7af97bf74.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by jmikell821** [comment]
@karanbirsingh-qasource can you tell us what server you're using? We do not see this behavior on any 7.15 BC server. Please, in the future, include the server URL on which you are testing so we can try to replicate the behavior on our end. Thank you! 

cc: @manishgupta-qasource @joepeeples @nastasha-solomon

**Comment by joepeeples** [comment]
Corrected as part of PR #1028.

**Comment by muskangulati-qasource** [comment]
Hi @joepeeples ,

We tested this ticket and found that it is now fixed.
**Screenshot**:
![2](https://user-images.githubusercontent.com/60252716/134162660-e4963fdb-b659-465b-889e-e5d656399152.JPG)

Hence, we are closing this ticket.

Thanks!
