### ISSUE TITLE
[DOCS]Old row action showing under timeline for Elastic Security Solution doc

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1051]
**Describe the bug**
Old row action showing under timeline for Elastic Security Solution doc

**Guide Link**
https://security-docs_1028.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html#detection-engine-ui

**Steps**
- Go to above mentioned guide link
- Scroll down and found "Interact with Drag gable elements" section
- old event row action are showing , new tgrid table form should show

**Screen-Shoot**

- Actual

![image](https://user-images.githubusercontent.com/59917825/133585753-c8e4cd30-d0c3-435b-be7d-115c82187b09.png)
![image](https://user-images.githubusercontent.com/59917825/133586054-58d3cb89-fe04-4a08-9aca-214f7b125198.png)

- Expected
![image](https://user-images.githubusercontent.com/59917825/133585689-4896fb55-4a3c-44fb-870d-a9ba458a53b6.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Thanks for filing this @karanbirsingh-qasource ! I'll also need to update the Timeline screenshots in https://www.elastic.co/guide/en/security/current/timelines-ui.html before my PR's ready to be reviewed, so that's coming shortly.

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource the updates are ready for your review at #1061 when you have a chance!

**Comment by muskangulati-qasource** [comment]
Hi @natasha-solomon,

We tested this ticket and found that this is partially fixed for the [Elastic Security UI](https://security-docs_1028.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html#detection-engine-ui) page.

**Screenshots**:

![3_1](https://user-images.githubusercontent.com/60252716/134162754-ae88b4da-bc0f-4682-96fc-1795671a1974.JPG)

![3_2](https://user-images.githubusercontent.com/60252716/134162869-a58df79b-b8cd-49d3-aa2a-a745fd2260d7.JPG)

![3_3](https://user-images.githubusercontent.com/60252716/134162783-20173e1c-3cf5-4915-b102-edcab9b55ce2.JPG)

Thanks!

**Comment by deepikakeshav-qasource** [comment]
Hi @nastasha-solomon ,

We tested this ticket and found that it is now fixed.

**Screenshot**:
- [Elastic Security UI](https://security-docs_1061.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html#draggable-timeline-elements)

https://user-images.githubusercontent.com/61860752/134163611-8cdbd7cb-1317-4d1b-a6da-aad75e027e7b.mp4

- [Investigate events in Timeline](https://security-docs_1061.docs-preview.app.elstc.co/guide/en/security/master/timelines-ui.html)



https://user-images.githubusercontent.com/61860752/134163761-0c740cff-3f53-4470-b1f0-3b12bd0bc2ce.mp4


Hence, we are closing this ticket.

Thanks!
