### ISSUE TITLE
[BUG] No update regarding the Linux platforms that do not support isolation

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1052]
**Description**: No update regarding the Linux platforms that do not support isolation

**URL link or topic name**: 
- [**Host Isolation**](https://security-docs_1010.docs-preview.app.elstc.co/guide/en/security/master/host-isolation-ov.html)

**Screenshot**:
- Centos 7
![Centos7](https://user-images.githubusercontent.com/60252716/133586948-d26c9365-90cf-40b1-a5b0-1bacfe491a98.JPG)

- RHEL 7
![RHEL7](https://user-images.githubusercontent.com/60252716/133587024-e0edf204-810f-4d80-90c1-2286744a3836.JPG)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821
