### ISSUE TITLE
[DOCS] Extra graphics are displaying on chrome browser in Lens Visualization Plugin Available for Cases doc

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#1053]
**Describe the bug**
Extra graphics are displaying on chrome browser in Lens Visualization Plugin Available for Cases doc

**Guide Link**
https://security-docs_1018.docs-preview.app.elstc.co/guide/en/security/master/cases-overview.html#cases-lens-visualization

**Steps**
- Go to above mentioned guide link
- Observed that Extra graphics are displaying under "To add a Lens visualization to a comment within your case:" 

**Note:** This issue is occurring on chrome browser.
**Version: 93.0.4577.82** 

![image](https://user-images.githubusercontent.com/61860752/133589684-d029cd49-bf23-4be5-bb8c-79689aa613a4.png)

**Comment by deepikakeshav-qasource** [comment]
@manishgupta-qasource Please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821
