### ISSUE TITLE
[DOCS] Release notes [7.14.2] 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#1059]
- Check out the `7.14` branch
 - Add new 7.14.2 RNs to the `docs/release-notes/7.14.asciidoc` file (follow same structure for 7.14.1)
 - Once PR review is done, merge to `7.14` (you'll have to change the drop-down from `main` if it defaults to this), then backport to `7.x` and `7.15`.

**Comment by nastasha-solomon** [comment]
Merged #1060.
