### ISSUE TITLE
[7.16]Trusted Apps by Policy[DOCS]

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#1102]
## Description 
EPIC: https://github.com/elastic/security-team/issues/122

This features allows users to set trusted applications on a per policy basis (rather than each trusted application being applied "globally", to all endpoints/hosts in their environment). We are starting the "by policy" feature with Trusted Applications, and will eventually expand to other artifacts - Event filters, exceptions, etc.  

User Story:
As a security solution user, I need to be able to target a set of hosts with certain configurations and and settings (like trusted applications). The settings may need to be unique to that group, and not applied to any other hosts in my organization.  

## Acceptance Test Criteria

Note: **User = Platinum and Enterprise Users. Basic and Gold customers will not be able to set Trusted Apps on a per Policy basis.**

- Users need to be able to assign a trusted app entry to a policy. 
- Users need entries to be “reusable”. User can utilize single "entry" in multiple policies
- Users need to be able to edit/update the entry
     - User edits single entry and it’s updated in all policies
- Users need to be able to delete the entry
     - User deletes an entry and it’s removed from all policies
- Users need to keep users informed  of the impact of deleting/editing entries
     - If user deletes an entry, they are informed of the impact (“Deleting  this entry will remove it from the “x” policies it is associated with”)
- Users need to be able to unassign/disassociate an entry from a policy
- Users can save a trusted app without assigning it to a policy (but ux should make it clear it is unassigned)

## Mocks
https://www.figma.com/file/msfFXMLZcLZaDJ56Sf6ty1/Trusted-apps-per-policy-7.16?node-id=3%3A2

**Comment by joepeeples** [comment]
Merged #1240
