### ISSUE TITLE
[7.16] Host Isolation - IP Allowlist [DOCS]

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#1103]
## Description 
Related Tickets: 
https://github.com/elastic/security-team/issues/829
https://github.com/elastic/security-team/issues/1708

While containing threats with Host Isolation, users may want to allow communication with a limited set of IPs on their network. 

## Acceptance Test Criteria

- User can enter a set of IPs that the Endpoint can still communicate with although it's isolated.
- The set of IPs will be global to start and apply to every policy
- The IPs are maintained on a separate page in the security app

**Comment by joepeeples** [comment]
We'll use this issue to track the documentation of the actual feature, but we'll also need to update a lot of other screenshots that happen to have the side nav menu in them (and now need to include the "Host isolation exceptions" menu option).

See https://github.com/elastic/security-docs/issues/1189 for these related screenshot changes.

**Comment by joepeeples** [comment]
Merged #1190.
