### ISSUE TITLE
[DOCS]New Integration `Cloudflare` mentioned in docs instead not available on Kibana 7.15.0

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1109]
**Describe the bug**
New Integration `Cloudflare` mentioned in docs however same not available on Kibana 7.15.0

**Guide Link**
https://www.elastic.co/guide/en/security/current/whats-new.html

**Build Details**
```
Version: 7.15.0
Commit:add5d2c5ebeba1d8bcf6a79f8863cd78760e1b3e
Build:44040
```

**Steps**
- Log in to Kibana
- Click on left side navigation panel > Select Integration
- Search for `Cloudflare` under all
- Observed that `CloudFlare` integration is not available in 7.15.0 Build , however mentioned in 7.15.0 Doc.

**Screen-Shoot**

- 7.15.0 Build Integration
![image](https://user-images.githubusercontent.com/59917825/134457570-9ed338b4-2c08-4a60-aef0-6cf735ae0a3b.png)
- 7.15.0 Elastic Security Solution Doc
![image](https://user-images.githubusercontent.com/59917825/134457627-1790c528-d454-4a59-8ab7-a9bf366991b9.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821 

Environment Details are added in Bug Description

**Comment by jmikell821** [comment]
@karanbirsingh-qasource I just create a 7.15.0 BC deployment and found it here: 
![2021-09-23_11-26-37](https://user-images.githubusercontent.com/57149392/134536869-829edabc-5cc2-4d1f-be0e-4bdf9812f4ed.png)

I will double check with the Security team to ensure this integration has been added.

**Comment by karanbirsingh-qasource** [comment]
Closing this issue as now we are getting cloud flare integration.

![image](https://user-images.githubusercontent.com/59917825/134850730-2656e5e0-6cf9-4d98-a9b7-812ee9618149.png)
