### ISSUE TITLE
[DOCS]Old State in-progress mentioned in cell actions for Rule Exception in Elastic Doc

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1110]
**Describe the bug**
Old State in-progress mentioned in cell actions for Rule Exception in Elastic Doc

**Guide Link**
https://www.elastic.co/guide/en/security/current/detections-ui-exceptions.html

**Build Details**
Version: 7.15.0
Commit:add5d2c5ebeba1d8bcf6a79f8863cd78760e1b3e
Build:44040

**Steps**
- Go to Add Exception to a rule section of Elastic Security Solution doc
- Observed that in doc old alert state in-progress is mentioned , new alert state Acknowledged should be there in doc

**Screen-Shoot**

- **_Actual_**
![image](https://user-images.githubusercontent.com/59917825/134459115-e8878400-247a-415e-816f-b3df35aa5be6.png)
- _**Expected**_
![image](https://user-images.githubusercontent.com/59917825/134459109-d5d57ead-f188-4146-94d4-63c75bb969a4.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821 

Environment Details are added in Bug Description

**Comment by joepeeples** [comment]
Merged #1118.
