### ISSUE TITLE
[DOCS]lens visualization missing in case details page

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1111]
**Describe the bug**
lens visualization missing in case details page

**Guide Link**
https://www.elastic.co/guide/en/security/current/cases-overview.html

**Build Details**
Version: 7.15.0
Commit:add5d2c5ebeba1d8bcf6a79f8863cd78760e1b3e
Build:44040

**Steps**
- Go to open a new case section of Elastic Security Solution doc
- Observed that in case details snap-shoot , lens option is missing 

**Screen-Shoot**

- Actual
![image](https://user-images.githubusercontent.com/59917825/134459908-a7ae5d94-6d04-4c6a-beab-89cf846e8327.png)

- Expected
![image](https://user-images.githubusercontent.com/59917825/134459901-8ed38c85-a762-44d2-9219-d2e73a08d741.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821 

Environment Details are added in Bug Description

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource appreciate you finding this. The updated docs are ready for your review when you have a moment. Thank you!

**Comment by karanbirsingh-qasource** [comment]
Thanks @nastasha-solomon for the update .

This issue is now Fixed so Closing this issue.

![image](https://user-images.githubusercontent.com/59917825/135422001-f6183456-7bd8-4af4-b6cd-4dba0ebfb3ba.png)

c.c @MadameSheema
