### ISSUE TITLE
[BUG]Change "Email or Username" field to "Email address" for JIRA connector docs 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#1126]
Addresses https://github.com/elastic/kibana/issues/108656

Topic to update: https://www.elastic.co/guide/en/security/master/cases-ui-integrations.html#create-new-connector

cc: @cnasikas 

<img width="619" alt="gh-issue-1126" src="https://user-images.githubusercontent.com/79124755/135493631-8e3d5a9f-029f-4335-bbd0-96409a7b3624.png">

**Comment by cnasikas** [comment]
Thanks, @nastasha-solomon. I would like to add that the same applies to the "API token (or password)" label. Needs to be corrected to "API token".
