### ISSUE TITLE
[DOCS][Detections] - Update detection rule actions import/export docs

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#1169]
## Description 

As part of 7.16 there are some noticeable changes to the detection rules export/import functionality.

Starting 7.16, [`actions`](https://www.elastic.co/guide/en/security/current/rules-api-create.html#actions-object-schema) will be exported as part of the rules export. Previously, the `actions` were stripped out on rule export and there was no support for actions import.

## Possible docs needing updates
- https://www.elastic.co/guide/en/security/current/rules-ui-management.html#import-export-rules-ui
- https://www.elastic.co/guide/en/security/current/rules-api-import.html
- https://www.elastic.co/guide/en/security/current/rules-api-export.html

## Notes
- Connectors will not be exported with rules  
    - Connectors are what contain the credentials for say slack, or email or whatever notification type was selected
- Rules that contain actions pointing to non-existent connectors will result in an import error
    - User in this case would need to either:
        - Modify their import ndjson to remove the `actions` pointing to non-existent connectors
        - Create the same connector (say a slack connector), export it, update the export ndjson so that the connector `id` matches the `id` the rule's action is pointing to, import said connector and try importing rule again
- **The suggested way of exporting/importing rules with actions is to:**
    - Use the [Saved Object Management (SOM) UI to export connectors](https://www.elastic.co/guide/en/kibana/current/managing-saved-objects.html#managing-saved-objects-export-objects)
    - Export detection rules 
    - On import, first import the connectors back in via the SOM
    - Then after connectors are exported, import rules with actions back in
- Note that the Saved Objects Management Kibana privilege is required to access the Saved Objects UI.
- If a user on import selects to `overwrite`, if a rule being imported matches an existing rule, the actions will be updated to match that of the rule being imported

**Comment by yctercero** [comment]
Connector error example on import - https://github.com/elastic/kibana/pull/116490

**Comment by joepeeples** [comment]
@alexfrancoeur We're wondering if we should refer customers to the Saved Objects [export](https://www.elastic.co/guide/en/kibana/current/saved-objects-api-export.html) and [import](https://www.elastic.co/guide/en/kibana/current/saved-objects-api-import.html) APIs if they want to automate the process of exporting/importing connectors for their rule actions. The connectors are labeled `experimental` in the docs, so we weren't sure how that might affect what we tell customers in the docs.

This is from discussion with @yctercero and @jethr0null, who suggested reaching out to you on the Kibana side. Thanks!

**Comment by alexfrancoeur** [comment]
Thanks for the ping @joepeeples. I think it's perfectly fine to use these APIs in your documentation. This is the only reference I saw in the previews outside of the request and response examples.

![image](https://user-images.githubusercontent.com/25181823/144857907-aa661510-5968-4725-b3e2-187b7ae0ccac.png)

The one thing I'll add is that if we're going to be going into this level of detail for the APIs themselves, we may want to explicitly add and experimental label in the documentation. Given that these referenced APIs listed as experimental elsewhere, I'm not sure how best to surface this label, but I do think it should be on the page to avoid any confusion. @gchaps do you have any ideas?

Adding a few folks for visibility in case they want to chime in: @mikecote @arisonl @gmmorris @lukeelmers @thesmallestduck

**Comment by joepeeples** [comment]
@alexfrancoeur We can definitely identify the APIs as experimental in our docs. Maybe the simplest way would just be revise that statement to "... or the Saved Objects APIs **(experimental)** to export and import any connectors...." The linked pages for the export and import APIs are also both flagged as experimental with more explanation of what that means, so I think the reader would get the information they need.

**Comment by lukeelmers** [comment]
> The APIs are labeled `experimental` in the docs, but they've been that way since 7.4, so we didn't know if there were still any concerns over referring them to customers.

FWIW, we are [considering upgrading the import & export APIs to beta](https://github.com/elastic/kibana/issues/90429), but have held off for the time being as we are currently evaluating our long-term strategy around our saved objects REST APIs.

That said, we've worked very hard to keep these APIs stable despite the fact that they are experimental, and I don't know that I can think of a time when we have broken these in a minor. So there are no major concerns from my end with pointing users to these as a solution. If we do end up making breaking changes in the future, there will be plenty of advance notice & a long deprecation period, since we know this is a heavily used API.

**Comment by joepeeples** [comment]
Thanks for the additional context, @lukeelmers! I subscribed to the issue you linked to stay informed on any future upgrade to beta.

**Comment by joepeeples** [comment]
Merged #1264.
