### ISSUE TITLE
[DOCS] Document privileges needed for CCS rules

### ISSUE THREAD

**Issue by rylnd** [elastic/security-docs#1181]
## Description 

We recently had an [SDH](https://github.com/elastic/sdh-security-team/issues/229) where the underlying issue was related to CCS and API keys. The behavior is described [here](https://elastic.slack.com/archives/CA6N3HDF1/p1635404144037000), but the TLDR is that:

* CCS with API keys is different than CCS for users
* remote privileges don't matter; local privileges are applied to the remote
* local privileges are captured when the API key is created (i.e. a snapshot)

## Acceptance Test Criteria

* User can correctly configure CCS permissions for their detection rules

Related: https://github.com/elastic/security-team/issues/1983

**Comment by rylnd** [comment]
It doesn't look like there are [existing docs](https://github.com/elastic/elasticsearch/issues/72841) to reference from the elasticsearch side, but I'm happy to help iterate on this one.

**Comment by joepeeples** [comment]
Merged #3119.
