### ISSUE TITLE
[DOCS] Alerts table updates (7.16)

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#1196]
Though this work was done by the threat hunting team, it's more of a D&R feature, hence the two labels. 

Topic: [View and filter detection alerts](https://www.elastic.co/guide/en/security/current/alerts-ui-manage.html#detection-view-and-filter-alerts)

Threat Hunting Feature Sync Notes [here](https://docs.google.com/document/d/19CQVJxs1V7Lg3EoYdhtIppmQcprpAQ_CGIuHoxSS-fc/edit?usp=sharing).

There have been some enhancements to the Alerts table: 

- Analyze event appears in the table, where available, provided they have entered the correct KQL query. 
**Note:** This feature is also available in `7.15.2`, to be documented in #1191. 

![2021-11-04_10-48-19](https://user-images.githubusercontent.com/57149392/140409135-26ec50e3-f409-4eab-b42b-931d36a013b8.png)

- Default inline actions have been limited to `filter in, filter out, add to timeline`, and ` expand`. 
![2021-11-04_15-48-10](https://user-images.githubusercontent.com/57149392/140409621-ac9e14a5-35cb-4351-b805-7ab83a7f5a50.png)

- `Reason` field renamed and no longer a default field/table column

Users need to manually add the reason field to the Alerts table. To do this: 
   1. Click **Fields**. 
   2. Enter  `signal.reason` into the search bar. 
   3. Select the `signal.reason` field to add it to the Alerts table. 
   4. Click **Close** to return to the Alerts table. 
 
![2021-11-04_12-52-25](https://user-images.githubusercontent.com/57149392/140534339-b1fe3c4e-976f-4fc2-a377-cf072caa1cf9.png)

**Note:** In `v8.0`, the `reason` field will be renamed to `kibana.alert`. 
The **Expand** button is the only inline action available for the `reason` field. When selected, the complete reason for why the alert was generated displays in the event renderer view.

**Comment by joepeeples** [comment]
Merged #1249
