### ISSUE TITLE
META Issue: Security Documentation TOC Outline

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#12]
The purpose of this ticket is to record the final TOC/outline of our security documentation. Security docs are located here: https://www.elastic.co/guide/en/endpoint/current/index.html.

**Comment by benskelker** [comment]
Aside from terminology and flow changes, this seems like a good time to rearrange the SIEM docs (which I've wanted to do for a while). Currently, the docs are based on the UI. I'd like your input on moving to a more workflow-based structure.

Instead of this:
<img width="353" alt="Screenshot 2020-05-20 at 10 10 45" src="https://user-images.githubusercontent.com/54019610/82416157-43ac1b00-9a82-11ea-9dac-cea951c401f9.png">

Something like this:

- Overview
   - Getting started (prerequisites, recommended beats, endpoint, ECS fields)
- Investigations
    - Terminology/UI
    - Host events
    - Network events
    - Timeline/Timeline templates
    - Cases
- Detections
   - Detection rules
   - ML jobs
- APIs

Please add your thoughts, Endpoint headings wherever it makes sense, and CC other relevant people.
Thanks,

cc @jmikell821 @DonNateR

**Comment by DonNateR** [comment]
Adding in some of the content I've been working on, iterating on top of beans:

- Get Started
   - Security App Overview
   - Prerequisites
   - Install the Endpoint Agent
   - SIEM related onboarding documentation
- User Guide
   - Investigations
       - Terminology/UI 
       - Host events
       - Network events
       - Timeline/Timeline templates
       - Cases
   - Resolver 
   - Detections 
      - Detection rules
      - ML jobs
- Admin Guide
   - Endpoint Management
   - Other admin tasks 
- API
- Reference guide
   - Detailed ECS mappings (coming soon to 7.7)
   - Object schemas (as the number of APIs grow, we're going to need dedication sections for each object, like alerts and timelines)

**Comment by DonNateR** [comment]
Oh, one thing I forgot to add was **Release Notes**, but that'll be at the bottom I imagine.

**Comment by benskelker** [comment]
Thanks @DonNateR 

> I don't think we have to explicitly call out User Guides as "User Guides" as long as the persona and use case is obvious.

Yes, I agree. Unlike admin stuff, I don't think this needs to be explicitly stated in the first-level sections.

> Because there are so many ways to interact (Resolver, Case Management, Timelines) with events, I wonder if it would be best to make each a separate User Guide, kind of like how SIEM is separated now.

I'd prefer to restructure and have high-level intro sections. I think it'll help users get a better overview of how Elastic Security can be used.

For Kibana-specific security stuff (siem index mappings, map configuration, user permissions), we need to decide what goes in the getting started chapter, what goes in the admin chapter, and what goes in both.

**Comment by DonNateR** [comment]
TOC:
- Get Started
   - Security App Overview
       -  Ben's User flows (Functionality)
   - UI overview (what's in each section)
        - Host events
        - Network events
   - Terminology 
   - Prerequisites 
      - Supported operating systems
      - Weird detections admin requirements
      - Full Disk Access 
      - Firewall rules 
   - Install the Endpoint Agent
- Hosts overview
  - Supported hosts
  - Add hosts 
  - Manage hosts
- Alerts
   - Rules overview 
      - prebuilt rules overview
      - Detection (custom) rules
           - ML Jobs
  - External alerts overview
  - Endpoint policies 
  - Reponses 
  - Use cases 
- Investigations
   - Terminology/UI
   - Timeline/Timeline (Resolver/Graphical timeline) templates
   - Demonstration flow (?)
- Reference guide
   - Detailed ECS mappings (coming soon to 7.8)
   - API
   - Object schemas (as the number of APIs grow, we're going to need dedication sections for each object, like alerts and timelines)

TBD (content we don't know enough about/content that doesn't have)
- Admin Guide
   - Management sections 
   - Permissions 
   - Ingest functionality

**Comment by benskelker** [comment]
> * Alerts

@jmikell821 @DonNateR 
Now we know there is going to be a first-level `Detections` tab in the UI, maybe we should name this section `Detections and Alerts`?

**Comment by jmikell821** [comment]
> > * Alerts
> 
> @jmikell821 @DonNateR
> Now we know there is going to be a first-level `Detections` tab in the UI, maybe we should name this section `Detections and Alerts`?
> 
> Also, do you think we need a `What's new` section (starting from the 7.10 release I guess)?

@benskelker let's clarify the definition of each because isn't a detection a type of alert? Or I guess in theory, a detection is the same thing as an alert? I'll follow up with the PMs.

**Comment by benskelker** [comment]
@jmikell821 I think it's something like this:
* Enable and create detection rules which generate detection alerts
* Enable `promotion` detection rules to:
** Generate external alerts
** Generate endpoint alerts 

So all alerts rely on detections.
