### ISSUE TITLE
[DOCS] Suspicious hosts card/Host scoring metadata

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#1213]
Related issue: https://github.com/elastic/security-team/issues/1308

**Hosts card:** As an analyst, I want to review the list of risky hosts from my network, in my triaging workflow. I also should be able to determine the relative riskiness, drill down to consume the reasons behind their riskiness, and finally the associated events.

**Hosts scoring metadata:** As an analyst, when reviewing an alert I want to readily see the associated host, host risk classification (if any), and associated risk score in a singular view. This additional information will help me expedite triage activities.

**Note:** This is behind feature flag `riskyHostsEnabled`. Also requires setup of Host Risk transform.  

Host risk score readme [here](https://github.com/elastic/detection-rules/blob/main/docs/experimental-machine-learning/host-risk-score.md). 

Google doc [here](https://docs.google.com/document/d/160VnX4gE25rGYUjj6clv7bvb2WEER5b_V_fbAAZqxcg/edit).

**Comment by ajosh0504** [comment]
Screenshot of the Risky hosts view:
<img width="587" alt="Screen Shot 2021-11-17 at 10 08 39 AM" src="https://user-images.githubusercontent.com/30438249/142257829-63e8d45a-a589-4169-961a-816240dbf9f1.png">

Screenshot of the drilldown:
<img width="1787" alt="Screen Shot 2021-11-17 at 10 09 07 AM" src="https://user-images.githubusercontent.com/30438249/142257885-2925f116-db3c-4f33-8c33-8f6be77bb1a3.png">

**Comment by jmikell821** [comment]
Merged #1261.
