### ISSUE TITLE
[DOCS] Update potential screenshots for new Add Data Page

### ISSUE THREAD

**Issue by kevinlog** [elastic/security-docs#1223]
## Description 
The empty states for some of the application have changed to use a new design with a single call to action, to simply "Add a Security Integration" which takes users to the Add integration page in the Integrations app.

The pages in Security that are updated:
- Overview
- Hosts
- Network
- Timelines

These pages has different empty states before, so we may need to update screenshots in some places.

## Acceptance Test Criteria
- [ ] Update any existing screenshots of empty states for:
   - Overview
   - Hosts
   - Network
   - Timelines

**Screenshots**

Overview:
![image](https://user-images.githubusercontent.com/56395104/142067932-85a32ffd-128e-4ff7-ae55-f93ee311f34f.png)

Hosts:
![image](https://user-images.githubusercontent.com/56395104/142067974-32d2a034-bf92-4637-ae4c-dcea30ba3686.png)

Network:
![image](https://user-images.githubusercontent.com/56395104/142068013-ebb52f6b-5ef0-4f37-8a68-ab2424bbcd10.png)

Timelines:
![image](https://user-images.githubusercontent.com/56395104/142068072-58fa77d5-b158-4407-ae18-c17c8431232b.png)

## Notes

- Add all appropriate labels to the issue, especially the version number label. 
- Be sure to add any necessary screenshots, code text or console commands for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by joepeeples** [comment]
I reviewed the current docs and didn't find any screenshots that will need to be updated for this UI change. We typically include sample data in screenshots, so empty states aren't usually included. Thanks @kevinlog for the heads-up though -- I'm glad we checked!
