### ISSUE TITLE
[DOCS] Update text to include name for the new transform in the transform troubleshooting docs

### ISSUE THREAD

**Issue by kevinlog** [elastic/security-docs#1224]
## Description 
We've added a new transform for the 7.16 release.  We should update the text in the docs to include the name of that transform.

Users should now check for both `endpoint.metadata_current-default` and `endpoint.metadata_united-default`

This is the doc in question that we should update: https://www.elastic.co/guide/en/security/7.16/ts-management.html

We should update this line: Enter `endpoint.metadata_current-default` in the search box to find the transform for Endpoint Security.

We could say: Enter `endpoint.metadata` in the search box to find the transforms for Endpoint Security.

We could also update this screenshot:
![image](https://user-images.githubusercontent.com/56395104/142070921-99e473ad-efd1-4893-8a80-bceb843765b9.png)

## Acceptance Test Criteria
- [ ] Update https://www.elastic.co/guide/en/security/7.16/ts-management.html to include mention of the new transform.

## Notes

- Add all appropriate labels to the issue, especially the version number label. 
- Be sure to add any necessary screenshots, code text or console commands for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by joepeeples** [comment]
Merged #1228
