### ISSUE TITLE
[DOCS] Trusted Applications `matches` path functionality

### ISSUE THREAD

**Issue by kevinlog** [elastic/security-docs#1243]
## Description 
Users can choose a `matches` operator when creating Trusted Applications by Path inside of the of the Trusted Applications flow.  This will allow users to send down a path that has a wildcard in it's path, i.e. `*`

## Acceptance Test Criteria

- Document that users can choose `matches` when creating a Trusted Application
- TBD: some examples to share with the user

If the enhancement requires a procedure, include the steps.  

## Notes

- Add all appropriate labels to the issue, especially the version number label. 
- Be sure to add any necessary screenshots, code text or console commands for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by joepeeples** [comment]
Documented in #1240 (Trusted Apps by Policy).
