### ISSUE TITLE
[BUG] Memory threat is supported on Mac, Windows and Linux as well. The screenshot shows supported on Windows only

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1250]
**Description**: 
Memory threat is supported on Mac, Windows and Linux as well. The screenshot shows supported on Windows only

**URL link or topic name**: 
- https://security-docs_1240.docs-preview.app.elstc.co/guide/en/security/master/configure-endpoint-integration-policy.html#memory-protection

**Screenshots**:
![5](https://user-images.githubusercontent.com/60252716/143830352-3d6146b3-f5e1-4797-8887-fe4c3f8ebbf6.JPG)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
Fixed in PR #1240.

**Comment by muskangulati-qasource** [comment]
Hi @joepeeples,

Thank you for merging the changes, we can see updation correctly done.

**Screenshot**:
![mem](https://user-images.githubusercontent.com/60252716/144003798-32d19484-d03d-4327-8bd8-86e7297fa11e.JPG)

Hence, closing this issue.

Thanks!
