### ISSUE TITLE
[BUG] No update for navigation to the Host Isolation Exceptions tab.

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1251]
**Description**: 
No update for navigation to the Host Isolation Exceptions tab.

**URL link or topic name**: 
- https://security-docs_1190.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html

**Screenshots**:
![6](https://user-images.githubusercontent.com/60252716/143831420-d3f5002c-ae57-4b7a-b917-f60849b7340f.JPG)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
Fixed in PR #1190.

**Comment by muskangulati-qasource** [comment]
Hi @joepeeples,

Thank you for merging the changes, we can see updation correctly done.

**Screenshot**:
![PN](https://user-images.githubusercontent.com/60252716/144004853-6ee2932b-889e-4b06-a500-d15ac9996722.JPG)

Hence, closing this issue and marking it as QA Validated.

Thanks!
