### ISSUE TITLE
[BUG] No description is provided for the Host Isolation Exceptions tab.

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1252]
**Description**: 
No description is provided for the Host Isolation Exceptions tab.

**URL link or topic name**: 
- https://security-docs_1190.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html#host-isolation-exceptions-page

**Screenshots**:
- Actual:
![7](https://user-images.githubusercontent.com/60252716/143831735-f0994785-9249-4cd4-9f1b-e7edabb61593.JPG)

- Expected:
![7Expected](https://user-images.githubusercontent.com/60252716/143831743-7671978f-a606-4b1f-8552-8882a2f38bca.JPG)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
Fixed in PR #1190.

**Comment by muskangulati-qasource** [comment]
Hi @joepeeples,

Thank you for merging the changes, we can see updation correctly done.

**Screenshot**:
![HIS](https://user-images.githubusercontent.com/60252716/144004810-3d0aef27-37b6-4216-9d16-23ee44ab9504.JPG)

Hence, closing this issue and marking it as QA Validated!.

Thanks!
