### ISSUE TITLE
[DOCS] Extra graphics are displaying on chrome browser in Prerequisites for Service now Connectors

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#1253]
**Describe the bug**
Extra graphics are displaying on chrome browser in Prerequisites for Service now Connectors

**Guide Link**
https://security-docs_1188.docs-preview.app.elstc.co/guide/en/security/master/post-upgrade-deprecated-sn-connector.html#pre-req-deprecated-sn-connector

**Steps**
- Go to above mentioned guide link
- Observed that Extra graphics are displaying under "Prerequisites " 

**Note:** This issue is occurring on chrome browser.
**Version: 96.0.4664.45** 

![image](https://user-images.githubusercontent.com/61860752/143833820-1d1258a4-9798-4d5f-807f-fd5274ccb5fb.png)

**Comment by nastasha-solomon** [comment]
Related to https://github.com/elastic/security-docs/pull/1188 and https://github.com/elastic/kibana/pull/117122.

**Comment by nastasha-solomon** [comment]
@deepikakeshav-qasource thanks for filing this! Please see https://github.com/elastic/security-docs/pull/1188 for the latest draft.

**Comment by deepikakeshav-qasource** [comment]
Hi @nastasha-solomon,

We tested this ticket and found that it is now fixed.

**Screenshot**:
![image](https://user-images.githubusercontent.com/61860752/144560960-6a40b11b-34d8-4609-8a17-2f87642daefb.png)

Hence, we are closing this ticket and marking as QA Validated.

Thanks!
