### ISSUE TITLE
[BUG] Security docs prescribe incorrect ML requirements

### ISSUE THREAD

**Issue by rylnd** [elastic/security-docs#1256]
**Description**:

Security's [ML docs](https://www.elastic.co/guide/en/security/current/ml-requirements.html#ml-requirements) indicate that _all_ nodes need ML privileges, while [ML's own docs](https://www.elastic.co/guide/en/machine-learning/current/setup.html#ml-nodes) indicate that only one node need be an ML node. We should update our docs accordingly, and also link to the more detailed ML guide.

It looks like this discrepancy has been present since [7.9](https://github.com/elastic/security-docs/pull/125), so ideally this change would be backported to all relevant releases.

**Comment by benironside** [comment]
Merged #1281
