### ISSUE TITLE
[DOCS] Github style markdown causes issues during upgrade

### ISSUE THREAD

**Issue by jonathan-buttner** [elastic/security-docs#1267]
## Description 

There is a known bug where if a user has a case comment containing github style markdown it will cause the migration to fail during an upgrade to 7.15.

The bug issue is here: https://github.com/elastic/kibana/issues/119509

We need to add some release notes to 7.15.x version if possible to let users know.

Our hope is to have this fixed in 7.16.1 but so far there won't be a fix in 7.15.x.

This PR fixes the issue: https://github.com/elastic/kibana/pull/119995

## Acceptance Test Criteria

Add the following documentation:

There is a known bug where Case comments containing Github Formatted Markdown (GFM) will cause the Case migrations to fail during an upgrade to 7.15.x or later. The work around for this bug is to remove the GFM from the comment prior to upgrading. 

An example of GFM is Githubs extension for tables: https://github.github.com/gfm/#tables-extension-

The following table will cause the migration to fail:

```
| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |
```

**Comment by nastasha-solomon** [comment]
Merged #1268.
