### ISSUE TITLE
[DOCS] Tell users how to trust Endpoint in third-party security applications

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#1280]
## Description 

@gabriellandau suggested adding docs that tell users how to trust Endpoint in third-party security applications.

## Notes

- Content will likely be maintained in a [Google doc](https://docs.google.com/document/d/1BY0O2L2zUsKFi7kz-sAK3sqm7KlLACGlbRZFU4YOx7c/edit?usp=sharing) for now.

**Comment by gabriellandau** [comment]
Gdoc: https://docs.google.com/document/d/1BY0O2L2zUsKFi7kz-sAK3sqm7KlLACGlbRZFU4YOx7c/edit?usp=sharing

**Comment by joepeeples** [comment]
Duplicate of https://github.com/elastic/security-docs/issues/3433
