### ISSUE TITLE
[DOCS] Move `Known issues` section to top of page

### ISSUE THREAD

**Issue by a03nikki** [elastic/security-docs#1285]
## Description 

The other Elastic software products list the known issues first for a release.  This makes it less likely to miss these critical pieces of information.  At least two other release notes for Elastic software have them at the top of the page, however the security documentation is the anomaly by putting them at the bottom.  This is inconsistent for doc users familiar with our larger set of pages as the expect breaking changes and known issues to be at the top of the release notes and may only check the top of the page.

For example, https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.15.1.html

> Elasticsearch version 7.15.1
>
> Also see Breaking changes in 7.15.
>
> Known issues
> ....
> Enhancements
> ...

Another example, https://www.elastic.co/guide/en/kibana/current/release-notes-7.15.0.html

> Kibana 7.15.0
> For information about the Kibana 7.15.0 release, review the following information.
>
> Known issue
> ...
> Breaking changes
> ...

However, Security puts them at the bottom https://www.elastic.co/guide/en/security/current/release-notes.html#known-issue-7.15.0

> # Release Notes
>
> This section summarizes the changes in each release.
>
> ## 7.15
> 
> ### 7.15.2
> ...
> 
> ### 7.15.1
> ...
>
> ### 7.15.0
> ....
> #### Known issues
> -  Case comments containing GitHub Flavored Markdown (GFM) will cause migrations to fail when upgrading to Elastic Stack version 7.15.0 or later. To prevent this, remove GFM from the case comment before upgrading (#119509).
> 

 
## Acceptance Test Criteria

I would like to see the documentation list the known issues at the top of the release highlights

> # Release Notes
>
> This section summarizes the changes in each release.
>
> ## 7.15
>
> ### Known issues
> -  Case comments containing GitHub Flavored Markdown (GFM) will cause migrations to fail when upgrading to Elastic Stack version 7.15.0 or later. To prevent this, remove GFM from the case comment before upgrading (#119509).
>
> ### 7.15.2
> ...
>
> ### 7.15.1
> ...
> ### 7.15.0
> ...

## Notes

- [ ] Add all appropriate labels to the issue, especially the version number label. 
    - Sorry, I do not have permissions to modify the labels on this issue
- [x] Be sure to add any necessary screenshots, code text or console commands for clarity. 
- [x] Include any conditions or caveats that may affect customers.
    - The example of on this ticket is linked to these tickets
        - https://github.com/elastic/security-docs/issues/1267 (v7.15)
        - https://github.com/elastic/kibana/issues/119509 (v7.15+)
        - https://github.com/elastic/kibana/pull/119995 (TBD)
    - This recommendation came as a result of missing the known issue section due to the inconsistency in formatting, which resulted in a bad user experience during upgrade as Kibana would not start

**Comment by nastasha-solomon** [comment]
Thanks for filing this @a03nikki! We'll incorporate these changes into the 7.15 and 7.16 release notes to ensure known issues are visible to users.

**Comment by nastasha-solomon** [comment]
Merged #1295.
