### ISSUE TITLE
[DOCS][7.16.0] Old Threat Intelligence screen-shoot under Elastic Security UI 

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1313]
**Describe the bug**
Old Threat Intelligence screen-shoot under Elastic Security UI 

**Page:** https://www.elastic.co/guide/en/security/current/es-ui-overview.html#detection-engine-ui

**Topic:** Threat Intelligence

Actual Result | Expected Result
-- | --
![image](https://user-images.githubusercontent.com/59917825/145339435-c4ccaa39-05d0-4c77-951d-e1c1e4186699.png)|![image](https://user-images.githubusercontent.com/59917825/145339324-c5423f32-248a-44d3-9d30-928c0090d76b.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by karanbirsingh-qasource** [comment]
Hi @nastasha-solomon 

we have reviewed the PR and required fix are there . So we are now closing this issue.

**Snap shoot:**
![image](https://user-images.githubusercontent.com/59917825/145750838-8cc50b0c-0eeb-492f-a102-60a31edc19aa.png)

c.c @jmikell821
