### ISSUE TITLE
[DOCS][7.16.0]Old Timeline Cell Action items showing under Host Page Overview

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1314]
**Describe the bug**
Old Timeline Cell Action items showing under Host Page Overview

**Page:** https://www.elastic.co/guide/en/security/current/hosts-overview.html#hosts-overview

**Topic:** Add data values to the Timeline

Actual Result | Expected Result
-- | --
![image](https://user-images.githubusercontent.com/59917825/145339757-9ec2c095-4e1f-47d5-83ff-7a08ad88cba2.png)|![image](https://user-images.githubusercontent.com/59917825/145339849-b1ba5048-9ab1-46ca-baa7-0df9a0661218.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by karanbirsingh-qasource** [comment]
Hi @joepeeples 

Validated the PR and Requested changes are now available. Hence closing this issue.

![image](https://user-images.githubusercontent.com/59917825/145515701-1e3c795f-b5cb-4f49-9793-159ea0bac3a5.png)


c.c @jmikell821
