### ISSUE TITLE
[DOCS][7.16.0]Trend Canvas showing on Left Side of Application instead of Right under Anomaly Detection with Machine Learning

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1315]
**Describe the bug**
Trend Canvas showing on Left Side of Application instead of Right under Anomaly Detection with Machine Learning

**Page:** https://www.elastic.co/guide/en/security/current/machine-learning.html#manage-jobs

**Topic:** Manage Machine learning jobs

Actual Result | Expected Result
-- | --
![image](https://user-images.githubusercontent.com/59917825/145340133-c573dc91-4c89-4193-b18e-f303f890394c.png)|![image](https://user-images.githubusercontent.com/59917825/145340266-52777738-e1a5-4611-a45a-9241eea6d03e.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
@karanbirsingh-qasource Screenshot updated and ready for review in #1318.

**Comment by karanbirsingh-qasource** [comment]
thanks @joepeeples for the update.

Reviewed PR and required changes are now available . So closing this issue.

![image](https://user-images.githubusercontent.com/59917825/145515344-ec92a1b1-e154-4037-a4a7-5136fadc7c27.png)

thanks !!
c.c @jmikell821
