### ISSUE TITLE
[DOCS][7.16.0]Missing new Feature `Host Isolation Exceptions` in left navigation bar under visual event analyzer

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1316]
**Describe the bug**
Missing new Feature `Host Isolation Exceptions` in left navigation bar under visual event analyzer

**Page:** https://www.elastic.co/guide/en/security/current/visual-event-analyzer.html#find-events-analyze

**Topic:** Find Event to Analyze

Actual Result | Expected Result
-- | --
![image](https://user-images.githubusercontent.com/59917825/145340482-152f52ab-c43c-4d7d-9348-3797e5e30214.png)|![image](https://user-images.githubusercontent.com/59917825/145340797-f77f6757-84fd-4a50-9449-d0820b7ef104.png)
![image](https://user-images.githubusercontent.com/59917825/145340526-768cd64e-508d-4ab9-b929-6e959211a4c2.png)|![image](https://user-images.githubusercontent.com/59917825/145340655-acbe1d99-5664-4979-b0c1-ae1cdde2ef26.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by benironside** [comment]
This was fixed in an unrelated screenshot update PR. I confirmed the screenshots do not have the errors in this issue anymore.
