### ISSUE TITLE
[BUG] Manage tab does not have information about Host Isolation exceptions tab

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1334]
**Description**: 
Manage tab does not have information about Host Isolation exceptions tab

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/current/sec-manage-intro.html

**Screenshots**:
- Actual:
![1](https://user-images.githubusercontent.com/60252716/145780334-c4a86632-3be6-4471-b5f0-ca1f1648fc43.JPG)

- Expected:
The host Isolation Exception Tab should be mentioned there in the Manage Tab section

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @jmikell821
