### ISSUE TITLE
[BUG] Host Isolation Activity logs are updated to show the success or unsuccessful message and coloured ticks are also added now. Need to update the screenshot and add text for the colour information.

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1335]
**Description**: 
Host Isolation Activity logs are updated to show the success or unsuccessful message and coloured ticks are also added now. Need to update the screenshot and add text for the colour information.

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/current/host-isolation-ov.html#view-host-isolation-details

**Screenshots**:
- Actual:
![Actual](https://user-images.githubusercontent.com/60252716/145787275-0c7a244d-fcfb-4fa6-bb44-b234ecf25b49.JPG)

- Expected:
![Expected](https://user-images.githubusercontent.com/60252716/145787284-cce0d84c-0d77-41e5-9501-bd9b09b1b655.JPG)

**Related Ticket**:
https://github.com/elastic/kibana/pull/114905

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @jmikell821

**Comment by muskangulati-qasource** [comment]
Hi @joepeeples,

We tested this ticket according to the PR: https://github.com/elastic/security-docs/pull/1340 and found that the changes are correctly done.

**Screenshot**:
![1](https://user-images.githubusercontent.com/60252716/145956627-eb583786-30ff-4942-ad5a-c382a99f9241.JPG)

Hence, closing this issue and marking it as 'QA Validated'.

Thanks!
