### ISSUE TITLE
[BUG] OR operator is removed from the Event Filtering flyout

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1336]
**Description**: 
OR operator is removed from the Event Filtering flyout

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/current/event-filters.html#event-filters

**Screenshots**:
- Actual:
![4](https://user-images.githubusercontent.com/60252716/145789059-58fca97d-4e09-4bfa-b05a-a7b614d72a54.JPG)

- Expected:
![4_Expected](https://user-images.githubusercontent.com/60252716/145789072-28ad8f3e-580a-4c78-a1a2-85b602acbd0b.JPG)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @jmikell821

**Comment by muskangulati-qasource** [comment]
Hi @joepeeples,

We tested this ticket according to the PR: https://github.com/elastic/security-docs/pull/1339 and found that the changes are correctly done.

**Screenshot**:
![2](https://user-images.githubusercontent.com/60252716/145957376-53faff3d-4ed5-412b-b466-f4c77a5870aa.JPG)

Hence, closing this issue and marking it as 'QA Validated'.

Thanks!
