### ISSUE TITLE
[DOCS] Pre-configured connectors can no longer be used within Cases

### ISSUE THREAD

**Issue by jonathan-buttner** [elastic/security-docs#1358]
## Description 

PR: https://github.com/elastic/kibana/pull/120686

Within Cases there is a bug that when a user attempts to use a pre-configured connector (https://www.elastic.co/guide/en/kibana/master/pre-configured-connectors.html) it causes the UI to crash. The solution we chose was to filter out pre-configured connectors, which effectively means users will not be able to use them within Cases.

## Acceptance Test Criteria

Update the docs [here](https://www.elastic.co/guide/en/security/current/cases-ui-integrations.html#cases-ui-integrations) to state something like:

_Pre-configured connectors [link] are not accessible within Cases._

Maybe also update the docs within [pre-config docs](https://www.elastic.co/guide/en/kibana/master/pre-configured-connectors.html#pre-configured-connectors) potentially to state that the connectors won't be accessible within Cases?

**Comment by nastasha-solomon** [comment]
Thanks for filing this @jonathan-buttner! I agree that the topics you linked in the Security and Kibana docs are the appropriate places to add this information. 

Also, I noticed you had labeled https://github.com/elastic/kibana/pull/120686 to be skipped for `7.17`, `8.0`, and `8.1` release notes and just wanted to verify that it didn't need to be release-noted as a known issue.

**Comment by jonathan-buttner** [comment]
> Also, I noticed you had labeled [elastic/kibana#120686](https://github.com/elastic/kibana/pull/120686) to be skipped for `7.17`, `8.0`, and `8.1` release notes and just wanted to verify that it didn't need to be release-noted as a known issue.

Yeah now that you mention it we probably should. I'll change the label on the PR 👍 

Let me know if you need an additional blurb for the known issue.

**Comment by nastasha-solomon** [comment]
Sounds good! For something this straightforward, I don't envision needing super detailed release notes. Though, I suppose it could be helpful to clarify that pre-configured connectors can still be used for rule actions. WDTY?

**Comment by jonathan-buttner** [comment]
> Though, I suppose it could be helpful to clarify that pre-configured connectors can still be used for rule actions. WDTY?

Yeah we only want to communicate that it's specifically Cases that they can't be used for. They still work within the rest of Kibana.
