### ISSUE TITLE
[DOCS] Inform users that at least one Endpoint Security Alert is required to create an Endpoint Exception

### ISSUE THREAD

**Issue by kevinlog** [elastic/security-docs#1360]
## Description 

In order for users to create an Endpoint Exception, there must be at least one alert present.  We should include a note about this in the Endpoint Exceptions section of the docs as it could be confusing in the event that a user wants to create an Endpoint Exception from scratch.

See this bug ticket for more info: https://github.com/elastic/kibana/issues/121475

## Acceptance Test Criteria

- At least one alert should exist in the user's system before they can create an Endpoint Exception.
- For users who are experimenting, they can create a test alert by downloading the [Eicar test file](https://www.eicar.org/?page_id=3950) onto a machine with Endpoint installed and Malware enabled. 

## Notes

- Add all appropriate labels to the issue, especially the version number label. 
- Be sure to add any necessary screenshots, code text or console commands for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by joepeeples** [comment]
@kevinlog Thanks for submitting! This issue has the `v8.1.0` label, but should we add this note to versions earlier than that? I see the issue was discovered in 7.16, per https://github.com/elastic/kibana/issues/121475, so maybe backport that far back?

**Comment by kevinlog** [comment]
@joepeeples - it's certainly relevant to backport, I wasn't sure if that was a possible part of the process.  I will update the labels.  Thanks!
