### ISSUE TITLE
[DOCS] Update to Host Risk Score docs

### ISSUE THREAD

**Issue by ajosh0504** [elastic/security-docs#1436]
## Description 

We've made some updates to Host Risk Score in 8.1. These need to be reflected in our official documentation about the feature.

1. Host Risk Score is no more limited to detection rule alerts (it never was, but we realized this in 8.1), nor is it limited to open alerts. This needs to be updated [here](https://www.elastic.co/guide/en/security/current/whats-new.html#experimental-feature-7.16) and [here](https://www.elastic.co/guide/en/security/current/host-risk-score.html).

2. Host Risk Score is NOT limited to alerts with "open" status anymore.

3. We've added risk multipliers, which will boost the final risk score based on certain attributes of the host itself. For example, alert activity on a server calls for greater scrutiny than that on a laptop, so we  boost the host risk score by 1.5 times if the host is a server. This is done AFTER calculating the weighted sum of the time-corrected risks.

4. Users can now view host risk score data in a few more places other than the Host Overview and Alerts Flyout. @machadoum can provide details and screenshots.

5. We also want to callout the fact that views in the Security App might break if users don't upgrade the Host Risk Score artifacts in accordance with the Stack update. We've already [called this out in the GitHub docs](https://github.com/elastic/detection-rules/pull/1716), but a callout in the official documentation might also be useful.

Unrelated to 8.1 changes, but I just noticed that the second paragraph [here](https://www.elastic.co/guide/en/security/current/host-risk-score.html) has the following sentence:  

> A weighted sum of the individual time-corrected rule risks is then applied to the risk score.

This is a bit unclear. A weighted sum is not applied to the risk score, but is used to calculate the risk score.

**Comment by machadoum** [comment]
New places where you can visualize host risk score:

_Host risk classification column in the All hosts table on the Hosts page_
<img width="1503" alt="0c_host_page_risk_column" src="https://user-images.githubusercontent.com/1490444/152117083-97aafe3b-058d-40f1-aed5-415ba83999a5.png">

_Hosts by risk tab on the Hosts page_
<img width="1504" alt="0d_host_page_hosts_by_risk_tab" src="https://user-images.githubusercontent.com/1490444/152117131-a8a36d2d-0573-4ecf-b9f2-6a9ef9216bc4.png">

_Host risk overview on the Host details page_
![0e_host_details_page_risk_overview](https://user-images.githubusercontent.com/1490444/152117205-3c7bb596-39d9-49dd-afd9-7cb3f8c9a7dd.png)

_Hosts by risk tab on the Host details page_
<img width="1509" alt="0f_host_details_page_hosts_by_risk_tab" src="https://user-images.githubusercontent.com/1490444/152117238-c6e8bdca-a3e4-4a11-8505-1fa614a57174.png">

**Comment by SourinPaul** [comment]
@jmikell821 is there anything pending from our end on this? Thanks

**Comment by jmikell821** [comment]
@SourinPaul I have a question about this: 

>  We also want to callout the fact that views in the Security App might break if users don't upgrade the Host Risk Score artifacts in accordance with the Stack update. We've already https://github.com/elastic/detection-rules/pull/1716, but a callout in the official documentation might also be useful.

I'm not sure what this means. How are users supposed to upgrade artifacts? cc: @ajosh0504 @machadoum

**Comment by ajosh0504** [comment]
@jmikell821 There is a note in the [README](https://github.com/elastic/detection-rules/blob/main/docs/experimental-machine-learning/host-risk-score.md):

> Note: Host Risk Score artifacts should be updated if/when you update to a newer Elastic Stack version. To do this, simply download a release bundle that is compatible with your new Stack version and repeat all the steps. Backwards compatibility of release bundles is not guaranteed.

You could call out the same in your docs as well.
