### ISSUE TITLE
[BUG] API Connector Doc Issues 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#1463]
@cnasikas noticed the following doc bugs in our connector API docs:

- [x]  The `caseId` field description for Swimlane connectors is incomplete in several topics-- it should be `caseId (string | null): The case ID.` The rest of the description is currently in the **Required** column, so it needs to be moved down and replaced with "Yes". This change will likely need to be backported to `7.14`. Bug is observed in the following topics:
  - [Set default Elastic Security UI connector](https://www.elastic.co/guide/en/security/master/assign-connector.html)
  - [Update case configurations](https://www.elastic.co/guide/en/security/master/case-api-update-connector.html)
  - [Update case](https://www.elastic.co/guide/en/security/master/cases-api-update.html)

- [x] Need to add the Swimlane connector to the list that describes third-party systems that users can push Elastic Security cases to in the [actions API topic](https://www.elastic.co/guide/en/security/master/actions-api-overview.html). This change needs to be backported to `7.14`.

**Comment by cnasikas** [comment]
Hi @nastasha-solomon! Thanks for improving the docs. A few comments:

> This change will likely need to be backported to 7.14

That is correct. The Swimlane connector was introduced in 7.14.

> need to split ServiceNow (this connector is deprecated) into ServiceNow SecOps and ServiceNow ITSM since we offer two > SN connectors now

The ServiceNow connector is the same as the ServiceNow ISTM connector. When we introduced the ServiceNow SecOps connector we renamed the ServiceNow connector to ServiceNow ITSM. The deprecation of the ServiceNow connectors has to do only with the Elastic application in the ServiceNow store.

>In the response example in the Find connectors topic, "usesTableApi": false is missing in the config of the ServiceNow >connector.

This is only applicable to 7.16+
