### ISSUE TITLE
[DOCS] Improve Trusted Apps "wildcard"/"matches" field documentation

### ISSUE THREAD

**Issue by kevinlog** [elastic/security-docs#1467]
## Description 

We should add extra information to the Trusted Apps section in the documentation regarding "wildcard"/"matches".  

A section similar to the below:

Current behavior is:
- `?` : match any one character
- `*` :  match zero to many characters

## Acceptance Test Criteria

- [ ] Add a section to the existing description of Trusted Apps "wildcard"/"matches" section to include specific character info.
- [ ] `?` : match any one character
- [ ] `*` :  match zero to many characters

**Comment by joepeeples** [comment]
@kevinlog Are these character wildcards also valid for `8.0.0`? We're currently working on 8.0 docs and might be able to fit this in.

**Comment by kevinlog** [comment]
@joepeeples they are valid - it would be great to get it in for `8.0` if there's bandwidth!

**Comment by kevinlog** [comment]
@joepeeples they're also valid for `7.16`/`7.17` if it's possible to "backport" docs to earlier releases.

**Comment by joepeeples** [comment]
@kevinlog Yep, backporting should be no problem, especially for a fairly small change like this. I'll let you know when the PR is ready for review, hopefully soon!
