### ISSUE TITLE
[DOCS] Cases ServiceNow Support Matrix

### ISSUE THREAD

**Issue by jonathan-buttner** [elastic/security-docs#1493]
## Description 

We'd like to publish information regarding which versions of ServiceNow Kibana is able to integrate with and the functionality that we provide through the integration.

## Acceptance Test Criteria

As a user I can understand features and deprecations I will encounter when upgrading to a specific version of Kibana for the ServiceNow connectors integration.

## Notes

Google sheet support matrix: https://docs.google.com/spreadsheets/d/141QZ_zFhu7QoHEVEwha5R64rKmn0Vk4YOs5dzSD6yCs/edit#gid=0

Enhancement request: https://github.com/elastic/enhancements/issues/15241

Public Release notes: https://www.elastic.co/what-is/servicenow

### 7.16.0 Details
This section describes a few additional details around the 7.16.0 release of Kibana and its impact on the ServiceNow connectors:

#### Deprecation and Elastic Application
In 7.16.0 we deprecated ServiceNow connectors that leveraged the V2 Table API (all ServiceNow connectors up to this point in Kibana, both ITSM and SecOps). The deprecation means a user will see a warning describing the deprecation and will not be able to use that connector with any new cases. Existing cases also cannot switch their connector to a deprecated one. Existing cases that already were using the deprecated connector remain the same and are still supported.

The deprecation is to inform the user to upgrade the connectors to use the latest Elastic Application within ServiceNow. The new ServiceNow connectors (ITSM and SecOps) leverage the Import Set Table API instead of the V2 Table API. This allows user greater control over transforming and manipulating the data before ServiceNow incidents are created.

#### SecOps
The SecOps connector was made available within the Stack in addition to the Cases plugin. It can be used with Stack Alerts and Cases.

#### ITOM
The ITOM connector was introduced within the Stack only. It leverages an Events API which is separate from the V2 Table API or the Elastic Application/Import Set Table API.

Events API: https://docs.servicenow.com/bundle/rome-it-operations-management/page/product/event-management/task/send-events-via-web-service.html

**Comment by nastasha-solomon** [comment]
All doc updates completed.
