### ISSUE TITLE
[DOCS] Additional guidance to users on alerts index naming

### ISSUE THREAD

**Issue by marshallmain** [elastic/security-docs#1495]
## Description 

As a result of the RAC effort and migration to the rule registry, alerts in 8.0+ are no longer written to legacy signals indices but are instead written to alerts-as-data indices. We would like to provide guidance to users on how to query these indices going forward.

For reference, the index names and aliases are structured as follows:
#### Name
`.siem-signals-<space id>-NNNNNN` where `NNNNNN` is a number that counts up over time, starting from 000001
#### Aliases
`.siem-signals-<space id>`
`.alerts-security.alerts-<space id>` - **only added after upgrading to 8.0**

#### Name
`.internal.alerts-security.alerts-<space id>-NNNNNN`where `NNNNNN` is a number that counts up over time, starting from 000001
#### Aliases
`.siem-signals-<space id>`
`.alerts-security.alerts-<space id>`

Users should be strongly encouraged to **always** query their alerts, both legacy and alerts-as-data, through one of the aliases on the index such as `.siem-signals-<space id>` and **not** through a wildcard pattern on the index name such as `.siem-signals-<space id>-*`. However, patterns like this may be in use by customers today in custom dashboards, visualizations, rule queries, and any other places where they have written custom queries that search legacy alerts indices. If they use the pattern `.siem-signals-<space id>-*`, it will not match the alerts-as-data indices and their queries will not find new alerts after upgrading to 8.0.

#### Bad
`.siem-signals-<space id>-*` - not recommended because it will not match alerts-as-data indices
`.internal.alerts-security.alerts-*` - not recommended because it will not match legacy alerts indices, and couples queries to real index names which may change in the future. Querying through aliases, as shown below, is ideal.

#### OK
These patterns match aliases that are deprecated, but will allow queries to work across both legacy and alerts-as-data indices for the time being. When possible, users should upgrade their queries to use the recommended aliases below but it is not required immediately after upgrading.
`.siem-signals-<space id>` - note that there is no dash or wildcard after the space ID
`.siem-signals-*` for querying all spaces

#### Recommended
These are the recommended patterns that users should ideally be using. These will work across both legacy and alerts-as-data indices and follow the same `.alerts` naming scheme as other Kibana solutions that leverage alerts-as-data.
`.alerts-security.alerts-<space id>` - note that there is no dash after the space ID
`.alerts-security.alerts-*` - for querying all spaces

### User guidance
- After upgrade, users should check their existing custom visualizations, dashboards, and rule queries to ensure they are using the proper index alias names, either **OK** or **Recommended**
- When writing new visualizations, dashboards, and queries, they should use index patterns that match the recommended aliases. They should **not** use `.internal.alerts` in their index patterns.

**Comment by joepeeples** [comment]
@benironside and I are collaborating on creating a new topic for this information.

Once we have a solid draft, we should coordinate with @jmikell821 to include consistent wording in the [What's New in 8.0](https://github.com/elastic/security-docs/issues/1412) page.
