### ISSUE TITLE
[BUG] Missing detail in response example SN connector 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#1496]
In the response example in the [Find connectors](https://www.elastic.co/guide/en/security/current/cases-api-find-connectors.html) topic, `"usesTableApi": false` is missing in the config of the ServiceNow connector. Support for the V2 Table API was added in `7.9` and deprecated in `7.16`, so this change applies to `7.9`-`7.15`. 

<img width="700" alt="example-response" src="https://user-images.githubusercontent.com/79124755/151438197-5953dc13-f87c-4a2a-974f-ae9b91252932.png">

cc: @cnasikas

**Comment by nastasha-solomon** [comment]
@cnasikas think I'm wrong about how far back to backport this. If the line I'm adding says that the SN connector _does not_ use the table API, this should go into the docs for 7.16 and up.

**Comment by cnasikas** [comment]
Yes, the backport should go into the docs from 7.16 and up. The `usesTableApi` was introduced in 7.16.
