### ISSUE TITLE
[DOCS] Document known issue for "alerts on alerts" rules potentially having gaps after 8.0 upgrade

### ISSUE THREAD

**Issue by peluja1012** [elastic/security-docs#1533]
## Description 

**If a user creates any rule that references “.siem-signals” as a source index (“alerts-on-alerts”) or a rule that leverages “building block” alerts or in 7.x and then upgrades their environment to 8.0, the rule may encounter an execution failure, which in turn results in a gap in alert coverage.** The reason for this is that legacy alert documents that were generated by the “building block” rules pre-8.0 contain fields that are not compatible with the new AAD alerts index post-8.0. So when the main rule processes this legacy alert data and is ready to generate new alerts, the “index” operation into Elasticsearch fails.

More information can be found in this [document](https://docs.google.com/document/d/1ni7ZodkAXZ20-0mNvnns2rnPgTZpnn4BkAG2N-3xAe4/edit#).

## Acceptance Test Criteria

Document this as a known issue for 8.0. The related bug can be found [here](https://github.com/elastic/kibana/issues/124327).

## Notes

- More information about user impact in this [document](https://docs.google.com/document/d/1ni7ZodkAXZ20-0mNvnns2rnPgTZpnn4BkAG2N-3xAe4/edit#).

**Comment by nastasha-solomon** [comment]
Is currently doc'd in the 8.0 release notes as a known issue titled "Existing or new rules that use the legacy alerts index may temporarily fail after upgrading".
