### ISSUE TITLE
[DOCS] Enhance 8.0 upgrade documentation related to disabled detection rules

### ISSUE THREAD

**Issue by peluja1012** [elastic/security-docs#1562]
## Description 

In our 8.0 documentation we let users know ([here](https://www.elastic.co/guide/en/security/current/upgrade-intro.html) and [here](https://www.elastic.co/guide/en/security/current/release-notes-header-8.0.0.html#release-notes-8.0.0-rc2)) that their rules will be disabled upon upgrade to 8.0. We would like to add more information about how users could keep track of their enabled rules before upgrade so they can more easily find them and re-enable them after upgrade. We suggest the following changes.

1. The description of the issue in the [release notes](https://www.elastic.co/guide/en/security/current/release-notes-header-8.0.0.html#release-notes-8.0.0-rc2) section of the docs should match the description in the [Pre-upgrade requirements for 8.0](https://www.elastic.co/guide/en/security/current/upgrade-intro.html) section.
2. We should add the following additional information:
   - Users should be advised to keep track of their enabled rules before upgrade so that they are able to find them and re-enabled them after upgrade to 8.0.
   - They can capture a list of their enabled rules before upgrade by using the [Find rules API](https://www.elastic.co/guide/en/security/8.0/rules-api-find.html#_example_request_2) like this. We should also inform the users that they'll need to use `curl` or another HTTP tool to run Elastic Security API commands.
      ```
      GET /api/detection_engine/rules/_find?per_page=10000&filter=alert.attributes.enabled:true
      ```
   - Users should be informed that there will be a more streamlined approach in 8.0.1 to find rules that were disabled during the upgrade process.

**Comment by nastasha-solomon** [comment]
@peluja1012 thank you for filing this! I've updated the 8.0.0-rc2 release notes at https://github.com/elastic/security-docs/pull/1558.

**Comment by nastasha-solomon** [comment]
Not including the third bullet under #2 as @peluja1012 verified with @MikePaquette that this info should _not_ be included in the official docs.
