### ISSUE TITLE
[DOCS] Enhance 8.0.1 upgrade documentation related to disabled detection rules

### ISSUE THREAD

**Issue by peluja1012** [elastic/security-docs#1563]
## Description 

In our 8.0 documentation we let users know ([here](https://www.elastic.co/guide/en/security/current/upgrade-intro.html)) that their rules will be disabled upon upgrade to 8.0. We also [advise them](https://github.com/elastic/security-docs/issues/1562) to keep track of their enabled rules before upgrade so they can find them and re-enable them after upgrade. In 8.0.1, we add an automated way for users to keep track of their enabled rules before upgrade. We should update our 8.0.1 upgrade docs with the following:

1. ~~Users should be advised to **no longer** manually disable rules prior to upgrading to 8.0.1 from 7.17.~~
2. Any active/enabled rules prior to upgrade from 7.17 will be automatically disabled during the upgrade process and a tag with the value of `auto_disabled_8.0` will be added to those rules.
3. After upgrade, users can filter their rules by the newly added `auto_disabled_8.0` tag and then use bulk actions to re-enable them.

**Comment by jmikell821** [comment]
Merged #1642.
