### ISSUE TITLE
[BUG][Detections] Clarify 7.x privileges required to prevent creation/modification of Detection Rules

### ISSUE THREAD

**Issue by spong** [elastic/security-docs#1570]
## Description 

Was working with @octavioranieri on determining the required privileges to make Rules read-only, and we noticed that the `7.x` docs say that the Kibana space privileges should be `All` for the Security feature instead of `Read`. This appears to have been corrected in `8.0`, and so only needs to be updated in the `7.x` docs. The privileges docs [were overhauled](https://github.com/elastic/security-docs/pull/634/) in `7.13`, and so ideally this should be backported all the way to that release.

For the `Manage alerts` action of

[8.0 Docs](https://www.elastic.co/guide/en/security/current/detections-permissions-section.html#detections-on-prem-requirements)
<p align="center">
  <img width="500" src="https://user-images.githubusercontent.com/2946766/153961589-2324a837-18ba-47da-9c81-8c3a00fa5b38.png" />
</p>

[7.13](https://www.elastic.co/guide/en/security/7.13/detections-permissions-section.html#detections-on-prem-requirements) -> [7.17](https://www.elastic.co/guide/en/security/7.17/detections-permissions-section.html#detections-on-prem-requirements) Docs

<p align="center">
  <img width="500" src="https://user-images.githubusercontent.com/2946766/153962036-ff6c7c04-8beb-49af-b3d2-f061c4ff5af2.png" />
</p>

Relavant links:
PR that removed the need for `Saved Object Management` privileges in 7.12: https://github.com/elastic/kibana/pull/90895

**Comment by jmikell821** [comment]
Merged #1685.
