### ISSUE TITLE
[DOCS] Add note that `binary` fields are not supported in Detection Rule Exceptions

### ISSUE THREAD

**Issue by spong** [elastic/security-docs#1681]
## Description 

A recent issue was identified (https://github.com/elastic/kibana/issues/127168) where using fields of type `binary` within Rule Exceptions would result in the rule failing execution. Currently the UI allows selection of these field types, so users can end up with failing rules and no clear remediation steps. This issue is for either adding a note to the [exceptions docs](https://www.elastic.co/guide/en/security/current/detections-ui-exceptions.html#detections-ui-exceptions) or listing https://github.com/elastic/kibana/issues/127168 as a known issue, whichever you think makes the most sense from a docs perspective.

## Acceptance Test Criteria

As a user, I should be able to identify un/supported field types that can be used within exceptions, and/or any known issues around their use.

## Notes

This issue was discovered in `8.2`/`main`, and is present in all versions of the stack that have shipped with exceptions `7.9+`.

**Comment by joepeeples** [comment]
Of note (possible "for more information" xref): https://www.elastic.co/guide/en/elasticsearch/reference/current/binary.html
