### ISSUE TITLE
[DOCS] Cloud Security Posture Monitoring (CSPM) docs for 8.3

### ISSUE THREAD

**Issue by goodroot** [elastic/security-docs#1682]
## Description 

The CSPM team (build.security) will soon have features within Kibana + Integrations.

Integration documentation is taken care of as part of package registry.

Traditional docs are needed to provide context about cloud security posture monitoring.

This issue is to help CSPM team (@amar-rama-elastic) with the initial IA & asciidoc structuring.

The requirement is for "technical preview" CSPM documentation for 8.3.

Relates to: https://github.com/elastic/security-team/issues/3267

**Comment by jmikell821** [comment]
Merged #2089.
