### ISSUE TITLE
[BUG] Icon for Isolation is changed

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1698]
**Description**: 
Icon for Isolation is changed

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/current/admin-page-ov.html

**Screenshots**:
- Actual:
![1](https://user-images.githubusercontent.com/60252716/157616077-1bcdef12-643c-47cb-bb28-e869e50bbd48.PNG)

- Expected:
![image](https://user-images.githubusercontent.com/60252716/157616035-e648f6bb-df92-4ba3-882c-9d9324adcb38.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821
