### ISSUE TITLE
[BUG] Event Filters and Host isolation Exception tabs are also added in the policy

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1699]
**Description**: 
Event Filters and Host isolation Exception tabs are also added in the policy

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/current/admin-page-ov.html

**Screenshots**:
- Actual:
![2](https://user-images.githubusercontent.com/60252716/157616244-357209bb-3873-4562-87cc-4a5efba64975.PNG)

- Expected:
![image](https://user-images.githubusercontent.com/60252716/157616407-bc628cb8-b4b3-4527-ab11-cec9c8438bc3.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821
