### ISSUE TITLE
[BUG] The button for auto refresh is updated

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1700]
**Description**: 
The button for auto refresh is updated

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/current/host-isolation-ov.html

**Screenshots**:
- Actual:
![3](https://user-images.githubusercontent.com/60252716/157616548-767911cb-2bfa-44d1-b0dd-9bfa04344859.PNG)

- Expected:
![image](https://user-images.githubusercontent.com/60252716/157616686-994306e5-5c29-43f9-87d7-ee59958f7411.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821
