### ISSUE TITLE
[BUG] Remove the Lens visualization icon Create Case Modal under Documentation

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1701]
## Description 
Remove the Lens visualization icon from Create Case Modal Description under Documentation

## URL
_Issue is there on below 03 Pages of Documentation_

https://www.elastic.co/guide/en/security/8.1/alerts-ui-manage.html#signals-to-existing-cases
https://www.elastic.co/guide/en/security/8.1/alerts-ui-manage.html#detection-alert-status
https://www.elastic.co/guide/en/security/8.1/alerts-ui-manage.html

## Screen-Shoot

- Actual Result of documentation

![image](https://user-images.githubusercontent.com/59917825/157618968-982de50c-7a21-49dd-b960-79ab0e3d7ec5.png)

- Expected Result 

![image](https://user-images.githubusercontent.com/59917825/157618948-c86c6499-a9b9-498c-960d-4b90c555409e.png)

## Notes
Now user can only add Len Visualization under case comment and it will not show on create Case modal on both Case Page and Alert Page Attach to Case

![image](https://user-images.githubusercontent.com/59917825/157619082-61708dcb-2cff-4104-8510-297793dd8596.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Thanks for filing this @karanbirsingh-qasource! I fixed the outdated image under step 5 of the "Add an alert to a new case" section, but was not sure where additional fixes were needed in the two other sections you linked to in the issue description:

- [elastic.co/guide/en/security/8.1/alerts-ui-manage.html#detection-alert-status](https://www.elastic.co/guide/en/security/8.1/alerts-ui-manage.html#detection-alert-status)
- [elastic.co/guide/en/security/8.1/alerts-ui-manage.html](https://www.elastic.co/guide/en/security/8.1/alerts-ui-manage.html)

Would you mind pointing out where you noticed outdated instructions or screenshots in these sections? Thanks in advance for your help!

**Comment by karanbirsingh-qasource** [comment]
Hi @nastasha-solomon

apologizes for the confusion actually those 3 sub links are redirected to single page that is Manage Detection . Issue fix is only required for one place that as you mentioned is already been take care.

**Comment by nastasha-solomon** [comment]
Thanks for the clarification @karanbirsingh-qasource !

**Comment by nastasha-solomon** [comment]
Closing since was resolved in https://github.com/elastic/security-docs/pull/1718.
