### ISSUE TITLE
[BUG] Rename the Index Patterns to Data view under Management area

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1702]
## Description 

Rename the Index Patterns to Data view under Management area

## URL

https://www.elastic.co/guide/en/security/8.1/cases-overview.html#cases-export

## Screen-Shoot

- Actual Result

![image](https://user-images.githubusercontent.com/59917825/157620402-5a83feea-ddaf-4bdb-b052-48f0cbc62c28.png)

- Expected Result

![image](https://user-images.githubusercontent.com/59917825/157620364-a04ec63c-f083-425b-9a92-2b252c1a7dcd.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Closing since it was resolved in https://github.com/elastic/security-docs/pull/1718.
