### ISSUE TITLE
[BUG] Rename Data source to Data View inside timeline 

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1703]
## Description 
Rename Data source to Data View inside timeline 

## URL

_Multiple instance are there in the below 02 pages where rebranding is required_

https://www.elastic.co/guide/en/security/8.1/es-ui-overview.html#draggable-timeline-elements

https://www.elastic.co/guide/en/security/8.1/visual-event-analyzer.html#visual-analyzer-ui

## Screen-Shoot

- Actual Result

![image](https://user-images.githubusercontent.com/59917825/157621450-12031f23-1c5e-4c80-88a1-fc880e8f30f9.png)

![image](https://user-images.githubusercontent.com/59917825/157621680-be9b8e91-b810-4f55-9eda-f23a7a384568.png)

- Expected Result

![image](https://user-images.githubusercontent.com/59917825/157621954-94f0cf08-b4dd-4001-ba37-d9fd9dad7540.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Closing since it was resolved in https://github.com/elastic/security-docs/pull/1718.
