### ISSUE TITLE
[BUG] Elastic Security Solution Page Explore Page order

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1704]
## Description 
Elastic Security Solution Page Explore Page order to switch keeping host page to first 

## URL

https://www.elastic.co/guide/en/security/8.1/index.html

## Screen-Shoot

- Actual Result

![image](https://user-images.githubusercontent.com/59917825/157622387-0e704c5f-5de3-4edc-aaed-3e76e6f8c3fa.png)

- Expected Result

![image](https://user-images.githubusercontent.com/59917825/157622415-5140c735-767c-48d1-8618-232576f08fc8.png)

![image](https://user-images.githubusercontent.com/59917825/157623402-17b52334-f436-4340-ae00-11031183254c.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by jmikell821** [comment]
This was resolved in `8.2`.
