### ISSUE TITLE
[BUG] Old UI for Alert page canvas on Visual Event Analyze Documentation Page

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1706]
## Description 

Old UI for Alert page canvas on Visual Event Analyze Documentation Page

## URL

https://www.elastic.co/guide/en/security/8.1/visual-event-analyzer.html#find-events-analyze

## Screen-Shoot

- Actual Result

![image](https://user-images.githubusercontent.com/59917825/157625878-1a480764-4292-4b5a-9789-54f5bb4d6956.png)

- Expected Result

![image](https://user-images.githubusercontent.com/59917825/157625893-59bdd054-5799-4ec4-bdf5-0867f3ba0d64.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Closing since it was resolved in https://github.com/elastic/security-docs/pull/1718.
