### ISSUE TITLE
[BUG] Old Toolbar of Alerts page showing in visual event analyzer

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1707]
## Description 

Old Toolbar of Alert page showing in Documentation

## URL
https://www.elastic.co/guide/en/security/8.1/visual-event-analyzer.html#find-events-analyze

## Screen-Shoot

- Actual Result

![image](https://user-images.githubusercontent.com/59917825/157626526-c6e3fc6a-b887-4a6c-a24b-23d722c42311.png)

- Expected Result

![image](https://user-images.githubusercontent.com/59917825/157626505-ead1b905-8f50-4e85-9c9c-77cd446c8972.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Closing since resolved in #1718 .
