### ISSUE TITLE
[BUG] Old Alert Flyout under Host Risk Documentation

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1708]
## Description 

Old Alert Flyout under Host Risk Documentation

## URL

https://www.elastic.co/guide/en/security/8.1/host-risk-score.html#_view_host_risk_score_data

## Screen-Shoot

- Actual Result

![image](https://user-images.githubusercontent.com/59917825/157630578-db0adf54-2010-431d-a860-e648cc0dfe1b.png)

- Expected Result

![image](https://user-images.githubusercontent.com/59917825/157630971-51a69012-0c63-4da4-a276-daedba5176eb.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821
