### ISSUE TITLE
[BUG] Timeline Schema of Documentation requires update

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1709]
## Description 

Timeline Schema of Documentation require updatation

- Old Data Source terminology expected Data View should be there
- Positioning of Timeline elements need to be updated 

## URL

https://www.elastic.co/guide/en/security/8.1/timeline-object-schema.html

## Screen-Shoot

- Actual Result

![image](https://user-images.githubusercontent.com/59917825/157636218-d18d58ad-c051-4553-be3a-e3d81db132f8.png)

- Expected Result

![image](https://user-images.githubusercontent.com/59917825/157638008-08d7cb5f-d6aa-4340-be3d-74e822a1eb05.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821
