### ISSUE TITLE
[BUG] Missing API documentation for [Cases]Stub Metrics 

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1710]
## Description 
Missing API documentation for [Cases]Stub Metrics 

## URL

https://www.elastic.co/guide/en/security/8.1/cases-api-overview.html

## Reference Ticket 

https://github.com/elastic/kibana/pull/119393

## Notes

**Method:** `GET`
**URL:** `<kibana_url>/api/cases/metrics/<case_id>?features=["alerts.count","alerts.users","alerts.hosts","actions.isolateHost","connectors","lifespan"]`
**Response:**
```
{
    "alerts": {
        "count": 1,
        "hosts": {
            "total": 1,
            "values": [
                {
                    "name": "windows-machine",
                    "id": "4143c277-074e-47a9-b37d-37f94b508705",
                    "count": 1
                }
            ]
        },
        "users": {
            "total": 1,
            "values": [
                {
                    "name": "zeus",
                    "count": 1
                }
            ]
        }
    },
    "actions": {
        "isolateHost": {
            "isolate": {
                "total": 0
            },
            "unisolate": {
                "total": 0
            }
        }
    },
    "connectors": {
        "total": 1
    },
    "lifespan": {
        "creationDate": "2022-03-10T06:19:10.525Z",
        "closeDate": null,
        "statusInfo": {
            "openDuration": 14420046,
            "inProgressDuration": 8015,
            "reopenDates": [
                "2022-03-10T10:20:43.447Z"
            ]
        }
    }
}
```

![image](https://user-images.githubusercontent.com/59917825/157641630-edc6988a-c6d5-4f31-b041-4220fd95bbde.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by jmikell821** [comment]
Hi @cnasikas -- do you think you could help us drafting the API documents for this?

**Comment by cnasikas** [comment]
Hi both! Thank you for the feedback. We intentionally do not want to publish the API to our users. The API is not mature and is subject to change in the future. If we publish the API, it will very difficult for us to do changes.

**Comment by karanbirsingh-qasource** [comment]
thanks @cnasikas for looking and sharing the update for this.

Closing this issue as this is expected behavior.
