### ISSUE TITLE
[DOCS] Create new "Deploy Elastic Endpoint" section 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#1757]
Related issue: #1312 

Google doc to macOS deployment instructions [here](https://docs.google.com/document/d/1016kbw02GqqfvxJqg7YCkYZ-fs1upaubplrjHdIRQfA/edit#). 

Create a new sub-section within "Getting Started" that bundles all deployment topics together: 
- [Configure and install the Endpoint Security integration](https://www.elastic.co/guide/en/security/current/install-endpoint.html)
- [Install Elastic Endpoint manually](https://www.elastic.co/guide/en/security/current/deploy-elastic-endpoint.html)
- Deploying Elastic Endpoint with Mobile Device Management, etc.

**Comment by ferullo** [comment]
We have access to a small JAMF instance so we can use that to test the MDM documentation is accurate.

**Comment by jmikell821** [comment]
Tracking Endpoint updates in meta #3890.
