### ISSUE TITLE
Add Documentation Details for Malware Prevention 

### ISSUE THREAD

**Issue by bradenlpreston** [elastic/security-docs#176]
## Description 

Customers often ask - "how do you prevent malware?" we should describe malware prevention in more detail in the docs.

## Acceptance Test Criteria

Something similar to <endgame_platform>/api/help/Content/Admin%20User%20Guide/Sensor%20Topics/malware_protection_ov.htm?Highlight=malwarescore

@jmikell821 , @JamieRButler , @cosiomoises , @mark-dufresne , @bfilar

**Comment by DonNateR** [comment]
Duplicate of number #226
