### ISSUE TITLE
[DOCS] Retroactive Endpoint 8.1.1 release notes

### ISSUE THREAD

**Issue by ferullo** [elastic/security-docs#1760]
Endpoint failed to include in the 8.1.1 release notes that we fixed a pretty serious bug that was affecting users. If we can, can we get the 8.1.1 notes updates to include:

* Fixed a bug with Endpoint Security introduced in 7.17.1, 8.0.1, and 8.1.0 that could in some circumstances prevent benign files from being deleted on Windows.

**Comment by ferullo** [comment]
> To clarify, did you want the release versions (7.17.1, 8.0.1, and 8.1.0) included in the release note summary?
> In the summary that you offered, are you saying that this bug was discovered in 7.17.1 and persisted in 8.0.1 and 8.1.0 until it was fixed in 8.1.1?

The problem was new to each of those versions and so wasn't in any prior Endpoint versions. I don't feel strongly whether to call out in the note the versions where the issue was first introduced, my thought was though to not make a user running a prior unaffected version think they ought to upgrade to pick up this fix. Whatever is most commonly done works for me.

> What's the PR for this bug fix?

Sure, links are:
* Private GitHub [issue](https://github.com/elastic/endpoint-dev/issues/10689) and [PR](https://github.com/elastic/endpoint-dev/pull/10699)

**Comment by nastasha-solomon** [comment]
@ferullo requested that the PR remain internal because it's within a private repo, so not including the PR number in the release notes.
