### ISSUE TITLE
[DOCS] Case API for adding comment is incorrect

### ISSUE THREAD

**Issue by pixelsquared** [elastic/security-docs#1769]
The API for adding comments to a case does not say that it requires "owner" and "rule" fields in the request. However without those fields kibana will reject the request. I think only for "alert" type comments but not 100% sure.

https://www.elastic.co/guide/en/security/current/cases-api-add-comment.html#cases-api-add-comment

**Comment by nastasha-solomon** [comment]
Thank you for filing this @pixelsquared! @lcawl and I have started looking into this and I'll set up a PR once I finish testing the API.

**Comment by nastasha-solomon** [comment]
@pixelsquared a brief summary of my test findings and some notes on the current docs:
- The `owner` field _is_ required for string comments and when adding an alert as a comment. When defining this field, users will need to specify which solution that owns the case. For the Security app, they'd enter the value `securitySolution`. 
-  When adding an alert to the case, details about the rule that triggered the alert are required. More specifically, users will need to define the rule ID (`id`) and the rule name (`name`).  
- As we continue to develop docs about cases in other solutions, we'll likely need to revisit the note that says Elastic Security alerts are the only alerts supported. 
- Our example response needs to be refreshed, the format has changed. 

cc: @cnasikas @academo @peteharverson

**Comment by pixelsquared** [comment]
@nastasha-solomon Thanks for the update! I did get it to work.
