### ISSUE TITLE
[DOCS] Known issue with Endpoint 8.1.1

### ISSUE THREAD

**Issue by ferullo** [elastic/security-docs#1779]
Endpoint 8.1.1 will not run on Windows 8.1 or Server 2012 R2 as described in this public issue https://github.com/elastic/endpoint/issues/15

The issue does not affect any other Endpoint versions. It will be resolved in a change to 8.1.2 ([release note request](https://github.com/elastic/security-docs/issues/1776).

Oddly, this bug does _not_ affect 7.17.1 but we're also making the same change to that version which needs a [release note](https://github.com/elastic/security-docs/issues/1761#issuecomment-1080753167).

The underlying problem is in the release process not in Endpoint code. So any Endpoint released after this problem surfaced would have the bug. That's why changes are being made for 7.x even though there are no affected 7.x versions.

**Comment by nastasha-solomon** [comment]
Documenting this in https://github.com/elastic/security-docs/pull/1778.

**Comment by nastasha-solomon** [comment]
Merged https://github.com/elastic/security-docs/pull/1778.
