### ISSUE TITLE
[DOCS] 8.1.1 Known Performance Issue Advisory

### ISSUE THREAD

**Issue by jethr0null** [elastic/security-docs#1785]
## Add recommendation to wait for the next patch release to upgrade (skipping the current 8.1.1 release) for users on the following 2 pages: 

[elastic.co/guide/en/security/8.1/upgrade-intro.html](https://www.elastic.co/guide/en/security/8.1/upgrade-intro.html)
[elastic.co/guide/en/security/current/release-notes-header-8.1.0.html#release-notes-8.1.1](https://www.elastic.co/guide/en/security/current/release-notes-header-8.1.0.html#release-notes-8.1.1)

There was a bug in 8.1.1 that resulted in slow UI responsiveness and, as such, we'd like to add an advisory to security users (asap) to hold off on upgrading until the next patch release is available. 

cc @jmikell821 @peluja1012

**Comment by nastasha-solomon** [comment]
@jmikell821 adding this content to https://github.com/elastic/security-docs/pull/1778 since I've already been updating the `8.1.1` release notes section.
