### ISSUE TITLE
[DOCS] Document new "Sessions" tab on Hosts page 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#1796]
Related PRs/issues: 
- https://github.com/elastic/kibana/issues/125950
- https://github.com/elastic/kibana/pull/127920
- https://github.com/elastic/security-docs/issues/1781

Document the new **Sessions** tab on the Hosts page. Users will see an EuiDataGrid table focused on session events and be able to launch the session viewer in an investigative timeline. Similar to how External Alerts are currently focused on events from the endpoint and can launch the analyze event tool. 

**Sessions view on Hosts page** 
![image](https://user-images.githubusercontent.com/57149392/161113194-0bc098e7-ffcf-4583-9569-5ee44ea57d7a.png)

**Sessions view on Hosts details page**

![image](https://user-images.githubusercontent.com/57149392/161113338-afee5f29-aa73-46c0-a834-9bd9483fc612.png)

**Comment by benironside** [comment]
I believe this was fixed in another issue/PR, because the Hosts topic refers to the Sessions tab and links to the Session View topic.
