### ISSUE TITLE
[BUG] Missing breaking change notice for preconfigured connectors in cases

### ISSUE THREAD

**Issue by a03nikki** [elastic/security-docs#1801]
**Description**: 
The change introduced by kibana#120686 is a breaking change.  In versions 7.16 and earlier, preconfigured connectors  (in the kibana.yml) could be used to push cases to 3rd party systems.  After 7.17, they are no longer allowed and there was a note added to the connectors page for cases.  The bug fix description gives no indication that preconfigured connectors were removed either.

This should be called out in the documentation as a breaking change because it broke prior functionality.

**URL link or topic name**:

<https://www.elastic.co/guide/en/security/7.17/release-notes-header-7.17.0.html#bug-fixes-7.17.0>

> 7.17.0
>  Bug fixes and enhancements
> ...
> Fixes an issue that caused the Cases feature to crash the UI when determining if a connector was deprecated ([#120686](https://github.com/elastic/kibana/pull/120686)).

The only thing that was updated was <https://www.elastic.co/guide/en/security/7.17/cases-ui-integrations.html>

> Note: [Preconfigured connectors](https://www.elastic.co/guide/en/kibana/7.17/pre-configured-connectors.html) cannot be used with cases.

**Related Issues:**
- https://github.com/elastic/security-docs/issues/1358
- https://github.com/elastic/security-docs/pull/1454
- https://github.com/elastic/kibana/pull/120686

**Comment by nastasha-solomon** [comment]
Thanks for filing this @a03nikki ! To clarify, are you primarily requesting that #120686 be moved out the "Bug fixes and enhancements" section and categorized as a breaking change in the 7.17.0 release notes?

**Comment by a03nikki** [comment]
@nastasha-solomon : I think it is fine to be listed as a bug fix with its current description.  
But we need to add the breaking change list about the preconfigured connectors no longer being an option with cases.  I think it would need to be added to the 7.17 release notes at a minimum.

https://github.com/elastic/kibana/pull/120686 summary states

> Release Notes
> Pre-configured connectors cannot be used within Cases.

**Comment by nastasha-solomon** [comment]
Merged #1810 .
