### ISSUE TITLE
[DOCS][Rules][Data Views] - Data views available in rule creation flow

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#1832]
## Description 

Users can specify data views wherever index pattern specification is available in order to take advantage of runtime fields, which are associated with a data view.

Issue: https://github.com/elastic/security-team/issues/2874
PR: https://github.com/elastic/kibana/pull/130929

## Acceptance Test Criteria

- When creating a rule, the user should be able to select a **Data View**  to be used as the source of data
   - Note that this should be **in addition to** allowing them to select "source index patterns". The ability to select "source index patterns" is still needed because prebuilt rules rely on it.
   - For Indicator Match rules, a user should also be able to select a "Data View" as the indicator data source.
- After a "Data View" is selected, when entering a "custom query" the user should see runtime fields associated with the "Data View" in the field suggestions.
- After a "Data View" is selected, when entering an "EQL query" the user should be able to use runtime fields associated with the "Data View" in the EQL editor.
- After a "Data View" is selected, runtime fields associated with the "Data View" should be available as options for field overrides such as `rule name override`.
- When creating a Threshold Rule, the user should be able to select a runtime field as the `group by` field, if they configured a Data View as the data source.
- When creating an Indicator Match rules, runtime fields associated with the "Data View" should be available as options for the `Indicator mapping field` and `Indicator index field` configurations.
- When selecting a Data View, the user should have the option or a link to add a new runtime field to their selected Data View. Similar to the workflow in Discover.
- For the "alerts on alerts" scenario, the user should be guided towards using the `.alerts` Data View so they can take advantage of any runtime fields they may have added.

## Notes

- Be sure to add any necessary screenshots, code text or console commands for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by dhurley14** [comment]
related PR: https://github.com/elastic/kibana/pull/130929

**Comment by dhurley14** [comment]
some screenshots please let me know if you need more!

<details><summary>Data view selection</summary>

<img width="936" alt="data_view_selection" src="https://user-images.githubusercontent.com/915763/177802682-3f9a3063-64df-4959-bfa2-9066dba06da6.png">

</details>

<details><summary>Example data view options</summary>

<img width="934" alt="data_view_item_list" src="https://user-images.githubusercontent.com/915763/177802679-6783e587-bfe2-4f0a-bec2-84ce3a94ab2e.png">

</details>

<details><summary>Rule details view</summary>

<img width="1153" alt="rule_details_data_view" src="https://user-images.githubusercontent.com/915763/177802669-0c982619-f2ab-422f-b0dd-2b40bc8b0d0f.png">

</details>

**Comment by nastasha-solomon** [comment]
@dhurley14 when you're ready, feel free to reach out to the @elastic/security-docs team for help crafting and reviewing the UI tour text for this feature.

**Comment by yctercero** [comment]
Error state when imported rule where data view does not exist - https://github.com/elastic/kibana/issues/137841

**Comment by joepeeples** [comment]
Reassigning to @jmikell821 since she's documenting rule creation for 8.4 in #2258.

**Comment by yctercero** [comment]
Hey there! We'd discussed needing additional details for documenting. Hopefully the following helps:

## API changes
- Rule creation
    -  Can now specify a `data_view_id`
    - There is no schema check/validation disallowing a user from specifying both an `index` and a `data_view_id`, BUT our detection logic is that if a `data_view_id` is specified, that is what will be used to search
- Rule update/rule patch
    -  Can update or patch `data_view_id`
-  /api/detection_engine/rules/_bulk_action
    -   There's no bulk actions specific to data views, but if a user selects to bulk edit indices of a bunch of rules, and some of those rules use data views the following behavior applys:
    - If `overwriteDataViews` is set to `true` - even rules using data views will be updated to include the index changes and the `data_view_id` will be removed
    - If `overwriteDataViews` is set to `false` - no updates or changes will be made to rules using data views

## Affected flows
### Rule Creation
- User can select to use index pattern, OR data view
- Data view selector currently displays the data view's `title` property, not `name`
- Only selection of a single data view, not multiple, is supported
- Runtime fields associated with data views are available
- Any runtime fields need to be created prior to rule creation. There's no options to create runtime fields or data views in rule creation.
- Options to overwrite fields will also display runtime fields if relevant (timestamp override, risk score...)
- If a user selects the Security default data view, we show a warning letting them know that using this data view could result in alerts on alerts
<img width="949" alt="Screen Shot 2022-08-08 at 10 10 24 AM" src="https://user-images.githubusercontent.com/10927944/183475512-88435a63-5d38-439e-8789-56b76cae7d34.png">

<details>
<summary>Rule creation</summary>
<img width="1031" alt="Screen Shot 2022-08-08 at 10 24 38 AM" src="https://user-images.githubusercontent.com/10927944/183477111-0bf5f451-6def-433f-a485-7505f004bd0c.png">

</details>

### Rule Edit
- User can select to use index pattern OR data view
- Data view selector currently displays the data view's `title` property, not `name`
- Only selection of a single data view, not multiple, is supported
- Runtime fields associated with data view are available
- 👀 If the selected data view no longer exists (like it was deleted), user is prompted with a warning, letting them know
  - To test create a rule with a data view, go to Stack Management --> Data Views --> delete the data view you selected, go back to the rule and click to edit
<details>
<summary>Rule Edit when error present</summary>
<img width="1030" alt="Screen Shot 2022-08-08 at 10 27 36 AM" src="https://user-images.githubusercontent.com/10927944/183477568-65c5b9bb-253a-433d-9854-4bdd5d54e00f.png">

</details>

### Rule Details
- User can see what data view they've selected - text displayed is the data view `title`, not `name` (name introduced 8.4 - we weren't aware till too late)
- 👀 If the selected data view no longer exists (like it was deleted), user is prompted with an error, letting them know that rule execution failed
  - To test create a rule with a data view, go to Stack Management --> Data Views --> delete the data view you selected, go back to the rule
<details>
<summary>Rule details when error present</summary>
<img width="2292" alt="Screen Shot 2022-05-19 at 1 47 14 PM" src="https://user-images.githubusercontent.com/10927944/169401880-5ab4bf55-2bc6-4ea8-9026-8de4dd8eba7b.png">
</details>

<details>
<summary>Rule details</summary>
<img width="1147" alt="Screen Shot 2022-08-08 at 10 29 16 AM" src="https://user-images.githubusercontent.com/10927944/183477866-ff875db8-1c0d-4546-925d-b388a93cf0b4.png">

</details>

### Rules Management
- User can select to bulk edit rule index patterns
    - If they select to apply changes to rules with data views, those rules will be updated as well
    - If they do not select to apply changes to rules with data views, those rules are not updated, but the rest are
- To test:
    - Create a rule with a data view and a rule with index patterns. Go to rule management and select both rules. Select 'Bulk actions' --> Add index patterns --> go through flow to add index pattern (don't select any boxes). The rule using index patterns should be updated, the rule using data views should not be.
    - Create a rule with a data view and a rule with index patterns. Go to rule management and select both rules. Select 'Bulk actions' --> Add index patterns --> go through flow to add index pattern --> check the box `Apply changes to rules configured with data views`. The rule using index patterns should be updated, the rule using data views should not be.
<details>
<summary>Bulk action flyout</summary>
<img width="675" alt="Screen Shot 2022-05-19 at 1 54 00 PM" src="https://user-images.githubusercontent.com/10927944/169403077-71a17570-40f4-4f94-8791-c24a4237036c.png">
</details>
<details>
<summary>Bulk action flyout success toast</summary>
<img width="402" alt="Screen Shot 2022-05-19 at 1 28 22 PM" src="https://user-images.githubusercontent.com/10927944/169403161-c1edd45b-c8b6-4ef1-9a29-6906474eb78e.png">
</details>

### Add/edit rule exception modal
- If rule list is assigned to is using runtime fields, runtime fields show as a field option to add an exception for
