### ISSUE TITLE
[BUG] Incorrect screenshot for Select Agents section under Run Osquery flyout.

### ISSUE THREAD

**Issue by arvindersingh-qasource** [elastic/security-docs#1867]
**Describe the bug**
Incorrect screenshot for Select Agents section under Run Osquery flyout.

**Guide Link**
https://security-docs_1836.docs-preview.app.elstc.co/guide/en/security/master/alerts-run-osquery.html

**Steps**
1. Open Kibana Docs for Os query Module with link - https://security-docs_1836.docs-preview.app.elstc.co/guide/en/security/master/alerts-run-osquery.html
2. Scroll down to ```Run Osquery``` section.
3. Observe that screenshot for Select Agents section under Run Osquery flyout is incorrect as there is count of selected agents is present under dropdown and in screenshot on document is not mentioned.

**Actual Result**
![2](https://user-images.githubusercontent.com/78947943/164419763-f417eaab-a3de-447d-aadd-5519b73a7094.png)

**Expected Results**
![3](https://user-images.githubusercontent.com/78947943/164419825-c388a624-d36d-436e-bc2a-4b758782558e.png)

**Comment by arvindersingh-qasource** [comment]
@manishgupta-qasource  Please review this bug.

Thanks.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by arvindersingh-qasource** [comment]
Hi @nastasha-solomon ,

Thanks for the update.
We have validated this ticket on updated Kibana Documentation and found that issue is now **fixed**.
### Please find the below observations
#### Kibana Documentation Guide
https://security-docs_1836.docs-preview.app.elstc.co/guide/en/security/master/alerts-run-osquery.html

#### Screenshot
![1](https://user-images.githubusercontent.com/78947943/165036731-c00c064c-6f5a-42ca-b337-b50b71e3e991.png)

Hence, we are closing this ticket.

Thanks.
