### ISSUE TITLE
[BUG] Incorrect screenshot for Results section under Run Osquery flyout.

### ISSUE THREAD

**Issue by arvindersingh-qasource** [elastic/security-docs#1868]
**Describe the bug**
Incorrect screenshot for Results section under Run Osquery flyout.

**Guide Link**
https://security-docs_1836.docs-preview.app.elstc.co/guide/en/security/master/alerts-run-osquery.html

**Steps**
1. Open Kibana Docs for Os query Module with link - https://security-docs_1836.docs-preview.app.elstc.co/guide/en/security/master/alerts-run-osquery.html
2. Scroll down to ```Run Osquery``` section.
3. Observe that screenshot for Results section under Run Osquery flyout is incorrect as in Document it is shown that there is an option for user to view Results in Full Screen mode and in Kibana there is no such option.

**Actual Result**
![3](https://user-images.githubusercontent.com/78947943/164420971-2634f3c0-7ee1-4ab7-b3b2-5708be1b5181.png)

**Expected Results**
![4](https://user-images.githubusercontent.com/78947943/164421018-553f2f90-5e6f-44b1-ba5c-b963ee964b6c.png)

**Comment by arvindersingh-qasource** [comment]
@manishgupta-qasource  Please review this bug.

Thanks.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Thanks for filing this @arvindersingh-qasource ! I just tested this on our docs server, which is running 8.2.0 BC-3 and grabbed the correct screenshots. Will ping you here once the doc updates are ready. Thanks!

**Comment by arvindersingh-qasource** [comment]
Hi @nastasha-solomon ,

Thanks for the update.
We have validated this ticket on updated Kibana Documentation and found that issue is now **fixed**.
### Please find the below observations
#### Kibana Documentation Guide
https://security-docs_1836.docs-preview.app.elstc.co/guide/en/security/master/alerts-run-osquery.html

#### Screenshot
![2](https://user-images.githubusercontent.com/78947943/165036824-78e33074-d891-47dd-a60f-7532c9de9c77.png)

Hence, we are closing this ticket.

Thanks.
