### ISSUE TITLE
[BUG] Endpoint events have other fields as well apart from the endpoint.events.network field

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1869]
**Description**: 
Endpoint events have other fields as well apart from the endpoint.events.network field

**URL link or topic name**: 
- https://security-docs_1823.docs-preview.app.elstc.co/guide/en/security/master/event-filters.html#event-filters

**Screenshots**:
- Actual:
![image](https://user-images.githubusercontent.com/60252716/164415554-fef46487-0c5e-4605-8240-1edbd3cf3188.png)
![image](https://user-images.githubusercontent.com/60252716/164415960-98ad7bf4-7cb5-4ae1-a301-b8192be3b822.png)

- Expected:
![image](https://user-images.githubusercontent.com/60252716/164416421-f2d452b7-2e35-4cb0-ad38-d81f6b575404.png)
![image](https://user-images.githubusercontent.com/60252716/164416547-ccb12912-b03d-48d3-a342-e38eb589ceb0.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
I don't think the docs are implying that the _only_ field that endpoint events have is `endpoint.events.network`. That field is mentioned as a way to narrow down results, not an absolute statement of everything included in an event.

**Comment by muskangulati-qasource** [comment]
@joepeeples,

Thank you for the update.

We are closing this issue as it's written as expected.

Thanks!
