### ISSUE TITLE
[BUG] The Linux event collection UI have been updated for a new toggle

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1870]
**Description**: 
The Linux event collection UI have been updated for a new toggle

**URL link or topic name**: 
- https://security-docs_1812.docs-preview.app.elstc.co/guide/en/security/master/configure-endpoint-integration-policy.html#event-collection

**Screenshots**:
- Actual:
![Linux](https://user-images.githubusercontent.com/60252716/164416816-af5a7855-3002-4d6e-ae5a-39e4bc426f43.PNG)

- Expected:
![Linux_Kibana](https://user-images.githubusercontent.com/60252716/164416807-9dc62ec9-08d6-49b6-bf96-43a42eca4d28.PNG)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
The new "Include session data" toggle is being documented in PR https://github.com/elastic/security-docs/pull/1846.

**Comment by muskangulati-qasource** [comment]
Hi @joepeeples,

Thank you for looking into our issue.

We looked into the updated docs and found that issue is now fixed. 🟢

**Screenshot**
![image](https://user-images.githubusercontent.com/60252716/164701216-4a0c7acc-fcc0-402c-94f5-7729f646cd82.png)

Hence, we are closing this issue and marking it as 'QA Validated'.

Thanks!!
