### ISSUE TITLE
[BUG] The enrollment command section is updated

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1871]
**Description**: 
The enrollment command section is updated

**URL link or topic name**: 
- https://security-docs_1812.docs-preview.app.elstc.co/guide/en/security/master/install-endpoint.html#enroll-agent

**Screenshots**:
- Actual:
![Enrollment Command](https://user-images.githubusercontent.com/60252716/164417008-fc9954a5-0598-4828-afe6-8725264d0fff.PNG)

- Expected:
![image](https://user-images.githubusercontent.com/60252716/164417170-f1aa2d09-2971-4926-a1a8-43c16cc6a599.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
@muskangulati-qasource Please see PR #1886, which should resolve this issue. Thank you!

**Comment by muskangulati-qasource** [comment]
Hi @joepeeples,

Thank you for looking into our issue.

We looked into the updated docs and found that issue is now fixed. 🟢

**Screenshot**
![image](https://user-images.githubusercontent.com/60252716/165024644-21270bf8-edc1-44cf-a7f7-7841fae402d8.png)

Hence, we are closing this issue and marking it as 'QA Validated'.

Thanks!!
