### ISSUE TITLE
[BUG] The Tab name is wrongly written as Blocked instead of Blocklist 

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1872]
**Description**: 
The Tab name is wrongly written as Blocked instead of Blocklist 

**URL link or topic name**: 
- https://security-docs_1812.docs-preview.app.elstc.co/guide/en/security/master/sec-manage-intro.html#sec-manage-intro

**Screenshots**:
- Actual:
![BlockedInsteadOfBlocklist](https://user-images.githubusercontent.com/60252716/164417664-23e888cc-e6dc-4129-b060-525f0cf55426.PNG)

- Expected:
![image](https://user-images.githubusercontent.com/60252716/164417871-6b8dec15-6c80-4454-82fb-f598a56f4532.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
This paragraph is referring to the general things that the user can manage, not the literal names of each page/tab in the app. Since the Blocklist page allows users to manage blocked applications, it's appropriate as written.

**Comment by muskangulati-qasource** [comment]
@joepeeples,

Thank you for the update.

We are closing this issue as it's written as expected.

Thanks!
