### ISSUE TITLE
[BUG] No mention of the Blocklist tab under the install endpoint page

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1873]
**Description**: 
No mention of the Blocklist tab under the install endpoint page

**URL link or topic name**: 
- https://security-docs_1812.docs-preview.app.elstc.co/guide/en/security/master/install-endpoint.html#install-endpoint

**Screenshot**:
![NoMentionOfBlocklist](https://user-images.githubusercontent.com/60252716/164419772-b95d64f4-0d95-4258-b9ce-9bd13d7dd2ee.PNG)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
Thanks for the catch, @manishgupta-qasource! I already have an issue (https://github.com/elastic/security-docs/issues/1818) to follow up on some other fixes related to blocklist, so I've added this as a task on that issue.

**Comment by muskangulati-qasource** [comment]
Hi @joepeeples,

Do you want us to close this issue as it is already being checked under the other issue? Or do you want us to keep it open to verify the fix when it is merged?

Thanks!

**Comment by joepeeples** [comment]
> Do you want us to close this issue as it is already being checked under the other issue? Or do you want us to keep it open to verify the fix when it is merged?

OK to close this issue, @muskangulati-qasource -- the fix in the other issue/PR has been merged now. Thanks!
