### ISSUE TITLE
[BUG] No mention of the policies tab under the new features release notes

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1875]
**Description**: 
No mention of the policies tab under the new features release notes

**URL link or topic name**: 
- https://security-docs_1828.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.2.0.html#features-8.2.0

**Screenshots**:
![image](https://user-images.githubusercontent.com/60252716/164420237-8c8effce-afaf-4e18-8c25-cfbf6f595900.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Thanks for catching this, @muskangulati-qasource ! I've added the summary for the new Policies page at https://github.com/elastic/security-docs/pull/1828. Please take a look when you have a chance - thank you!

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

Thank you for looking into our issue.

We looked into the updated docs and found that issue is now fixed. 🟢

**Screenshot**
![image](https://user-images.githubusercontent.com/60252716/164700074-a0e7e6f1-9454-4958-9a97-b92a0b9caf37.png)

Hence, we are closing this issue and marking it as 'QA Validated'.

Thanks!!
