### ISSUE TITLE
[BUG] Authentication Tab and Graph should not present on Hosts page.

### ISSUE THREAD

**Issue by karanverma-qasource** [elastic/security-docs#1879]
**Description**: 
Authentication Tab and Graph should not present on Hosts page.

**Actual Result and Guide link**:

- Authentication Tab and Graph should not present on Hosts page:  https://security-docs_1809.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html#overview-ui

![image](https://user-images.githubusercontent.com/91867110/164442737-8e2a6bf5-2890-41f1-8337-4ed7f80380ee.png)

**Expected Result:**

![image](https://user-images.githubusercontent.com/91867110/164442880-fc1d7c22-9f86-40e3-a0aa-e28c3ef82ddd.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource the updated image is ready for your review at https://github.com/elastic/security-docs/pull/1865 - thanks!

**Comment by karanverma-qasource** [comment]
Hi @nastasha-solomon,

Thank you for looking into our issue.

We looked into the updated docs and found that issue is now fixed. 🟢

**Screenshot**

[Host page](https://security-docs_1865.docs-preview.app.elstc.co/guide/en/security/master/hosts-overview.html)

![image](https://user-images.githubusercontent.com/91867110/165044516-8f37bbfe-91bc-44d7-b7fa-e8728c92f28a.png)

Hence, we are closing this issue and marking it as 'QA Validated'.

Thanks!!
