### ISSUE TITLE
[DOCS] Remove note that pre-configured connectors are not supported on cases 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#1903]
Addresses https://github.com/elastic/kibana/pull/130372.

Pre-configured connectors _can_ be used with cases in `7.17` and `8.2.1`, so will need to remove the note in these docs that say it's not supported:
- [Security docs | Configure external connectors](https://www.elastic.co/guide/en/security/master/cases-ui-integrations.html#cases-ui-integrations)
- [Kibana docs | Preconfigured connectors](https://www.elastic.co/guide/en/kibana/master/pre-configured-connectors.html#preconfigured-connector-example)

cc: @cnasikas @academo @peteharverson

**Comment by cnasikas** [comment]
@nastasha-solomon The preconfigured connectors will not be supported on 8.0.0 and 8.1.0 as there is no plan for a patch release. Netherelsess, I will backport to the 8.0 and 8.1 branches in case they do.

**Comment by nastasha-solomon** [comment]
@cnasikas posting my notes from our Slack convo here:
- Support for pre-configured connectors being used with cases was re-added to `7.17` through the `7.17.4` patch.
- Although the change that supports pre-configured connectors with cases has been backported to the `8.0` and `8.1` branches, there's currently no plan to patch either releases. Unless plans change, pre-configured connectors will remain _unsupported_ with cases in `8.0` and `8.1`.
- This change will not be applied to the `8.2` branch, but will be added to `8.2` later through an `8.2.1` patch release.  When this happens, I'll need to: 
  -  [ ] Document the change in the `8.2.1` release notes 
  -  [ ] Remove the note saying preconfigured connectors can't be used with cases from the `8.2` Kibana and Security docs 

I'll close this doc issue once I've completed both of the above tasks for the `8.2.1` release.
