### ISSUE TITLE
[BUG] Authentications tab should not present on Hosts Page.

### ISSUE THREAD

**Issue by karanverma-qasource** [elastic/security-docs#1913]
**Description**
Authentications tab should not present on Hosts Page.

**Actual Result and Guide links**

- Hosts Page : https://security-docs_1824.docs-preview.app.elstc.co/guide/en/security/master/session-view.html

![image](https://user-images.githubusercontent.com/91867110/165446604-1a53a020-2554-47a1-af32-4378ca0fdc04.png)

**Expected Result**

![image](https://user-images.githubusercontent.com/91867110/165446711-7a2ea90d-ce8f-4468-91f1-ff258d131513.png)

**Comment by benironside** [comment]
Thanks @karanverma-qasource, I have fixed this bug in https://github.com/elastic/security-docs/pull/1824.

**Comment by karanverma-qasource** [comment]
Hi @benironside ,

Thank you for looking into our issue.

We looked into the updated docs and found that issue is fixed. 🟢 

**Screenshots:**
[Session View](https://security-docs_1824.docs-preview.app.elstc.co/guide/en/security/master/session-view.html)

![image](https://user-images.githubusercontent.com/91867110/165705643-880f9721-9d28-4e7b-96a3-97c1008f930c.png)

Hence, we are closing this issue and marking it as 'QA Validated'.

Thanks!!
