### ISSUE TITLE
[DOCS] Update Indicator Match rule documentation

### ISSUE THREAD

**Issue by nkhristinin** [elastic/security-docs#1923]
## Description 

[Clients can have a problem](https://github.com/elastic/security-team/issues/3673) with the Indicator match rule and maxClauseCount.

So, if clients have an error with the IM rule like that:

`.. reason: "too_many_clauses: maxClauseCount is set to ...`

We should suggest client, in this case, to increase memory for Elasticsearch and maybe point them to [this document](https://www.elastic.co/blog/managing-and-troubleshooting-elasticsearch-memory)

Also, it's worth mentioning that for correct works of the IM rule you need to have **at least 2GB** of RAM

**Comment by nastasha-solomon** [comment]
Merged #2162.
