### ISSUE TITLE
[BUG]Missing User page under Explore group under Page navigation 

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1946]
## Description 
User page under Explore group under Page navigation

## URL
https://www.elastic.co/guide/en/security/8.2/es-ui-overview.html#page-tabs

## Screen-Shoot

- **Actual Result**

![collapse-side-nav-button](https://user-images.githubusercontent.com/59917825/166671247-a0182861-e91f-4c56-bd18-87fbf72236c9.gif)

- **Expected Result**

![image](https://user-images.githubusercontent.com/59917825/166671111-83e1fba8-1463-40bf-9164-ee8a894bc305.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by karanbirsingh-qasource** [comment]
Issue has been fixed under [#1966](https://github.com/elastic/security-docs/pull/1966) PR

![collapse-side-nav-button](https://user-images.githubusercontent.com/59917825/166888822-4478a04c-1cef-44f0-94db-28a1a69ec1c5.gif)
