### ISSUE TITLE
[BUG]Session tab missing under Timeline screen shoot

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1947]
## Description 
Session tab missing under Timeline screen shoot under 'find events to analyze' section

## URL
https://www.elastic.co/guide/en/security/8.2/visual-event-analyzer.html#find-events-analyze

## Screen-Shoot

- **Actual Result**

![image](https://user-images.githubusercontent.com/59917825/166671506-06cfec49-e2a1-43fe-85e0-7915e28f8e35.png)

- **Expected Result**

![image](https://user-images.githubusercontent.com/59917825/166671579-01fda2c5-eaf5-4893-92d0-05dbf39dcad7.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by benironside** [comment]
Thanks @karanbirsingh-qasource, this bug is fixed in: https://github.com/elastic/security-docs/pull/1968

**Comment by karanbirsingh-qasource** [comment]
issue has been fixed under #1968 PR

![image](https://user-images.githubusercontent.com/59917825/166889888-be210b2a-0d43-43c7-b45f-6dbb9bf4e9a2.png)
