### ISSUE TITLE
[BUG]Missing newly added template in 8.2.0 are missing under template doc

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1948]
## Description 
Missing newly added template in 8.2.0 are missing under template doc

## URL
https://www.elastic.co/guide/en/security/8.2/timeline-templates-ui.html#template-legend-ui

## Screen-Shoot

- **Actual Result**
![image](https://user-images.githubusercontent.com/59917825/166672012-0e3edbeb-e6f8-41d3-92f5-885bc1df881b.png)

- **Expected Result**

![image](https://user-images.githubusercontent.com/59917825/166671935-25cceeb6-d8e0-491b-a2b1-87ae430be8ff.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Chatted with @DefSecSentinel and will be adding the following summaries:

- **Comprehensive Process Timeline:** Useful for quickly assessing and investigating process related alerts.
- **Comprehensive File Timeline:** Useful for quickly assessing and investigating file related alerts.
- **Comprehensive Network Timeline:** Useful for quickly assessing and investigating network related alerts.
- **Comprehensive Registry Timeline:** Useful for quickly assessing and investigating registry related alerts.

**Comment by karanbirsingh-qasource** [comment]
thanks for the update @nastasha-solomon  👍
