### ISSUE TITLE
[BUG]Old alert details fly out in Host Risk screen-shoot

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1949]
## Description 
Old alert details fly out in screen-shoot under additional placed to visualize host risk score data section

## URL
https://www.elastic.co/guide/en/security/8.2/host-risk-score.html#_additional_places_to_visualize_host_risk_score_data

## Screen-Shoot

- **Actual Result**

![image](https://user-images.githubusercontent.com/59917825/166672346-e0044a4d-3c23-4f31-b7b4-dbe439dfe958.png)

- **Expected Result**

![image](https://user-images.githubusercontent.com/59917825/166673556-1f70fae6-1703-4cd9-95e3-79cba39a64d2.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821
