### ISSUE TITLE
[BUG]Missing components for Endpoint under Host Details Page

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1951]
## Description 
Missing components of Endpoint under Host Details Page

- Endpoint integration policy
- Policy status
- Endpoint version
- Agent Status

## URL
https://www.elastic.co/guide/en/security/8.2/host-risk-score.html#_additional_places_to_visualize_host_risk_score_data

## Screen-Shoot

- **Actual Result**

![image](https://user-images.githubusercontent.com/59917825/166674395-bd815ceb-ad12-4b72-98e6-98d8bc66e5b2.png)

- **Expected Result**

![image](https://user-images.githubusercontent.com/59917825/166674457-622ab514-db49-4f8a-a691-66ac29f87784.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821
