### ISSUE TITLE
[BUG]No mention of user page under explore group Documentation

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1952]
## Description 
No mention of user page under explore group Documentation

## URL
https://www.elastic.co/guide/en/security/8.2/es-ui-overview.html#page-tabs

## Screen-Shoot

![image](https://user-images.githubusercontent.com/59917825/166674860-602c2680-4a8c-4d71-9d25-951efb033fa2.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
I think the URL listed above is incorrect -- based on the image it's probably https://www.elastic.co/guide/en/security/8.2/es-ui-overview.html#page-tabs

**Comment by karanbirsingh-qasource** [comment]
right @joepeeples  let me correct in the bug description

**Comment by karanbirsingh-qasource** [comment]
Issue has been fixed under [#1966](https://github.com/elastic/security-docs/pull/1966) PR


![image](https://user-images.githubusercontent.com/59917825/166889095-fa90113a-dee8-418f-bce5-1515cdf9389a.png)
