### ISSUE TITLE
[BUG]Missing block-list tab under screenshot of integration policy details section

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1953]
## Description 
Missing block-list tab under screenshot of integration policy details section

## URL
https://www.elastic.co/guide/en/security/8.2/admin-page-ov.html#endpoints-list-ov

## Screen-Shoot

- **Actual Result**

![image](https://user-images.githubusercontent.com/59917825/166676031-62bce3bf-63b6-456d-abf6-8b6da1babe6a.png)

- **Expected Result**

![image](https://user-images.githubusercontent.com/59917825/166676145-fc264aa8-5a05-42a7-a4ac-bbd87f07ce07.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by karanbirsingh-qasource** [comment]
issue has been fixed udner #1960 PR

![image](https://user-images.githubusercontent.com/59917825/166889377-a65e7b82-d07a-43c4-afd6-bb838886be6b.png)
