### ISSUE TITLE
[BUG] Old screenshot are displayed for Timeline under Timeline Schema

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#1955]
**Description**
Old screenshot are displayed for Timeline under Timeline Schema

**Guide links**

- Timeline Schema - https://www.elastic.co/guide/en/security/8.2/timeline-object-schema.html

**Actual Results**

![image](https://user-images.githubusercontent.com/61860752/166678785-d7b30383-311a-4608-8a54-a8fcf177085d.png)

**Expected Result**

![image](https://user-images.githubusercontent.com/61860752/166679281-beaaab9b-8745-4e8f-a788-dda39a73288f.png)

**Comment by benironside** [comment]
Thanks @deepikakeshav-qasource, this bug is fixed by: https://github.com/elastic/security-docs/pull/1967

**Comment by deepikakeshav-qasource** [comment]
Hi @benironside ,

We tested this ticket according to the PR: https://github.com/elastic/security-docs/pull/1967 and found that the changes are correctly done.

**Screenshot**:
![image](https://user-images.githubusercontent.com/61860752/166868349-7d6bc138-31c5-4ebe-85ea-2fc4d83bd379.png)


Hence, closing this issue and marking it as 'QA Validated'.

Thanks!
