### ISSUE TITLE
[BUG] Old UI is displayed in video for Tutorial: Connect Elastic Security to Jira

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#1956]
**Description**
Old screenshot are displayed for indicator rule screenshots

**Guide links**

- Tutorial: Connect Elastic Security to Jira - https://www.elastic.co/guide/en/security/8.2/cases-ui-integrations.html#connect-security-to-jira

**Expected Result**

https://user-images.githubusercontent.com/61860752/166678392-1bf4ea65-6d87-4e88-8b12-22aea3de0397.mp4

**Comment by jmikell821** [comment]
@karanbirsingh-qasource and @deepikakeshav-qasource - we may have to just leave this bug as is. Video tutorials are created by a different team and we have no control when they are updated at the moment.

**Comment by jmikell821** [comment]
Going to close this bug for now until we have a better method of updating videos on a regular cadence.
