### ISSUE TITLE
[BUG] Updated Endpoint docs to say Windows 11 and Server 2022 support self protection

### ISSUE THREAD

**Issue by ferullo** [elastic/security-docs#1991]
This page https://www.elastic.co/guide/en/security/master/es-overview.html#self-protection should also say Windows 11 and Server 2022 support self protection.

EDIT: Also include macOS 12 (Monterey)

cc @bjmcnic

**Comment by joepeeples** [comment]
Per discussion with @ferullo and @bjmcnic, we'll backport this to 7.16 and later.
