### ISSUE TITLE
[DOCS] Update attributes and text references that mention `Endpoint Security integration` 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#2046]
Meta: #2025 
Related issue: https://github.com/elastic/security-team/issues/3928

Pending the new attribute that will be created, all existing docs that reference the `Endpoint Security` integration `{endpoint-sec}` need to be updated to reference the new text, `Endpoint and Cloud Security` and attribute, `{endpoint-cloud-sec}`. Note that not all docs included the current attribute, so we'll need to run an attribute AND text search. 

Also please note that `endpoint security` as a general industry term when not referring to the integration is acceptable. As such, we'll need to carefully track docs that do and do not need to be updated. 

Docs will need to be merged to `main` and backported to `8.3`. All docs prior to `8.3` will still reference the old `{endpoint-sec}` attribute.

**Comment by joepeeples** [comment]
@benironside and I discussed how to coordinate our efforts:
- @joepeeples will handle replacing old attribute with new attribute (phase 1).
- @benironside and @joepeeples will collaborate on updating hard-coded references (phase 2).
- We'll keep a spreadsheet to track any references we decide don't need to be updated.

**Comment by joepeeples** [comment]
- Completed in https://github.com/elastic/security-docs/pull/2059.
