### ISSUE TITLE
[DOCS] New option to add Osquery results to a timeline investigation

### ISSUE THREAD

**Issue by melissaburpo** [elastic/security-docs#2060]
## Description 

After running Osquery from an Alert, users now have the option to add the results to an investigation in timeline. There are two ways to add the results:
* Add a single row of results to timeline. 
* Add all results to timeline.

Both options are shown in the screenshot below.

If you select the "Add to timeline investigation" option from the top of the Results, this will add all results. If you select the single row option (hover shown below), this adds just that row of data to Timeline.

![image](https://user-images.githubusercontent.com/5898424/172945191-32161f0a-e302-43e4-9e4b-fc54955ef2ed.png)

## Related PR
This change was implemented with https://github.com/elastic/kibana/pull/128596 and is targeted for the 8.3 release.

## Acceptance Test Criteria

The [Run Osquery](https://www.elastic.co/guide/en/security/master/alerts-run-osquery.html) page is updated with this new option. This likely impacts the options related to step 7 and the screenshot in step 8.

Here's a more zoomed in screenshot of just the Results section with the new timeline buttons.

![add-to-timeline-osquery](https://user-images.githubusercontent.com/5898424/172946724-e38a12db-6858-424b-925e-052a2eafc077.png)

## Other notes
It may not be worth noting the docs, but in case it's useful info: this option is only available when running osquery within the Security solution. Users won't see this option if they run a live query in the main Kibana > Osquery > Live query page.

**Comment by nastasha-solomon** [comment]
Thanks for filing this @melissaburpo ! I have some initial questions about these changes and some general questions:
- Are each of these results considered "events" and are they represented as events in Timeline?
<img width="1015" alt="osquery-results" src="https://user-images.githubusercontent.com/79124755/173884084-e8cd9b58-53aa-4d8e-9e0f-f8b563f2652e.png">


- When I added an individual Osquery result to Timeline, the Timeline query showed a single ID. What is that ID? What does it represent? 
<img width="1910" alt="osquery-individ-result" src="https://user-images.githubusercontent.com/79124755/173873554-882563b0-ef04-4d21-b776-595588c07029.png">

- I tested the option to add all Osquery results to Timeline and noticed that the KQL query bar at the top of the Timeline page gets automatically populated with a query. A few questions about this query:
  - How is it formed? Is there a base query that gets formed when users click on the option to add all Osquery results to Timeline?  What fields are included in the query and are these ECS fields?
   - I also noticed the query sometimes changes. For example, in the handful of times I've tested this, the query will adjust to include additional `action_id`s (example below). What dictates the contents of the query?

<img width="1134" alt="expanded query" src="https://user-images.githubusercontent.com/79124755/173878134-eeffad71-c58e-4ce6-8310-e9722826349e.png">

**Comment by melissaburpo** [comment]
Hi @nastasha-solomon, all great questions! I think @tomsonpl might be the best able to answer these for you; he worked on the feature and is most familiar with how it works :)

**Comment by tomsonpl** [comment]
Hey, thanks for reaching out, I'll try to help the best I can :) 

_1. Are each of these results considered "events" and are they represented as events in Timeline?_
- From how I understand - YES, I consider them events. When we add action_id to timeline by clicking the bigger button in the results table then all the rows in the osquery results table (events) are added. But if we click the add to timeline Icon on the left of the row, then we send the `eventId`, and filter only that one row. 
 
 _2.When I added an individual Osquery result to Timeline, the Timeline query showed a single ID. What is that ID? What does it represent?_ 
 - This is the _id of an event
<img width="479" alt="Zrzut ekranu 2022-06-17 o 08 51 19" src="https://user-images.githubusercontent.com/16632552/174242235-52ee506b-f5b4-42f8-a261-aa336b24e235.png">

_3. I tested the option to add all Osquery results to Timeline and noticed that the KQL query bar at the top of the Timeline page gets automatically populated with a query. A few questions about this query:
How is it formed? Is there a base query that gets formed when users click on the option to add all Osquery results to Timeline? What fields are included in the query and are these ECS fields?
I also noticed the query sometimes changes. For example, in the handful of times I've tested this, the query will adjust to include additional action_ids (example below). What dictates the contents of the query?_
 - What we do is only add either `_id` or `action_id` to filters. Unfortunately, I am not sure what else are you referring to, so probably we will have to meet up on Monday just to clarify this quickly :) 
 - We keep adding to the timelines filters - it may contain multiple `_id`s, as well as `action_id`s, if the user keeps running osquery queries, each of them get new action_id, and adding them to timeline - multiple action_ids in filters will be the result of this. 
 
 
 I hope this helps, if not fully - I'll be happy to meet to figure stuff out together :)

**Comment by nastasha-solomon** [comment]
Thanks for the follow-up meeting today @tomsonpl ! I created an ESTEC test instance to test the options to add one and all Osquery results to Timeline and got the expected outcomes. When I added a single result, only the event ID filter (`_id1`) got passed to Timeline. When I added all results to timeline, the `action_ID` (the ID that's generated when users run an Osquery query) gets passed to Timeline. I checked both options in the 8.3.0 BC5 test deployment we're using for doc testing and observed the same behavior so I must've encountered a bug earlier (when I left my initial questions for you).

**Adding a single result to Timeline:**
![add-single-result](https://user-images.githubusercontent.com/79124755/174854717-7ac62087-9d9c-4973-bb8b-9ca4b9b8d79f.gif)


**Adding all results to Timeline:**
![add-all-results](https://user-images.githubusercontent.com/79124755/174854737-743b1ced-d6ce-44d2-aa17-4529624015dd.gif)

**Comment by tomsonpl** [comment]
Thanks @nastasha-solomon, that's great news :) Thanks for sharing - I'll try to remember about the other filter fields, just in case it happens again in the future! 👍 Let me know if you need anything else, I will try to help, or find out if I don't know it yet.
