### ISSUE TITLE
[DOCS] Enhancements to Users page

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#2064]
Topic to update: https://www.elastic.co/guide/en/security/current/users-page.html

Related issue: https://github.com/elastic/kibana/issues/129046
Related PRs: 
- https://github.com/elastic/kibana/pull/130256
- https://github.com/elastic/kibana/pull/131715

## Users by Risk tab
Add the "Users by Risk" tab to the user details page. The tab should be similar to the one on the host details page.
The tab is only visible when `riskyUsersEnabled` is enabled.

![image](https://user-images.githubusercontent.com/57149392/173399439-5b846848-8a18-42bb-9a5c-6c1b1c42ea3f.png)

![image](https://user-images.githubusercontent.com/57149392/173399480-27a70518-dd67-43d6-9ec8-87fd238abd30.png)

## Add Authentication tab 
Related issue: https://github.com/elastic/kibana/issues/129047, PR: https://github.com/elastic/kibana/pull/129456

## How to test it
1. Enable feature flag `riskyUsersEnabled`
2. Insert and enable user risk transforms https://github.com/elastic/mechagodzilla/pull/188/files (currently not working)
3. Go to the user page and click on the 'users by risk' tab
4. Click on a user name
5. Click on the 'users by risk' tab
6. Make sure the time range includes dates with user risk data

**Comment by SourinPaul** [comment]
@jmikell821 connecting our offline conversations here - @randomuserid is working on the URS readme and can share the work-in-progress PR here, so you can review it in parallel. Thanks for collaborating.

**Comment by randomuserid** [comment]
Have written detailed docs on user risk score, PR is here: https://github.com/elastic/detection-rules/pull/2055
