### ISSUE TITLE
[DOCS] Add the "investigate in timeline" button to the alert prevalence section

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#2065]
Related issue: https://github.com/elastic/kibana/issues/129591

Adds the investigate in timeline functionality to the alert details flyout to show the listed alerts in the timeline flyout. 

When clicking the investigate in timeline button, the alert count in the timeline should match the alert count from the flyout.

![2022-06-13_12-42-10](https://user-images.githubusercontent.com/57149392/173403461-4f864ed8-cc13-4ce0-be70-e83e1ff54e9a.png)

**Comment by nastasha-solomon** [comment]
The Timeline icon is being removed with https://github.com/elastic/kibana/pull/133791. With this change, the alert prevalence numbers will link to Timeline.

Will need to add this information to the section describing the **Alert prevalence** column in the Manage detection alerts topic. Also need to update the screenshot in that section. Will take care of the screenshot in https://github.com/elastic/security-docs/pull/2067.
