### ISSUE TITLE
Create kernel extension loading documentation for elastic endpoint

### ISSUE THREAD

**Issue by willyu-elastic** [elastic/security-docs#208]
## Description 
We are currently missing documentation on how to approve the kernel extension for the elastic endpoint

## Acceptance Test Criteria
Instructions and diagrams showing the user how to approve the elastic endpoint kernel extension on macOS

**Comment by ferullo** [comment]
JAMF users will also be able to preapprove loading "Endgame, Inc" kernel extensions the same way they can for Elastic Endgame. We should include a note on how to do that.

**Comment by willyu-elastic** [comment]
https://docs.google.com/document/d/1nnxRMoaj7LmlRw4d5B-aki7AHYYYaQHo4Dl3bgj0gxQ/edit

**Comment by jmikell821** [comment]
Doc is here: https://www.elastic.co/guide/en/security/7.9/install-endpoint.html#enable-kernel-extension
