### ISSUE TITLE
Response Actions Copy[DOCS]

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#2105]
Response Actions Epic/Meta issue: https://github.com/elastic/security-team/issues/3392

Figma link: https://www.figma.com/file/4U0smPyCa86uWsPn8EMFNu/Response-actions?node-id=1614%3A305161

Build: https://kibana.endpoint.elastic.dev/app/security/administration/endpoints 
* click Action Menu > Launch Responder to view. Note: this is not in a final state but will give you a rough idea of how the interactions work!

**Comment by benironside** [comment]
Just left a round of suggestions on the Figma page! Feel free to let me know if there are any questions

**Comment by joepeeples** [comment]
Closing this issue as the response console UI copy has been reviewed and released.
