### ISSUE TITLE
[DOCS] Security Solution Advance Setting : Missing New Streamlined navigation

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#2165]
**Description**
Security Solution Advance Setting : Missing New Streamlined navigation

**URL**
- https://www.elastic.co/guide/en/security/8.3/admin-page-ov.html#endpoints-list-ov

**Actual Result**

![image](https://user-images.githubusercontent.com/59917825/176387136-cb2cf9c1-affa-4ac5-a9d7-4d9a001da958.png)

**Expected Result**

![image](https://user-images.githubusercontent.com/59917825/176387190-214ebd44-7384-4496-b49a-011f4cd06bc0.png)

**Comment by joepeeples** [comment]
This advanced setting is already documented: https://www.elastic.co/guide/en/security/8.3/advanced-settings.html#_enable_grouped_navigation

The name of the feature is "grouped navigation" — "new streamlined navigation" is just a description, not a proper name.
