### ISSUE TITLE
[DOCS]Prebuilt rule reference table last column name and details not showing 

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#2166]
**Description**
Prebuilt rule reference table last column name and details not showing 

**URL**
- https://www.elastic.co/guide/en/security/8.3/prebuilt-rules.html

**Actual Result**

![image](https://user-images.githubusercontent.com/59917825/176388317-f62ed486-7036-422f-ab70-b34ca11f2ae9.png)

- Issue there on Firefox and chrome browser and also occuring by decreasing the browser zoom

![image](https://user-images.githubusercontent.com/59917825/176388357-c77be21d-25c6-4baf-a4ae-102d9204ed20.png)

**Expected Result**
- Wraping of Table last column version should be done 
- wraping of Table last column version content should also be done

**Comment by deepikakeshav-qasource** [comment]
@karanbirsingh-qasource , if user scroll down to the bottom then we have horizontal scroll bar by which user can read last column of table.

Hence, Closing this issue now!!
