### ISSUE TITLE
[BUG] User Risk Score: missing ml_userriskscore_init_script script file

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#2167]
**Description**
User Risk Score: missing `ml_userriskscore_init_script` script file

**Details**

Documentation Guide link( for user risk):https://github.com/elastic/detection-rules/blob/209b40b0a30d87898d75bb2d5dc3f2e068b5f09d/docs/experimental-machine-learning/user-risk-score.md
Documentation Guide link (from security app ): https://github.com/elastic/detection-rules/blob/main/docs/experimental-machine-learning/user-risk-score.md

Issue is there on both guide link one link that is from security app and another from kibana guide 

Extracted Package : Download the package from [here](https://github.com/elastic/detection-rules/releases/download/ML-UserRiskScore-20220628-1/ML-UserRiskScore-20220628-1.zip) and unzip it and found that  `ml_userriskscore_init_script` script file is not present 

![image](https://user-images.githubusercontent.com/59917825/176391197-a437365c-5757-4ae3-a7d1-471c8b72f75b.png)

![image](https://user-images.githubusercontent.com/59917825/176393242-665c5401-8675-4f27-88f9-b3987ba5c409.png)

**Comment by randomuserid** [comment]
OK yes there is no init script in user risk score so the doc is wrong and that section in the red box can be removed.

**Comment by jmikell821** [comment]
Merged https://github.com/elastic/detection-rules/pull/2065.
