### ISSUE TITLE
[DOCS]Mention of Host Risk on user risk score

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#2168]
**Description**
Mention of Host Risk on user risk score [page ](https://github.com/elastic/detection-rules/blob/209b40b0a30d87898d75bb2d5dc3f2e068b5f09d/docs/experimental-machine-learning/user-risk-score.md
)

**URL**
- https://github.com/elastic/detection-rules/blob/209b40b0a30d87898d75bb2d5dc3f2e068b5f09d/docs/experimental-machine-learning/user-risk-score.md

**Note**

Documentation Guide link( for user risk):https://github.com/elastic/detection-rules/blob/209b40b0a30d87898d75bb2d5dc3f2e068b5f09d/docs/experimental-machine-learning/user-risk-score.md

Issue is not there on Documentation Guide link (from security app ): https://github.com/elastic/detection-rules/blob/main/docs/experimental-machine-learning/user-risk-score.md

![image](https://user-images.githubusercontent.com/59917825/176394341-92ecc93f-f731-4b23-a7cf-8ccb69021033.png)

![image](https://user-images.githubusercontent.com/59917825/176394439-66cd0156-8b61-424f-9380-4517c322942b.png)

**Comment by jmikell821** [comment]
@karanbirsingh-qasource going to close this. The `.md` file is just for customers to view instructions to download the artifacts. We link to this `.md` file from the user risk score documentation, so I think we're good. Feel free to reopen if I misunderstood anything. Thanks!
