### ISSUE TITLE
[DOCS] [8.4] Create documentation for Kubernetes support with Endpoint

### ISSUE THREAD

**Issue by qcorporation** [elastic/security-docs#2187]
## Description 

For the 8.4 release, AWP will be introducing functionality into Elastic Endpoint to support Kubernetes-managed deployments within [EKS](https://aws.amazon.com/eks/) and [GKE](https://cloud.google.com/kubernetes-engine). Users will be instructed to take a YAML file and add it to their Kubernetes deployment to integrate Endpoint and a new service called Elastic-CWP-Metadata.
Users will also be introduced to a new Kubernetes dashboard to visualize the new data coming from Endpoint. 

For this release, we will require documentation help to:

- Explain the deployment strategy of Endpoint+CWP-Metadata and what to expect to be installed in their cluster
- Document the onboarding workflow and provide a recommended YAML file for customers to use to integrate Endpoint+CWP-Metadata into their installation
- Document the new support matrix of Endpoint, versioning within EKS and GKE [support matrix](https://github.com/elastic/security-team/issues/3336)
- Document the new K8s dashboard being introduced into 8.4. The best way to understand the dashboard is through the [Figma files](https://www.figma.com/file/BdAcN5SbfW629OMvJrGT2r/%5B8.4%5D-%5BKubernetes%5D-Viz-of-k8s-environment-in-a-topological-view?node-id=2%3A105323) and the [test plan](https://docs.google.com/spreadsheets/d/17-gT1jcDvA4F2wfdAEqoClvvWC2Li1EmbS3KB_n1h-E/edit#gid=590501705)
- Document the new Session View Details panel additions, with the new populated ECS fields to describe the K8s visualization; New fields will also be displayed within the Details Panel
- Document any adjacent features within the Security Solution in Kibana, including but not limited to enrichment of K8s metadata within the Analyser view, ability to search for these new K8s fields within KQL
- Recommended YAML files to apply with the different cloud providers: [files](https://github.com/elastic/awp-tools/tree/main/kubernetes/yaml)

## Acceptance Test Criteria
TBD

## Notes
- Add all appropriate labels to the issue, especially the version number label. 
- Be sure to add any necessary screenshots, code text or console commands for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by qcorporation** [comment]
cc. ing for visibility:
@daniel-almeida @lrishi @norrietaylor @learhy @nick-alayil @snehsach19

**Comment by benironside** [comment]
fixed in https://github.com/elastic/security-docs/pull/2243
