### ISSUE TITLE
[DOCS][Exceptions] - Unsupported detection engine operator discovered in past releases

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#2199]
## Description 

A bug was discovered that surfaces the "matches" operator in the exception item builder, however, this operator is not supported by the detection engine, only by OLM team (artifacts, event filters, etc). This was found to be present in 8.2 and 8.3.

The following doc updates will be needed:
- 8.2 add known issue. Users who add an exception item that uses "matches" will result in a rule run error (see bug issue for error)
- 8.3/8.3.1/8.3.2 - add known issue. Users who add an exception item that uses "matches" will result in a rule run error (see bug issue for error)
- 8.3.3 - bug fix will be backported to 8.3 so just a release note should suffice (?)

Issue - https://github.com/elastic/kibana/issues/136224
PR - https://github.com/elastic/kibana/pull/136340

**Comment by nastasha-solomon** [comment]
Thanks for filing this, @yctercero ! Should the version in the last bullet be 8.3.3?

**Comment by nastasha-solomon** [comment]
Updating the 8.3.3 release notes in https://github.com/elastic/security-docs/issues/2199.

**Comment by nastasha-solomon** [comment]
@joepeeples support for the `MATCHES` operator has been added to the exceptions builder for rules in 8.4.0. Not sure if you want to mention this in [rule exception docs](https://www.elastic.co/guide/en/security/master/detections-ui-exceptions.html#detection-rule-exceptions) or if you think doc'ing the enhancement in release notes is sufficient. 

@yctercero since we'll need to doc this in release notes, should we reference https://github.com/elastic/kibana/pull/136340 for the enhancement PR?
cc: @benironside

**Comment by joepeeples** [comment]
> @joepeeples support for the `MATCHES` operator has been added to the exceptions builder for rules in 8.4.0. Not sure if you want to mention this in [rule exception docs](https://www.elastic.co/guide/en/security/master/detections-ui-exceptions.html#detection-rule-exceptions) or if you think doc'ing the enhancement in release notes is sufficient.

Yep, this should be in the main docs! I'll be creating a separate issue for this soon.

**Comment by nastasha-solomon** [comment]
@yctercero is the `MATCHES` operator also supported for the rule exceptions API? I could be misunderstanding [these API docs](https://www.elastic.co/guide/en/security/master/exceptions-api-create-exception-item.html#entries-object-schema), but it looks like we currently say the `MATCHES` operator works for rule exceptions -- or maybe the `match` operator?  
cc: @joepeeples

**Comment by nastasha-solomon** [comment]
Merged updates to 8.2 and 8.3 release notes:
- Added a known issue to 8.2, 8.3, 8.3.1, and 8.3.2:
   - 8.2: https://www.elastic.co/guide/en/security/8.2/release-notes-header-8.2.0.html#known-issue-8.2.0
   - 8.3: https://www.elastic.co/guide/en/security/master/release-notes-header-8.3.0.html#known-issue-8.3.0 (see section titled "The matches operator is not supported for rule exceptions")
   - 8.3.1: https://www.elastic.co/guide/en/security/master/release-notes-header-8.3.0.html#known-issue-8.3.1 (see section titled "The matches operator is not supported for rule exceptions")
   - 8.3.2: https://www.elastic.co/guide/en/security/master/release-notes-header-8.3.0.html#known-issue-8.3.2
- Added a fixed issue to 8.3: https://www.elastic.co/guide/en/security/master/release-notes-header-8.3.0.html#bug-fixes-8.3.3

**Comment by yctercero** [comment]
Thanks @nastasha-solomon ! Gonna close this out.
