### ISSUE TITLE
[DOCS][Cases] Deletion Sub privilege

### ISSUE THREAD

**Issue by jonathan-buttner** [elastic/security-docs#2205]
## Description 

The cases team implemented a new deletion sub feature privilege within Kibana for Security Solution, Observability, and Stack Management. The deletion sub feature privilege governs a users ability to delete cases and comments. If a user does not have the deletion privilege they cannot delete these entities.

https://github.com/elastic/kibana/pull/135487

## Acceptance Test Criteria

As a user I should be able to view documentation explaining when to use the deletion sub feature.
 

## Notes

User who already have `all` access within cases will automatically be granted the deletion privilege when upgrading to 8.4. Users who have `read` access within cases will not automatically be granted the deletion privilege upon upgrading to 8.4. An admin can customize the cases privileges by enabling the sub feature radio button and checking/unchecking the box for deletion.

**Comment by nastasha-solomon** [comment]
@jonathan-buttner @cnasikas just an FYI that @lcawl is handling these docs in https://github.com/elastic/kibana/issues/136996

**Comment by lcawl** [comment]
oops, sorry should have just transferred this issue to the kibana repo.  I'll copy the info over now instead.
