### ISSUE TITLE
[DOCS] [Osquery] New option for users to run a single query or run a pack

### ISSUE THREAD

**Issue by melissaburpo** [elastic/security-docs#2231]
## Description 

When running osquery from an Alert, users now have an option to either run a single query or to run a pack of queries. This impacts all instances of the Live Query UI, including when running osquery from an Alert in the Security app.

## Related PR
* https://github.com/elastic/kibana/pull/132198

## Contacts
For any questions about this feature, reach out to @patrykkopycinski or @james-elastic 

## Acceptance Test Criteria

* The [Run Osquery](https://www.elastic.co/guide/en/security/current/alerts-run-osquery.html) page is updated as needed. This likely includes:
  * Update screenshots in steps 3 and 7
  * Revise steps to indicate this new choice. Users first need to choose whether they want to run a single query or a pack of queries. 
    * If they choose to run a single query, they would then do step 3 as written "Enter a new query or select a new saved query." 
    * If they choose to run a pack of queries, they would then select which pack to run. When you select a pack, all queries that will be run are shown. When you hit Submit, a status is shown for each query in the pack.
 

## Screenshots

Running a single query

![image](https://user-images.githubusercontent.com/5898424/181642518-8e37e455-e3db-47f6-8518-cb68501d0ff6.png)

Running a query pack

![image](https://user-images.githubusercontent.com/5898424/181642542-52d82b1c-181d-4c4e-ad3b-05f35e6c387d.png)

**Comment by nastasha-solomon** [comment]
Merged #2249 and #138844.
