### ISSUE TITLE
[Docs][Exceptions] - Screenshot updates

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#2241]
### Description

The UI for displaying exception items was updated. No additional functionality was updated or changed, pure cosmetic change.

Relevant PR: https://github.com/elastic/kibana/pull/135255

The PR includes screenshots, but we can also provide additional ones if those aren't great.

**Comment by joepeeples** [comment]
Looked through existing docs & screenshots, and there actually aren't any existing screenshots that include the list of exception items, so nothing to update. Closing the issue.
