### ISSUE TITLE
[DOCS] Known issues for `8.4` 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#2245]
Tracking known issues we need to include in our `8.4` release notes. 

Related: https://github.com/elastic/security-docs/issues/2175

## Known issues 
- https://github.com/elastic/kibana/issues/137422

**Comment by nastasha-solomon** [comment]
@e40pud @marshallmain I noticed that https://github.com/elastic/kibana/pull/137517 was merged and https://github.com/elastic/kibana/issues/137422 was closed. Will https://github.com/elastic/kibana/issues/137422 still need to be doc'd a known issue for `8.4`?

**Comment by nastasha-solomon** [comment]
@benironside I verified with @marshallmain that #137422 still needs to be doc'd as a known issue. Summary can be something like:
If an additional lookback time is used for rule preview, alerts from source documents that are outside the preview timeframe may not appear in the histogram.

**Comment by nastasha-solomon** [comment]
Merged https://github.com/elastic/security-docs/issues/2175.
