### ISSUE TITLE
[DOCS] Enhancements to host risk score UI 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#2270]
PR: https://github.com/elastic/kibana/pull/133708

After this enhancement, the steps above can be done via **dev tools**

Start from very beginning:
More hints are added to guide users enabling the module:

- `Learn more` link takes users to the [Github page](https://www.github.com/elastic/detection-rules/blob/main/docs/experimental-machine-learning/host-risk-score.md):
- Before enabling the module, the `Import dashboard` button is **hidden**, it is enabled after host risk score data is available:
<img width="1656" alt="Screenshot 2022-07-21 at 01 11 07" src="https://user-images.githubusercontent.com/6295984/180103398-b78ccd6e-5d2e-4038-94ed-b250d53f1c24.png">

- Without alerts data, the `Enable via Dev Tools` button is disabled, it is enabled after alerts data is available:
<img width="1663" alt="Screenshot 2022-07-22 at 13 45 49" src="https://user-images.githubusercontent.com/6295984/180442733-7bf0c99b-2ca6-416d-946f-d146f941361a.png">

**Comment by ajosh0504** [comment]
PR for this is now ready for review: https://github.com/elastic/security-docs/pull/2308
