### ISSUE TITLE
[DOCS] Endpoint high CPU known issue in 8.3.3

### ISSUE THREAD

**Issue by ferullo** [elastic/security-docs#2291]
## Description 

Endpoint 8.3.3 introduced a bug on macOS and Linux that can cause Endpoint's CPU to permanently spike CPU (e.g. to 200%) if Malware protection is enabled. When this happens Endpoint is locked up and will not continue function normally.

Workarounds are to reboot the computer (which is likely on a temporary fix until it happens again), disable Malware protection, or downgrade to 8.3.2 or earlier. This issue will be fixed in 8.4.0.

## Acceptance Test Criteria

Can we please post a known issue about this for the 8.3.3 notes. 

## Notes

cc @nfritts @ricardoungureanu

**Comment by ferullo** [comment]
@ricardoungureanu @nfritts can you confirm my workarounds are correct and the anticipated fix version is right?

**Comment by ricardoungureanu** [comment]
@ferullo Your workarounds are correct and the fix version is right

**Comment by ricardoungureanu** [comment]
Tracking this issue in our [public endpoint repo](https://github.com/elastic/endpoint/issues/22)

**Comment by nastasha-solomon** [comment]
Merged #2292
