### ISSUE TITLE
[BUG] `Upload` is displayed instead of `Import` under Note section

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#2310]
**Description**
`Upload` is displayed instead of `Import` under Note section

**URL**
- https://security-docs_2268.docs-preview.app.elstc.co/guide/en/security/master/detections-ui-exceptions.html

**Screenshot:**

![image](https://user-images.githubusercontent.com/61860752/185042176-3d9d38d7-6443-48f5-b8cd-00af25121b4d.png)

**Comment by joepeeples** [comment]
Corrected in commit https://github.com/elastic/security-docs/pull/2268/commits/a7f5981bdee0a61d9acbe0e02fd3901d8f8bcb69 of https://github.com/elastic/security-docs/pull/2268. Thanks!

**Comment by deepikakeshav-qasource** [comment]
Hi @joepeeples,

We have validated this issue and observed that all changes are present 🟢

![image](https://user-images.githubusercontent.com/61860752/185346893-6c49ed4a-71ac-4db7-a0cb-3dd268efce5f.png)

Hence we are closing this issue and added the "QA: Validated" label to it.

Thanks!!
