### ISSUE TITLE
[BUG] Incorrect Screenshot for `Review Query Pack Results` 

### ISSUE THREAD

**Issue by arvindersingh-qasource** [elastic/security-docs#2311]
**Description**
Incorrect Screenshot for `Review Query Pack Results` 

**URL**
https://security-docs_2249.docs-preview.app.elstc.co/guide/en/security/master/alerts-run-osquery.html

**Steps**
1. Open Kibana Docs for `Run Osquery from a detection Alert` with link - https://security-docs_2249.docs-preview.app.elstc.co/guide/en/security/master/alerts-run-osquery.html
2. Scroll down to `Review Query Pack Results`
3. Observe that, Screenshot for `Review Query Pack Results` is not updated as it does not shows the option of `Add to timeline investigation` 

**Actual Result**
![1](https://user-images.githubusercontent.com/106220189/185048368-678d4f6d-5dca-47b0-b5e9-31b13c0403d9.png)

**Expected Result**
![2](https://user-images.githubusercontent.com/106220189/185048254-1b04fdea-553a-4a3f-839e-c2b77509fd98.png)

**Comment by arvindersingh-qasource** [comment]
@manishgupta-qasource  Please review this bug.

Thanks.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Thanks for catching this @arvindersingh-qasource ! Please find the corrected image in https://github.com/elastic/security-docs/pull/2249.

**Comment by arvindersingh-qasource** [comment]
Hi @nastasha-solomon ,

Thanks for looking into the issue.
We have validated this issue on update [Documentation](https://security-docs_2249.docs-preview.app.elstc.co/guide/en/security/master/alerts-run-osquery.html) and found that issue is now **fixed** and updated Screenshot for `Review Query Pack Results` is available.

### Please find the below observations
**Guide Link** 
 - https://security-docs_2249.docs-preview.app.elstc.co/guide/en/security/master/alerts-run-osquery.html

**Observation**
 - Screenshot for `Review Query Pack Results`
![1](https://user-images.githubusercontent.com/106220189/185333449-70ce0002-5e2d-4a94-a9a5-7a0fff3a3e36.png)

Hence, we are closing this ticket.

Thanks.
