### ISSUE TITLE
[DOCS] Document breaking changes in Lucene that caused EQL rule issues

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#2337]
Changes to Lucene 9 introduced a bug in Kibana 8.x (which uses Lucene 9). These changes affect regular expressions that are used in EQL rule queries. As of now, this issue has only been reported for custom EQL rules. We'll need to doc this as a known issue for all of the `8.x` releases, including `8.4`. 

**SDH ticket:** https://github.com/elastic/sdh-security-team/issues/436

@e40pud @peluja1012 @jmikell821 @benironside

**Comment by nastasha-solomon** [comment]
This is doc'd for 8.4 at https://github.com/elastic/security-docs/pull/2314.

**Comment by w0rk3r** [comment]
https://github.com/elastic/sdh-security-team/issues/436#issuecomment-1225651077

**Comment by nastasha-solomon** [comment]
Investigation is being continued at https://github.com/elastic/detection-rules/issues/2260.

**Comment by nastasha-solomon** [comment]
Investigation is ongoing - there might be a limitation to what EQL is acceptable to use in the expression. Some notes are available [here](https://github.com/elastic/detection-rules/issues/2260#issuecomment-1236851275). In the meantime, I'll keep https://github.com/elastic/security-docs/pull/2357 in the draft state. Will work with @w0rk3r once more information is available for release notes.
