### ISSUE TITLE
[BUG]: Incorrect alert risk score is displaying for each alert color code.

### ISSUE THREAD

**Issue by samratbhadra-qasource** [elastic/security-docs#2341]
**Description**:
Incorrect alert risk score is displaying for each alert color code.

**URL**:
https://security-docs_2280.docs-preview.app.elstc.co/guide/en/security/master/visualize-alerts.html

**Screenshot:**
![Screenshot (828)](https://user-images.githubusercontent.com/84007952/186105315-a76af41a-f9b1-416c-9f94-ad70f18d864f.png)

**Comment by joepeeples** [comment]
Corrected values in this commit https://github.com/elastic/security-docs/pull/2280/commits/e8603dc2340707e43e80cbc5cf3a9fadf7fb3f32 of PR #2280.

**Comment by samratbhadra-qasource** [comment]
Hi @joepeeples 

We have validated the issue and observed that all the required change are present and correct. ✔️

**Screenshots:**

![Screenshot (839)](https://user-images.githubusercontent.com/84007952/186364035-d76a22e6-c527-4cf7-8464-f03b6ab4eb7a.png)

Hence, we are closing this issue and marking it as  "**QA:Validated**"

Thanks!
