### ISSUE TITLE
[DOCS] The docs are not added for troubleshooting the Linux deadlock issue

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#2344]
**Description**: 
The docs are not added for troubleshooting the Linux deadlock issue

**URL link or topic name**: 
- https://security-docs_2317.docs-preview.app.elstc.co/guide/en/security/master/ts-management.html#ts-unhealthy-agent

**Screenshots**:
![image](https://user-images.githubusercontent.com/60252716/186129115-dc032796-2be3-42c6-9075-a58909b49058.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
Closing this as a duplicate of issue #2197.
