### ISSUE TITLE
[BUG] All navigation pages are not present under Page navigation section

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#2393]
**Description**: All navigation pages are not present under Page navigation section

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/current/es-ui-overview.html#page-tabs

**Screenshots**:
- Actual:
![doc page navigation](https://user-images.githubusercontent.com/61860752/187133175-22e22099-6f3d-498c-aa9d-bae5168f70fb.jpg)

- Expected:
![elastic navigation page](https://user-images.githubusercontent.com/61860752/187133181-b2423af8-1fdd-4b52-bd41-320f53f25e72.jpg)

**Comment by jmikell821** [comment]
This should have been fixed with https://github.com/elastic/security-docs/pull/2451.
