### ISSUE TITLE
[BUG] External alerts is displaying in screenshots under overview dashboard and live feed section

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#2395]
**Description**: External alerts is displaying in screenshots under overview dashboard and live feed section

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/8.4/overview-dashboard.html#overview-dashboard
- https://www.elastic.co/guide/en/security/8.4/overview-dashboard.html#_live_feed

**Screenshots**:
- Actual:
**Overview Dashboard**
![doc overview  dashboard](https://user-images.githubusercontent.com/61860752/187137450-e39961ad-9523-4cb3-8424-439a95d3c395.jpg)

**Live Feed**
![Live feed](https://user-images.githubusercontent.com/61860752/187137342-a32126c8-d283-420b-8ecf-e0f10a800323.jpg)

- Expected:
![image](https://user-images.githubusercontent.com/61860752/187137534-25d53dd9-d812-46ed-a416-53fca9658bcb.png)

**Comment by joepeeples** [comment]
This has been fixed at some point; confirmed in docs for 8.4 and later.
