### ISSUE TITLE
[BUG] Old Alert page is displaying in screenshot under manage machine learning screenshot

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#2396]
**Description**: Old Alert page is displaying in screenshot under manage machine learning screenshot

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/8.4/machine-learning.html#manage-jobs

**Screenshots**:
- Actual:
![Doc ML page](https://user-images.githubusercontent.com/61860752/187137969-1be479b0-25f1-4904-b989-277bd40c50ee.jpg)

- Expected:
![image](https://user-images.githubusercontent.com/61860752/187138183-95aafa7c-f368-4163-b2c0-60a65cbe24b2.png)

**Comment by joepeeples** [comment]
Screenshot updated in #2422. Thanks!

**Comment by deepikakeshav-qasource** [comment]
Hi @joepeeples  ,

We have validate tis issue and all the required changes are present and correct. ✔️

![image](https://user-images.githubusercontent.com/61860752/188367886-0cf8e7b3-7043-412d-a9c5-ece204feadce.png)


Hence, we are marking as QA Validated!!

Thanks!!
