### ISSUE TITLE
[BUG] Old screenshot is displaying under set up rules that run on alert indices

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#2397]
**Description**: Old screenshot is displaying under set up rules that run on alert indices

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/8.4/building-block-rule.html#_set_up_rules_that_run_on_alert_indices

**Screenshots**:
- Actual:
![doc alert indices](https://user-images.githubusercontent.com/61860752/187140094-96b5d4bb-5bbc-4da0-9155-ba2918a3ce35.jpg)

- Expected:
![image](https://user-images.githubusercontent.com/61860752/187140898-d5235018-4e24-410f-89fb-4cb42dc8568e.png)

**Comment by joepeeples** [comment]
This was actually fixed for 8.5 and later in https://github.com/elastic/security-docs/pull/2663 (4d2a38a93dcbd7798ae021e7db576e5d9634078e), but it wasn't backported to 8.4. Will open a new PR to update in 8.4.

**Comment by joepeeples** [comment]
Fixed in https://github.com/elastic/security-docs/pull/2698.
