### ISSUE TITLE
[BUG] Old link for manage rule is displayed in screenshot under treemap section

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#2398]
**Description**: Old link for manage rule is displayed in screenshot under treemap section

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/8.4/visualize-alerts.html#_treemap

**Screenshots**:
- Actual:
![manage rule](https://user-images.githubusercontent.com/61860752/187143415-757f2d78-e8ab-421d-b709-4d7fefbc4198.jpg)

- Expected:
![image](https://user-images.githubusercontent.com/61860752/187143368-0430542f-869d-4568-94eb-7f71f8d4de37.png)

**Comment by joepeeples** [comment]
This is a known issue, acknowledged in https://github.com/elastic/security-docs/pull/2280 where these docs were created:

> The animation treemap-click.gif was captured right before the "Manage rules" link was turned into a button. For now, I'm deprioritizing getting this GIF updated just for that minor detail, since it doesn't affect the functionality being illustrated, and it involves a lot of setup work.

We're still OK with this very minor discrepancy, considering the amount of setup still required to reproduce the animation.
