### ISSUE TITLE
[BUG] Old screenshot is displaying under visual event analyzer

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#2399]
**Description**: Old screenshot is displaying under visual event analyzer

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/8.4/visual-event-analyzer.html#find-events-analyze

**Screenshots**:
- Actual:
![doc visual event](https://user-images.githubusercontent.com/61860752/187144731-328d6079-cb07-4897-ab33-f4a361b2ae6c.jpg)

- Expected:
![image](https://user-images.githubusercontent.com/61860752/187144646-5ef95760-3d56-4e1e-8287-e7f38e854839.png)

**Comment by nastasha-solomon** [comment]
Thanks for filing this @deepikakeshav-qasource ! Please find the updates at https://github.com/elastic/security-docs/pull/2420.

**Comment by deepikakeshav-qasource** [comment]
Hi @nastasha-solomon ,

We have reviewed the shared preview  and all the required changes are present and correct. ✔️

![image](https://user-images.githubusercontent.com/61860752/187888620-0391eb47-f3f9-409a-bbbe-02f24f1b7905.png)

Hence, We are closing this issue and marking as QA Validated!!

Thanks!!
