### ISSUE TITLE
[BUG] Information not provided for CSP Benchmarks under Endpoint management section.

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#2402]
**Description**: Information not provided for CSP Benchmarks under Endpoint management section.

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/8.4/sec-manage-intro.html

**Screenshots**:
- Actual:
![image](https://user-images.githubusercontent.com/61860752/187150294-05b3970e-02f1-4692-8211-6dbd37114f8a.png)

- Expected:
![image](https://user-images.githubusercontent.com/61860752/187150388-03dc07cd-23d2-4ac2-8d5a-3e91ced03249.png)

**Comment by joepeeples** [comment]
Closing this issue, no change needed. We're no longer organizing the docs sections to mimic the nav menu organization in the UI, so it's OK for CSP Benchmarks to be covered elsewhere. It's currently [documented](https://www.elastic.co/guide/en/security/8.4/benchmark-rules.html) in the new Cloud native security section.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/87339667/187928295-4d9e2ced-76d4-4a59-8983-66bdfc4d8f34.png">
