### ISSUE TITLE
[BUG]: Missing context of delete comment under cases sub-future.

### ISSUE THREAD

**Issue by samratbhadra-qasource** [elastic/security-docs#2410]
**Description**: 
Missing context of delete comment under cases sub-future.

**URL**:
https://www.elastic.co/guide/en/security/current/case-permissions.html

**Expected:**
![image (3)](https://user-images.githubusercontent.com/84007952/187206643-f80e246c-9d8d-4f9f-b86e-6859b2723ca2.png)

**Screenshot:**
![image (2)](https://user-images.githubusercontent.com/84007952/187206616-d3490e9b-ae66-42f7-8091-794ed06a1c76.png)

**Comment by nastasha-solomon** [comment]
@jonathan-buttner is there a way to give users privs to delete case comments only? Or, are they only able to do so if they have `Read` or higher case feature privs + the `Delete` sub-feature priv enabled? 

Also, moving forward, will the`Delete` sub-feature priv encompass all other case sub-features? For example, will the scope of this sub-feature priv eventually expand to include deleting elements like user actions and alerts?

**Comment by lcawl** [comment]
According to the current docs, the prerequisites for the [delete comments](https://www.elastic.co/guide/en/kibana/master/cases-api-delete-comments.html) and [delete cases](https://www.elastic.co/guide/en/kibana/master/cases-api-delete-cases.html) are the same. My preference would be for these reference pages to be the source of truth rather than going into that level of detail in the Security, Observability, and Stack Management prerequisite overviews.

**Comment by jonathan-buttner** [comment]
> @jonathan-buttner can users be given privs to delete case comments only? 

No, you can't give users privileges to only delete case comments. Once they are given deletion privileges they can delete all entities within cases (most notably cases and comments).

> Or, are they only able to delete case comments if their role has `Read` or higher case feature privs + the `Delete` sub-feature priv enabled?

Users can delete case entities if they have the deletion sub feature privilege granted to them. Theoretically it'd be possible for them to only have deletion privileges (even if they have no read access, they'd have to create the role through the core security APIs directly though) and they'd be able to delete cases and comments through the cases APIs.

**Comment by nastasha-solomon** [comment]
Thanks @jonathan-buttner and @lcawl!

@lcawl I agree that the case API docs can be the source of truth and provide more granular details about the access privs provide.

**Comment by lcawl** [comment]
I ultimately added mention of the ability to delete comments and alerts in the setup docs via https://github.com/elastic/observability-docs/pull/2333 and https://github.com/elastic/security-docs/pull/2678
