### ISSUE TITLE
[BUG]: Missing type id for webhook case management connector.

### ISSUE THREAD

**Issue by samratbhadra-qasource** [elastic/security-docs#2411]
**Description**: 
Missing type id for webhook case management connector.

**URL**:
https://www.elastic.co/guide/en/security/current/register-connector.html

**Screenshot:**
![image (4)](https://user-images.githubusercontent.com/84007952/187208213-a321c9a1-7929-4c3d-a681-f50c1d1ca0fc.png)

**Comment by lcawl** [comment]
I have created https://github.com/elastic/kibana/issues/139763 to remove these duplicated API details from the Security Guide and I have https://github.com/elastic/kibana/pull/138583 up to add the Webhook Case Management connector details to the APIs in the Kibana Guide. When those projects are complete, I think this issue will be unnecessary.

**Comment by lcawl** [comment]
The referenced page was removed as part of https://github.com/elastic/kibana/issues/139763, therefore this issue is no longer required.
