### ISSUE TITLE
[BUG] Missing webhook-Case management connector API doc

### ISSUE THREAD

**Issue by karanverma-qasource** [elastic/security-docs#2412]
**Description**: 

Missing webhook-Case management connector API doc.

**URL link or topic name**:
https://www.elastic.co/guide/en/security/current/actions-api-overview.html

**Screenshots:**
![Annotation 2022-08-29 184820](https://user-images.githubusercontent.com/91867110/187209786-836b7d27-6c5f-4f6d-a3cb-eaddb08fb6b7.jpg)

**Comment by lcawl** [comment]
I have created https://github.com/elastic/kibana/issues/139763 to remove these duplicated API details from the Security Guide and I have https://github.com/elastic/kibana/pull/138583 up to add the Webhook Case Management connector details to the APIs in the Kibana Guide. When those projects are complete, I think this issue will be unnecessary.
