### ISSUE TITLE
[DOCS] placeholders to rule action fields - improve documentation to specify which fields are arrays

### ISSUE THREAD

**Issue by jguay** [elastic/security-docs#2442]
## Description 

https://www.elastic.co/guide/en/security/8.4/rules-ui-create.html#rule-action-variables show a list of fields - one of which mentions the word `array`. It is not very clear that all fields with plural name (ending with `s`) are also arrays

Current documentation : 
> You can use [mustache syntax](http://mustache.github.io/) to add the following placeholders to [rule action](https://www.elastic.co/guide/en/security/8.4/rules-ui-create.html#rule-notifications) fields:
...
{{context.alerts}}: Array of detected alerts

Suggested change : 
> You can use [mustache syntax](http://mustache.github.io/) to add the following placeholders to [rule action](https://www.elastic.co/guide/en/security/8.4/rules-ui-create.html#rule-notifications) fields - any field name ending with `s` is an array:
...
{{context.alerts}}: Detected alerts

**Comment by joepeeples** [comment]
Closing this issue, as it's a very stale effort at this point. We can reopen if it becomes a higher priority in the future.
