### ISSUE TITLE
[DOCS] updating prebuilt rules before upgrade Kibana to 8.x +

### ISSUE THREAD

**Issue by vitaliidm** [elastic/security-docs#2443]
## Description 

In [this SDH](https://github.com/elastic/sdh-security-team/issues/449), the customer experienced the following issue: after upgrading Kibana to 8.1.3 from 7.17, prebuilt rules update started to fail.
The reason for it: the customer had some very old prebuilt rules from early versions(7.10), which were not updated prior to 8.1 upgrade.
It's possible to avoid this issue by updating prebuilt rules at 7.17 version before upgrading Kibana to 8.0 or 8.1
This affects only Kibana versions 8.0 and 8.1. [If customer upgrades to 8.2+](https://github.com/elastic/kibana/pull/128283), this issue will be fixed and would not require prior prebuilt rules update in 7.17.  

Would it make sense to mention this caveat in [upgrade guide](https://www.elastic.co/guide/en/security/current/upgrade-intro.html) to avoid similar issue for other customers?

**Comment by joepeeples** [comment]
Merged #2643.
