### ISSUE TITLE
Trusted Applications

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#245]
## Description
Background:
Users expect to be able to use Elastic Security without any conflicts or compatibility issues with other installed applications on their system. They want to be able to intentionally exclude some processes from being monitored and make them completely trusted - or, conditionally trusted. This is easier on the user than adding multiple entries to their allowlist in order to ensure an application can be used.

User Story/Problem Statement(s):

As an elastic endpoint security user, I want to be able to trust applications by defining what process to trust to trust, so that I can ensure there are no compatibility or performance issues with applications I need in my environment.

## Acceptance Test Criteria

- User can add trusted apps by OS
- User can add an entry by Process Path
- User can wild card the process path
- User can add entry by Hash
- User can view a list of Trusted Apps
- We do not automatically trust child processes of a trusted process
- Users are able to access Trusted Apps from the Fleet application through the "edit" integration page

## Screenshots:

![image](https://user-images.githubusercontent.com/26076500/94957776-5c125480-04bc-11eb-9124-600c6cc6ee7e.png)

![image](https://user-images.githubusercontent.com/26076500/94957798-67fe1680-04bc-11eb-9fff-596c212aceb4.png)

![image](https://user-images.githubusercontent.com/26076500/94957901-954ac480-04bc-11eb-9729-63911007e1a1.png)

![image](https://user-images.githubusercontent.com/26076500/94957978-bf9c8200-04bc-11eb-9de6-e00a783fd12f.png)

## Notes
* Team: endpoint management (Kevin/Caitlin)

**Comment by jmikell821** [comment]
Merged #322.
