### ISSUE TITLE
[DOCS] User Attestation for kubernetes installation with Endpoint

### ISSUE THREAD

**Issue by qcorporation** [elastic/security-docs#2456]
For the 8.5 Release, we will release User Attestation for Endpoint installations in a Kubernetes cluster. The product impact and epic definition are outlined here:
https://github.com/elastic/security-team/issues/3798
[after reading the ticket]

## Assumptions
With the 8.4 release, Elastic has public documentation on guiding the user to installing and setting up Endpoint within a Kubernetes cluster.

## What's needed
- A new YAML file will be needed alongside the existing YAML. This new YAML file will include a new container within the pod called `elastic-sec-identity`. The location of the file should exist here: https://github.com/elastic/endpoint/tree/main/releases/8.5.0/kubernetes/deploy (doesn't exist right now)
- A description of what is User Attestation and how does it benefit the infosec/devsecops user by having users identify enriched within process events
- Step by step process of how to deploy the new yaml file (should be the same as the existing Endpoint k8s deployment
- Document the index of Endpoint
- Document the new fields populated with the new attestation fields
`process.attested_group`, `process.attested_user.*`
PR: https://github.com/elastic/ecs/pull/2050

**Comment by qcorporation** [comment]
cc.ing Working Group: @daniel-almeida @lrishi @Tacklebox @learhy @mjwolf @patrickmamaid @norrietaylor @m-sample

**Comment by qcorporation** [comment]
@m-sample : Provide two YAML files, 1 as the base yaml and elastic-sec-identity will be additive to the base

**Comment by benironside** [comment]
Closing this for now since the feature has been pushed indefinitely
