### ISSUE TITLE
7.10 Terminology Changes

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#246]
## Description 

Terminology changes impacting 7.10

* Ingest Manager >> Fleet
     * The Ingest Manager application will be renamed to Fleet. We should no longer use Ingest Manager.
* Host >> Endpoint (under the Security App, Administration tab)
     * Also Host List >> Endpoint List
* Configuration >> Policy
     * Config has been changed to Policy in both the Fleet application and Security application
* Elastic Endpoint Security > Endpoint Security
    * This one may not really impact docs. We pulled out "Elastic" in a few sections and will generally reference it as "Endpoint Security" in kibana

**Comment by caitlinbetz** [comment]
fyi @dontcallmesherryli if anything is changing on your end for 7.10!

**Comment by dontcallmesherryli** [comment]
Thanks @caitlinbetz . I don't think we have any term changes for 7.10.

**Comment by jmikell821** [comment]
Hey @caitlinbetz - I want to clarify the definitions between `endpoints` and `hosts.` Is there a difference between the two? Currently, there is a `Hosts` tab in what was formerly the SIEM section. I know that the ones on the Admin page specifically list the endpoints running Endpoint Security, but if there are other differences I want to make sure we notate these in docs. Thanks!

**Comment by caitlinbetz** [comment]
Hey @jmikell821 -

Elastic Endpoint: Endpoint resides on the _host_  and provides capabilities such as collecting events, detecting and preventing malicious activity, whitelisting, artifact delivery, etc. (Previously referred to at Endgame as the Sensor.)

Host: Any system or host that is connected to a network and functions as a client or server in any capacity. Desktop computers, laptops, and servers are all examples of hosts. (Previously referred to at Endgame as the Endpoint.)

So yes, Admin page contains the "endpoint" list - or, hosts running Endpoint. Originally we had this page titled as the "Endpoint list" in order to distinguish it from the Host list tab. We were asked to change it from Endpoint to Hosts, and then asked to change it back to Endpoints. :) So the purpose of the admin tab list remains the same - hosts running endpoint.

**Comment by dedemorton** [comment]
Noting here that I made the Ingest Manager >> Fleet change when I cleaned up links in https://github.com/elastic/security-docs/pull/375.

I didn't make the other changes, though.
