### ISSUE TITLE
[META] Changes to host and user risk score features

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#2477]
## Description
In 8.5, improvements were made to the onboarding workflow for the host and user risk score features. These changes streamline previously complicated steps that required some technical knowledge and sometimes took users outside of the Security app. Now, users can enable both features and generate risk scores with a single click.

In addition, users can upgrade host and user risk score features in a single click. The **Upgrade** button will be display anywhere host and user risk scores are available. This includes the: 
- Host Risk Scores and User Risk Scores sections on the Entity analytics dashboard
- **Host risk** tab on the Hosts page
- **User risk** tab on the Users page 
- **Host risk** tab on a host's details page
- **User risk** tab on a user's details page

The following sections outline changes to the host and user risk score features in addition to caveats that may need to be doc'd. 

### Host risk score 
Changes introduced in 8.5:
- **Host risk score card removed** - The host risk score card will no longer display on the Overview dashboard. This will require multiple text and screenshot updates within the [Host risk score](https://www.elastic.co/guide/en/security/master/host-risk-score.html#_deploy_host_risk_score) topic. 
- **Simpler way to enable host risk score** - In 8.5, users only need to click the **Enable Host Risk Score** button in the "Host Risk Scores" section of the Entity Analytics dashboard to turn on the feature. When they click this button, host risk scores are generated as well _if alert data is present in the environment_. To account for this change, we'll need to revise the docs for [deploying host risk score](https://www.elastic.co/guide/en/security/master/host-risk-score.html#_deploy_host_risk_score) and [viewing host risk score data](https://www.elastic.co/guide/en/security/master/host-risk-score.html#view-host-risk-score). 
- **New way to upgrade the host risk score feature**: If the user had enabled the host risk score feature in 8.4 or earlier, they will see the an **Upgrade** button within the "Host Risk Scores" section instead of the **Enable Host Risk Score** button. When they click **Upgrade**, their “old” host risk scores are deleted and new ones are created. The “old” data is not preserved as that data type is no longer supported. This will likely need to be doc'd as a breaking change in the [8.5 release notes](https://github.com/elastic/security-docs/issues/2429). 
   - **IMPORTANT**: If the user wants to keep their “old” host risk scores, they need to reindex the data **_before_** upgrading the host risk score feature. They can use the [Elasticsearch Reindex API] (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) to reindex their "old" data. Their data will then be stored in the `ml_{host|user}_risk_score_{spaceId}` and `ml_${host|user}_risk_score_latest_{spaceId}` indices. Here is an example reindexing request:
 
````
POST _reindex
{
  "source": {
    "index": "ml_{host|user}_risk_score_{spaceId}"
  },
  "dest": {
    "index": "my_new_ml_{host|user}_risk_score_{spaceId}"
  }
}
````

### User risk score 
Changes introduced in 8.5:
- **Simpler way to enable user risk score** - Similar to the host risk score, in 8.5, users only need to click the **Enable User Risk Score** button in the "Host Risk Scores" section of the Entity Analytics dashboard to turn on the feature. We might need to refresh the docs for [deploying the user risk score package](https://www.elastic.co/guide/en/security/master/user-risk-score.html#deploy-user-risk-score) to account for these changes. 
- **New way to upgrade the user risk score feature**: If the user had enabled the user risk score feature in 8.4 or earlier, they will see the an **Upgrade** button within the "User Risk Scores" section instead of the **Enable User Risk Score** button. When they click **Upgrade**, their “old” user risk scores are deleted and new ones are created. The “old” data is not preserved as that data type is no longer supported. This will likely need to be doc'd as a breaking change in the [8.5 release notes](https://github.com/elastic/security-docs/issues/2429). 
   - **IMPORTANT**: Users will need to reindex "old" user risk scores to keep them. Steps are same as what mentioned for host risk score.

## Related issues/PRs
- Onboarding button -  Allows users to enable the host and user risk score features with a single click: https://github.com/elastic/kibana/pull/140377
 NOTE: The PR description contains useful videos that demo what happens when users enable and upgrade the features.
- Upgrading host/user risk score features: https://github.com/elastic/security-team/issues/4899 

## Additional notes/questions:
- Should we be directing users to the Entity Analytics dashboard in order to enable/upgrade the host and user risk score features? Are there any other places users can do this?
- Do users still need to enable feature flags for the user and host risk score features to turn them on?
- Outside of reindexing "old" risk scores, do users need to perform extra steps before upgrading the host or user risk score features? 
- In what situations would users encounter a transform error (i.e., the transform already exists) when they install the host or user risk score feature?
- Will the host and user risk score docs be linked to in any newly developed error messages? If yes, which ones and which doc sections will be linked in the code?

The deployment has three spaces for a quick view and we can add new spaces. Please note that we've been asked to _not_ add data, enable or upgrade any of the spaces. (Please create a new space if you'd like to try it out)
- Default - No data
- Installation panel
- Legacy data - upgrade panel

**Comment by peluja1012** [comment]
Hi @nastasha-solomon, we are also adding a feature called "alert enrichments" where we store and display the entity (host/user) risk score. Here is the [PR](https://github.com/elastic/kibana/pull/139478). I was wondering if that should be tracked as part of this github issue or if a separate one should be created.

**Comment by nastasha-solomon** [comment]
@peluja1012 thanks for pinging us about this! I think a separate PR is better for organization purposes. This PR is mainly for describing what changed in the host and user risk score onboarding/upgrading workflows. Correct me if I'm wrong, but it seem as though the docs for the [new alert enrichments feature](https://github.com/elastic/kibana/pull/139478) should describe the type of host/user risk data that's displayed on the Alert details flyout after the host/user risk score features are enabled.

**Comment by peluja1012** [comment]
> Correct me if I'm wrong, but it seem as though the docs for the https://github.com/elastic/kibana/pull/139478 should describe the type of host/user risk data that's displayed on the Alert details flyout after the host/user risk score features are enabled.

Hey @nastasha-solomon, yes that's correct.

**Comment by angorayc** [comment]
- Should we be directing users to the Entity Analytics dashboard in order to enable/upgrade the host and user risk score features? Are there any other places users can do this?

Users can enable both risk scores from Entity Analytics page
<img width="2559" alt="Screenshot 2022-09-22 at 11 04 27" src="https://user-images.githubusercontent.com/6295984/191719141-267d7618-3f27-4da4-8705-25b1b40d905a.png">

Users can enable host risk score from hosts / host details 
<img width="2547" alt="Screenshot 2022-09-22 at 11 04 52" src="https://user-images.githubusercontent.com/6295984/191720603-221fef9f-c08d-4a94-a885-55d39daf6c25.png">

<img width="2549" alt="Screenshot 2022-09-22 at 11 10 54" src="https://user-images.githubusercontent.com/6295984/191720577-822f9420-85a2-49fc-bb05-369db754d5c2.png">

Users can enable user risk score users / users details
<img width="2539" alt="Screenshot 2022-09-22 at 11 11 56" src="https://user-images.githubusercontent.com/6295984/191720771-ab143238-3f0f-4c5d-b8cc-3c66c1abc788.png">

<img width="2547" alt="Screenshot 2022-09-22 at 11 12 12" src="https://user-images.githubusercontent.com/6295984/191720757-20063401-db19-40ce-9f29-22744b1d91e8.png">


Do users still need to enable feature flags for the user and host risk score features to turn them on?
Outside of reindexing "old" risk scores, do users need to perform extra steps before upgrading the host or user risk score features?
In what situations would users encounter a transform error (i.e., the transform already exists) when they install the host or user risk score feature?
Will the host and user risk score docs be linked to in any newly developed error messages? If yes, which ones and which doc sections will be linked in the code?

**Comment by angorayc** [comment]
No user risk score data available to display - installation was finished without error but transforms haven't piked up data. Please restart transforms. (We'll add a restart button to the UI)
<img width="1391" alt="Screenshot 2022-09-22 at 16 26 48" src="https://user-images.githubusercontent.com/6295984/191788482-243bc9de-2188-4488-9ecc-ab8450c7eda9.png">

**Comment by angorayc** [comment]
Delete the module (in progress):
Remove saved objects: in /app/management/kibana/objects delete the created tag `{{Host|User}} Risk Score - {{spaceId}}` and the saved objects.
Remove transforms transforms (ml_{{host|user}}riskscore_latest_transform_{{spaceId}} and ml_{{host|user}}riskscore_pivot_transform_{{spaceId}}) in `/app/management/data/transform`. (stop them first then delete them, also delete the indices it created)
Make sure you don't have any user/host risk score ingest pipelines (ml_{{host|user}}riskscore_ingest_pipeline*) in /app/management/ingest/ingest_pipelines, if yes delete them.

**Comment by ajosh0504** [comment]
@nastasha-solomon Is there an open PR for this yet? We also have this old, and now outdated documentation for this feature in [detection-rules]((https://github.com/elastic/detection-rules/blob/main/docs/experimental-machine-learning/host-risk-score.md)). 

We would like to make the official documentation as exhaustive as possible so users don't have to look in multiple places- hopefully we can include everything Angela has detailed above in the main docs?

**Comment by SourinPaul** [comment]
@jmikell821 per our conversation linking the documentation task for 8.5 breaking changes 
 here for traceability https://github.com/elastic/security-team/issues/4898

**Comment by angorayc** [comment]
Known issue:
In 8.5, all the actions are done by client side requests, so it takes a while to enable / upgrade the module.
We have a fix in 8.6 for that to move most of the actions to the server side, this will reduce the enable / upgrade
https://github.com/elastic/kibana/pull/142434

**Comment by nastasha-solomon** [comment]
Thank you, @angorayc ! We'll make sure this gets doc' in the [8.5 release notes](https://github.com/elastic/security-docs/pull/2519) and will keep an eye on it when 8.6 rolls around. 

cc: @benironside

**Comment by angorayc** [comment]
https://github.com/elastic/detection-rules/blob/main/docs/experimental-machine-learning/host-risk-score.md and https://github.com/elastic/detection-rules/blob/main/docs/experimental-machine-learning/user-risk-score.md we might want to clarify in these two pages are for pre v8.5 only.

**Comment by ajosh0504** [comment]
@angorayc Any reason why we're asking users to delete everything in case of a conflict? I'm also unable to think of a situation when this would occur. Could you please elaborate on what you're thinking here?

**Comment by angorayc** [comment]
> @angorayc Any reason why we're asking users to delete everything in case of a conflict? I'm also unable to think of a situation when this would occur. Could you please elaborate on what you're thinking here?

As the current process continue even if error occurs in the middle of the process For example, the script continues to the end even if ingest pipeline conflict happens in the middle of the process. Indices and transforms will still be created, if they don't delete everything, then next time they might see indices already exists and transforms already exists. Therefore delete everything should be the safest way to avoid that.
