### ISSUE TITLE
[DOCS] Add exception to EQL Rule

### ISSUE THREAD

**Issue by dontcallmesherryli** [elastic/security-docs#250]
## Description 

EQL rules will require tuning like all other rule types. For 7.10 users can follow the usual exceptions flow to create an exception item that applies to the entire EQL query. If user wants exceptions to be applied to individual sequence of events inside the query, they can edit the EQL rule itself with EQL syntax.

## Notes

- Add the **"Team:Docs"** label to new issues. 
- Be sure to add the version number label. 
- Be sure to add any necessary screenshots for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by jmikell821** [comment]
Added note in the "Exceptions" topic.
