### ISSUE TITLE
[DOCS] Preview Queries for Custom Query Rule, Threshold Rule, and EQL Rule

### ISSUE THREAD

**Issue by dontcallmesherryli** [elastic/security-docs#253]
## Description 

A "preview" query component will be available for some of the rule types in 7.10: Custom Query Rule, Threshold Rule, and EQL Rule. Once a user writes a rule query, they may select a time range to try the rule out on, and get feedback on how noisy their rule will be based on the preview.

## Acceptance Test Criteria

Documentation for the "preview query" function.

## Notes

- Add the **"Team:Docs"** label to new issues. 
- Be sure to add the version number label. 
- Be sure to add any necessary screenshots for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by jmikell821** [comment]
More info about preview: https://github.com/elastic/kibana/pull/78985
