### ISSUE TITLE
[DOCS] Elastic Security UI updates 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#2547]
A few changes to the [security UI](https://www.elastic.co/guide/en/security/master/es-ui-overview.html): 

- New Entity Analytics dashboard https://github.com/elastic/security-docs/issues/2517
- New Intelligence section https://github.com/elastic/security-docs/issues/2497

**Comment by nastasha-solomon** [comment]
@jmikell821 I added the intelligence page to the Elastic Security UI topic [here](https://github.com/elastic/security-docs/pull/2526/files#diff-104ec26f4b74ea5b31e353ff2bda7804f7e927ee2346bba1a8f8c1ab4edbcb80R103). Let me know if you'd prefer for me to revert the change.
