### ISSUE TITLE
[DOCS] Security onboarding improvements

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#256]
Meta issue: https://github.com/elastic/endpoint-app-team/issues/669

Let's track progress of this so we have a list of all UI/workflow changes. 

Currently, users have to transition to ingest manager in order to add the endpoint security integration, then they go back to the security app where they are prompted to enroll an agent, then they go back to ingest manager to enroll an agent, which then transitions down to the fleet page to enable fleet, then they can click a button to enroll an agent. It would be better if all the steps are part of a single flow that redirects users back to the security app when they are done.

This flow should be consistent with the UX across other apps within kibana that utilize ingest manager

Issues:

-  Detect when Agents are in the process of standing up Endpoints https://github.com/elastic/security-team/issues/238
-  Improve Endpoint onboarding elastic/kibana#72688

**Comment by caitlinbetz** [comment]
@jmikell821 FYI we won't have any major changes with onboarding for 7.10. The main change is this ticket:
https://github.com/elastic/security-team/issues/238 - which provides better messaging once the user has enrolled Agents and is waiting for the endpoints to show up.
