### ISSUE TITLE
[DOCS] Document the rule details page 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#2560]
## Description 

Currently, we're missing docs that explain the rule details page and how to use it for rules, both custom and prebuilt. Several areas/features in the rule details page (for ex, investigation guides, tabs, etc.) are referenced throughout our docs. It'd be good to document the page in detail to provide more context for those areas/features. 

```[tasklist]
### To-do
- [ ] Decide whether to add this content as a new section to the [Manage detection rules](https://www.elastic.co/guide/en/security/master/rules-ui-management.html) topic or create a new topic
- [ ] Identify what needs to be doc'd and break out the work accordingly
```

**Comment by joepeeples** [comment]
Detail to mention: query and filter info in the Definition section can vary depending on whether the rule uses a saved query and the checkbox 'Load saved query "x" dynamically on each rule execution' is checked.

Related Kibana PR: https://github.com/elastic/kibana/issues/139250#issuecomment-1247918828
Docs PR: https://github.com/elastic/security-docs/pull/2559

**Comment by nastasha-solomon** [comment]
If we end up backporting this PR past 8.11 (e.g., to 8.11 or earlier), we'll need to be aware of this UI change that Nikita made in 8.11: https://github.com/elastic/security-docs/issues/3970

Related Kibana PR: https://github.com/elastic/kibana/pull/166158

**Comment by nastasha-solomon** [comment]
@natasha-moore-elastic talked this over with @jmikell821, and this might be something we can tackle in 8.13 if we have the bandwidth.

**Comment by nastasha-solomon** [comment]
Moving this to our project repo since it's not a request for feature docs.
