### ISSUE TITLE
[DOCS] Advanced policy configuration

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#257]
Meta issue: https://github.com/elastic/security-team/issues/168

**Initiative**
User can edit a set of advanced fields inside of the Policy experience.

**Background:**
In some instances, users need to edit advanced settings inside their Policies. These settings are for advanced use cases and allow users more control over their environments. These are generally outside of the common use cases of turn on protections and capabilities.

Example config: https://github.com/elastic/endpoint-dev/blob/master/Documentation/ElasticEndpoint/example_unofficial_config.yaml

**User Story/Problem Statement(s):**

As an elastic endpoint security user, I want to be able to edit advanced Policy settings for my Endpoint to better tune my environment.

**High Level AC:**

- User can see set of Advanced Policy settings
- User can edit a set of Advanced Policy settings for each Policy

**Comment by caitlinbetz** [comment]
@jmikell821  - Updated the label from 7.10 to 7.11; this feature won't ship with 7.10.

**Comment by jmikell821** [comment]
Closing. Duplicate of #419
