### ISSUE TITLE
[BUG] Refresh screenshot showing IM rule

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#2570]
Edit (@joepeeples): This is fixed in https://github.com/elastic/security-docs/pull/2559 (https://github.com/elastic/security-docs/commit/8ae25ead6cf084b7434f1c5eb7bae4fa1745cf43) for 8.5 and forward, so this issue only needs to backport 8.4 and back.

Screenshot under step 1F ([here](https://www.elastic.co/guide/en/security/8.4/rules-ui-create.html#create-indicator-rule)) shows outdated view for selecting data sources while setting up an indicator match rule. Needs to be replaced with:

<img width="800" alt="Screen Shot 2022-10-12 at 8 42 15 PM" src="https://user-images.githubusercontent.com/79124755/195473655-9d6b414a-51e9-457d-8d71-25ddfd43492f.png">

**Comment by nastasha-solomon** [comment]
Will likely need to create different PRs for these updates. There are slight differences in each release.

**8.0, 8.1 & 8.2**
Need to replace screenshot with the following:
<img width="600" alt="Screen Shot 2022-10-12 at 9 09 35 PM" src="https://user-images.githubusercontent.com/79124755/195475910-422d937a-2185-4a0f-9f37-f75652e87a99.png">

**8.3**
<img width="600" alt="Screen Shot 2022-10-12 at 9 23 21 PM" src="https://user-images.githubusercontent.com/79124755/195477271-245fe80b-b2fa-4a3c-be0b-a5a8feb3ce18.png">

**8.4** 
Can use same screenshot used for 8.5.

**Comment by joepeeples** [comment]
Removing `v8.5.0` label, because fixed in #2559 (https://github.com/elastic/security-docs/pull/2559/commits/8ae25ead6cf084b7434f1c5eb7bae4fa1745cf43) for 8.5 and forward.

**Comment by nastasha-solomon** [comment]
Merged changes.
