### ISSUE TITLE
[DOCS] Update Overview dashboard 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#2578]
The ability to access host risk score data is being removed from the Overview dashboard. So [this topic ](https://www.elastic.co/guide/en/security/8.4/overview-dashboard.html) needs to be updated. 

Related docs meta: https://github.com/elastic/security-docs/issues/2477

**Comment by nastasha-solomon** [comment]
@jmikell821 we might actually be able to close this doc issue without updating the [Overview dashboard](https://www.elastic.co/guide/en/security/8.4/overview-dashboard.html) topic. The Host risk score card is only mentioned in the [Host risk score docs](https://www.elastic.co/guide/en/security/8.4/host-risk-score.html#view-host-risk-score) and the outdated content was already removed in https://github.com/elastic/security-docs/pull/2580.

**Comment by nastasha-solomon** [comment]
No updates are required to the Overview dashboard topic. The current version of the topic doesn't contain screenshots of the host risk score card or references to using/enabling the card.
