### ISSUE TITLE
[DOCS] Set text to display pop up for macOS and Windows

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#258]
META Issue: https://github.com/elastic/endpoint-dev/issues/7602

A required feature for 7.10 is that the Kibana user can set text to display when the (malware) pop-up pops up. 

Let's keep track and sync with Dan F. on the progress.

**Comment by ferullo** [comment]
This is slipping from 7.10 on the Kibana side. It will be in 7.11 now.

Endpoint will include a pop up that is on by default (no user configuration) that displays in the following scenarios:
* When Malware is detected or prevented (Windows and macOS)
* When a user needs to grant the Endpoint Full Disk Access (macOS 10.14+ only)
* When a user needs to grant the Endpoint permission to load the Kernel Extension (macOS 10.13-10.15)
* When a user needs to grant the Endpoint permission to load the System Extension (macOS 11.0 Big Sur only)
