### ISSUE TITLE
[BUG]Analyze host risk score data and Analyze user risk score data section data not matching

### ISSUE THREAD

**Issue by ghost** [elastic/security-docs#2585]
**Describe the bug**
Analyze host risk score data and Analyze user risk score data section data not matching

**Build Details:**
```
Version:8.5.0 BC6
Commit:0b06c1437f38a9eb9a4273003d8d2ce2c8905189
Build:57022
```

**Steps**
- Go to below doc links
   - https://security-docs_2580.docs-preview.app.elstc.co/guide/en/security/master/host-risk-score.html#analyze-host-risk-score
   - https://security-docs_2580.docs-preview.app.elstc.co/guide/en/security/master/user-risk-score.html#view-user-risk-score
- Compare details under Analyze host risk score data and Analyze user risk score data section
- Observed that sub details under both section of different page is not matching . Additional on user page user details page one section is not present at all

Host Page | User page
-- | --
The Overview tab on the Alert details flyout: | The Overview tab on the Alert details flyout:
The Host risk classification column in the All hosts table on the Hosts page: | The Users by risk tab on the Users page:
Hosts by risk tab on the Hosts page: | The Overview section on the user details page:
The Overview section on the host details page: | The Users by risk tab on the user details page:
The Hosts by risk tab on the host details page: |  Not present on user page

**Screen-Shoot:**

![image](https://user-images.githubusercontent.com/59917825/196362822-793b4347-d8ef-4268-9c66-944be01b03d8.png)

![image](https://user-images.githubusercontent.com/59917825/196363001-1a0ba6f6-3e9c-4c83-8001-dba218eb449b.png)

**Comment by karanbirsingh-qasource** [comment]
@deepikakeshav-qasource  please review
