### ISSUE TITLE
[BUG] The screenshot needs to be updated for the Trusted Applications UI

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#2587]
**Description**: 
The screenshot needs to be updated for the Trusted Applications UI

**URL link or topic name**: 
- https://security-docs_2516.docs-preview.app.elstc.co/guide/en/security/master/trusted-apps-ov.html

**Screenshots**:
- Actual:
![1Actual](https://user-images.githubusercontent.com/60252716/196385266-ae026112-b326-4de3-a338-dca0d8398e83.PNG)

- Expected:
![1Expected](https://user-images.githubusercontent.com/60252716/196385281-8150debd-aa1b-43fb-99d7-721db21dd4ed.PNG)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
Updated in https://github.com/elastic/security-docs/pull/2516 (https://github.com/elastic/security-docs/pull/2516/commits/452c187aa2c06a76bb14002d43d6149bf0d33543)
