### ISSUE TITLE
[BUG] The placeholder text is updated under the Endpoints flyout for Response action

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#2588]
**Description**: 
The placeholder text is updated under the Endpoints flyout for Response action

**URL link or topic name**: 
- https://security-docs_2536.docs-preview.app.elstc.co/guide/en/security/master/admin-page-ov.html#response-action-history-tab
- https://security-docs_2536.docs-preview.app.elstc.co/guide/en/security/master/response-actions.html
- https://security-docs_2536.docs-preview.app.elstc.co/guide/en/security/master/host-isolation-ov.html#view-host-isolation-details

**Screenshots**:
- Actual:
![2Actual](https://user-images.githubusercontent.com/60252716/196385819-06e8e65e-7dd5-4daf-971e-62ebcc8a8eb6.PNG)

- Expected:
![2Expected](https://user-images.githubusercontent.com/60252716/196385807-c169a21a-f18a-414b-8364-7893e5fe1233.PNG)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
Screenshots fixed in https://github.com/elastic/security-docs/pull/2536 (https://github.com/elastic/security-docs/pull/2536/commits/b008699dfdd60270713258f80d700e7f2399ab77)
