### ISSUE TITLE
[BUG] Response Action History Tab have old placeholder text for search bar

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#2589]
**Description**: 
Response Action History Tab have old placeholder text for search bar

**URL link or topic name**: 
- https://security-docs_2536.docs-preview.app.elstc.co/guide/en/security/master/response-actions-history.html

**Screenshots**:
- Actual:
![3Actual](https://user-images.githubusercontent.com/60252716/196385919-ea61b97d-ef9b-407d-a62c-c0235a0e3ca3.PNG)

- Expected:
![3Expected](https://user-images.githubusercontent.com/60252716/196385904-31961378-7bf2-439e-a287-690ebc3ebbc4.PNG)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
Screenshots fixed in https://github.com/elastic/security-docs/pull/2536 (https://github.com/elastic/security-docs/pull/2536/commits/b008699dfdd60270713258f80d700e7f2399ab77)
