### ISSUE TITLE
[DOCS]Beta label showing for session under overview tab of alert flyout

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#2590]
**Describe the bug**
Beta label showing for session under overview tab of alert flyout

**Build Details:**
```
Version:8.5.0 BC6
Commit:0b06c1437f38a9eb9a4273003d8d2ce2c8905189
Build:57022
```

**Steps**
- Go to below doc links
   - https://security-docs_2558.docs-preview.app.elstc.co/guide/en/security/master/view-alert-details.html#view-alert-details
- Observed the Beta Label for Session under overview tab of alert flyout

**Expected result**
![image](https://user-images.githubusercontent.com/59917825/196387746-7cda7e28-4504-40d5-84ce-b1008f2e590f.png)

**Screen-Shoot:**
![image](https://user-images.githubusercontent.com/59917825/196387859-86537529-6f86-4878-ab2b-745e4fca0f3e.png)

**Comment by karanbirsingh-qasource** [comment]
@deepikakeshav-qasource please review

**Comment by joepeeples** [comment]
@karanbirsingh-qasource This screenshot was updated in https://github.com/elastic/security-docs/pull/2540, thanks!
