### ISSUE TITLE
[BUG]: The Screenshot needs to be updated for the count format of rules

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/security-docs#2591]
**Description:**
The Screenshot needs to be updated for the count format of rules.

**PR Ticket:**
https://github.com/elastic/security-docs/pull/2561

**URL link or topic name:**
https://security-docs_2561.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-create.html

**Screenshots:**
**Expected:**
![1Expected](https://user-images.githubusercontent.com/77374876/196400832-3555cd5b-f4c1-42a2-be9e-46de74cb4768.png)

**Actual:**
![1Actual](https://user-images.githubusercontent.com/77374876/196401033-af13b9c4-b5b3-4958-b08a-d95a2ef0738b.PNG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821
