### ISSUE TITLE
[BUG]: The Screenshot needs to be updated for the rule define section as there is no option for `Rule Preview` now

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/security-docs#2592]
**Description:**
The Screenshot needs to be updated for the rule define section as there is no option for `Rule Preview` now.

**PR Ticket:**
https://github.com/elastic/security-docs/pull/2561

**URL link or topic name:**
https://security-docs_2561.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-create.html

**Screenshots:**
**Expected:**
![2Expected](https://user-images.githubusercontent.com/77374876/196403453-bba0f396-fd40-42eb-b1a8-46763d3377ec.PNG)

**Actual:**
![2Actual](https://user-images.githubusercontent.com/77374876/196403486-f76124c0-87cc-48a5-b052-a1db65ed33a1.png)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821
