### ISSUE TITLE
[BUG]: Information for Prebuilt packs are loaded and activated information needs to be updated.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/security-docs#2611]
**Description:**
Information for Prebuilt packs are loaded and activated information needs to be updated.
- Prebuilt packs are first loaded and not automatically activated.
- To select from query packs that have been loaded, the pack needs not be activated.

**PR Ticket:**
https://github.com/elastic/security-docs/pull/2561

**URL link or topic name:**
https://security-docs_2561.docs-preview.app.elstc.co/guide/en/security/master/osquery-response-action.html#add-osquery-response-action
https://security-docs_2561.docs-preview.app.elstc.co/guide/en/security/master/alerts-run-osquery.html#alerts-run-osquery

**Screenshots/ Recordings:**
**Expected:**

https://user-images.githubusercontent.com/77374876/196620989-22e75abb-3c37-4384-a243-0ef8df716f65.mp4

https://user-images.githubusercontent.com/77374876/196621889-886992f5-02bf-4e11-ae48-6c78dcd92566.mp4

**Actual:**
![10](https://user-images.githubusercontent.com/77374876/196618698-801f1e26-879f-49f0-be94-cbb7bf04221c.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Thanks for filing this, @amolnater-qasource ! I'm following up on this and will get back to you soon.

**Comment by nastasha-solomon** [comment]
@amolnater-qasource the Security doc updates are ready for your review at https://github.com/elastic/security-docs/pull/2561. I applied the same corrections to the Kibana Osquery docs at https://github.com/elastic/kibana/pull/143242 (changes are [here](https://kibana_143242.docs-preview.app.elstc.co/guide/en/kibana/master/osquery.html#osquery-run-query)) and added some extra information about working with active and inactive packs (see the first bullet in the second step [here](https://kibana_143242.docs-preview.app.elstc.co/guide/en/kibana/master/osquery.html#load-prebuilt-packs).)

cc: @patrykkopycinski

**Comment by nastasha-solomon** [comment]
Merged https://github.com/elastic/security-docs/pull/2561

**Comment by arvindersingh-qasource** [comment]
Hi @nastasha-solomon ,

Thanks for looking into the issue.

We have validated this issue on the `Kibana Guide [8.5]` and found that issue is **Fixed**.

#### Guide Link
 - https://www.elastic.co/guide/en/security/8.5/alerts-run-osquery.html

### Please find the below observations
- Add Osquery Response Actions
![1](https://user-images.githubusercontent.com/106220189/199467678-9e76319e-0241-4a91-92d8-3c4dc82895dc.png)

- Run Osquery from Alerts
![2](https://user-images.githubusercontent.com/106220189/199467713-a435ac99-2a83-4967-ae94-8e36c8713fb5.png)

Thanks
