### ISSUE TITLE
[BUG]: Missing OSQuery information for OSQuery button available under Timeline>Notes section.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/security-docs#2613]
**Description:**
Missing OSQuery information for OSQuery button available under Timeline>Notes section.

**PR Ticket:**
https://github.com/elastic/security-docs/pull/2561

**URL link or topic name:**
https://security-docs_2561.docs-preview.app.elstc.co/guide/en/security/master/invest-guide-run-osquery.html#run-live-queries-ig

**Screenshots/ Recordings:**
**Expected:**

https://user-images.githubusercontent.com/77374876/196630865-bae78ad7-7382-4fe1-8d23-019c76d9d14c.mp4

**Actual:**

![13](https://user-images.githubusercontent.com/77374876/196630828-de7bfdd7-64a7-43b8-b68d-0ed7ac86a0ad.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by patrykkopycinski** [comment]
Thank you @amolnater-qasource, we have decided to not document osquery button in the timeline notes until we have a good use case for that. It was added here as a side effect, because timeline notes share the same component with investigation guide
