### ISSUE TITLE
[DOCS] Threat Matching Rules for 7.10

### ISSUE THREAD

**Issue by dontcallmesherryli** [elastic/security-docs#264]
## Description 

META: https://github.com/elastic/security-team/issues/20
Mock: https://www.figma.com/file/RicL36qDX8MjRTDL3CmrCr/Rules-7.10?node-id=206%3A0

Threat Matching rules would be introduced for 7.10, giving users the ability to match fields across Kibana indexes with Threat Intel Index that users uploaded into their stack.

## Acceptance Test Criteria

**Documentation is needed for Threat Matching rule type.**
Creation of Threat Matching Rule:
1. Go to Detections tab > Manage Detection Rules
2. Click on Create A New Rule
3. Select Threat Matching rule type
4. Enter necessary fields:
   1. Add the index patterns you are matching
   2. Type in query to narrow down your search
   3. Add the threat intel index you want to use in the match
   4. Type in query to narrow down threat intel index search
   5. Select the fields from the index patterns and threat intel index you want to receive alerts on when matched
5. Complete rest of rules creation steps. 

**Viewing Threat Matching Rule in Detections page:**
User will receive 1 alert per rule that produced 1 match.

## Notes

- Add the **"Team:Docs"** label to new issues. 
- Be sure to add the version number label. 
- Be sure to add any necessary screenshots for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by jmikell821** [comment]
PR #336 merged.
