### ISSUE TITLE
[DOCS]Assignee field not showing in create case form

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#2660]
**Description**
Assignee field not showing in create case form

**URL link**

https://www.elastic.co/guide/en/security/8.5/signals-to-cases.html

**Screen-Shot**

- actual result

![image](https://user-images.githubusercontent.com/59917825/199484695-6c7794f6-7bc2-4c69-ab49-5d0031e6e504.png)

- expected result

![image](https://user-images.githubusercontent.com/59917825/199484780-bd8ad9b9-c825-4bac-88d4-6e3e0ddfd7b0.png)

**Comment by nastasha-solomon** [comment]
Hi @deepikakeshav-qasource and @karanbirsingh-qasource - the screenshot was updated in https://github.com/elastic/security-docs/pull/2680. Please take a look when you have a chance. Thank you!

**Comment by karanbirsingh-qasource** [comment]
Hi @nastasha-solomon 

thanks for fixing the change, we have previewed the latest doc link and issue is fixed now. ✔️ 

![image](https://user-images.githubusercontent.com/59917825/200746477-b92567e0-8ca0-45ef-bdfc-e2ea00a05f3a.png)


Hence we are closing this issue and adding "QA:Validated" tag to it.

thanks !!
