### ISSUE TITLE
[DOCS] Document Endpoint known issue for 8.5.0

### ISSUE THREAD

**Issue by ferullo** [elastic/security-docs#2675]
## Description 

Endpoint has a bug introduced in 8.5.0 that can cause Linux Endpoints running on computers with many CPUs to fail in indeterminate ways (policy failures and/or crashes) https://github.com/elastic/endpoint/issues/34

Can we please add a release note for 8.5.0 to mention that.

cc @roxana-gheorghe @nfritts @nicholasberlin @stanek-michal @lrishi

**Comment by joepeeples** [comment]
@ferullo Do you think there's any need to document this beyond release notes, such as a troubleshooting topic, etc.? If we think the bug is likely to only exist in 8.5.0 and fixed in future versions (8.5.1?), adding just a release note is probably enough IMO, but just wanted to check.

**Comment by ferullo** [comment]
Yes, we expect to fix it in 8.5.1. There is no reason to document the workaround as a generic troubleshooting tip.
