### ISSUE TITLE
[DOCS] Add instructions for offline Endpoint global artifact updates

### ISSUE THREAD

**Issue by stevewritescode** [elastic/security-docs#2676]
## Description 

This issue covers docs changes to support https://github.com/elastic/security-team/issues/5289, so that users can better understand how to update the global artifacts used in Elastic Endpoint for installation that aren't internet-accessible. That meta-issue itself is largely about document and the description has more detailed use cases and information.

The target release is 8.6.

I have created a [document](https://docs.google.com/document/d/1VNt7gogyidcv4lssTQkCbjWJFy0X-FxLUALPPH4RBFA/edit?skip_itp2_check=true&pli=1#) which contains a rough draft of the content we'd like to add to the docs. However, I'm hoping the docs team can partner with me to figure out how to integrate this content into our existing documentation and how to properly organize the information to make it easily consumable by our users.

@jmikell821 this issue is a follow-up on our slack conversation. Thanks!

**Comment by stevewritescode** [comment]
@joepeeples is there anything I can do to help move this along?

**Comment by joepeeples** [comment]
Hi @stevewritescode, is the body content in the linked Google doc fully up to date? There are some fairly in-depth conversations going on in the comments, and it's not always clear if the body text has already been updated based on those conversations, or if more changes/decisions are still needed.

Would it be possible to mark the conversations as resolved where appropriate, and make sure that the body text reflects any decisions or suggestions from the comments? Then I can start adding the content to the docs, ensuring it's the latest version of the text.

**Comment by stevewritescode** [comment]
@joepeeples the linked document is not intended to act as a word-for-word source to directly copy and paste into our external documentation. Specifically the introduction "User Stories" and later "FAQ" is not intended for end-users.

The comments like [this one](https://docs.google.com/document/d/1VNt7gogyidcv4lssTQkCbjWJFy0X-FxLUALPPH4RBFA/edit?pli=1&disco=AAAAjOWk7Ag) are relevant to my question above about where and how we would integrate this documentation into our broader product docs:
>This script is really neat and brought me towards the idea what if we did the same optimization on the fleet airgapped documentation page?
[https://www.elastic.co/guide/en/fleet/8.5.0/air-gapped.html#host-artifact-registry](https://www.google.com/url?q=https://www.elastic.co/guide/en/fleet/8.5.0/air-gapped.html%23host-artifact-registry&sa=D&source=docs&ust=1669221600823054&usg=AOvVaw3OlFHuu2xAhqqpGMI05awW)

I'd like to keep those comments open until we decide where we need updates to the docs and what the general structure would be.

@joepeeples could you let me know where in our product documentation we would want to put this kind of setup/configuration information for Elastic Endpoint? I could then follow-up with a PR or a separate google doc that more precisely captures exactly what we would put in the docs.

**Comment by stevewritescode** [comment]
@joepeeples and I talked offline about this. Per our discussion, Joe, I made updates to the [Google doc](https://docs.google.com/document/d/1VNt7gogyidcv4lssTQkCbjWJFy0X-FxLUALPPH4RBFA/edit?skip_itp2_check=true&pli=1#heading=h.4lvc7a1tecwx). Ignore the section at the bottom titled "Internal FAQ"

Otherwise, the doc is ready to incorporate into a new section in https://www.elastic.co/guide/en/security/current/getting-started.html
