### ISSUE TITLE
[DOCS] Clarify dependencies for Threat intel card and Indicators page 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#2691]
## Description 

@maxcold and I met to discuss the doc feedback in https://github.com/elastic/seceng/issues/4768. Below, I’ve outlined the short and long-term action items for us to consider.

### Short-term:

- Make several improvements to the docs for setting up the Threat Intelligence card:
  - Specify that the card supports the indicator match rule
  - Emphasize that the card references the `defaultThreatIndex` advanced setting, as does the indicator match rule. 
  - Potentially revise the title of the “Enable threat intelligence integrations” topic to something that’s less generic (e.g., Set up the Threat Intelligence card). These instructions detail pre-reqs for using the Threat Intelligence card only.  
- Possibly expand the requirements for setting up the Indicators page. If I’m understanding the page dependencies correctly, users can still use the Filebeat threat intel integrations that they installed in 8.4 or earlier **_IF_** they’ve upgraded their Filebeat version to 8.x or later. 

### Long-term:
A couple of ideas for re-organizing and or condensing information about available threat intel features:
- Combine all threat intel features into a single section that details the different features offered and their dependencies. 
- Create instructions/explanatory content for getting started with threat intelligence. We could add this to the Getting started with Elastic Security portion of the docs so users can have all of the necessary set-up information upfront. 

## Notes

- It could also be worth clarifying that threat intelligence integrations, the indicator match rule, and the Threat intelligence card _do not_ require an Enterprise license to use.

**Comment by maxcold** [comment]
`Potentially revise the title of the “Enable threat intelligence integrations” topic to something that’s less generic (e.g., Set up the Threat Intelligence card)` I would make it more about the Indicator Match Rule then

**Comment by nastasha-solomon** [comment]
@maxcold that's a great idea and would immediately convey what threat intel features/capabilities the card supports.

**Comment by nastasha-solomon** [comment]
Closing since these set of features have been de-prioritized and @maxcold has moved to a different team. Will open a doc enhancement request if this needs to be revisited down the line.
