### ISSUE TITLE
[DOCS] Bulk alerts/events to Investigate in Timeline

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#2695]
## Description 

Related:
- https://github.com/elastic/kibana/pull/142737
- https://github.com/elastic/security-team/issues/3271

Add multiple events/alerts to investigate in Timeline.

## Docs to update

The main section to update is [Manage detection alerts | View alerts in Timeline](https://www.elastic.co/guide/en/security/master/alerts-ui-manage.html#signals-to-timelines). This section already describes two other ways of pivoting from an alert view to the Timeline view, and now we'll be adding a third way.

This could be very similar to [Change an alert's status](https://www.elastic.co/guide/en/security/master/alerts-ui-manage.html#detection-alert-status), which also explains three ways to do the same thing with alerts.

## Demo video

_(reproduced from https://github.com/elastic/kibana/pull/142737)_

https://user-images.githubusercontent.com/7485038/199056731-4287fc61-9d0b-4cf3-ba1f-741f6b66ae97.mov

**Comment by logeekal** [comment]
Hey @joepeeples , One update. Recently, we update the limit for maximum number of item can be added to the timeline to `2000` instead of `4000`

**Comment by joepeeples** [comment]
Good to know, thank you @logeekal! 🙏
