### ISSUE TITLE
[DOCS] Exception enhancements in 8.6

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#2728]
## Description 

Addresses completed items in https://github.com/elastic/security-team/issues/2089

The exceptions feature has undergone several significant UI and workflow changes in 8.6. The goal behind these changes is to provide users with more control over the way they share and segment rule exceptions. As an example, prior to these changes, users encountered problems when duplicating exceptions and weren't provided with user-friendly alternatives. 

The following is a list of changes that will need to documented:

- The Exceptions lists page has been renamed to ~“Rule exceptions”~ "Shared Exception Lists". The page is still located under the Manage section in the main nav.
- In 8.6, there will be two types of exception lists: default exception lists and shared exception lists. Both of these concepts will need to be explained as they are both created and managed differently. 
- Users can add exception items from an exception list using the Manage rules button.
- In 8.6, users can import existing exception lists and create new shared exception lists. 
    - [x] In the [8.5 docs](https://www.elastic.co/guide/en/security/master/detections-ui-exceptions.html#manage-exceptions), we state that exceptions are automatically grouped into exception lists. Need to check if the **Import exception list** feature on the Rule Exceptions page supports these types of "old" lists and the new shared exception lists or just one.    
- Users now have a third way of creating rule exceptions (exception items). Now, users can create a rule exception from the Alerts table (i.e., directly from an alert), the rule details page (i.e., from the Rule exceptions tab), and from the Rule Exceptions page (**Create shared exception list -> Create exception item**).
- When users duplicate rules, they will be prompted to specify whether they want to duplicate the rule and the rule's exceptions or if they want to duplicate the rule only.  
 
## Notes
- If I do change the title of the Rule exceptions and value lists topic, will need to do a quick search of the security docs project to locate all cross references to the file/topic anchor. Need to specifically look for instances when the anchor is accompanied by text that'll be linked. If references only contain the anchor, can leave as is. 
- Useful internal docs to reference while defining exception terms: https://github.com/elastic/security-team/blob/0d70b408774fa81b97b7c995155babbe06d8ff1f/docs/analyst-experience-team/detections/platform_area/exceptions/overview.mdx
- @dhurley14 to follow-up with Product on formalizing the following terms:
  - Default rule lists
  - Shared exception lists
  - Exception items 
- @dhurley14 to update Exception API docs
- Notes about the Rule Exceptions page:
  - When creating an exception item from the Rule Exceptions page, users can only add the exception to a rule or a list. They can’t do both.
  - After create the shared list and exceptions, can add exceptions in the list to one or more rules by clicking the **Manage Rules** button. 

<img width="800" alt="Screen Shot 2022-11-27 at 5 26 43 PM" src="https://user-images.githubusercontent.com/79124755/204163053-c7773d93-547a-4906-a3a6-ed14f89f068f.png">

### [Elastic Security UI | Manage](https://www.elastic.co/guide/en/security/master/es-ui-overview.html#_manage)

- [x] Refresh second bullet - page has been renamed to Rule exceptions
- [x] Refresh screenshot (`manage-pg.png`)

### [Rule exceptions and value lists](https://www.elastic.co/guide/en/security/master/detections-ui-exceptions.html)
Will need to make several changes to this topic:
- Consider creating individual topics for all of the sub-sections. 
- [x] Could be useful to define these terms/concepts:
  - Rule exceptions 
  - Exception items
  - Exception lists (there are two types: default rule lists and shared exception lists)
  - Value lists (used for building exceptions)
- Refresh steps for the following:
  - [x] Adding an exception to a rule - Users can now do this from the rule details page, the Alert table, or the Rule Exceptions page. 
  - [x] Adding Elastic endpoint exceptions - Users can now do this from the rule details page, the Alert table, or the Rule Exceptions page. (Need to verify if users can do this from the Rule Exceptions page. Also unable to refresh screenshots at the moment)

- Explain how to access and navigate the shared exception list details page. Need to cover the following: 
  - [x] Creating a shared exception list and viewing list details
  - [x] Adding exception items to a shared exception list 
  - [x] Editing exception items within a shared exception list 
  - [x] Applying a shared exception list to multiple rules 
  - [x] Editing, deleting, exporting, and importing shared exception lists (remember to explain how to import exception lists from 8.5)
- All screenshots need to be refreshed:
  - [x] `add-exception-ui.png`
  - [x] `endpoint-add-exp.png` (ATM, I'm unable to create an endpoint exception in test ESTEC deployment. Am running BC3)
  - [x] `nested-exp.png` (Same comment as above)
  - [x] `exceptions-page.png`
  - [x] `actions-exception-list.png`

### [Tune detection rules](https://www.elastic.co/guide/en/security/master/tuning-detection-signals.html) 
- Refresh steps in the following sections:
  - [x] Filter out uncommon application alerts 
  - [ ] Tune rules detecting authorized processes (check if step 1 needs to be revised with the new rule duplication feature)
- Refresh the following screenshots:
  - [x] `process-exception.png`
  - [x] `process-specific-exception.png`

### [Manage detection rules](https://www.elastic.co/guide/en/security/master/rules-ui-management.html#rules-ui-management)
- [x] Add a note to the "Manage rules" section.

**Comment by joepeeples** [comment]
Related PRs from D&R release demo:
- Manage exceptions overview: 
  https://github.com/elastic/kibana/pull/142289 and multiple other PRs
- Exception list details view: 
  https://github.com/elastic/kibana/pull/143041
- Sorting Exception lists and duplicating:
  https://github.com/elastic/kibana/pull/144782

**Comment by peluja1012** [comment]
Hey @joepeeples @nastasha-solomon, playing around with this feature the last couple of days, we realized we should make it clear to users that any existing exception lists created in 8.5 and below will be considered "shared" in 8.6. We will also be updating a the title of main exceptions page to "Shared Exception Lists". @dhurley14 will tag you in the PR. We might need to update a couple of screenshots accordingly.

**Comment by nastasha-solomon** [comment]
@peluja1012 @dhurley14 thanks for the ping about these changes! 

In the docs for [managing shared exception lists](https://www.elastic.co/guide/en/security/master/shared-exception-lists.html#manage-exception-lists), I included a note that exception lists created in 8.5 and earlier are imported as shared exception lists. Do you think this information needs to be more visible within the exception docs? Should we highlight this information in the release notes and release highlights (i.e. the What's new page) as well? 

I've also made a list of screenshot and text changes that I'll need to ensure the UI changes made last month are reflected in the 8.6 exception docs. You can find the list [here](https://github.com/elastic/security-docs/issues/2797).

**Comment by peluja1012** [comment]
> Do you think this information needs to be more visible within the exception docs? Should we highlight this information in the release notes and release highlights (i.e. the What's new page) as well?

Hi @nastasha-solomon, I think it's worth highlighting in the release notes also. We should also note that upon upgrade to 8.6, existing exception lists will be treated as shared exception lists and appear in the Shared Exception Lists page. Thanks!

**Comment by nastasha-solomon** [comment]
Got it, will do. Thanks, @peluja1012 !
cc: @jmikell821 @benironside

**Comment by nastasha-solomon** [comment]
Merged https://github.com/elastic/security-docs/pull/2808 and #2748
