### ISSUE TITLE
Update Endpoint quarantine documentation

### ISSUE THREAD

**Issue by ferullo** [elastic/security-docs#2784]
## Description 

Can we please update documentation for [Malware prevention](https://www.elastic.co/guide/en/security/8.5/configure-endpoint-integration-policy.html#malware-protection) and [blocklist](https://www.elastic.co/guide/en/security/8.5/blocklist.html) to indicate that:
1. When in prevent mode Endpoint will quarantine the file that is alerted on
2. The only way to restore the file is to add an Endpoint exception for it
3. Removing the file from the blocklist will not restore it
4. If Endpoint is uninstalled all quarantined files will be deleted and cannot be restored if Endpoint is reinstalled

cc @roxana-gheorghe @caitlinbetz @nfritts @softengchick @gabriellandau

**Comment by joepeeples** [comment]
https://github.com/elastic/security-docs/pull/3398 added this information to the integration policy docs starting in 8.7, with a whole section on [managing quarantined files](https://www.elastic.co/guide/en/security/current/configure-endpoint-integration-policy.html#manage-quarantined-files). Now that we have proper docs on how to restore a quarantined file, I don't think we need to mention the methods that _don't_ work (removing from blocklist, uninstalling Endpoint).
