### ISSUE TITLE
Introduce CSPM documentation for 8.7

### ISSUE THREAD

**Issue by tinnytintin10** [elastic/security-docs#2788]
## Background 

The Cloud Security Posture Management (CSPM) capability will be introduced in the security solution with the release of 8.7 🎉 

This capability will initially be released in BETA with plans to go GA in 8.8. This issue will track the work to create the necessary documentation for this capability.

## Rough Structure for Cloud Native Security section in security doc
- Cloud Native Security
   - Cloud Security Posture Management (CSPM)
     - Getting started with CSPM
     - Cloud Posture Dashboard 
     - Findings Page
     - Benchmark Rules
  - Kubernetes Security Posture Management (KSPM)
     - Getting started with KSPM
     - Cloud Posture Dashboard 
     - Findings Page
     - Benchmark Rules 
- [[CWP section(s) update not in scope for this issue]]

## Action Items 

- [x] @tinnytintin10 to schedule kickoff with security docs team 
- [x] @tinnytintin10 to provide a rough draft of content for various sections of the new CSPM docs (will be similar to KSPM docs) 
- [x] @tinnytintin10 to provide up-to-date screenshots of relevant pages 
- [x] @benironside to review, provide feedback and implement updates 
- [x] @elastic/cloud-security-posture to review docs for technical accuracy

## Related items :
- [📃 Master branch view of security solution docs](https://www.elastic.co/guide/en/security/master/index.html)
- [✍️ Epic](https://github.com/elastic/security-team/issues/5083)
- [🎥 Integration onboarding prototype](https://www.figma.com/proto/QITLtzCQWAJCOW2xNsnO81/CSP-Visualizations?node-id=1080%3A345376&scaling=scale-down&page-id=175%3A184210&starting-point-node-id=1080%3A345376)
- [🎨 Figma mocks](https://www.figma.com/file/QITLtzCQWAJCOW2xNsnO81/CSP-Visualizations?node-id=175%3A184210&t=EuR7BRS55GsLxQXT-0)

cc @snehsach19

**Comment by tinnytintin10** [comment]
As part of this work, I need to provide updates on what the new integration readme will be.

**Comment by tinnytintin10** [comment]
https://github.com/elastic/security-team/issues/5631#event-8355152001

**Comment by tinnytintin10** [comment]
> As part of this work, I need to provide updates on what the new integration readme will be.

https://github.com/elastic/integrations/pull/5133#issuecomment-1422452151 PR in review

**Comment by tinnytintin10** [comment]
Note to self for next week: we need to update 8.5 & 8.6 documentation regarding `namespaces` confusion for KSPM

**Comment by ari-aviran** [comment]
@tinnytintin10 regarding AWS permissions needed for CIS AWS CSPM - see my notes in [this ticket](https://github.com/elastic/cloudbeat/issues/716#issuecomment-1427419447)

**Comment by tinnytintin10** [comment]
@benironside here is the document with the proposed structure and starter content for [CSPM's 8.7 docs](https://docs.google.com/document/d/1fmChP48xUvl8e-2aYOBGT7n56LNOzU4K8ni-CJtfxbY/edit?usp=sharing) we talked about earlier.

As you start writing up the content, let me know if any questions come up or if ya need clarification on what I have documented above.
