### ISSUE TITLE
Exceptions UX updates

### ISSUE THREAD

**Issue by benironside** [elastic/security-docs#2797]
There are UX Updates to Exceptions in 8.6, detailed in this PR: https://github.com/elastic/kibana/pull/147955

Will need to make the following updates to account for the additional UI changes to exceptions in 8.6:
- [Elastic Security UI | Navigation menu](https://www.elastic.co/guide/en/security/master/es-ui-overview.html#navigation-menu-overview): 
  - [x] Refresh gif `nav-overview.gif` (shows the Manage menu options at the end).
- [Elastic Security UI | Manage](https://www.elastic.co/guide/en/security/master/es-ui-overview.html#_managel): Update text and screenshots
  - [x] Update page name in second bullet. The Rule Exceptions page was renamed the Shared Exceptions Lists page.
  - [x] Refresh screenshot `manage-pg.png`.
- [Rule exceptions | Shared exception lists](https://www.elastic.co/guide/en/security/master/detections-ui-exceptions.html#shared-exception-list-intro): Update text and screenshots
  - [x] Update reference to the Rule Exceptions page. Should be Shared Exceptions Lists page.
  - [x] Refresh screenshot `rule-exceptions-page.png`.
- [Add and manage exceptions](https://www.elastic.co/guide/en/security/master/add-exceptions.html)
  - [x] Update Rule Exceptions page reference in the intro para. Should be Shared Exceptions Lists page.
  - [x] Refresh instructions in the third bullet under step 1 within the [Add exceptions to a rule](https://www.elastic.co/guide/en/security/master/add-exceptions.html#detection-rule-exceptions) section.
  - [x] Refresh note and tip under step 5 within the [Add exceptions to a rule](https://www.elastic.co/guide/en/security/master/add-exceptions.html#detection-rule-exceptions) section. Both contain references to the old page name.
  - [x] Refresh instructions in the third bullet under step 1 within the [Add Elastic Endpoint exceptions](https://www.elastic.co/guide/en/security/master/add-exceptions.html#endpoint-rule-exceptions) section.
- [Create and manage shared exception lists](https://www.elastic.co/guide/en/security/master/shared-exception-lists.html): Update references to the Rule Exceptions page, instructions for creating shared exception lists, and screenshots.
  - [x] Update Rule Exceptions page reference in the intro para.
  - [x] Refresh screenshot `rule-exceptions-page.png`.
  - [x] Update reference to the Rule Exceptions page in step 1 in [Create shared exception lists](https://www.elastic.co/guide/en/security/master/shared-exception-lists.html#create-shared-exception-list).
  - [x] Update reference to the Rule Exceptions page in step 1 in [Add exception items to shared exception lists](https://www.elastic.co/guide/en/security/master/shared-exception-lists.html#add-exception-items).
  - [x] Make the following changes to the [Associate shared exception lists with rules](https://www.elastic.co/guide/en/security/master/shared-exception-lists.html#link-shared-exception-lists).
      - [x] Update reference to the Rule Exceptions page in step 1.
      - [x] Modify step 2 to include the option to associate rules from the **More actions (...)** menu.
      - [x] Modify step 3 to show that there's now a toggle option when selecting rules to associate the shared exception list with.
  - [x] Update Rule Exceptions page reference in the intro para of [View and filter exception lists](https://www.elastic.co/guide/en/security/master/shared-exception-lists.html#view-shared-exception-lists). 
  - [x] Update the [Manage shared exception lists](https://www.elastic.co/guide/en/security/master/shared-exception-lists.html#manage-exception-lists) section:
     - [x] Refresh screenshot `actions-exception-list.png`. The **Manage Rules** option was added to the shared exception list's overflow menu.
     - [x] Mention in the note that upon upgrade to 8.6, existing exception lists will be treated as shared exception lists and appear in the Shared Exception Lists page.

**Comment by nastasha-solomon** [comment]
Related to https://github.com/elastic/security-docs/issues/2728 and https://github.com/elastic/security-docs/pull/2748.

**Comment by nastasha-solomon** [comment]
Merged https://github.com/elastic/security-docs/pull/2808.
