### ISSUE TITLE
[BUG] "Set alert status" API doc mentions "in-progress" status instead of "acknowledged"

### ISSUE THREAD

**Issue by peluja1012** [elastic/security-docs#2798]
The "set alert status" API docs are outdated. They mention `in-progress` status, but this status was renamed to `acknowledged` in 7.15 by this [PR](https://github.com/elastic/kibana/pull/107972). @dplumlee to confirm this update is safe to make.

<img width="715" alt="Screen Shot 2022-12-22 at 4 08 12 PM" src="https://user-images.githubusercontent.com/616158/209246198-92cd113f-276e-4760-90d3-5fcdbddd7d27.png">

**Doc URL link or topic name**:
https://www.elastic.co/guide/en/security/8.5/signals-api-overview.html#_set_alert_status

**Comment by dplumlee** [comment]
I would say this is a safe update to make. We still support `in-progress` for backwards compatibility reasons but we should be telling users to use `acknowledged` as it lines up with the rest of the UI terminology past `7.15`
