### ISSUE TITLE
[BUG] Clarify that Elastic Defend requries Fleet

### ISSUE THREAD

**Issue by ferullo** [elastic/security-docs#2803]
**Description**: The below linked page contains the text "Like other Elastic integrations, Elastic Defend can be integrated into the Elastic Agent using [Fleet](https://www.elastic.co/guide/en/fleet/master/fleet-overview.html)". This has caused some confusion because Elastic Defend actually requires Fleet. It's not that it _can_ work with Fleet, it's that it _must_ work with Fleet. Is there some way to alter or add wording to make it clear Fleet is a firm requirement for Elastic Defend?

**Doc URL link or topic name**: https://www.elastic.co/guide/en/security/master/install-endpoint.html

**Comment by joepeeples** [comment]
Thanks for bringing attention to this, @ferullo! It should be a pretty small, but very meaningful edit, so I'll try to get this in by the 8.6 release. Backporting would also probably be helpful for customers using earlier versions -- any sense of how far back would be reasonable to backport?

**Comment by ferullo** [comment]
Thanks Joe. I think 8.4 is a reasonable place to stop backporting.
