### ISSUE TITLE
"Alert Reason" heading name missing under overview alert fly out

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#2853]
**Description**
"Alert Reason" heading name missing under overview alert fly out

**URL link**

- https://www.elastic.co/guide/en/security/current/whats-new.html

**Screen-Shot**

- Actual result

![image](https://user-images.githubusercontent.com/59917825/211739080-def142dd-2e00-4470-be40-5a8d5f83cc0b.png)

- Expected result

![image](https://user-images.githubusercontent.com/59917825/211739044-5b63df4f-b815-45c9-90a0-a486721425cd.png)

**Comment by karanbirsingh-qasource** [comment]
@deepikakeshav-qasource please review

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource the section title change was doc'd in the 8.6 What's new topic here: https://www.elastic.co/guide/en/security/current/whats-new.html#_alerts_enhancements

If this looks good, we can likely close this issue :)

**Comment by karanbirsingh-qasource** [comment]
Yes @nastasha-solomon the shared link has correct title Alert Reason being shown so we are good to close out this issue.

![image](https://user-images.githubusercontent.com/59917825/212243635-c3650c97-1f9e-493c-bd92-8c9ba56a4da3.png)
