### ISSUE TITLE
[BUG] Suppressed Field under Rule Creation modal missing 

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#2854]
**Description**
Suppressed Field under Rule Creation modal missing 

**URL link**

- https://www.elastic.co/guide/en/security/current/whats-new.html

**Screen-Shot**

- Actual result

![image](https://user-images.githubusercontent.com/59917825/211740051-d47fc819-d8b7-4baf-8631-3b888606cffe.png)

- Expected result

![image](https://user-images.githubusercontent.com/59917825/211739952-2108c14e-00c1-4c25-b2a9-203dc6555479.png)

**Comment by karanbirsingh-qasource** [comment]
@deepikakeshav-qasource please review

**Comment by joepeeples** [comment]
This screenshot was updated in https://github.com/elastic/security-docs/pull/2877.
