### ISSUE TITLE
close all alert that match this exception and were generated by selected rule/s checkbox is not showing

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#2855]
**Description**
close all alert that match this exception and were generated by selected rule/s checkbox is not showing

**URL link**

- https://www.elastic.co/guide/en/security/8.6/add-exceptions.html

**Screen-Shot**

- Actual result

![image](https://user-images.githubusercontent.com/59917825/211740694-8c10294b-947d-42b4-8c3f-ced67d00ee3c.png)

- Expected result

![image](https://user-images.githubusercontent.com/59917825/211740660-95a90fdb-2c7b-4513-90a3-a8e5c12c2548.png)

**Comment by karanbirsingh-qasource** [comment]
@deepikakeshav-qasource please review

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource @deepikakeshav-qasource I recreated this image using 8.5 BC10 and am still not seeing the second checkbox. @dhurley14 does that second checkbox only show up in certain scenarios or for specific rule types?

<img width="900" alt="bug-2855" src="https://user-images.githubusercontent.com/79124755/211872486-dad86b45-54d2-4568-be95-9cc760c81cb9.png">

**Comment by karanbirsingh-qasource** [comment]
hi @nastasha-solomon 

Similar case for this issue also as of https://github.com/elastic/security-docs/issues/2856 for this also we have 3 ways and for each ways components of exception modal changes so we can add screen-shot of each way if possible.

- ### Doc
![image](https://user-images.githubusercontent.com/59917825/211976147-db57ccc3-3e06-4fea-9e2c-9ee4f87337ab.png)

- ###  To add an exception from the rule details page: ✔️ 

![image](https://user-images.githubusercontent.com/59917825/211976347-6233c7e3-d352-4eb8-a1db-143d6222ef35.png)

- ### To add an exception from the Alerts table: ❌ 

![image](https://user-images.githubusercontent.com/59917825/211976477-a0dfc912-3de0-47c6-b9ca-63bd9502b68c.png)


- To add an exception from the Shared Exception Lists page: ❌ 

![image](https://user-images.githubusercontent.com/59917825/211976564-b430aec6-74b7-47cf-a012-140401a0ac0d.png)

**Comment by dhurley14** [comment]
This is interesting. @WafaaNasr Do you happen to know if anything changed lately?

**Comment by WafaaNasr** [comment]
Haven't touched the exceptions :( since a long time ago. This looks new :(

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource I'm not sure whether the three panes will eventually look the same, so I decided to revise the text describing the screenshot. The changes are available for your review at https://github.com/elastic/security-docs/pull/2900 when you have a chance. Let me know if it works and thanks in advance!

**Comment by karanbirsingh-qasource** [comment]
Hi @nastasha-solomon thanks for the update.

we have reviewed the file changes and our issue is resolved with the update context in the documentation and attached below screenshot match the documentation . so we are good to close this issue.

![image](https://user-images.githubusercontent.com/59917825/213616502-9ac889a1-4d1b-47cc-b0f3-79db87e8235b.png)

**Comment by nastasha-solomon** [comment]
Merged https://github.com/elastic/security-docs/pull/2900.
