### ISSUE TITLE
close this alert checkbox not showing

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#2856]
**Description**
close this alert checkbox not showing

**URL link**

- https://www.elastic.co/guide/en/security/8.6/add-exceptions.html

**Screen-Shot**

- Actual result

![image](https://user-images.githubusercontent.com/59917825/211741243-44d7307d-2bcb-41ef-801f-787cb574c34e.png)

- Expected result

![image](https://user-images.githubusercontent.com/59917825/211741270-4b74f9ab-f728-4b51-bf52-ca900f23ac6b.png)

![image](https://user-images.githubusercontent.com/59917825/211741429-047d0fd4-d032-4b07-acaa-38c1ffb54c3c.png)

**Comment by karanbirsingh-qasource** [comment]
@deepikakeshav-qasource please review

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource @deepikakeshav-qasource I recreated this image using 8.6 BC10 and am still seeing the following. 

<img width="600" alt="bug-2856" src="https://user-images.githubusercontent.com/79124755/211897096-83a94deb-6d31-4ad8-b10a-799b3304fe72.png">

@dhurley14 did the Add Endpoint Exception flyout change in a later BC for 8.6? I'm not sure what I'm missing here.

**Comment by karanbirsingh-qasource** [comment]
Hi @nastasha-solomon


thanks for looking into the observation actually for the given section that is endpoint exception we have described 3 of the ways by which user can add the endpoint exception so we were not sure if we will adding screen-shot of all the 3 ways as all the components of endpoint exception models varies in 3 ways.

- ### Doc

![image](https://user-images.githubusercontent.com/59917825/211974706-ce4b8ad0-0162-4fbf-9408-f37e4f687fe2.png)


- ### To add an Endpoint exception from the rule details page: ✔️

![image](https://user-images.githubusercontent.com/59917825/211974182-0472d15d-975e-4465-8913-0eae9ea3571a.png)

- ### To add an Endpoint exception from the Alerts table: ❌

![image](https://user-images.githubusercontent.com/59917825/211974195-40d9863e-bff1-4f8a-8788-4d9d09eaf923.png)

- ### To add an Endpoint exception from Shared Exception Lists page: ❌

![image](https://user-images.githubusercontent.com/59917825/211974209-4c57ac9f-fd5b-427e-a275-129fe733ca14.png)

**Comment by nastasha-solomon** [comment]
Fixed in https://github.com/elastic/security-docs/pull/2900
