### ISSUE TITLE
8.5 mentioned instead of 8.6 under new prebuilt rules 

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#2857]
**Description**
8.5 mentioned instead of 8.6 under new prebuilt rules 

**URL link**

- https://www.elastic.co/guide/en/security/current/whats-new.html#_endpoint_response_enhancements

**Screen-Shot**

- Actual result

![image](https://user-images.githubusercontent.com/59917825/211742219-1c4212eb-1799-42f4-8aeb-0070d26c32a8.png)

- Expected result

![image](https://user-images.githubusercontent.com/59917825/211742461-a1e2ebd3-eaee-4cfc-aabb-433719482ffd.png)

**Comment by karanbirsingh-qasource** [comment]
@deepikakeshav-qasource please review

**Comment by jmikell821** [comment]
@karanbirsingh-qasource please refresh your browser and check again. The view you're looking were highlights from `8.5`. I see the correct content showing in `8.6`, which had 18 new prebuilt rules. I'm going to close the issue for now; but please reopen if necessary.  
![2023-01-12_16-33-48](https://user-images.githubusercontent.com/57149392/212186582-952ad2da-6602-4400-bc39-2f9f50440171.png)
