### ISSUE TITLE
Incorrect count 28 instead of 18 prebuilt rules in documentation

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#2858]
**Description**
Incorrect count 28 instead of 18 prebuilt rules

**URL link**

- https://www.elastic.co/guide/en/security/current/whats-new.html#_endpoint_response_enhancements

**Screen-Shot**

Navigated to prebuilt rule reference page and then from browser do ctrl+f  text "8.6.0" and matching rules count 18 is found
however in doc 28 is mentioned

![image](https://user-images.githubusercontent.com/59917825/211744168-16aec9e7-4537-4bc4-91f8-e4c8987a6385.png)

![image](https://user-images.githubusercontent.com/59917825/211743902-4938574e-2bcd-4fd6-8a6f-5b6d24c6f14c.png)

![image](https://user-images.githubusercontent.com/59917825/211744280-61bac977-74b2-435e-99ac-068054bc6ff5.png)

**Comment by jmikell821** [comment]
This looks correct to me. Hence, closing. 

Topic: https://www.elastic.co/guide/en/security/current/whats-new.html
![2023-01-26_14-21-26](https://user-images.githubusercontent.com/57149392/214929882-43bd7363-228b-4dc2-b128-0fc6774fdb5d.png)
