### ISSUE TITLE
Investigation guide under rule creation timeline plugin doc is also not found

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#2859]
**Description**
Investigation guide under rule creation timeline plugin doc is also not found

**URL link**

- https://www.elastic.co/guide/en/security/current/rules-ui-create.html#rule-ui-advanced-params

**Screen-Shot**

![image](https://user-images.githubusercontent.com/59917825/211745278-e8ac4102-f696-46ed-90b0-22a4bd179fea.png)

Feature Ticket : https://github.com/elastic/security-team/issues/4824

**Comment by karanbirsingh-qasource** [comment]
@deepikakeshav-qasource please review

**Comment by joepeeples** [comment]
No change needed at this time. It sounds like this is referring to the interactive investigation guides feature, which is being documented in https://github.com/elastic/security-docs/pull/2821. Currently we're keeping any docs related to this feature isolated to the [**Technical preview**](https://www.elastic.co/guide/en/security/8.6/sec-experimental-intro.html) section, so we don't want to add anything to the rule creation docs identified above. Once the feature goes GA we might add something, but we'll open a new issue/PR for the change to GA.

**Comment by karanbirsingh-qasource** [comment]
thanks @joepeeples for looking into the issue and providing the confimration
