### ISSUE TITLE
Assignee filter not showing for existing case modal

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#2860]
**Description**
Assignee filter not showing for existing case modal

**URL link**

- https://www.elastic.co/guide/en/security/current/signals-to-cases.html

**Screen-Shot**

- Actual result

![image](https://user-images.githubusercontent.com/59917825/211748090-5d26c115-406b-4b91-813d-957941aac7f3.png)

- Expected result

![image](https://user-images.githubusercontent.com/59917825/211748047-6485ebdb-4500-4fbf-b8e2-cf6bbc5883e6.png)

**Comment by karanbirsingh-qasource** [comment]
@deepikakeshav-qasource please review

**Comment by nastasha-solomon** [comment]
Thanks for filing this, @karanbirsingh-qasource ! Please find the fixed doc at https://github.com/elastic/security-docs/pull/2876.

**Comment by karanbirsingh-qasource** [comment]
Closing this issue as the issue is fixed on [here](https://security-docs_2876.docs-preview.app.elstc.co/guide/en/security/master/signals-to-cases.html) 

![image](https://user-images.githubusercontent.com/59917825/212033073-f11bd7b4-013a-49c8-b159-5a1a72ea9161.png)
