### ISSUE TITLE
[BUG] Incorrect screenshot for `Response Action` option for a Detection Rule.

### ISSUE THREAD

**Issue by arvindersingh-qasource** [elastic/security-docs#2865]
**Description**
Incorrect screenshot for `Response Action` option for a Detection Rule.

**Doc URL link or topic name**
 - https://www.elastic.co/guide/en/security/8.6/osquery-response-action.html

**Screen Shots**

**Actual Results**

![8](https://user-images.githubusercontent.com/106220189/211762009-57f001a8-4d87-41a9-8483-94d045fe8a8b.png)

**Expected Results**

![9](https://user-images.githubusercontent.com/106220189/211762048-d5a1fb41-c088-4d5e-a697-6a0cf7671cdd.png)

**Comment by arvindersingh-qasource** [comment]
@manishgupta-qasource  Please review this bug.

Thanks.

**Comment by manishgupta-qasource** [comment]
Reviewed and assigned to @nastasha-solomon

CC: @jmikell821

**Comment by nastasha-solomon** [comment]
@arvindersingh-qasource please find the fixed docs at https://github.com/elastic/security-docs/pull/2874. Thank you!

**Comment by arvindersingh-qasource** [comment]
Hi @nastasha-solomon 

Thanks for the updates.

We have validated this issue on `Kibana Master Branch` and found that issue is now **fixed**.

### Please find the below Observations
![2865](https://user-images.githubusercontent.com/106220189/212630674-34668558-5b48-49ff-8ac2-592942666546.png)


Thanks.
