### ISSUE TITLE
[BUG] Incorrect Screenshot for `Osquery Results` under Alerts Detail flyout.

### ISSUE THREAD

**Issue by arvindersingh-qasource** [elastic/security-docs#2866]
**Description**
Incorrect Screenshot for `Osquery Results` under Alerts Detail flyout.

**Doc URL link or topic name**
 - https://www.elastic.co/guide/en/security/8.6/osquery-response-action.html

**Screen Shots**

**Actual Results**
 - Query Details option is missing 

![10](https://user-images.githubusercontent.com/106220189/211763050-8d99221a-5af3-4852-a629-759ab2c4e60f.png)

**Expected Results**
 - Query Details option should be present

![11](https://user-images.githubusercontent.com/106220189/211763156-abe85ee8-e916-4f22-afa8-5ad824389f7d.png)

**Comment by arvindersingh-qasource** [comment]
@manishgupta-qasource  Please review this bug.

Thanks.

**Comment by manishgupta-qasource** [comment]
Reviewed and assigned to @nastasha-solomon

CC: @jmikell821

**Comment by nastasha-solomon** [comment]
@arvindersingh-qasource please find the fixed docs at https://github.com/elastic/security-docs/pull/2874. Thank you!

**Comment by arvindersingh-qasource** [comment]
Hi @nastasha-solomon 

Thanks for the updates.

We have validated this issue on `Kibana Master Branch` and found that issue is now **fixed**.

### Please find the below Observations
![2866](https://user-images.githubusercontent.com/106220189/212630725-23f60278-b0df-4818-850a-a31e54ae9f2c.png)


Thanks.
