### ISSUE TITLE
[BUG] Incorrect Screenshot for `Run Osquery` flyout on Alerts Detail flyout.

### ISSUE THREAD

**Issue by arvindersingh-qasource** [elastic/security-docs#2867]
**Description**
Incorrect Screenshot for `Run Osquery` flyout on Alerts Detail flyout.

**Doc URL link or topic name**
 - https://www.elastic.co/guide/en/security/8.6/alerts-run-osquery.html

**Screen Shots**

**Actual Results**

![12](https://user-images.githubusercontent.com/106220189/211764192-74c0dd97-58b0-4a0d-8d4c-459a37e5608d.png)

**Expected Results**

![13](https://user-images.githubusercontent.com/106220189/211764227-18d9e4ed-88d7-491a-9d6a-9d97c88bc6c7.png)

**Comment by arvindersingh-qasource** [comment]
@manishgupta-qasource  Please review this bug.

Thanks.

**Comment by manishgupta-qasource** [comment]
Reviewed and assigned to @nastasha-solomon

CC: @jmikell821

**Comment by nastasha-solomon** [comment]
@arvindersingh-qasource please find the fixed docs at https://github.com/elastic/security-docs/pull/2874. Thank you!

**Comment by nastasha-solomon** [comment]
Closed  #2874

**Comment by arvindersingh-qasource** [comment]
Hi @nastasha-solomon 

Thanks for the updates.

We have validated this issue on `Kibana Master Branch` and found that issue is now **fixed**.

### Please find the below Observations
![2867](https://user-images.githubusercontent.com/106220189/212630758-fcd30ce9-9f22-4a93-843e-e4e299726216.png)


Thanks.
