### ISSUE TITLE
[BUG] Query Details option is missing in Screenshot for `Query pack results` 

### ISSUE THREAD

**Issue by arvindersingh-qasource** [elastic/security-docs#2868]
**Description**
Query Details option is missing in Screenshot for `Query pack results` 

**Doc URL link or topic name**
 - https://www.elastic.co/guide/en/security/8.6/view-osquery-results.html

**Screen Shots**

**Actual Results**

![14](https://user-images.githubusercontent.com/106220189/211764959-ae7162e8-9675-49bb-a06d-22724eebf8ef.png)

**Expected Results**

![15](https://user-images.githubusercontent.com/106220189/211764994-3c3088b4-817c-4a4b-9c15-a9f867799c99.png)

**Comment by arvindersingh-qasource** [comment]
@manishgupta-qasource  Please review this bug.

Thanks.

**Comment by manishgupta-qasource** [comment]
Reviewed and assigned to @nastasha-solomon

CC: @jmikell821

**Comment by nastasha-solomon** [comment]
@arvindersingh-qasource please find the fixed docs at https://github.com/elastic/security-docs/pull/2874. Thank you!

**Comment by nastasha-solomon** [comment]
Closed  #2874

**Comment by arvindersingh-qasource** [comment]
Hi @nastasha-solomon 

Thanks for the updates.

We have validated this issue on `Kibana Master Branch` and found that issue is now **fixed**.

### Please find the below Observations
![2868](https://user-images.githubusercontent.com/106220189/212630799-17322b70-d7b5-42b2-b4b6-c49446f26e02.png)


Thanks.
