### ISSUE TITLE
Alert suppression time window

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#2899]
## Description 

From related issue https://github.com/elastic/kibana/pull/148868 (images might be preliminary, subject to change):

> Adds ability to specify a time window with alert suppression on Query rules. If more alerts are detected with the same value in the "group by" field in subsequent rule executions, the existing alert will be updated to reflect the new doc count and suppression end time rather than creating a new alert.
> 
> ### Create Rule
> <img src="https://user-images.githubusercontent.com/55718608/212997145-cee96a7d-fc3b-4b08-8845-5a9c7876fa0a.png" width=500>
>
> ### Rule Details
> <img src="https://user-images.githubusercontent.com/55718608/212997293-69d93392-f74e-4e4e-925a-befbee531659.png" width=500>

**Comment by nastasha-solomon** [comment]
The `kibana.alert.last_detected` field will also need to be doc'd in the [alert schema table](https://www.elastic.co/guide/en/security/master/alert-schema.html). Here's the info for this field:

<table>
<tr>
	<td> 8.x alert field
    <td> Description
	<td> Type
<tr>
	<td> kibana.alert.last_detected
	<td> The most recent time this alert was updated
	<td> date
</table>

cc: @marshallmain
