### ISSUE TITLE
[BUG] Exception "matches" operator example is incorrect and misleading

### ISSUE THREAD

**Issue by peluja1012** [elastic/security-docs#2936]
**Description**:
In our documentation for wildcard/matches exception operator, we include an example that wouldn't yield expected results. More specifically, we say they can create a `matches` exception with a value of `C:\path\*\app.exe`. This won't match the results the user expects because the backslash (`\`) character is a special character and they would need to escape it. We have two requests:

1. Could we please update the example value to `C:\\path\\*\\app.exe`?
2. Could we pleased add a note saying that the backslash `\` character needs to be escaped (`\\`)?

cc @marshallmain 

**Doc URL link or topic name**:
https://www.elastic.co/guide/en/security/current/add-exceptions.html#detection-rule-exceptions

<img width="612" alt="image" src="https://user-images.githubusercontent.com/616158/214922898-ebceabb1-07ee-45a0-862f-7c268ecd87d5.png">

**Comment by nastasha-solomon** [comment]
Thanks for filing this bug, @peluja1012 ! Are there any other special characters that need to be escaped and that users need to be aware of?
