### ISSUE TITLE
Rules table UX enhancements for 8.7

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#2979]
## Description 

Several enhancements related to filtering the Rules table (part of epic https://github.com/elastic/security-team/issues/1972):

* https://github.com/elastic/kibana/pull/150153
* https://github.com/elastic/kibana/pull/150059

Moar enhancements and screenshots to update (as reported in https://github.com/elastic/security-docs/issues/3005):

- https://github.com/elastic/kibana/issues/145968 ([PR](https://github.com/elastic/kibana/pull/150059))
- https://github.com/elastic/kibana/issues/132497 ([PR](https://github.com/elastic/kibana/pull/150153))
- https://github.com/elastic/kibana/issues/148196 ([PR](https://github.com/elastic/kibana/pull/149840))
- https://github.com/elastic/kibana/issues/138907 ([PR](https://github.com/elastic/kibana/pull/149840))

## Notes

- Check with team at feature sync for any other related enhancements.
- Will affect both screenshots and text instructions.

**Comment by nastasha-solomon** [comment]
https://github.com/elastic/security-docs/issues/3005 contains some additional changes, most notably the version column being removed from the Rules table (https://github.com/elastic/kibana/issues/148196)
