### ISSUE TITLE
Bulk actions have been updated over time to have more capabilities, docs still have a select few.

### ISSUE THREAD

**Issue by jamster10** [elastic/security-docs#3004]
## Description 

[Our documentation notes that](https://www.elastic.co/guide/en/security/current/rules-api-create.html#actions-object-schema)

```
    .slack
    .email
    .pagerduty
    .webhook
```
are acceptable connectors for bulk actions but overttime we have increased its capability to:
```
Slack
Email
PagerDuty
Webhook
Microsoft Teams
IBM Resilient
Jira
ServiceNow
Swimlane
```

with new `action_type_id`s including:
`.index`
`.jira`
`.resilient`
`.servicenow`
`.servicenow-itom`
`.servicenow-sir` (ServiceNow SecOps)
`.swimlane`
`.teams` (Microsoft Teams)

Most of these are noted here: https://www.elastic.co/guide/en/security/current/rules-api-create.html#rules-api-create

But can we update the docs to provide the comprehensive list to our users.

Here is an image denoting the offerings the users currently have:
![image](https://user-images.githubusercontent.com/22603166/216065951-9eeb8541-1f98-42eb-a8ea-d5a96b8f9fc6.png)

This is related to this SDH: https://github.com/elastic/sdh-security-team/issues/534

**Comment by lcawl** [comment]
This might be a good opportunity to talk about moving to open API specifications as the source of truth for API docs. I've been working through the responseOps API specs per https://github.com/elastic/kibana/issues/137240 and am happy to chat further if the security dev teams are ready to begin down that path.

**Comment by nastasha-solomon** [comment]
@e40pud would you mind providing a list of accepted values for the [`action_type_id`](https://www.elastic.co/guide/en/security/current/rules-api-create.html#actions-object-schema) parameter that's available for the following endpoints: 

- [Create rule](https://www.elastic.co/guide/en/security/current/rules-api-create.html#actions-object-schema)
- [Update rule](https://www.elastic.co/guide/en/security/current/rules-api-update.html)
- [Bulk rule actions](https://www.elastic.co/guide/en/security/current/bulk-actions-rules-api.html)

Thank you!

**Comment by ymao1** [comment]
Yea, that list looks correct. Connectors available to the security form are registered with `SecurityConnectorFeatureId` and it looks like server log and xMatters are not registered with that feature ID.
