### ISSUE TITLE
[DOCS] Update screenshots of the Rules table

### ISSUE THREAD

**Issue by banderror** [elastic/security-docs#3005]
## Summary

In 8.7.0 we will ship a few updates to the Rules table, and we need to make sure our screenshots in the docs are up-to-date with these changes:

- [x] https://github.com/elastic/kibana/issues/145968 ([PR](https://github.com/elastic/kibana/pull/150059)) 
- [x] https://github.com/elastic/kibana/issues/132497 ([PR](https://github.com/elastic/kibana/pull/150153))
- [x] https://github.com/elastic/kibana/issues/148196 ([PR](https://github.com/elastic/kibana/pull/149840))
- [x] https://github.com/elastic/kibana/issues/138907 ([PR](https://github.com/elastic/kibana/pull/149840))

**Comment by joepeeples** [comment]
All changes already made in other PRs:

- Clear rules table filters - screenshot and text updated in #2998
- Filter enabled/disabled rules - screenshot and text updated in #2998
- Remove version column - screenshot updated in #2998, no text update needed (not previously mentioned)
- Remove "Advanced sorting" switch - done in #2960
