### ISSUE TITLE
[DOCS] Mention that the Rules table can now be shared via the URL

### ISSUE THREAD

**Issue by banderror** [elastic/security-docs#3006]
## Summary

In https://github.com/elastic/kibana/pull/145111 we made the state of the Rules table (filters, sorting, pagination, etc) persistent (stored) in the URL. This allows one user to set some filters in the Rules table, and send a link to the Rule Management page to another user. When the other user opens the page, they will see the table with the same filters restored for them.

We talked about that we might consider adding a small hint about that in the docs.

**Comment by nastasha-solomon** [comment]
Looks like this functionality was doc'd in https://github.com/elastic/security-docs/issues/2893. : D
cc: @joepeeples

**Comment by banderror** [comment]
I didn't know about this ticket! Thank you @joepeeples for looking after us 🙂

**Comment by joepeeples** [comment]
Duplicate of #2893.
