### ISSUE TITLE
Value list button renamed

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#3027]
## Description 

Per https://github.com/elastic/kibana/pull/152281, the "Import list" button has been renamed to "Import value list":

<img width="763" alt="Screenshot 2023-02-27 at 12 12 37 PM" src="https://user-images.githubusercontent.com/10927944/221673566-44e4e910-41d1-48b4-8bb6-2ac53a4a9717.png">

## Affected docs

The [Create and manage value lists](https://www.elastic.co/guide/en/security/master/value-lists-exceptions.html) topic has a couple screenshots and a text reference to update. Double-check for anything else that might need updating.

For images, assuming everything else in the UI is the same, it might be easier to just stitch on a new button, instead of trying to reproduce the test data in [manage-value-list.jpg](https://www.elastic.co/guide/en/security/master/images/manage-value-list.png).

**Comment by nastasha-solomon** [comment]
Merged https://github.com/elastic/security-docs/pull/3052
