### ISSUE TITLE
Detections rules in cross cluster search

### ISSUE THREAD

**Issue by vitaliidm** [elastic/security-docs#3033]
## Description

There were number of issues related to set up of detections rules to work in cross cluster envronment
- https://github.com/elastic/sdh-security-team/issues/520
- https://github.com/elastic/sdh-security-team/issues/555

The troubles seemed to be rooted in role configuration on the local and remote clusters.
There are some differences, how role applied to remote cluster depends on the way rule is executed:
 - when rule runs in preview, it uses basic authorization
 - during actual scheduled rule execution, it uses API token, which is a snapshot of the user privileges, on the time of API key creation

I didn't find any page on Security Documentation that gives an example of a rule set up in CCS.
Existing pages in ES documentation doesn't cover Security Solution specific nuances,  [for reference](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/remote-clusters-privileges.html#clusters-privileges-ccs-kibana)
I think it's might be beneficial to have one, with few of the examples and which highlights potential issues.

Based on the mentioned SDH tickets, I would focus document on:

- role on local cluster should give the same privileges as role on the remote cluster
  This due to the way how security authorization model works
  > CCS with users: an authenticated user in your local cluster is granted the same roles on the remote cluster. However, you have to make sure you have the same roles defined in your local cluster and your remote cluster for this to work as expected. If you don't define the same role on the remote cluster, the user won't have privileges on the remote cluster.
  > CCS with API keys: your API key is granted the same privileges on the remote cluster, regardless of whether the source roles are defined on the remote cluster or not
   - [reference 1](https://github.com/elastic/sdh-security-team/issues/555#issuecomment-1451877679)
   - [reference 2](https://github.com/elastic/sdh-security-team/issues/520#issuecomment-1406698489)
- after change in role on the local cluster, API key for rule should be [regenerated](https://github.com/elastic/sdh-security-team/issues/555#issuecomment-1452023792)
- warning https://www.elastic.co/guide/en/security/8.6/advanced-settings.html#enable-ccs-warning, can be avoided by [adding remote cluster prefix with index name to list of indices in the role](https://github.com/elastic/sdh-security-team/issues/520#issuecomment-1405074753)

## Acceptance Test Criteria

Documentation page or section with the examples how to set up rule to work in CCS environment
 

## Notes

- Add all appropriate labels to the issue, especially the version number label.
- Be sure to add any necessary screenshots, code text or console commands for clarity.
- Include any conditions or caveats that may affect customers.

**Comment by vitaliidm** [comment]
Hey @joepeeples, we discussed the priority of this ticket at a team meeting and agreed that it would be great if we can get at least the first simplified version of docs for 8.7. And later, add more details to it.

As we discussed at our call, we can go with the  **How to** example in the first iteration for 8.7, that would show how to set up the detection rule correctly for CCS. And later we can add more details to it and add **Troubleshooting** section.

Another question, would it be possible to backport this page to earlier versions of documentation(8.x)?

**Comment by joepeeples** [comment]
Thanks @vitaliidm for this info! I'll aim for 8.7, or very soon after if I'm unable to get something ready by release day proper. I like the idea of breaking up into iterations, so that might help accelerate delivery.

Backporting should be fine, especially if this ends up being a new page (much lower chance of conflicts with previous content). How far back are we thinking -- all the way to 8.0?

**Comment by vitaliidm** [comment]
> Backporting should be fine, especially if this ends up being a new page (much lower chance of conflicts with previous content). How far back are we thinking -- all the way to 8.0?

I think so, but we will need to do some testing before backporting, to ensure it works as expected
