### ISSUE TITLE
macOS System Preferences renamed, redesigned: System Settings

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#3036]
## Description 

In macOS Ventura 13, Apple renamed the [**System Preferences**](https://support.apple.com/guide/mac-help/change-system-preferences-mh15217/12.0/mac/12.0) app to ["**System Settings**"](https://support.apple.com/guide/mac-help/change-system-settings-mh15217/13.0/mac/13.0) and redesigned a lot of settings and tabs within the app.

Some of our Getting Started docs reference these settings, so search all of the Security docs for references to these settings, and update accordingly. Because we're still supporting some versions before Ventura, we'll need instructions for _both_ Ventura and any previous versions (Monterey and earlier).

## Docs to update
_(not an exhaustive list, just what came to mind; search the repo for any other references)_

- [Install Elastic Endpoint manually](https://www.elastic.co/guide/en/security/master/deploy-elastic-endpoint.html)
- [Enable Full Disk Access for the Endgame sensor](https://www.elastic.co/guide/en/security/master/endgame-sensor-full-disk-access.html)

## Notes

- Screenshots - retake? We have a lot of screenshots of the old System Preferences app, which would still be valid for many users not using Ventura yet (it was only released a few months ago in October 2022). Maybe wait until support for previous versions (Monterey etc) ends to replace all images, but update text for now?
- Double-check with development to confirm that Ventura is indeed supported for Elastic Stack, Elastic Security, Elastic Agent, etc.
- Added release labels for `v8.7.0` and `v8.8.0`, but confirm if this is correct and if any backports are needed. (Might depend on previous item, when exactly full support for Ventura is confirmed.)

## Doc plan

Approach for updating outdated pages. 

### Prep for doc updates
- [x] ~Set up infrastructure for tabbed widget within the Security project.~ No longer taking this approach. Will be creating a new page for Ventura users. 
- [x] Review [Install Elastic Endpoint manually](https://www.elastic.co/guide/en/security/master/deploy-elastic-endpoint.html) and [Enable Full Disk Access for the Endgame sensor](https://www.elastic.co/guide/en/security/master/endgame-sensor-full-disk-access.html) with @Trinity2019 and Jesse S.
   - NOTE: It might make sense to update instructions for enabling FDA on Endgame sensor in a sep PR if it's more important/urgent to refresh the Endpoint installation docs.
- [x] Gather new screenshots (if possible) of notifications that users will see when they're prompted to grant access to Endpoint and the Endgame sensor.

### Doc updates
- [x] Create a new top level topic to house the old and new instructions for installing Endpoint manually. 
- [x] Update the [Elastic Endpoint requirements](https://www.elastic.co/guide/en/security/master/deploy-elastic-endpoint.html) link in the "Feature-specific links" section to point to the new top-level topic.
- New topic for the Ventura users:
   - [x] Create new topic.
   - [x] Decide on topic titles for new topic and old one.
   - [x] Incorporate updated steps and screenshots

**Comment by malek-andrew** [comment]
@nastasha-solomon We have a customer that is trying to implement this, but the docs don't seem to be public. We are trying to access the current instructions needed to install Elastic Defender on MacOS Ventura. Can you point us in the right direction.

**Comment by nastasha-solomon** [comment]
Closing this doc issue as I updated docs for installing Elastic Endpoint. @malek-andrew the updated docs are here if you still need them: https://www.elastic.co/guide/en/security/8.9/elastic-endpoint-deploy-reqs.html

The last batch of updates for the Endgame docs is being tracked in the meta https://github.com/elastic/security-docs/issues/3563.
