### ISSUE TITLE
[Docs][Exceptions] - Revisiting new exceptions flows

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#3057]
## Description 

@nastasha-solomon and I went over the 8.7 exceptions docs. There were just a few areas that may need updating for subsequent versions. 

## Notes
- Docs currently specify 3 components to exceptions - exception items, default rule lists and shared exception lists
    -  I think that for the sake of a user wanting to figure out how to use exceptions and what they are, they really only need to know that you can 1) add an exception to a rule or 2) if you want to share exceptions with multiple rules, you can add them to a shared exception list. There may be value in adding more of these underlying details in the API docs for users, but for the majority of users they don't need to conceptually understand that even exception items tied to a single rule are grouped in a default exception list.
- This [section](https://www.elastic.co/guide/en/security/master/add-exceptions.html#add-exceptions) should include that exceptions can also be added from the alert details flyout
- Shared exception list [management](https://www.elastic.co/guide/en/security/master/shared-exception-lists.html#manage-exception-lists) can also be done from the list details page

**Comment by yctercero** [comment]
@MikePaquette @peluja1012 - can you take a look at what I described and give guidance on whether or not the concept of the "default rule list" should be explicitly shared in the docs or whether we can abstract it out for the user. The new UX was meant to allow users not to have to be aware of the list containers unless they were specifically looking for a way to share exceptions.

**Comment by MikePaquette** [comment]
Hi @yctercero I am in favor of simplifying by leaving out (or moving elsewhere) the details of default rule lists.

**Comment by peluja1012** [comment]
Hi @yctercero, I agree with your suggestions also. Thanks.

**Comment by yctercero** [comment]
Suggested edits - https://docs.google.com/document/d/1yUF9FvXZL1WXZ6yezEx1oJGawPn8fzcz18DCkZfufBc/edit#
