### ISSUE TITLE
[Docs]Add Elastic Security flowchart to the docs

### ISSUE THREAD

**Issue by benskelker** [elastic/security-docs#31]
Currently, there is no diagram illustrating the Elastic Security workflow. @MikePaquette and I started working on one for the 7.9 release (based on Mike's roadmap flow).

The draft flow is here: https://docs.google.com/drawings/d/1snRC0crIxcWdig3RsMkvKbIHq_lqZGpjymbpcT6O9rU/edit?usp=sharing

We'd like to get feedback on the flow from the other tech writers, and the product and UI teams. There's no need to worry about the diagram's aesthetics (unless you want to), as we'll send the approved flow to the design team.

Thanks,

cc @jmikell821, @DonNateR, @marrasherrier, @dontcallmesherryli, @caitlinbetz, @jamiehynds, @shimonmodi

**Comment by benskelker** [comment]
The design team doesn't support this type of request (see https://github.com/elastic/Design/issues/2565), so we're on our own.

**Comment by dontcallmesherryli** [comment]
Lucidchart (part of the google suite) is a very handy application that makes pretty flowcharts. Not sure if you want to try using that @benskelker

**Comment by jmikell821** [comment]
@DonNateR @benskelker please review the first draft Monina created. 
![7 9 Security Workflow ](https://user-images.githubusercontent.com/57149392/87679319-0a262200-c74a-11ea-9c00-3f8deadef90f.png)

**Comment by DonNateR** [comment]
> @DonNateR @benskelker please review the first draft Monina created.
> ![7 9 Security Workflow ](https://user-images.githubusercontent.com/57149392/87679319-0a262200-c74a-11ea-9c00-3f8deadef90f.png)

The information is good but I would like to see the shapes used more strategically. Specifically, I'm not sure the alerts, cases, and exceptions should be identified as "documents" when they're more similar to data <diamond> shape in my mind. Otherwise, looks good.

**Comment by monina-n** [comment]
@DonNateR @benskelker  Thank you for the feedback. I agree that the shapes don't all match the expected conventions and think it would be advantageous to change them. I've included a list of the traditional conventions for each shape.

Some examples of changes could be:
Detection alerts, Cases, and Exceptions -> Data/Stored Data/Database(?)
Timeline investigations -> Process

I'm not sure which shape type is the best representation for each item so when there is a consensus, I can update and finalize the chart :)

![7 9 Security Workflow  - Flowchart Elements](https://user-images.githubusercontent.com/67915896/87687514-a9431d80-c73a-11ea-8a23-c7005e2a6ab5.png)

**Comment by MikePaquette** [comment]
good points! We should indeed give some additional thought to the shapes we use. 
Interestingly, events and alerts **are** actual _documents_ in the Elasticsearch sense of the word.
The goal in the original diagram was to show that there were multiples of those things.

**Comment by benskelker** [comment]
Thanks @monina-n - I think it looks good. I don't know the conventions and I'm not sure about the meaning of the multiple document shape vs ES documents, so please feel free to change. I guess alerts, cases, and exceptions could be considered stored data.  I thought the parallelogram represented input/output: https://en.wikipedia.org/wiki/Flowchart#Building_blocks

**Comment by monina-n** [comment]
quick question, what's the difference between "Timeline investigations" and "Timelines"?

**Comment by MikePaquette** [comment]
@monina-n the original idea was that the timeline investigation was a _process_ that the analyst performed, drawing from (or adding to) a library of timeline _objects_ (now includes timeline templates) to assist the process.

**Comment by benskelker** [comment]
Thanks @monina-n - please don't feel rushed. I'd prefer this to be one diagram in the docs. @dontcallmesherryli asked me what we wanted the diagram for, maybe my answer helps:

> It’s going to be part of the app overview section. Together with a short description under the diagram, it can provide a high-level overview of what the app can do and how different features work together, as well as be a place from which users can pivot to more specific stuff. I guess the audience is very general, anyone who uses or is interested in the app.

If you need to correct shapes to keep this as one diagram, that's fine.

**Comment by monina-n** [comment]
Hi all, here is a link to a [Google Drive folder](https://drive.google.com/drive/folders/1vzJIi4lmncFynoPmzTaiIbYj19QQT5W0?usp=sharing) of the final draft of the security workflow chart. There's two versions- one with the original diagram language and one with more active language for the user processes. I've included screenshots here as well. Let me know if there's anything to be added or changed in the digram.

**Original:**
![7 9 Security Workflow - Original Language](https://user-images.githubusercontent.com/67915896/88863126-da016900-d1b6-11ea-96c7-39c70a138845.png)

**Active:**
![7 9 Security Workflow - Active Language](https://user-images.githubusercontent.com/67915896/88863121-d7067880-d1b6-11ea-9fa3-4decf431c2bb.png)

**Comment by benskelker** [comment]
Thanks very much - I think the Active version is great.

**Comment by MikePaquette** [comment]
@monina-n Whoa, this is looking great!  The active language for user processes works really well, and the organization is really clean.  

With this clean base, It really got me thinking on how to make this even better and more complete!  I have a bunch of minor suggestions and a few additions in the attached mark-up.

The biggest adds are:
-  to show the diversity of data sources we support on the left side of the diagram.  These are available as modules and packages.  
- adding a way to administer policies and configurations of hosts running Elastic Security at the top of the diagram
- Adding in the multiple analytics that support the detection engine
- Adding in our new-for-7.10 value lists into the diagram.  

Please let me know if any of these changes don't make sense.  
We really appreciate you taking the time to make this diagram accurate and helpful to our readers!

**Comment by monina-n** [comment]
happy monday! here's an updated version with the proposed changes. File can be found [here](https://drive.google.com/drive/u/1/folders/1vzJIi4lmncFynoPmzTaiIbYj19QQT5W0)

![7 9 Security Workflow  - Update](https://user-images.githubusercontent.com/67915896/89228477-85823300-d594-11ea-9d0a-e648c25cdcb2.png)

@MikePaquette

**Comment by MikePaquette** [comment]
Thanks @monina-n this looks great!  Just a few final requests:

1. Change "Hosts running Elastic Security Endpoint" to "Hosts running Elastic Endpoint Security" 
2. Change "Intrusion detection and preventions" to "Intrusion detection and prevention"
3. Change "via Logstash, Beats Modules, Elastic Packages" to "via Logstash, Beats modules, Ingest Manager integrations

Thanks!

**Comment by monina-n** [comment]
@MikePaquette  done and done! file [here](https://drive.google.com/file/d/1gVC4n_sVaq3QPoRAVLJJz_B9yu4TEjXp/view?usp=sharing)

![7 9 Security Workflow  - Update](https://user-images.githubusercontent.com/67915896/89316115-85d00c00-d630-11ea-9501-55f5f1850444.png)

**Comment by benskelker** [comment]
Closing this. Thanks again @monina-n
