### ISSUE TITLE
Kubernetes Defend Install Docs in 8.7.0

### ISSUE THREAD

**Issue by ScottElastic** [elastic/security-docs#3114]
## Kubernetes Install Doc in 8.7.0

https://www.elastic.co/guide/en/security/8.7/kubernetes-dashboard.html#_download_and_modify_the_daemonset_manifest

The documentation above the curl one liner links to 8.6 install:
`curl -L -O https://raw.githubusercontent.com/elastic/endpoint/main/releases/8.6.0/kubernetes/deploy/elastic-defend.yaml
`
an 8.7.0 link doesn't seem to exist:
`https://raw.githubusercontent.com/elastic/endpoint/main/releases/8.7.0/kubernetes/deploy/elastic-defend.yaml`

I changed the yaml file anywhere it stated 8.6.0 to 8.7.0 and it ran fine in my 8.7.0 cluster. Maybe we can update the yaml file and update the curl one liner to reflect this?

**Comment by benironside** [comment]
This issue was fixed, thanks Scott!
