### ISSUE TITLE
Missing Data Quality Dashboard under Doc 

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#3125]
**Description**
Missing Data Quality Dashboard under Doc 

**URL link**

- https://www.elastic.co/guide/en/security/current/es-ui-overview.html
- https://www.elastic.co/guide/en/security/current/dashboards-overview.html

**Screen-Shot**

- Actual Result
![image](https://user-images.githubusercontent.com/59917825/229767764-daff2bd3-7849-4e53-8e4a-40b18b6247ac.png)

- Expected Result

![image](https://user-images.githubusercontent.com/59917825/229767808-01bb19ca-8b2a-4412-a7df-b4c48a7309d9.png)

**Comment by karanbirsingh-qasource** [comment]
@amolnater-qasource  Please review

**Comment by amolnater-qasource** [comment]
Reviewed and assigned to @jmikell821
