### ISSUE TITLE
Technical Name of ML Jobs on EA page instead of updated Friendly names

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#3126]
**Description**
Technical Name of ML Jobs on EA page instead of updated Friendly names

**URL link**

- https://www.elastic.co/guide/en/security/current/detection-entity-dashboard.html

**Screen-Shot**

- Actual

![image](https://user-images.githubusercontent.com/59917825/229768333-53afe2cb-8404-4a8d-b95e-2403b4e60e05.png)

- Expected

![image](https://user-images.githubusercontent.com/59917825/229768376-0f178617-db38-46eb-8853-634132c6dc4e.png)

**Comment by karanbirsingh-qasource** [comment]
@amolnater-qasource please review

**Comment by amolnater-qasource** [comment]
Reviewed and assigned to @jmikell821
