### ISSUE TITLE
By Default Rule Preview should be enabled on Create Rule Doc Screen-Shot

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#3127]
**Description**
By Default Rule Preview should be enabled on Create Rule Doc Screen-Shot

**URL link**

- https://www.elastic.co/guide/en/security/current/rules-ui-create.html

**Screen-Shot**

- Actual

![image](https://user-images.githubusercontent.com/59917825/229768925-d5019d0e-49d0-406e-b310-371576a0c3c9.png)

- Expected

![image](https://user-images.githubusercontent.com/59917825/229768972-081916b6-fbba-4a35-bec9-89334c10a7fe.png)

**Comment by amolnater-qasource** [comment]
Reviewed and assigned to @jmikell821

**Comment by jmikell821** [comment]
@karanbirsingh-qasource I think adding the preview panel will take focus from the main create rule page. We show the preview pane in the preview section. Thanks for the catch, but I think it's safe to bypass this one. Hence, closing.
