### ISSUE TITLE
[BUG] The screenshots need to be updated to reflect the count of actions to 06 instead of 05

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#3129]
**Description**: 
The screenshots need to be updated to reflect the count of actions to 06 instead of 05

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/8.7/response-actions.html#actions-log
- https://www.elastic.co/guide/en/security/8.7/response-actions-history.html
- https://www.elastic.co/guide/en/security/8.7/host-isolation-ov.html#host-isolation-ov
- https://www.elastic.co/guide/en/security/8.7/admin-page-ov.html 

**Screenshots**:
- Actual:
![image](https://user-images.githubusercontent.com/60252716/229772545-8f42b677-3a71-4290-98f6-4e77de5b657c.png)

- Expected:
![1](https://user-images.githubusercontent.com/60252716/229772147-e335aa46-74b6-4843-afd5-9f247c997bae.png)

**Comment by muskangulati-qasource** [comment]
@karanbirsingh-qasource please review!!

**Comment by joepeeples** [comment]
No updates needed. Thanks to role-based access control, not all users will have access to all 6 possible response actions, so seeing 5 instead of 6 in a screenshot shouldn't be confusing, misleading, or inaccurate for readers.
