### ISSUE TITLE
[BUG] No update to the user that the files are deleted periodically and user must save the files if needed later

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#3131]
**Description**: 
No update to the user that the files are deleted periodically and user must save the files if needed later

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/8.7/response-actions.html#_get_file

**Screenshots**:
- Actual:
![3](https://user-images.githubusercontent.com/60252716/229773380-e89cee24-85d4-4e3f-873a-87d5cae8afdb.PNG)

- Expected:
![image](https://user-images.githubusercontent.com/60252716/229774945-dc38103c-1ead-4861-b953-bc967975542f.png)

**Comment by muskangulati-qasource** [comment]
@karanbirsingh-qasource please review!!

**Comment by jmikell821** [comment]
@kevinlog @caitlinbetz please give me your thoughts on if you think this should be mentioned in docs. IMO, the UI is pretty clear, so I don't know if we really need to mention what's already stated or if it's worth repeating.

**Comment by joepeeples** [comment]
Confirmed with @kevinlog and @caitlinbetz that it's OK to leave docs as is, UI text is clear and sufficient.

**Comment by caitlinbetz** [comment]
apologies for delay. @kevinlog and I agree with you that it is pretty clear in the UI. We can consider adding this to docs if it comes up again, but okay leaving as is for now.

cc @joepeeples
