### ISSUE TITLE
Doc not available for Actionable investigation guide form builder.

### ISSUE THREAD

**Issue by sukhwindersingh-qasource** [elastic/security-docs#3134]
## Description 

 Doc not available for Actionable investigation guide form builder.

**Doc URL link**

-  https://www.elastic.co/guide/en/security/current/rules-ui-create.html#rule-ui-advanced-params

**Feature Ticket URL link**

- https://github.com/elastic/security-team/issues/5600

 Screen-Shot

![image](https://user-images.githubusercontent.com/108654988/230058674-69e83716-70c9-4772-9118-b1688c5afb76.png)

**Comment by jmikell821** [comment]
@sukhwindersingh-qasource this is a `technical preview` feature ([here](https://www.elastic.co/guide/en/security/master/interactive-investigation-guides.html)), so I think, for now, we'll just include a cross-ref link to it. cc: @joepeeples

**Comment by sukhwindersingh-qasource** [comment]
Hi @joepeeples,

We tested the latest docs and found the issue was fixed there.

**Screenshot:**
![image](https://user-images.githubusercontent.com/108654988/231696937-44bbcb0a-7080-41a0-a2fd-f2e2b0c20ad7.png)


Hence, we are closing this issue and marking it as QA Validated.

Thanks!
