### ISSUE TITLE
Alert summaries and conditional actions 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#3142]
## Description 

In 8.8, users could specify how often alert notifications were to third-party systems (e.g., Slack, JIRA, email, etc.). The action frequency configuration applied to all actions that were added to the rule.  

<img width="600" alt="Screenshot 2023-05-05 at 10 33 31 AM" src="https://user-images.githubusercontent.com/79124755/236526296-702d4bb7-a692-4892-955e-bde05e857f9b.png">

In 8.8, users can set notification frequency on a per-action basis. Now, they have more control over specifying how often actions send notifications about alerts. 
<img width="600" alt="Screenshot 2023-05-04 at 11 05 47 AM" src="https://user-images.githubusercontent.com/79124755/236525693-4e68ec23-2dc9-4f4e-a134-0e99951fc945.png">

<img width="600" alt="Screenshot 2023-05-05 at 1 29 10 PM" src="https://user-images.githubusercontent.com/79124755/236526264-96f111a6-7a68-4405-b5c1-88fb72f9376a.png">

On top of more control over action notification frequency, users can choose to be notified on a per alert basis or with alert summaries:
- **Per alert basis**: You'll receive a notification for each alert that's generated. 
- **Alert summaries**: You'll receive a single notification on the interval schedule that you choose and the notification will summarize multiple alerts. 

From here, you can define additional conditions that must be met for the connector to send a notification: 
- **if alert matches a query**: Notifications are only sent if alerts match the conditions of the KQL query that the user writes. Note that this query searches alert documents in the rule's specified index.  
- **if alert is generated during timeframe**: Notifications are only sent if alerts are generated within the specified timeframe.

Related:
- https://github.com/elastic/kibana/issues/151916: Main meta for implementing this feature in the Security app
- https://github.com/elastic/kibana/issues/154531 and https://github.com/elastic/kibana/issues/154534: Adds UI options for sending notifications per-action or as alert summaries. 
- https://github.com/elastic/kibana/issues/154532: Adding support for the new per-action `frequency` field in Security rule API.
- https://github.com/elastic/kibana/issues/150655: Example docs issue that shows how this feature was doc'd in the Observability docs. 

## Questions
- What new fields/parameters will be added to/changed in the following APIs:
   - [Create rule | actions schema](https://www.elastic.co/guide/en/security/master/rules-api-create.html#actions-object-schema)
   - [Update rule | actions schema](https://www.elastic.co/guide/en/security/master/rules-api-update.html#actions-object-schema-update) 
   - [Bulk rule actions | actions schema](https://www.elastic.co/guide/en/security/master/bulk-actions-rules-api.html#actions-object-schema-bulk)

## Required doc updates
- Make the following changes to the [Set up alert notifications (optional)](https://www.elastic.co/guide/en/security/master/rules-ui-create.html#rule-notifications) section:
  - [x] Add new mandatory and optional configuration options. 
  - [x] Refresh screenshots: `available-action-types.png` and `selected-action-type.png`
- Make the following changes to the [Alert notification placeholders](https://www.elastic.co/guide/en/security/master/rules-ui-create.html#rule-notifications) section:
  - [x] Explain that variables will differ based on the action frequency that's selected.  
  - [x] Point users towards the [Action frequency: Summary of alerts](https://github.com/elastic/kibana/edit/main/docs/user/alerting/action-variables.asciidoc) section for a list of Summary of alerts variables that they can use.
- Update docs for notification placeholder fields. Notes for organization are [here](https://docs.google.com/document/d/18mSi1dBNQ_3GGwkdwsGWAXfsooyV2_j5A7g4UKnHnfA/edit?usp=sharing):
   - [x] Create a section for placeholder fields that are only available when users choose the per-alert option. 
   - [x] Create a section for fields that are available if users choose either the per alert option or the alert summary option. 
   - [x] Add in the `Alert.flapping` field to the section that details placeholder fields available for the per alert option. _(Verifying this with Zhenia)_  
- Note that after a user upgrades to 8.8, actions on rules will have their own frequency. In 8.7 and earlier, action frequency was set on a rule-level, meaning users would set action frequency once and that configuration would apply to all actions added to the rule:
   - [x] [Upgrade Elastic Security | Upgrade from a 7.x version](https://www.elastic.co/guide/en/security/master/upgrade-intro.html#upgrade-reqs): Create a new section detailing what will happen to "old" rules.
   - [x] [Manage detection rules | Modify existing rule settings](https://www.elastic.co/guide/en/security/current/rules-ui-management.html#edit-rules-settings): Expand the notes for the Add rule actions bullet under step 2.
-  Rule API docs updates will be tracked in a separate doc issue: https://github.com/elastic/security-docs/issues/3257

## Notes

- The two notification options were described in the Kibana [Actions](https://www.elastic.co/guide/en/kibana/master/alerting-getting-started.html#alerting-concepts-actions) docs. Might be able to reference those docs or re-use the content when explaining this feature in the Security docs. 
- When users import rules with actions created in 8.7, actions are automatically set to run on a per-alert frequency. 
- [x] @e40pud to create a doc issue for the rule API doc updates.

**Comment by lcawl** [comment]
Since the conditional actions feature is only available to rules in the Security app, IMO it makes sense to add it only in the [Security 8.8 highlights](https://www.elastic.co/guide/en/security/8.8/whats-new.html). If you agree, here's what's proposed for the release blog:

> Conditional Actions
>
> When you create a rule, you define conditions that must be met for an alert to occur. Now you can also add conditions that affect the actions associated with an alert. For example, you might choose to send notifications only if the alert is received between defined hours.
