### ISSUE TITLE
Rule immutability and customization

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#3147]
## Description 

Users should be able to customize Elastic prebuilt rules without having to duplicate rules or forego updates to core rule logic.

Related:
- https://github.com/elastic/security-team/issues/1974 

## Notes

- Refer to https://github.com/elastic/security-team/issues/6122 for a full list of changes that are being implemented in 8.8. 

```[tasklist]
### Tasks & sub-issues
- [ ] https://github.com/elastic/security-docs/issues/4371
```

**Comment by joepeeples** [comment]
Closing as this is a very broad epic spanning many individual features across multiple release versions. We can open separate issues to track those features on a more granular level.
