### ISSUE TITLE
Update macOS Endpoint install and deploy documentation for Ventura

### ISSUE THREAD

**Issue by Trinity2019** [elastic/security-docs#3154]
## Description 
 A customer feedback that [this document page](https://www.elastic.co/guide/en/security/master/deploy-elastic-endpoint.html) is out-dated for macOS `Ventura` since `Ventura` made quite some changes to its appearance.

I also did an endpoint installation on `Ventura 13.2.1 M1`. I found following changes on Ventura:

### 1. OS components' title changed.
`System Preferences` -> `System Settings`
 `Security & Privacy` -> `Privacy & Security`

And the Full Disk Access(FDA) tab looks like this in `Ventura`:
![ventura-privacy-security](https://user-images.githubusercontent.com/56367679/228990425-ea3925aa-72b9-4489-b99e-84d7de00998d.png)

### 2.On the FDA tab, system extension's full name was shortened
The previous `.systemextension` suffix is not shown any more. So our system extension's display name changed:

`co.elastic.systemextension` -> `co.elastic`
`com.endgame.systemextension`->`com.endgame`

### 3. Moved System Extension and network extension approval
It was moved to `Security` section on `Privacy & Security` tab as [this article](https://iboysoft.com/howto/enable-system-extension-m1-mac.html) indicated.

cc @jesse-sant @roxana-gheorghe  @ricardoungureanu @nfritts Please feel free to correct/add any details. 
Also please correct me if I'm wrong, I believe we'll need to collect new screenshots from QA.

**Comment by nastasha-solomon** [comment]
Thanks for filing this @Trinity2019! I'll open a PR to make the necessary changes. 

Related: https://github.com/elastic/security-docs/issues/3036
