### ISSUE TITLE
Add Linux Elastic Defend Issue to the release notes.

### ISSUE THREAD

**Issue by nicholasberlin** [elastic/security-docs#3157]
## Description 

There's a known issue for Elastic Defend Linux version v8.7.0 that I would like to add documentation for. Associated [PR](https://github.com/elastic/security-docs/pull/3156).

## Acceptance Test Criteria

For example: As a consulting engineer, when viewing known issues, should be informed of this known issue.

**Comment by nastasha-solomon** [comment]
Merged https://github.com/elastic/security-docs/pull/3156
