### ISSUE TITLE
Exception API docs

### ISSUE THREAD

**Issue by DionAkkerman** [elastic/security-docs#3160]
## Description 

1. Error in url in Docs for [exceptions-api-update-container](https://www.elastic.co/guide/en/security/current/exceptions-api-update-container.html) for the last couple versions.
Example url is "PUT <kibana host>:<port>/api/lists" should be "PUT api/exception_lists"

2. Filter description in [exceptions-api-find-exception-containers](https://www.elastic.co/guide/en/security/current/exceptions-api-find-exception-containers.html) could use improvement. The docs suggest using <field name>:<field value> but ignores that the fields are nested. To use "name" for example, <exception-list.attributes.name>:<field value> is required.

**Comment by yctercero** [comment]
Please find comments below:

1. That's correct - should be `/api/exception_lists`

2. That is correct, that the filters should be formatted as described in the ticket description. However, this [PR](https://github.com/elastic/kibana/pull/138770) also added a `search` param which allows the user to more easily search using the simple query search outlined [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#simple-query-string-syntax).

Here's a [test](https://github.com/elastic/kibana/blob/main/x-pack/test/lists_api_integration/security_and_spaces/tests/find_exception_list_items.ts#L60) that gives an example of using `search` and the expected results.

**Comment by yctercero** [comment]
NOTE TO SELF: Expand on need for specifying SO type in addition to field name for `filter` and expand on how to use `search` param.

**Comment by yctercero** [comment]
Updated text for the `filter` param:

>Filters the returned results according to the value of the specified field, using the <so type>.<field name>:<field value> syntax, where <field name> can be: 
>
>- name
>- type
>- created_by
>- updated_by
>
>And <so type> can be:
>- exception-list - Space aware exception lists. 
>- exception-list-agnostic - Global exception lists that are shared across spaces. 

Text for `search` param:

>Filters the returned results according to the [simple query string](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#simple-query-string-syntax) filter.
