### ISSUE TITLE
[BUG] Cannot start service elastic-agent on computer '.'

### ISSUE THREAD

**Issue by The1WhoPrtNocks** [elastic/security-docs#318]
Hi I have a fresh install of windows 10 enterprise and I am getting the above error when the enrollment tries to start the installed elastic-agent service

**Comment by The1WhoPrtNocks** [comment]
I have tried setting the startup type to manual as shown here

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-service?view=powershell-7#example-4--start-a-disabled-service

**Comment by The1WhoPrtNocks** [comment]
I think it is not registering properly, this is the output on an instance that worked.

PS C:\Program Files\Elastic-Agent\Elastic-Agent> Get-CimInstance win32_service | Where-Object Name -eq "elastic-agent"

ProcessId Name          StartMode State   Status ExitCode
--------- ----          --------- -----   ------ --------
20728     elastic-agent Auto      Running OK     0

And if i run on the instance with the cannot start-service error it can not find the object elastic-agent" under Win32_service

**Comment by jmikell821** [comment]
Hello @The1WhoPrtNocks, please open a case at support@elastic.co, or you can raise the issue in the Security discuss forum: https://discuss.elastic.co/c/security/83. This repo, unfortunately, is not for support issues. Thank you!
