### ISSUE TITLE
Rule page displays notification banner if there's an active Maintenance Window

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#3180]
## Description 

Not sure what will need to be doc'd in Security docs, but filing this doc issue in case updates are needed. 

Related:
- https://github.com/elastic/kibana/issues/155099

## Notes

- Am working with @lcawl and @nikitaindik on UI copy for banner.

**Comment by banderror** [comment]
> Not sure what will need to be doc'd in Security docs, but filing this doc issue in case updates are needed.

@nastasha-solomon here's a ticket from @nikitaindik for documenting this feature. It explains what needs to be done, please let us know if there's not enough info in it:

https://github.com/elastic/security-docs/issues/3181

**Comment by nastasha-solomon** [comment]
Thanks, @banderror and @nikitaindik! The main docs for configuring the maintenance window will likely live in the Kibana docs so we might not need help on that front. However, we might need your help with https://github.com/elastic/security-docs/issues/3153, which is a new page that'll define the different types of alert suppression and snoozing functionality that's offered in the Security app. We'll keep you posted. Thank you!

cc: @joepeeples

**Comment by nastasha-solomon** [comment]
Closing as a duplicate of https://github.com/elastic/security-docs/issues/3181.
