### ISSUE TITLE
Agent Tamper Protection feature docs

### ISSUE THREAD

**Issue by roxana-gheorghe** [elastic/security-docs#3183]
We plan to release a new feature called Agent Tamper Protection to enhance the existing security  and self control over our product. the main functionality of the issue will be to secure the uninstall process and deny any unauthorised attempt to perform this action.
What we will  need for release:

- official UI text for product interface
   - [x] Uninstall agent flyout (https://github.com/elastic/security-team/issues/6028)
   - [x] Policy page protection & uninstall options (https://github.com/elastic/security-team/issues/5789)
- documentation
   - [x] Create placeholder stub for docs links — https://github.com/elastic/security-docs/pull/3214
   - [x] Actual documentation: uninstall agent page, anti-tampering protection docs
   - [x] Mention in release notes

- Main issue where we track the work: https://github.com/elastic/security-team/issues/5742  
- Related issue: https://github.com/elastic/endpoint-dev/issues/11679
- Technical documentation associated: https://docs.google.com/document/d/1u58eFbkXq7Sdh5sWkMjV0EHCRMOgcgHu7xEZCqhUM5U/edit?pli=1 

### Requirements
* Elastic Defend only (no other use cases)
* Licensing
   * Classic: Platinum subscription
   * Serverless: Endpoint Complete (pending fix in https://github.com/elastic/security-team/issues/7977)

```[tasklist]
### Pull Requests
- [x] Classic docs PR: https://github.com/elastic/security-docs/pull/4232
- [x] Serverless docs PR: https://github.com/elastic/staging-serverless-security-docs/pull/227
```

**Comment by FideliusFalcon** [comment]
I think some documentation about the required host OS is needed - I assume this doesn't work on Linux, as I just stopped the service with `systemctl stop elastic-agent.service'.
