### ISSUE TITLE
[DOCS]: System Requirements 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#32]
Draft a topic that includes hardware, system, and OS requirements for Elastic Security. If applicable, include these components: 
![image](https://user-images.githubusercontent.com/57149392/85077573-a03d4b80-b190-11ea-85b5-38dad3afaa93.png)

**Comment by jmikell821** [comment]
@caitlinbetz if we have this info, can you please add the pertinent info in the comments please? Thanks!

**Comment by caitlinbetz** [comment]
re: supported operating systems:
https://docs.google.com/spreadsheets/d/1PuHAQFyUGvukfbGc_gRN-p9gaHvQ1bMWiP2pmp66jNc/edit#gid=0

See Column B in this doc. 
The Legend says U = unofficial, I'm looking for a definition of what we mean by this. When I filled this out, I intended u = unsupported.

Will try to find some of the other info!

**Comment by jmikell821** [comment]
@benskelker passing the ball to you - lmk if I need to get it started! [Google doc link.](https://docs.google.com/document/d/1bYiqwaopsEtayFofXgSqIVS-5FFBO8sm6X8LRlZWmmg/edit?ts=5f1edee7#heading=h.im84hrv56a94)
