### ISSUE TITLE
[Security Solution] document a guidance for 8.5 constant loading  rule edit/details page

### ISSUE THREAD

**Issue by vitaliidm** [elastic/security-docs#3204]
## Description 

We've seen during the last few month 2 SDH issues related to constant loading rule edit/details page that prevent users to edit rule
- https://github.com/elastic/sdh-security-team/issues/598
- https://github.com/elastic/sdh-security-team/issues/558

It looks like this:
<img width="1157" alt="Screenshot 2023-04-27 at 16 36 11" src="https://user-images.githubusercontent.com/92328789/235156148-dac9b964-672d-4f09-8cf3-19484ae2a82d.png">

<img width="2236" alt="Screenshot 2023-04-28 at 14 31 56" src="https://user-images.githubusercontent.com/92328789/235161379-61daacac-16dd-43f0-b6c1-956f496bb87b.png">

It would happen only for the rules that have `saved_id` property and rule type, that is not `saved_query`.
After upgrade to 8.6, it will work as expected without issues.

We would like to highlight this issue to customers on 8.5.x and give them guidance how to resolve it, which is update to 8.6.x version.
Which documentation page could be the best option to do this? Maybe [troubleshooting](https://www.elastic.co/guide/en/security/8.5/troubleshooting-ov.html) for version 8.5 only? Or some other pages?

**Comment by vitaliidm** [comment]
cc: @joepeeples

**Comment by nastasha-solomon** [comment]
@vitaliidm another option is to document this as a known issue in [8.5.x releases](https://www.elastic.co/guide/en/security/8.5/release-notes-header-8.5.0.html) and then as a fixed issue in [8.6.0](https://www.elastic.co/guide/en/security/8.6/release-notes-header-8.6.0.html#release-notes-8.6.0). Putting these details in the release notes would lend visibility to the troubleshooting steps and show that the issue only affects a small batch of releases (i.e., the 8.5.x releases). 

cc: @elastic/security-docs

**Comment by vitaliidm** [comment]
@nastasha-solomon , thanks for this suggestion. I think it's a good option to go.

Can we, in known issues of 8.5.x release, give a recommendation to update to 8.6 if that issue is encountered?

**Comment by nastasha-solomon** [comment]
@vitaliidm yep, that should be fine! Can you share the known issue summary and the workaround/troubleshooting steps?

**Comment by vitaliidm** [comment]
Summary:
Rules that are not of `saved_query` type but configured with property `saved_id` , can not be edited through UI, due to constant displaying of progress loader (see screenshot id the description. Do we want to include any screenshots?)

Troubleshooting:
1. Update Kibana to 8.6+ version (Preferable)
2. If customer wants to stay on 8.5: Update troublesome rule through [update API call ](https://www.elastic.co/guide/en/security/8.5/rules-api-update.html#_field_required_for_saved_query_rules_put_calls), by removing `saved_id` property  from that rule

**Comment by nastasha-solomon** [comment]
@vitaliidm thanks for sharing the additional details and workarounds! 

I did have one question: can you give an example of a rule that's not of the `saved_query` type but is configured with the `saved` property? Are you saying that all rule types, _except the custom query rule type_, will run into this issue if the rule query uses a saved query?

**Comment by vitaliidm** [comment]
>  can you give an example of a rule that's not of the saved_query type but is configured with the saved property? 
Here is a threshold rule, with `saved_query` property
```
{
    "id": "7c1221e0-fecc-11ed-a20e-d113fed99a8f",
    "updated_at": "2023-05-30T09:29:32.675Z",
    "updated_by": "elastic",
    "created_at": "2023-05-30T09:29:32.675Z",
    "created_by": "elastic",
    "name": "threshold with saved query legacy",
    "tags": [],
    "interval": "5h",
    "enabled": false,
    "revision": 0,
    "description": "threshold with saved query legacy",
    "risk_score": 21,
    "severity": "low",
    "license": "",
    "output_index": "",
    "meta": {
        "from": "1m",
        "kibana_siem_app_url": "http://localhost:5601/kbn/app/security"
    },
    "author": [],
    "false_positives": [],
    "from": "now-18060s",
    "rule_id": "07632379-b802-46a1-8010-0cdd7cf5e3a0",
    "max_signals": 100,
    "risk_score_mapping": [],
    "severity_mapping": [],
    "threat": [],
    "to": "now",
    "references": [],
    "version": 1,
    "exceptions_list": [],
    "immutable": false,
    "related_integrations": [],
    "required_fields": [],
    "setup": "",
    "type": "threshold",
    "language": "kuery",
    "index": [
        "apm-*-transaction*",
        "auditbeat-*",
        "endgame-*",
        "filebeat-*",
        "logs-*",
        "packetbeat-*",
        "traces-apm*",
        "winlogbeat-*",
        "-*elastic-cloud-logs-*"
    ],
    "query": "*",
    "filters": [],
    "threshold": {
        "field": [
            "agent.type"
        ],
        "value": 2,
        "cardinality": []
    },
    "saved_id": "48e2f3d0-fecc-11ed-a20e-d113fed99a8f",
    "actions": []
}
```

> Are you saying that all rule types, except the custom query rule type, will run into this issue if the rule query uses a saved query?

Yes, it's correct. `saved_id` property prior to 8.5 didn't have any effect on rules of other types, but could been saved within its configuration due to UI bug. In 8.5 we don't save `saved_id` anymore in rules of different than `saved_query` type.
Unfortunately, only 8.5 version it can cause indefinite page load issue. But, again it will only affect rules that have  `saved_id` property and rule type, that is not `saved_query`.




> I noticed that the create rule API [docs](https://www.elastic.co/guide/en/security/master/rules-api-create.html#ref-fields-all) list saved_query as a rule type, but I'm still not entirely clear what that translates to in the UI.


In UI, **Custom query** input is disabled, and checkbox **Load query "..." dynamically ** is checked

<img width="1044" alt="Screenshot 2023-05-30 at 10 41 36" src="https://github.com/elastic/security-docs/assets/92328789/c2b7dc89-2d45-48ba-8177-3edd456e0067">

More on saved query can be found in this PR: https://github.com/elastic/kibana/pull/140064

**Comment by nastasha-solomon** [comment]
Will use the following summary for 8.5 release notes:

The rule details page and **Edit rule settings** page load indefinitely if you edit a rule that has the `saved_id` property configured. All rule types, except for the custom query rule, are affected.

Upgrading to 8.6 or higher resolves this issue. If you’d prefer to stay on 8.5, use the Update rule API to remove the `saved_id` field from the non-functioning `query`, `eql`, `machine_learning`, `threat_match`, `threshold`, or `new_terms` rule.
