### ISSUE TITLE
Response action: `execute`

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#3215]
## Description 

Related: 
* Epic: https://github.com/elastic/security-team/issues/5441
   Epic includes 3 response actions (`upload`, `execute`, `execute-file`), but only `execute` is releasing in 8.8
* Issue: https://github.com/elastic/security-team/issues/5370

## Notes
* UI help text also under review: https://github.com/elastic/security-team/issues/6575

**Comment by caitlinbetz** [comment]
**Execute Response action:**

**Technical details:** 
- Users provide a shell command and the Endpoint uses a default shell to run that command on the host.  Users cannot specify a specific shell.
     - Executed as root
- Stderr, stdout, and the return code are saved in the response doc. We limit the stdout and stderr to 2k characters each in the console; a file with the complete output is available.
- There is a default maxTimeout of 4 hours.
     - If a user adds their own maxTimeout we override the default
     - Scripts and executables (but especially scripts as people make mistakes) can unexpectedly hang indefinitely, enter infinite loop for example. Max time helps with this.
- Endpoint will have a set working directory for the execution

**Supportability**
- Permissions controlled by Execute kibana feature privilege
- Supported across all operating systems
- Requires Enterprise license (same as other console response actions)

**Comment by caitlinbetz** [comment]
cc @kevinlog
