### ISSUE TITLE
Options in the duplicate rule modal updated

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#3220]
## Description 

In 8.8, the duplicate rule modal now shows three options:
- Duplicate the rule and all of its exceptions
- Rules and active exceptions only
- Only rules

<img width="430" alt="Screenshot 2023-05-04 at 11 59 35 AM" src="https://user-images.githubusercontent.com/79124755/236266140-3c6aaeb1-e58a-4e6f-81ad-f7558f03ed24.png">

This modal appears when users duplicate a single rule or multiple rules from the Rules table. It also shows up when users duplicate a rule from the rule details page.

Related:
- https://github.com/elastic/kibana/pull/154991

## Doc updates
- [ ] Refresh note in https://www.elastic.co/guide/en/security/master/rules-ui-management.html#manage-rules-ui

## Notes
- [x] Will work with @yctercero to review copy for the duplicate rules modal. Copy convos happening [here](https://docs.google.com/document/d/1SauCRVJYOOE2Cwucopp0iQB_IHAYbVNAl3UnkpQQI6U/edit#).

**Comment by yctercero** [comment]
Note: during our chat, came up that we need to update this text to be more clear.

When duplicating a rule:

- if it has a reference to a shared exception list, that reference will remain the same in the newly duplicated rule. So if rule 'Foo' points to a shared exception list with `list_id: 123`, the new rule, `Foo [Duplicate]` will also point to list `list_id: 123`
- if it has default rule exceptions (ones that just belong to the rule, not shared across rules), those will be duplicated so `Foo` and `Foo [Duplicate]` will point to default rule exceptions with different `list_id`s

<img width="270" alt="Screenshot 2023-05-05 at 11 49 58 AM" src="https://user-images.githubusercontent.com/10927944/236543617-40aeef67-e24b-4ab2-a574-5af97a36b914.png">

**Comment by nastasha-solomon** [comment]
Hey, @yctercero! I've offered up some options for the tooltip below. Let me know if we still need to tweak any of them further. 

#### Option 1
**Tooltip message:** Exception items in shared exception lists aren't duplicated. Instead, duplicated rules will reference the shared exception lists that contain the exception items. 

This option assumes that users know (or will at least expect) that exceptions assigned to individual rules will be duplicated along with the rule. It might be safe to make this assumption because this isn't new functionality -- i.e., duplicating exceptions has worked this way in the past. But, it could be safer to err on the side of caution and include more info for clarity.  

#### Option 2
**Tooltip message:** Exception items associated with individual rules are duplicated. Exception items linked to shared exception lists are not. Instead, the duplicated rules will reference the shared exception lists that contain the exception items. 

This option is more explicit about what's duplicated, which makes it slightly longer.

#### Option 3
**Tooltip message:** References to shared exception lists are duplicated along with the rule. 

This option is the most succint and assumes that the most important information that we want to impart to users is how shared exception list references are treated.

**Comment by yctercero** [comment]
Thanks @nastasha-solomon ! PR with fixes here: https://github.com/elastic/kibana/pull/155959
