### ISSUE TITLE
Add new `revision` field to alert schema

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#3237]
Related issue/PR: https://github.com/elastic/security-docs/issues/3116, https://github.com/elastic/kibana/pull/147398

Add the `revision` field to the [alert schema](https://www.elastic.co/guide/en/security/current/alert-schema.html). 

Type: `Long` | Description: `Reflects any local rule modifications`.

**Comment by jmikell821** [comment]
@marshallmain @spong please confirm if this description ^ is OK. Also, I noticed we don't have `version` in the alert schema table -- should that be in there?

**Comment by spong** [comment]
That sounds good to me @jmikell821 👍. As for `version`, it is listed as `kibana.alert.rule.version` in the schema, we just don't have a description for it. Would be good to add it for discerning between the two I think.


Note: The [ECS docs](https://www.elastic.co/guide/en/ecs/current/ecs-rule.html#field-rule-version) do conflate version/revision, so just take that into account. This is technically a separate field in the alerts schema, so it doesn't need to match the ECS description.
