### ISSUE TITLE
[BUG] Document required Security privs for cases 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#3239]
## Description
The priv [docs](https://www.elastic.co/guide/en/security/master/case-permissions.html) for Security cases could be expanded. Currently, the following details are not included when describing the privs needed for base use cases:
- **Required Security feature privs**: Some use cases, such as the "Give full access to manage cases" case, require at least `Read` Security feature privs to allow users to attach alerts to cases -- and this is of course assuming the user has the index privs needed to access alerts.
   <img width="400" alt="case-privs" src="https://user-images.githubusercontent.com/79124755/236861788-1aa516aa-d113-4f39-bab4-3f25f7721920.png">
- **Required index privs**: Some use cases require users to interact with data that's stored in indices. For example, if a user needed to attach alerts to a case, the minimum privs that they'd need are:
   - `Read` for the Security feature 
   - `All` for the Cases feature
   - Minimum privs for accessing alerts 
    
### Questions
- What are the min privs for accessing alerts? According to this warning message, it looks like it's `read`, `write`, `view_index_metadata`, `maintenance privileges` for the `.alerts-security.alerts-default` index.
  <img width="500" alt="Screenshot 2023-05-08 at 6 38 35 PM" src="https://user-images.githubusercontent.com/79124755/236952979-7e509f98-e497-4712-a5a4-d03b7024540f.png"> 
- What can users do with full access to manage cases? So far, we've gathered that they can:
  - [Review the case summary](https://www.elastic.co/guide/en/security/8.7/cases-open-manage.html#cases-summary)
  - [Add and manage comments](https://www.elastic.co/guide/en/security/8.7/cases-open-manage.html#cases-manage-comments)
  - Add and examine [alerts](https://www.elastic.co/guide/en/security/8.7/cases-open-manage.html#cases-examine-alerts) and [indicators](https://www.elastic.co/guide/en/security/8.7/indicators-of-compromise.html#review-indicator-in-case) attached to the case
  - [Add a Lens visualization](https://www.elastic.co/guide/en/security/8.7/cases-open-manage.html#cases-lens-visualization)
  - Modify the case’s description, assignees, severity, status, and tags.
  - [Manage connectors](https://www.elastic.co/guide/en/security/8.7/cases-ui-integrations.html) and send updates to external systems (if you’ve added a connector to the case)
  - [Copy the case UUID](https://www.elastic.co/guide/en/security/8.7/cases-open-manage.html#cases-copy-case-uuid)
  - Refresh the case to retrieve the latest updates
  - [Isolate a host from an alert](https://www.elastic.co/guide/en/security/8.0/host-isolation-ov.html#isolate-a-host) (will need to test this because users can add comments to a case with the right privs)
  - Create a new case from the Alerts page and Timeline. 
 

## Notes
- Doc updates being tracked [here](https://docs.google.com/document/d/1rP1rIUXXK8d9FtjZCt1DOP6Ss1N99nldmOdEkpjpSH4/edit).
- Changes will need to be backported to 8.0
- Create a matrix to track priv testing 

cc: @lcawl @jonathan-buttner

**Comment by nastasha-solomon** [comment]
Hey, @jonathan-buttner! @lcawl and I met today to discuss this doc issue. Here's some notes that came out of our chat: 
- In their current form, the case priv [docs](https://www.elastic.co/guide/en/security/master/case-permissions.html) correctly describe what's required to _only_ use the case feature within the Security Cases page. 
- The privs users need to add content to cases (e.g., attaching alerts, Timeline, and Lens vis) aren't included at the moment, but that might be ok because the functionality that allows them to do this exists outside of the Cases page. The docs that describe priv requirements for using these features also exist outside of the case priv doc so while they are spread out, they are in the appropriate spots. 
   - One possible way to tell users that they'll need additional privs for attaching items (mainly alerts) is to include a note at the start of the Cases prerequisites doc that tells users they may need to reference other feature docs for more info on feature priv and license requirements. I added a draft of what that note might look like in the [Google doc](https://docs.google.com/document/d/1rP1rIUXXK8d9FtjZCt1DOP6Ss1N99nldmOdEkpjpSH4/edit#).

**Comment by jonathan-buttner** [comment]
Thanks @nastasha-solomon , I responded with some comments in the doc.
