### ISSUE TITLE
Add a note that in 8.8 rule's APIs (create, update, bulk, get, find) won't return `throttle` in a response payload

### ISSUE THREAD

**Issue by e40pud** [elastic/security-docs#3257]
/## Description
In 8.8 we introduced conditional actions feature where we had to update security solution rule's APIs. The rule level notification frequency defined by `throttle` attribute was replaced by action level `frequency` attribute. User no longer will receive a rule level `throttle` field in response payload and instead should rely on actions frequencies.

Affected APIs:
- [Get rule](https://www.elastic.co/guide/en/security/master/rules-api-get.html)
- [Find rule](https://www.elastic.co/guide/en/security/master/rules-api-find.html)
- [Create rule](https://www.elastic.co/guide/en/security/master/rules-api-create.html)
- [Update rule](https://www.elastic.co/guide/en/security/master/rules-api-update.html)
- [Bulk rule actions](https://www.elastic.co/guide/en/security/master/bulk-actions-rules-api.html)

cc @peluja1012 @XavierM @banderror 

## Doc updates

- [Create rule | actions schema](https://www.elastic.co/guide/en/security/master/rules-api-create.html#actions-object-schema): 
  - [x] Add the optional `Frequency` and `Alerts_filters` fields - doc’d [here](https://docs.google.com/document/d/1uyw4Pc96Zw2GILEa3o2IsIFJj6WbxsGAGZKOdnlkWkU/edit#heading=h.f03wh3i0gd8o).
  - [x] Remove `"throttle": "rule"` from Example 3 and add the example content that Zhenia provided [here](https://docs.google.com/document/d/1uyw4Pc96Zw2GILEa3o2IsIFJj6WbxsGAGZKOdnlkWkU/edit#heading=h.7i4hx69pl0ef).
  - [x] Under the [Response payload](https://www.elastic.co/guide/en/security/master/rules-api-create.html#_response_payload) section, make the following updates:
     - [x] Remove `"throttle": "no_actions"` from the example response for a machine learning job rule.
     - [x] Remove `"throttle": "no_actions"` from the example response for an EQL rule.
     - [x] Remove `"throttle": "no_actions"` from the example response for an indicator match rule.
- [Update rule APIs | Optional fields for all rule types](https://www.elastic.co/guide/en/security/master/rules-api-create.html#opt-fields-all):
  - [x] Add the optional `Frequency` and `Alerts_filters` fields.
  - [x] Add a note to the throttle field description (see notes [here](https://docs.google.com/document/d/1uyw4Pc96Zw2GILEa3o2IsIFJj6WbxsGAGZKOdnlkWkU/edit#heading=h.6htia5tvx79e))
- [Bulk rule actions | Throttle schema](https://www.elastic.co/guide/en/security/master/bulk-actions-rules-api.html#throttle-schema-bulk)
  - [x] Add the optional `Frequency` and `Alerts_filters` fields.
  - [x] Add a note to the throttle field description (see notes [here](https://docs.google.com/document/d/1uyw4Pc96Zw2GILEa3o2IsIFJj6WbxsGAGZKOdnlkWkU/edit#heading=h.6htia5tvx79e)). 
- [Bulk rule actions | Response payload](https://www.elastic.co/guide/en/security/master/bulk-actions-rules-api.html#_response_payload_8)
  - [x] Remove `"throttle": "no_actions"` from all the example responses.

**Comment by peluja1012** [comment]
@XavierM do you know if this change was documented in the Alerting public docs in 8.7 when we introduced Alert Summaries?

**Comment by nastasha-solomon** [comment]
@peluja1012 @XavierM I looked through the 8.7 Kibana docs to see if the `frequency` field was doc'd. Here are my notes:
- 8.7 release notes:
  - Currently, I don’t see anything in the [8.7 breaking changes](https://www.elastic.co/guide/en/kibana/current/release-notes-8.7.0.html#breaking-changes-8.7.0) section for Kibana that tells users that the throttle field was replaced with the frequency field for the Kibana rule APIs. Maybe it was accidentally missed? Or maybe it was doc'd and I'm not looking in the right place?
  - Conditional actions are also not noted as a new Alerting feature in [8.7 Kibana release notes](https://www.elastic.co/guide/en/kibana/current/release-notes-8.7.0.html#features-8.7.0). Also don’t see it under the [Alerting Enhancements](https://www.elastic.co/guide/en/kibana/current/enhancements-and-bug-fixes-v8.7.0.html#enhancement-v8.7.0) section.
- Alerting API docs:
   - Looks like the 8.8 Kibana [create rule](https://www.elastic.co/guide/en/kibana/current/create-rule-api.html#create-rule-api-request-body) and [update rule](https://www.elastic.co/guide/en/kibana/current/update-rule-api.html#update-rule-api-request-body) API docs still show the throttle field as the only field to set action frequency when creating rules.
   - [These docs](https://www.elastic.co/guide/en/kibana/current/rule-apis.html#Legacy_create_alert_request_properties), which I think are built from Kibana’s open API spec, still show that `throttle` field is the primary way of setting alert frequency – though I’m not sure if they’re describing the “old” way of creating a rule (or creating an alert? Not sure what the docs are describing). 
      - I’ve not looked through all of the API docs on this page because there’s a lot to go through and it’s difficult for me to clearly identify what’s doc’d.
      - I have noticed that all examples still contain the `throttle` field
   - Don’t see the new action fields defined in [these](https://www.elastic.co/guide/en/kibana/current/rule-apis.html#createRule) Create rule docs.
   
cc: @e40pud

**Comment by nastasha-solomon** [comment]
@e40pud would the following work for the breaking changes release notes summary?

Rule API changes are introduced with conditional actions in 8.8. In 8.7 and earlier, action frequencies were set on a rule level by defining the `throttle` field. In 8.8, action frequencies are set on an action level and the `throttle` field is being replaced by the  `frequency` and `alert_filters` fields. This change affects the following APIs:
- [Get rule](https://www.elastic.co/guide/en/security/master/rules-api-get.html)
- [Find rule](https://www.elastic.co/guide/en/security/master/rules-api-find.html)
- [Create rule](https://www.elastic.co/guide/en/security/master/rules-api-create.html)
- [Update rule](https://www.elastic.co/guide/en/security/master/rules-api-update.html)
- [Bulk rule actions](https://www.elastic.co/guide/en/security/master/bulk-actions-rules-api.html)

**Comment by peluja1012** [comment]
Hi @nastasha-solomon, that looks great. I think we should also explain that those APIs (create, update, bulk, get find) no longer return the `throttle` field in the response, so any scripts that rely on that field should be updated to use the action level fields instead.

**Comment by banderror** [comment]
@e40pud @peluja1012 I know that our APIs will continue to accept rule-level frequency parameters. However, would we benefit from explicitly deprecating them in our user-facing docs and in our code (for the latter, see how it was done for the bulk CRUD endpoints)?

**Comment by e40pud** [comment]
@banderror agree, would be nice to deprecate rule level frequency. Do we need to have a clear understanding of "end of life" schedule? @peluja1012 what do you think about it, is it fair to tell uses that we won't support rule level throttle after lets say Q4 2023?

**Comment by peluja1012** [comment]
Hi @e40pud @banderror, I agree. We should deprecate this field and follow what we did for the bulk CRUD endpoints. When we deprecated the bulk CRUD endpoints in 8.2 (May 2022), we gave them and EOL of about a year, Q4 2023. I think we should do the same for the rule throttle field. Deprecated it in 8.8 and give it and EOL of a year, so Q4 2024.

**Comment by nastasha-solomon** [comment]
Thanks @peluja1012 and @banderror - I'll update the API docs and release notes to show that the rule-level `throttle` field is deprecated in 8.8. I'll also mention in the API docs that the field's EOL is Q4.

cc: @jmikell821 @benironside
