### ISSUE TITLE
[BUG] [v8.7] Create exception item API: expire_time

### ISSUE THREAD

**Issue by Liblor** [elastic/security-docs#3294]
**Description**: The `expire_time` option is only available for non-enpoint exceptions as described in this PR: #2891
> In 8.7, this feature is only available for regular exceptions, not Endpoint exceptions.

This should also be documented in the correspondings docs.

**Doc URL link or topic name**: https://www.elastic.co/guide/en/security/8.7/exceptions-api-create-exception-item.html#_request_body_11

**Comment by nastasha-solomon** [comment]
@yctercero to verify info for docs.

**Comment by yctercero** [comment]
@dplumlee could you confirm that the expiration field is **not** available for endpoint exceptions? Also, is this validation baked into the API?

**Comment by dplumlee** [comment]
Yeah this field is not available for endpoint exceptions and the validation is present in the API. If the user tries to add it manually, it should throw the standard validation error
