### ISSUE TITLE
[BUG] macOS Full Disk Access document slightly wrong

### ISSUE THREAD

**Issue by ferullo** [elastic/security-docs#334]
This page https://www.elastic.co/guide/en/security/master/sensor-full-disk-access.html gives directions for enabling full disk access on macOS.

The document is slightly wrong for Elastic and is missing an image. The page ends with this text

```
5. Click the + button to view Finder. Navigate to the /Library/Endgame directory, select the elastic-agent or esensor file, and then click Open.
6. In the Privacy tab, confirm that the elastic-agent or esensor file appears in the list of applications that have full access permission, as seen in the following image:

Elastic Endpoint Security now has the access required to fully protect your system.
```

The two issues are that
1. While `esensor` lives in `/Library/Endgame`, `elastic-endpoint` is found in `/Library/Elastic/Endpoint/elastic-endpoint`
2. There is no image following the text `as seen in the following image`

**Comment by DonNateR** [comment]
@ferullo: Can't you technically save the `elastic-agent` file in any local directory?  In my on-boarding testing, it appears in the `download `folder by default.

**Comment by ferullo** [comment]
Oh, nice further catch. It is `elastic-endpoint` that needs Full Disk Access, not `elastic-agent`. You are right that up until 7.9 `elastic-agent` can run from anywhere (in `7.10` Agent will have an installer and so it will also more-or-less always run from the same place) `elastic-endpoint` only installs into `/Library/Elastic/Endpoint/elastic-endpoint` so users will always find it there.

**Comment by DonNateR** [comment]
Got it!! I'll add a link to the integration through Fleet instructions at the top of this page so people understand how `elastic-endpoint` appears in the Endpoint directory.
