### ISSUE TITLE
Document a change to the Detection Engine's "Delete Index" API

### ISSUE THREAD

**Issue by rylnd** [elastic/security-docs#3353]
## Description 

With the changes summarized in [this kibana issue], our API to [delete the signals index](https://www.elastic.co/guide/en/security/current/index-api-overview.html#_delete_index) has changed behavior, and will no longer delete _alerts_ indices (i.e. the indices controlled by the alerting framework).

Since this behavior is desired (there is not a nice recovery state if users were to delete _alerts_ indices; a kibana restart would be required), and since the current documentation mentions _signals_ indices, we think it's appropriate to denote this change in behavior in 8.8 as a __bugfix__.

## Acceptance Test Criteria

* Release Notes readers can discover that the bug was fixed in 8.8.0
* API Docs readers can learn that the endpoint does _not_ delete alerts indices, which should contain all alerts written in 8.x

**Comment by nastasha-solomon** [comment]
API doc updates in https://github.com/elastic/security-docs/pull/3355. Bug fix summary doc'd in [8.8 release notes](https://github.com/elastic/security-docs/pull/3282/files#diff-286e4844675af19e18fa339b9647052567b6126db4e52c5f337b9deb44434ca4R95).
