### ISSUE TITLE
rules Notification setup guide point out better the timeframe and matches query

### ISSUE THREAD

**Issue by 111andre111** [elastic/security-docs#3367]
## Description 
At the moment there are meanwhile 2 approaches to set up notifications:
it and be `If alert matches a query`  and the newer occasion is `If alert is generated during timeframe`.
Now we mention that latter one here:
  https://www.elastic.co/guide/en/security/8.8/rules-ui-create.html#rule-notifications
But it would be good however to share some more specific screenshots and describe it a bit better on those places:
  https://www.elastic.co/guide/en/security/8.8/rules-ui-management.html#edit-rules-settings
<img width="572" alt="Screenshot 2023-05-26 at 00 07 45" src="https://github.com/elastic/security-docs/assets/48132449/ba5d3808-33f5-42d7-8cbc-a457d0a08fc9">

## Acceptance Test Criteria

Should be at the end better visible how to set up notification actions and point out the flexibility of the whole thing that you could set up multiple notifications with completely different timed notifications.

^^ @paulewing

**Comment by natasha-moore-elastic** [comment]
Hey @paulewing, what are your thoughts on expanding more on this information per @111andre111's suggestions?
Would you be able to provide some content for us to add here? Thanks!

**Comment by e40pud** [comment]
I see that on "Manage detection rules" page we don't do a detail overview of rule settings like actions just mention those and as I can see there is a link to the page where we describe how to "Set up alert notifications":

<img width="735" alt="Screenshot 2023-10-26 at 14 08 52" src="https://github.com/elastic/security-docs/assets/2700761/0f29d3f6-0bcf-43d0-bd67-e034cbcaecdb">

@111andre111 do you think we should add more details/screenshots about those two options: _"If alerts matches a query"_ and _"If alert is generated during timeframe"_?

**Comment by 111andre111** [comment]
It's interesting. I don't know if something changed but somehow it's looking better now.

![Screenshot 2023-12-13 at 15 21 27](https://github.com/elastic/security-docs/assets/48132449/4e9c0c6c-bcc9-4d8d-bd3d-1d3e57c3b319)
![Screenshot 2023-12-13 at 15 19 35](https://github.com/elastic/security-docs/assets/48132449/3806da44-a089-4711-a089-d2bfc079bdd8)

It might still be not 100% obvious but now I defer it to you if you want to share more information. But I think for now that under Rule Management it links back to the Rule Actions and describes there the options might make it already a lot better docs experience.
