### ISSUE TITLE
Privileges for Security Kibana are not complete

### ISSUE THREAD

**Issue by 111andre111** [elastic/security-docs#3368]
## Description 

The screenshot on page
https://www.elastic.co/guide/en/security/8.8/endpoint-management-req.html
is not complete - it misses `Execute Operations` as well as `Cases`.
<img width="726" alt="Screenshot 2023-05-26 at 00 40 24" src="https://github.com/elastic/security-docs/assets/48132449/a5f476ca-a465-40cc-b6aa-bae7a5af167b">

The latter `Cases` privilege is not described on that page at all.

I saw however for cases here a documentation:
https://www.elastic.co/guide/en/kibana/8.8/setup-cases.html
However I am not sure it the information there is even true it's under `Tech Preview` but it could be that this partucular page is more about Observability cases. That's to be clarified.

**Comment by joepeeples** [comment]
The Execute Operations privilege is added to the screenshot as part of https://github.com/elastic/security-docs/pull/3392.

Cases aren't part of Elastic Defend, so they're not included on this page or screenshot for "Elastic Defend feature privileges." However, the privileges & requirements for Security Cases are documented separately [here](https://www.elastic.co/guide/en/security/8.8/case-permissions.html). Also, Security Cases have a separate UI from generic [Kibana Cases](https://www.elastic.co/guide/en/kibana/8.8/cases.html), and AFAIK Security Cases are not technical preview in 8.8, but it appears that Kibana Cases still are.

**Comment by joepeeples** [comment]
Closing as fixed in #3392 with updated screenshot.
