### ISSUE TITLE
wrong issue type "improvement" for Jira Connector

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#3378]
## Description 
Wrong issue type `improvement` for Jira Connector

## Documentation Guide Link
https://www.elastic.co/guide/en/security/8.8/rules-ui-create.html#rule-notifications
 

## Expected
![image](https://github.com/elastic/security-docs/assets/59917825/fd229168-ff9d-42e4-a909-d6cea5334551)

## Actual 
![image](https://github.com/elastic/security-docs/assets/59917825/4dccbc62-445f-40dd-ad28-c9a8aaf1b2f6)

**Comment by karanbirsingh-qasource** [comment]
@sukhwindersingh-qasource please review

**Comment by nastasha-solomon** [comment]
Thanks for catching this, @karanbirsingh-qasource! Doc updates are ready for review at https://github.com/elastic/security-docs/pull/3388. Thanks!

**Comment by sukhwindersingh-qasource** [comment]
Hi @nastasha-solomon 

We tested the latest docs and found the issue was fixed there.

**Screenshot:**

![image](https://github.com/elastic/security-docs/assets/108654988/1daab7d5-1e92-46e2-b5de-a4f015d68655)


Hence, we are closing this issue and marking it as QA Validated.

Thanks!
