### ISSUE TITLE
Outdated section "Action Frequency" drop-down in Rule Action Guide

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#3379]
## Description 

Outdated section "Action Frequency" drop-down in Rule Action Guide

## Documentation Guide Link

https://www.elastic.co/guide/en/security/8.8/rules-ui-create.html#rule-response-action

## Expected

![image](https://github.com/elastic/security-docs/assets/59917825/017fbd5b-e374-4a02-a5b0-0de55b848394)

## Actual

![image](https://github.com/elastic/security-docs/assets/59917825/07566bd8-d624-4760-934d-d3b0b48259d0)

**Comment by karanbirsingh-qasource** [comment]
@sukhwindersingh-qasource please review

**Comment by nastasha-solomon** [comment]
Thanks for catching this, @karanbirsingh-qasource! Doc updates are ready for review at https://github.com/elastic/security-docs/pull/3388. Thanks!

**Comment by sukhwindersingh-qasource** [comment]
Hi @nastasha-solomon 

We tested the latest docs and found the issue was fixed there.

**Screenshot:**

![image](https://github.com/elastic/security-docs/assets/108654988/4d9331dc-56f3-45f1-bd9d-78f62f9e0542)

Hence, we are closing this issue and marking it as QA Validated.

Thanks!
