### ISSUE TITLE
Data Quality tagged as beta in Documentation

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#3384]
## Description 

Data Quality tagged as beta in Documentation

## Documentation Guide Link

https://www.elastic.co/guide/en/security/8.8/es-ui-overview.html

## Expected

![image](https://github.com/elastic/security-docs/assets/59917825/b846a03e-6ed3-43c0-815c-2a265b891c06)

## Actual

![image](https://github.com/elastic/security-docs/assets/59917825/9059bb14-af86-46bd-b517-dcba02bda2b2)

**Comment by karanbirsingh-qasource** [comment]
@sukhwindersingh-qasource please review

**Comment by benironside** [comment]
This issue was resolved, refer to: https://www.elastic.co/guide/en/security/8.9/es-ui-overview.html
