### ISSUE TITLE
Trusted applications for other Security products

### ISSUE THREAD

**Issue by 111andre111** [elastic/security-docs#3433]
## Description 

Endpoint Security needs to be whitelisted each other with 3rd party security solutions in case someone wanted to use in parallel both on endpoints.

## Acceptance Test Criteria

Can we add this to our Security troubleshooting section please and possibly link to it from installation guide in case there are issues installing endpoint solution?
https://www.elastic.co/guide/en/security/current/install-endpoint.html
https://www.elastic.co/guide/en/security/current/troubleshooting-ov.html
I suppose we need to use `Trusted Applications` for that
https://www.elastic.co/guide/en/security/current/trusted-apps-ov.html

**Comment by joepeeples** [comment]
Additional info from https://github.com/elastic/security-docs/issues/1280:
- Content will likely be maintained in a [Google doc](https://docs.google.com/document/d/1BY0O2L2zUsKFi7kz-sAK3sqm7KlLACGlbRZFU4YOx7c/edit?usp=sharing) for now.
