### ISSUE TITLE
[DOCS] Add access permissions for macOS 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#344]
In 7.10, we're adding a pop up for elastic endpoint when it is unable to load the kernel extension (10.13, 10.14, 10.15), system extension (11.0), or have full disk access (10.14.6+, 10.15, 11.0). 

Let's rename the title to something like "Enable full disk access and extensions on macOS" - something to that effect. Let's retain the tag ID because I believe there are internal refs that link to this. 

Full disk access will be one section. Let's add these two subsections: 

[Enable full disk access for system extensions](https://docs.google.com/document/d/1KCffuaSzPFi1_JI7T1e4fXa8BnD6ewr2rS5QIcCtxxI/edit)
**Note:** For Elastic Security, the filename is actually `co.elastic.systemextension` instead of the Endgame extension in the doc/screenshot. 

[Enable kernel extension for Elastic Endpoint](https://docs.google.com/document/d/1nnxRMoaj7LmlRw4d5B-aki7AHYYYaQHo4Dl3bgj0gxQ/edit)

This will be an addendum to PR #335.

**Comment by jmikell821** [comment]
@DonNateR 
Steps: 

1. Run the installer file
2. When the prompt appears, either click OK to continue w/ install or open security preferences to approve it.
3. If they click OK, once the install is finished, they need to go back into security preferences to allow the system extension. 
4. Enable FDA for the system extension. 
5. Enable FDA for where the sensor was installed.

**Comment by DonNateR** [comment]
@jmikell821: These steps have already been added to https://github.com/elastic/security-docs/pull/335
