### ISSUE TITLE
[Detection Engine] - Exceptions flyout not loading or extremely slow

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#3449]
## Description 

The exceptions flyout makes an initial call to _field_caps to get _all_ field (mapped and unmapped) info. If a rule has indices with a large number of fields, this call is very slow and upon completing returns a very large response which causes some users to see an out of memory error in the browser.

We are moving to fix this issue for 8.8.2 and 8.9 but 8.7 will need to have this included as a known issue. There is no good workaround for this at the moment other than using the API.

SDH [#591](https://github.com/elastic/sdh-security-team/issues/591), [#587](https://github.com/elastic/sdh-security-team/issues/587), [#585](https://github.com/elastic/sdh-security-team/issues/585), [#3795](https://github.com/elastic/sdh-kibana/issues/3795)
Issues [#158751](https://github.com/elastic/kibana/issues/158751), [#158110](https://github.com/elastic/kibana/issues/158110)
PRs [#158371](https://github.com/elastic/kibana/pull/158371), [#159216](https://github.com/elastic/kibana/pull/159216)

This [PR](https://github.com/elastic/kibana/pull/159216) will trigger the release notes fix for 8.8.2/8.9 so I think we should be ok there.

**Comment by nastasha-solomon** [comment]
@yctercero which API should users use? The [Get exception item](https://www.elastic.co/guide/en/security/master/exceptions-api-get-item.html) API?

**Comment by yctercero** [comment]
@nastasha-solomon it does affect the UI. Previously, when a user opened the dropdown to select a field, a warning icon would appear next to the field if a mapping conflict was detected. Now with this change, that warning icon will no longer show up, a user will only see the warning text about a mapping conflict after field selection.

**Comment by nastasha-solomon** [comment]
Thanks for confirming, @yctercero! I've filed https://github.com/elastic/security-docs/issues/3527 to track the necessary doc updates.
