### ISSUE TITLE
[Detection Engine] - Triaging issues with rules querying frozen tiers

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#3450]
## Description 

Every so often we get an SDH about users seeing some sudden performance issues with their rules. This document that @marshallmain created does a good job of walking through the issue and what we suggest. Because this continues to come up as an SDH issue, thought it would be worth adding it to the triage section.

[Document with info](https://docs.google.com/document/d/1gYQ1lvn1ruBI_rwdLTDketx9KrU0PIGW4rc46SZocAc/edit#heading=h.b9vdv8xl2odp)
[Most recent SDH](https://github.com/elastic/sdh-elasticsearch/issues/7225)

## Notes

- We're working with the Elastic team on some possible solutions, but for now there's only some things to triage the issue, no real "fix"

**Comment by nastasha-solomon** [comment]
Investigations are ongoing and @yctercero is exploring ways to deliver this information. We're putting this doc issue on hold in the meantime.

**Comment by yctercero** [comment]
Just updating - we continue to triage this issue so no updates yet.

**Comment by yctercero** [comment]
No status updates here. We continue to triage some of these issues. A PR was recently merged ES side that may alleviate some issues, but we need more time to confirm. Will continue updating.

**Comment by 111andre111** [comment]
Would this PR here help:
https://github.com/elastic/kibana/pull/172162
That adds setting `securitySolution:excludeColdAndFrozenTiersInAnalyzer` in 8.12?
At least should be considered to be added to docs. 
^ @yctercero

**Comment by yctercero** [comment]
Thanks @111andre111 ! @elastic/security-docs is that [PR](https://github.com/elastic/kibana/pull/172162) already planned to be doc'd? If so, we can probably close this ticket.

**Comment by stefnestor** [comment]
FYI: I updated [the core KB](https://support.elastic.dev/knowledge/view/39606517) with this feature flag noting this only solves the problem on the SIEM-not-KB-or-ES layer ≥8.12.

**Comment by nastasha-solomon** [comment]
@yctercero the `securitySolution:excludeColdAndFrozenTiersInAnalyzer` setting was doc'd for ESS and Serverless docs with https://github.com/elastic/security-docs/pull/4484 and https://github.com/elastic/staging-serverless-security-docs/pull/250

**Comment by yctercero** [comment]
Thanks @nastasha-solomon ! Then I think we're ok to close this out for now.
