### ISSUE TITLE
[Detection Engine] - Sourcerer not picking up aliases

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#3455]
## Description 

Issues with sourcerer not picking up aliases and some data streams v8.7. This was fixed in 8.8, but needs filed as known issue for 8.7.

SDH [#618](https://github.com/elastic/sdh-security-team/issues/618), [#615](https://github.com/elastic/sdh-security-team/issues/615)
Issue [#156263](https://github.com/elastic/kibana/issues/156263)
PRs [#156311](https://github.com/elastic/kibana/pull/156311)

**Comment by nastasha-solomon** [comment]
@yctercero just double checking whether this bug affects 8.7.0 _and_ 8.7.1, or just 8.7.0.

**Comment by yctercero** [comment]
> @yctercero couple questions:
> 
> * Does this bug affects 8.7.0 _and_ 8.7.1, or just 8.7.0?
> * Does this bug affect the [default](https://www.elastic.co/guide/en/security/8.8/data-views-in-sec.html#default-data-view-security) Security data view? Or does this affect all data views (i.e. the ones you can create and manage from Stack management).

@dhurley14 correct me if I'm wrong here, but I believe it affects all versions 8.7.0 and up, so all minors included. And it affects all data views, not just a default security data view issue.

**Comment by dhurley14** [comment]
8.7.x and the PR was backported to 8.8.0 so should be fixed there. And this impacts all data views.
