### ISSUE TITLE
[DOCS] Document the new `Detection rule monitoring` dashboard

### ISSUE THREAD

**Issue by banderror** [elastic/security-docs#3478]
**Ticket:** https://github.com/elastic/security-team/issues/6032 (internal)
**PRs:** https://github.com/elastic/kibana/pull/159875, https://github.com/elastic/kibana/pull/160316

## Summary

In https://github.com/elastic/kibana/pull/159875 we added a new Kibana dashboard called `[Elastic Security] Detection rule monitoring`. All the details about it should be in the PR description, but please ping me if you have any questions.

We'd like the dashboard to be mentioned in the docs so that our users become aware of it and start using it for monitoring rules and troubleshooting issues with the Detection Engine.

The API endpoint added in the above-mentioned PR doesn't need to be documented.

## Known issue

A "known issue" should be added to the release notes: the number of `Rule executions` on the dashboard will not always be equal to the sum of the `Succeeded` + `Warning` + `Failed` numbers. This is normal and the reason for that is the following: any rule can write multiple statuses per each execution. One of the typical cases is gap detection: if a rule detects a gap in rule execution, it will first write an intermediate `Failed` status and continue to run, and then it will write a final status (e.g. could be `Warning`) before finishing its execution.

**Comment by joepeeples** [comment]
Add note in docs about required role/privilege to query and view the indices on this dashboard. 

@banderror: Could you confirm what specific role or privilege is needed?

**Comment by banderror** [comment]
@joepeeples Sorry for not being 100% clear in the PR. To be very specific, in order to be able to view the dashboard, users will need to have at least the following 2 privileges:

1. At least `Read` access to Kibana dashboards (`Analytics` -> `Dashboard` : `Read`)

<img width="731" alt="Screenshot 2023-06-22 at 20 49 38" src="https://github.com/elastic/security-docs/assets/7359339/e7f52c29-0492-423e-8fb2-0dab9b5bd400">

2. At least `read` access to the `.kibana-event-log-*` index.

<img width="1472" alt="Screenshot 2023-06-22 at 20 52 10" src="https://github.com/elastic/security-docs/assets/7359339/844f650b-b285-48ae-ac59-42831fc406d9">

I will update the PR with this info.

**Comment by banderror** [comment]
@joepeeples I just opened the 2nd PR with some fixes, and would appreciate any comments on the text I added to the dashboard: https://github.com/elastic/kibana/pull/160316 Thank you 🙏
