### ISSUE TITLE
[DOCS] Document the new rule execution status filter

### ISSUE THREAD

**Issue by nikitaindik** [elastic/security-docs#3486]
**Related issue**: https://github.com/elastic/kibana/issues/138903
**Related PR**: https://github.com/elastic/kibana/pull/159865

## Summary 
We've added a new filter by execution status to the Rules Management page. We might need to update the docs to reflect this new change. Make new screenshots, for example.

<img width="984" alt="Screenshot 2023-06-22 at 14 04 57" src="https://github.com/elastic/security-docs/assets/15949146/05bed1e3-29d2-4278-8697-c66563564473">

**Comment by nastasha-solomon** [comment]
Thanks, @joepeeples! I didn't find any other affected screenshots or text outside of what you already pointed out. @natasha-moore-elastic and I went through this issue today and we're going to split the work as follows:

- @natasha-moore-elastic to update the following:
  - [ ] [Sort and filter the rules list](https://www.elastic.co/guide/en/security/master/rules-ui-management.html#sort-filter-rules): Include the option to filter the rules list by the Status filter.
  - [ ] [Check the current status of rules](https://www.elastic.co/guide/en/security/master/rules-ui-management.html#rule-status): Add a sentence or two that, in addition to sorting rules by status, they can filter them by status. 
- @nastasha-solomon to refresh the following rule page screenshots:
  - [ ] `all-rules.png`
  - [ ] `monitor-table.png`

**Comment by joepeeples** [comment]
Solid plan, thanks for the update! My PR for the rest of the rules management UI overhaul will be available soon.
