### ISSUE TITLE
[BUG] Endpoint Trusted Applications docs need to mention that process events will always be generated

### ISSUE THREAD

**Issue by ferullo** [elastic/security-docs#3489]
**Description**: The Endpoint Trusted Applications documentation doesn't mention that processes that match Trusted Applications still intentionally generate process create and terminate events that are written to Elasticsearch. This is done to preserve process lineage information in the stack, which for instance is used to render Analyze Events graphs. Can we get the document updated to clear up this confusion?

If a user does want to prevent process create and terminate events for Trusted Applications from being written to Elasticsearch they can use a Event Filter to suppress them.

**Doc URL link or topic name**: https://www.elastic.co/guide/en/security/current/trusted-apps-ov.html

---

### Pull requests
```[tasklist]
### Tasks
- [x] Classic docs — https://github.com/elastic/security-docs/pull/4640
- [x] Serverless docs — https://github.com/elastic/staging-serverless-security-docs/pull/272
```

**Comment by ferullo** [comment]
cc @nfritts @nicholasberlin @gabriellandau

**Comment by caitlinbetz** [comment]
thanks @ferullo , we mention this briefly on the [Optimize Defend ](https://www.elastic.co/guide/en/security/current/endpoint-artifacts.html)page - but it would be beneficial to include those bullets in the respective artifact main pages.

**Comment by joepeeples** [comment]
Serverless OK to publish whenever content is ready
