### ISSUE TITLE
[UX Copy] Security Mitre Attack detection coverage page.

### ISSUE THREAD

**Issue by ARWNightingale** [elastic/security-docs#3495]
**Summary**
When users start using Security Solution and detection rules, they want to understand and keep track of the coverage the Solution can provide. Currently we provide them with Rules in a table that can be sorted and filtered, but there is no overview that can give an understanding about coverage at a glance.
Different teams worked around this problem by building their custom tools as referenced in the Related Epics.

The popular way to represent coverage is using MITRE ATT&CK(TM) framework. It is a knowledge base of adversary tactics and techniques based on real-world observations. Currently it consists of 14 Tactics, 191 Techniques and 385 Sub-techniques. It is used by different teams and tools as a common reference.

Tactics represent an adversary tactical goal (eg Credential access), and in general can be viewed as an attack progression stages. Techniques represent how the attacker is achieving their goal.

We map our pre-built protections to ATT&CK tactics/techniques/sub-techniques where applicable. When creating custom rules, users can also map them to ATT&CK.

By coverage we usually understand the availability and number of detections for a given tactic/technique.

**Request**
We would like to review the UX copy in the UI. We have a quick description of the page under the page title and a reference to the docs page. This docs page would need to be created.

**Additional information** 

[Related Epic ](https://github.com/elastic/security-team/issues/2905)

[Design](https://www.figma.com/file/xIrb0z8utiqAeC17RBiMM1/Protections%2FDetections-Coverage-Overview-%232905?type=design&node-id=1%3A40&mode=design&t=oh3YVkGpLWPVBBD3-1)

**Comment by joepeeples** [comment]
UX copy revised in https://github.com/elastic/kibana/pull/164613, no further changes at this time so closing this issue.
