### ISSUE TITLE
Negative correlation in event correlation (EQL) rules

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#3497]
## Description 

Event correlation (EQL) rules now support negative correlation for missing events. When writing an EQL query for an event correlation rule, users can specify events that _should not_ happen in a sequence. 

## Related
* Security issue: https://github.com/elastic/security-team/issues/2835
* Added to Elasticsearch: https://github.com/elastic/elasticsearch/pull/92348
   - Note: [maxspan] is required for sequences with missing events queries (per [here](https://github.com/elastic/elasticsearch/pull/92348/files#diff-123105fcd0030e62f4100ab1424e1e978bcffa93eb64169867557eb3136c0fe1R338))
* Docs issue for Elasticsearch: https://github.com/elastic/platform-docs-team/issues/72

## Areas to update

Technically this is just a change to the EQL language, but it's requested/popular enough in Security to warrant an update on our side.

- [x] Release notes: Will be documenting in the [8.9.1 release notes](https://github.com/elastic/security-docs/pull/3690).
- [ ] What's new: @jmikell821 to file a doc issue or PR for these changes. 
- [x] Create rule instructions - Mention negative correlation, ~add example ([suggested example](https://github.com/elastic/eql/issues/21#issuecomment-1599745058))~.
- [x] Elasticsearch docs - Will be updated by Platform docs team, but might want to coordinate for consistency, links. Update: EQL docs published.

**Comment by nastasha-solomon** [comment]
Feature has been moved out of 8.9. Might be implemented in 8.10, hence the version label update.

cc: @yctercero

**Comment by nastasha-solomon** [comment]
Re-opening since release notes haven't been merged yet.

**Comment by nastasha-solomon** [comment]
Merged doc updates and 8.9.1 release notes.
