### ISSUE TITLE
[Detection Engine][Actions] - Deprecated values will no longer appear in UI

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#3498]
## Description 

A blocker [bug](https://github.com/elastic/kibana/issues/160446) came up for 8.8.2 release after some actions mustache variables were deleted in 8.8. Users whose actions were still using these deprecated values would have their actions fail silently. This bug has been fixed and backported and I believe a docs release note was done for it.

However, @e40pud noted that even though the fix allows users to continue using these deprecated variables, these variables are not showing in the UI as options. Per this [comment](https://github.com/elastic/kibana/pull/160451#issuecomment-1609855593) - response ops feels the UI should be left as is. Perhaps we can add a small callout in our docs 1) listing the deprecated values and 2) explaining that they will continue to work but will no longer be shown as options in the UI.

**Comment by nastasha-solomon** [comment]
Deprecated placeholders that were re-added to the API: https://github.com/elastic/kibana/pull/160451

**Comment by nastasha-solomon** [comment]
Chatted about this with @lcawl. Here are my notes:

- In 8.10, legacy action variables will be officially deprecated and @lcawl will be documenting this in the 8.10 Kibana release notes under the “Deprecations” section.  
- As of today, the legacy variables that will eventually be deprecated aren’t documented in the Kibana and Security docs (API and UI), so no doc changes are needed.
- It might be worth adding a short blurb to the UI docs that users can’t select legacy variables in 8.8.x but the variables will continue to work if they’ve already being used. I’m not sure how often users are doing this, or if this is a common occurrence.  If it’s not, it might not be worth updating docs.

**Comment by CyberTaoFlow** [comment]
Our org was definitely impacted by this....

**Comment by peluja1012** [comment]
Hi @CyberTaoFlow, I'm so sorry your team was impacted by this. We recommend that you upgrade your system to `8.8.2` in order for those actions variables to work as expected. Please let us know if you still experience problems after the upgrade.

**Comment by yctercero** [comment]
Chatted with @nastasha-solomon about this ticket. As she mentioned in her previous comment:

>In 8.10, legacy action variables will be officially deprecated and @lcawl will be documenting this in the 8.10 Kibana release notes under the “Deprecations” section.

I think we can close this ticket out for now since it will be documented by the team that implemented these changes.
