### ISSUE TITLE
[Detection Engine][Exceptions] - Known issue for exceptions fetch error

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#3523]
## Description 

We should update 8.8.2 known issues section to include this issue - https://github.com/elastic/kibana/issues/160851

It came in as a potential blocker for 8.8.2 but it was too late. There are no more planned 8.8 releases so fix will not be seen until 8.9. The fix for this issue is found in this [PR](https://github.com/elastic/kibana/pull/157930). Not sure if we double docs it as a fix on our end and response ops end or just one or the other.

Some suggested text for the issue: `A bug in 8.8.2 results in a toast messages "Failed to fetch detailed fields information" when adding an exception. While it does not block from exception creation, it disturbs the user flow.`

**Comment by nastasha-solomon** [comment]
@yctercero exploring options for delivering this information.

**Comment by yctercero** [comment]
This error was addressed and fixed by response ops. Going to close this out for now as I don't think we need to document it as a known issue on our end for now.
