### ISSUE TITLE
UI updated for unmapped fields and fields with type conflicts 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#3527]
## Description 

Previously, when a user opened the dropdown to select a field, a warning icon would appear next to the field if a mapping conflict was detected. Now with this change, that warning icon will no longer show up, a user will only see the warning text about a mapping conflict after field selection.

Will need to update [docs](https://www.elastic.co/guide/en/security/master/ts-detection-rules.html#rule-exceptions-ts) that describe the warning that users see when a field has a type conflict or is unmapped. Might also need to refresh note under step 2 [here](https://www.elastic.co/guide/en/security/8.8/add-exceptions.html#detection-rule-exceptions).

Related:
- https://github.com/elastic/kibana/pull/159216

## Notes

- This change was merged into 8.8.2 and 8.9, so will need to port the doc updates to the 8.8 docs.

cc: @yctercero @e40pud

**Comment by yctercero** [comment]
Thanks for this! Description/summary looks great!
