### ISSUE TITLE
Add Lateral Movement Detection analytics package info to release notes

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#3540]
Related issue: https://github.com/elastic/infosec/issues/14114

### Description
We have released a new version of the Lateral Movement Detection analytics package in 8.9 adding the ability to detect RDP threats. This should be added to the `8.9` release notes.

**Comment by SourinPaul** [comment]
@jmikell821 let's introduce Lateral Movement under `New features` in 8.9. We are yet to formally release this package, although we published fleet packages for iterations. 

A quick question: Can we link blogs to our release notes in practice or just elastic-doc pages?  

`New features`:
- Introduces Lateral Movement Detection advanced analytics package in General Availability. And adds the ability to detect malicious activities in Windows RDP events (https://github.com/elastic/integrations/pull/6588)

Thanks.

**Comment by jmikell821** [comment]
> A quick question: Can we link blogs to our release notes in practice or just elastic-doc pages?

@SourinPaul we can include a cross-reference link within the release notes summary, sure. Keep in mind we can also add this to our [release highlights](https://www.elastic.co/guide/en/security/current/whats-new.html) and include a link there too.

**Comment by SourinPaul** [comment]
Thanks, @jmikell821. We also have this staged for release blogs. 

Is there a separate GH issue for the release notes summary wherein I can provide the content/visuals?

**Comment by jmikell821** [comment]
Hi @SourinPaul - we would just add visuals to our highlights section. Release notes are pretty minimal. Feel free to add any notes or details in a comment in this issue: https://github.com/elastic/security-docs/issues/3543. Thanks!

**Comment by nastasha-solomon** [comment]
Update: We still need content (and potentially visuals) for the what's new in 8.9 page. I'll follow up with @SourinPaul on these next Monday.

**Comment by nastasha-solomon** [comment]
Closing since https://github.com/elastic/security-docs/pull/3668 was merged.
