### ISSUE TITLE
Add Data Exfiltration Detection integrations package info to 8.9 release notes

### ISSUE THREAD

**Issue by sodhikirti07** [elastic/security-docs#3554]
**Related Issue:** https://github.com/elastic/security-team/issues/4606

**Description:**
In 8.9, we released an enhancement for the Data Exfiltration Detection package adding the ability to detect exfiltration via external sources such as USB drives and Airdrop. Add this under the `Enhancements` section of this release.

Cc: @SourinPaul @jmikell821

**Comment by sodhikirti07** [comment]
@jmikell821 Similar to [LMD](https://github.com/elastic/security-docs/issues/3540), we plan to introduce this new DED ability under the `New features` section. Below is the summary for the same.


- The 8.9 release of Data Exfiltration Detection adds the ability to detect exfiltration anomalies via USB devices and Airdrop (https://github.com/elastic/integrations/pull/6577)

**Comment by SourinPaul** [comment]
@sodhikirti07 @jmikell821, please note that we should list this in the `Enhancements` section and not the `New features` section.

Thanks.

**Comment by nastasha-solomon** [comment]
Doc'd as an enhancement in the [8.9 release notes](https://www.elastic.co/guide/en/security/8.9/release-notes-header-8.9.0.html#enhancements-8.9.0).
