### ISSUE TITLE
Add a note in 8.8 docs about known legacy action migration issue

### ISSUE THREAD

**Issue by e40pud** [elastic/security-docs#3572]
## Description

In 8.8 we introduced conditional actions and moved legacy actions migration code to the alerting framework.

As part of these changes we introduced [the issue](https://github.com/elastic/kibana/issues/157462) which can happen during the migration. The issue happens when the frequency of legacy action is shorter than the rule execution interval. In this case during the migration alerting framework will convert and delete legacy actions and then do validation (action frequency cannot be shorter than rule interval) and throw an exception which leads to data loss (all actions will be lost in this case).

We will add [the fix](https://github.com/elastic/kibana/pull/160798) for this issue in `v8.9.1` and need to report a known issue for `v8.8`.

### There are few possible workarounds:
1. Users can manually set rule interval to be greater or equal to rule's interval and save the rule.
2. Users can export a rule, fix it manually and import it again.
3. Users can remove legacy action from rule in UI. Save rule, and try to create new action afterwards for this rule.
4. Users can just re-create the whole rule from scratch.

**Comment by nastasha-solomon** [comment]
Am using the summary that was reviewed/confirmed [here](https://github.com/elastic/security-docs/pull/3536#discussion_r1271544745).
