### ISSUE TITLE
[Filebeat Modules] Pointing users to Elastic Agent integrations

### ISSUE THREAD

**Issue by jamiehynds** [elastic/security-docs#3576]
While Filebeat modules are still supported by us, we do not typically apply bug fixes or enhancements to these modules, or ship any new modules.. Our focus is now entirely on Elastic Agent integrations. However, based on telemetry Beats are still used by a large percentage of customers, possibly due to a lack of awareness that Elastic Agent integrations exist. 

Our Filebeat module documentation should be advising users to use Elastic Agent integrations instead, as they are actively maintained and all new integrations will ship as agent integrations. 

Is it possible to add some wording or even a banner at the top of the [Module Reference docs](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-modules.html), to point users to Elastic Agent and associated integrations?

**Comment by natasha-moore-elastic** [comment]
@jmikell821, I'm not sure which team owns this – could you help me out with the correct team label for this issue? Thanks!
