### ISSUE TITLE
[DOCS] Update docs to reflect the new "building block" enhancement on the Rule Details page

### ISSUE THREAD

**Issue by nikitaindik** [elastic/security-docs#3596]
**Related issue**: https://github.com/elastic/security-team/issues/6950
**Related PR**: https://github.com/elastic/kibana/pull/162233

In 8.10 we are going to release a change that adds a line to the Rule Details page to indicate whether a rule is a "building block" rule. We might want to update screenshots or text in the docs.

[Docs: Manage detection rules](https://www.elastic.co/guide/en/security/current/rules-ui-management.html#rule-prerequisites)
[Docs: About building block rules](https://www.elastic.co/guide/en/security/current/building-block-rule.html)

<img width="938" alt="Screenshot 2023-07-19 at 14 02 48" src="https://github.com/elastic/security-docs/assets/15949146/a1d2cff6-d334-44e2-8235-ce5ebdc0031a">

**Comment by banderror** [comment]
Hey @nikitaindik, I'm curious why this ticket is assigned to you. Are you planning to write the docs?

**Comment by banderror** [comment]
Hey @elastic/security-docs, are we documenting this for 8.10? If there are no docs to update, I can close the ticket.

**Comment by joepeeples** [comment]
@banderror We can close this, thanks. We were waiting to sort out who needed to be assigned, but I've looked over it again and I don't think we need to update docs. No screenshots need updating, and we don't go into detail about every item listed on a rule's details page. And the description in the UI is straightforward enough too.
