### ISSUE TITLE
Dashboard landing page: filters for custom dashboards

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#3620]
## Description 

As of https://github.com/elastic/kibana/pull/160540, the Dashboards landing page is being updated with drop-down filters and other UI elements for managing custom dashboards.

> **Before:**
> 
> <img width="2545" alt="Screenshot 2023-06-27 at 09 24 19" src="https://github.com/elastic/kibana/assets/6295984/bc0fa0b1-96ad-43b0-afc1-48444dfb5691">
> 
> **After:**
> <img width="2543" alt="Screenshot 2023-06-27 at 09 22 21" src="https://github.com/elastic/kibana/assets/6295984/82d0a868-bda2-431f-b0b5-9cbc34d3ae71">
>

**Comment by angorayc** [comment]
Hello team, there's a [bug](https://github.com/elastic/kibana/issues/163459) fixed on the dashboard listing page: There is only **one** Create dashboard button left on the page. Please update the screenshot with this version, thanks a lot for your help!
https://my-deployment-b991eb.kb.us-central1.gcp.qa.cld.elstc.co:9243/app/security/dashboards
login details: https://p.elstc.co/paste/R1Sh0QHN#FrfVpMV3Bv-N4NlJkhrlkok+wVVq2eo37U68uu2Nmwf

Preview:
![dashboard_listing](https://github.com/elastic/security-docs/assets/6295984/2a76545d-c3ea-42b8-b893-5054f5474fad)
