### ISSUE TITLE
[Update] Manual prebuilt rule updates notice for older stack versions

### ISSUE THREAD

**Issue by approksiu** [elastic/security-docs#3622]
**Description**: 
Add the following note to the upgrade notes [eg](https://www.elastic.co/guide/en/security/8.1/upgrade-intro.html) for releases < latest-3 versions (please rephase appropriately):

- If you are upgrading to the version older than "latest-3" (eg latest version is 8.9, and you are upgrading to 8.5) - you will have to update prebuilt rules manually. If you want to get automatic updates - please consider upgrading to the latest version.

**Comment by jmikell821** [comment]
@approksiu just to clarify, what are all `8.x` versions this notice should apply to?

**Comment by approksiu** [comment]
@jmikell821 we should add this note to 7.17 - 8.5 docs. Thank you!

**Comment by joepeeples** [comment]
Removing the `Docset: Serverless` label, because we don't need to add anything to serverless docs. Serverless is always on the latest version.
