### ISSUE TITLE
[BUG] Screenshot needs to be updated for the updated count of Actions for the response action history tab

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#3636]
**Description**: 
Screenshot needs to be updated for the updated count of Actions for the response action history tab

**URL link or topic name**: 
https://www.elastic.co/guide/en/security/8.9/admin-page-ov.html#response-action-history-tab
https://www.elastic.co/guide/en/security/8.9/host-isolation-ov.html#view-host-isolation-details

**Screenshots**:
- Actual:
![image](https://github.com/elastic/security-docs/assets/60252716/42b96304-bf7f-4a3f-bc2d-e4a9ee622a63)

- Expected:
![image](https://github.com/elastic/security-docs/assets/60252716/031a85ed-ec80-49ad-be02-9736e59f3c45)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

We have validated the ticket against the latest docs for the changes done in the PR https://github.com/elastic/security-docs/pull/3678

All the changes are correctly updated and fixed.

Hence, we are closing this issue and marking it as QA Validated.

Thanks!
