### ISSUE TITLE
2 New Integration "Zero Networks Firewall" & "Google Cloud Security Command Center" are missing on Kibana

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#3637]
**Description**: 
2 New Integration "Zero Networks Firewall" & "Google Cloud Security Command Center" are missing on Kibana

**URL link or topic name**: 
https://www.elastic.co/guide/en/security/current/whats-new.html#_new_integrations

**Screenshots**:

![image](https://github.com/elastic/security-docs/assets/59917825/107a6848-eec2-492e-866a-4f7ff9aa9001)

![image](https://github.com/elastic/security-docs/assets/59917825/8bec9d0e-01bd-4034-845c-e3ed6e754c2f)

![image](https://github.com/elastic/security-docs/assets/59917825/f4e6c7d1-35d3-4844-8daf-66ebe69f936b)

**Expected**

- Update the new "Google Security Command Center" in doc instead of "Google Cloud Security Command Center"
- Update the new "Zero Networks" in doc instead of "Zero Networks Firewall" 

![image](https://github.com/elastic/security-docs/assets/59917825/8e529ba0-03b0-4519-87a6-d4f5de681205)

![image](https://github.com/elastic/security-docs/assets/59917825/d1888183-33f0-4adb-9829-5406304f905c)

**Comment by karanbirsingh-qasource** [comment]
@muskangulati-qasource please review

**Comment by muskangulati-qasource** [comment]
Reviewed!!
