### ISSUE TITLE
Document a known issue about detection rules being duplicated upon update

### ISSUE THREAD

**Issue by xcrzx** [elastic/security-docs#3645]
## Description 

**Bug Ticket:**
- https://github.com/elastic/kibana/issues/161305

**Summary:**
Upon upgrading prebuilt detection rules, users may observe duplication of some rules. One version of the rule will appear under the `Elastic rules` tab, while its duplicate will be found under the `Custom rules` tab. To rectify this, users should delete the duplicate from the `Custom rules` tab.

The issue has been fixed in `8.9`: https://github.com/elastic/kibana/pull/161331

Affected versions: `8.8`, `8.7`, `8.6`, and probably earlier.

**Comment by nastasha-solomon** [comment]
Hey, @xcrzx! Sorry for the delay on this one. The changes are ready for review at https://github.com/elastic/security-docs/pull/4022.
