### ISSUE TITLE
[DOCS] - Add section on using Value Lists with Indicator Match Rules

### ISSUE THREAD

**Issue by MikePaquette** [elastic/security-docs#368]
## Description 

Add a doc section on how to use Value lists with the Indicator Match rules. 

While users can add data into indicator indices in a variety of Elastic Stack methods, this is the only **_in-app_** method available in 7.10, so rather to help users gain value from this new rule type, we should document this capability.

 I've taken a cut at it for the 7.10 Technical Enablement [slides](https://docs.google.com/presentation/d/1gJnbZvuNKpShCFmLKBXVKsEqWu6ui_QU-uGES-EhitE/edit?ts=5fa873ad#slide=id.ga9842b28cd_1_3726) planned for 19-Nov, that we can use as basis.  

![image](https://user-images.githubusercontent.com/22619280/98843719-555ef180-2419-11eb-939d-82c86724572d.png)

![image](https://user-images.githubusercontent.com/22619280/98843773-64de3a80-2419-11eb-8baa-7bbd9f3188df.png)

![image](https://user-images.githubusercontent.com/22619280/98843806-71629300-2419-11eb-809a-3ce5b6ab311a.png)

![image](https://user-images.githubusercontent.com/22619280/98844038-c30b1d80-2419-11eb-932d-7bfd01c517ed.png)

![image](https://user-images.githubusercontent.com/22619280/98844108-dc13ce80-2419-11eb-9c13-7372e0e6fcee.png)

## Acceptance Test Criteria

As a user, after viewing this documentation section, I'll be able to create and activate an Indicator Match rule that uses a Value List as its indicator index.

## Notes

- [x] Add the **"Team:Docs"** label to new issues. 
- [x] Be sure to add the version number label. 
- [x] Be sure to add any necessary screenshots for clarity. 
- [ ] Include any conditions or caveats that may affect customers.

**Comment by jmikell821** [comment]
Merged #450.
