### ISSUE TITLE
[DOCS] Update docs for alert notifications section in Rule Creation page

### ISSUE THREAD

**Issue by peluja1012** [elastic/security-docs#378]
## Description 

Update docs for alert notifications section in Rule Creation page. Currently, our "Setup alert notification" [section](https://www.elastic.co/guide/en/security/current/rules-ui-create.html#rule-notifications) in our docs shows a screenshot with the available alert actions. This [PR](https://github.com/elastic/kibana/pull/83781) expanded the number of available actions to include ServiceNow, Jira, and IBM Resilient. The screenshot below shows what this section will look like in `7.10.1`. 

![image](https://user-images.githubusercontent.com/616158/99843601-d0be5280-2b3f-11eb-9bda-146dee55b35b.png)

**Comment by jmikell821** [comment]
#384 merged.
