### ISSUE TITLE
[DOCS] Document the new MITRE ATT&CK Coverage page

### ISSUE THREAD

**Issue by banderror** [elastic/security-docs#3797]
**Epic:** https://github.com/elastic/security-team/issues/2905
**Main PRs:** https://github.com/elastic/kibana/pull/161556, https://github.com/elastic/kibana/pull/163498
**All PRs:** https://github.com/orgs/elastic/projects/699/views/15?filterQuery=is%3Apr+devcycle%3A%228.10%22+epic%3A%22Protections%2FDetections+Coverage+Overview%22

## Summary

We've implemented a new page called `MITRE ATT&CK® Coverage` that allows users to see how their installed rules "cover" all the tactics and techniques of the MITRE ATT&CK® framework.

On this page, users are able to:

- see the grid of tactics and techniques + rules mapped to them
- filter rules
- enable rules

The link to the page is located under the _Dashboards_ nav menu, but will be moved under the _Rules_ one before the `8.10.0` release.

Please contact @dplumlee for any questions.

**Comment by dplumlee** [comment]
I'm adding a link to docs in [this PR](https://github.com/elastic/kibana/pull/164613) that can easily be updated for wherever this documentation ends up living. Not sure if it's far enough in the process at the moment that y'all can project what that link will be but just thought I'd give you a heads up

**Comment by joepeeples** [comment]
- Stub page created for doc link: https://github.com/elastic/security-docs/pull/3813
- UI copy suggestions added to PR https://github.com/elastic/kibana/pull/164613#issuecomment-1693927267

**Comment by joepeeples** [comment]
Blocked until BC3 -- bug in BC2 prevents displaying cells
