### ISSUE TITLE
[DOCS]: Host List Overview 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#38]
Meta issue: https://github.com/elastic/endpoint-app-team/issues/63

AC:

Lists Endpoints in a tabular format
Contains fields: IP, Hostname (fully qualified?), OS, Endpoint Status (last seen), Policy Status, Domain
Unit Tests at a minimum
API response format agreement: #65
For this ticket, all Endpoint data can mocked/faked including Endpoint Status and Policy Status

**Comment by kevinlog** [comment]
@jmikell821 
Currently, the Endpoint will reflect whichever status the parent Agent has, so these are from an Agent perspective.  It still gives Security users insight into their Endpoint in the Administration tab

Possible Host statuses:
- Online, Green.  This indicates that the Agent is online and communicating with Kibana
- Unenrolling, Yellow.  This indicates that the Agent is currently unenrolling and will soon be removed from Ingest and the Endpoint will follow.
- Grey, Offline.  This indicates that the Agent is still enrolled, but may be on a machine that is shutdown or doesn't have internet access currently.  In this state, the Agent is no longer communicating with Kibana on a regular interval
- Red, Error.  This indicates an Error in the Agent and means something has gone wrong.  The user should look at the Agent logs in Fleet to find out more.  This can also mean that the Endpoint is unable to find the parent Agent or that is it missing the Agent ID.  This is also a problem and the user should investigate Endpoint or Agent logs.
