### ISSUE TITLE
[Detection Engine][ESQL] - Document new rule type

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#3817]
## Description 

Ticket for docs updates that will be required for new ESQL rule type.

Related:
- https://github.com/elastic/security-team/issues/7215
- https://github.com/elastic/kibana/pull/165450

## Copy work

- https://github.com/elastic/ux-writing/issues/41
- https://github.com/elastic/kibana/pull/168611

## Notes
To keep in mind:
- UI changes (rule creation/edit/details)
- API changes
- Will be tech preview

## Doc updates

- [About detection rules | Rule types](https://www.elastic.co/guide/en/security/master/about-rules.html#rule-types): 
   - [x] Add a bullet to the end of the list for the new ES|QL rule. 
- [Create a detection rule](https://www.elastic.co/guide/en/security/master/rules-ui-create.html): 
   - [x] Add a section for creating an ESQL rule. \
   - [x] Explain the two types of queries that users can write: aggregating and non-aggregrating  
- [Create rule API docs](https://www.elastic.co/guide/en/security/master/rules-api-create.html): 
   - [x] @vitaliidm making doc updates via https://github.com/elastic/security-docs/pull/4052

**Comment by nastasha-solomon** [comment]
Temporarily re-opening since the PR still needs an editorial review and PM review.
