### ISSUE TITLE
[DOCS] Add known issue for "ip range" value lists not working in Exceptions

### ISSUE THREAD

**Issue by peluja1012** [elastic/security-docs#382]
## Description 
It's not possible to select value lists of type `ip_range` when adding exceptions via the `Add Rule Exception` modal. More details in this [ticket](https://github.com/elastic/kibana/issues/79511). This ticket is to add a new item to the release notes "known issues" section detailing this problem.

![image](https://user-images.githubusercontent.com/616158/100104373-15920400-2e34-11eb-83e4-c9add7017648.png)

**Comment by jmikell821** [comment]
@peluja1012 Nate updated the RNs -- can you review and approve this PR: https://github.com/elastic/security-docs/pull/383
