### ISSUE TITLE
[BUG] Old screenshot is displayed for Endpoint list details under the Administration/Endpoint Tab.

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#387]
**Description**: Old screenshot is displayed for Endpoint list details under the Administration/Endpoint Tab.

**Observation**: Operating System details don't show the OS version now.

**URL link or topic name**: [Adminstration page](https://www.elastic.co/guide/en/security/current/admin-page-ov.html#admin-page-ov)

**Screenshots**:
- Screenshot in doc:
![DocsScreenshot](https://user-images.githubusercontent.com/60252716/100862506-3fdd6480-34b9-11eb-9d0b-8cd7b7026a0d.png)

- UI screenshot:
![UI](https://user-images.githubusercontent.com/60252716/100862525-48ce3600-34b9-11eb-88b5-808b1b8219dc.png)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource Please review!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @jmikell821

**Comment by jmikell821** [comment]
Fixed in #411.

**Comment by muskangulati-qasource** [comment]
Hi @jmikell821,

We validated this issue again and found that issue now **fixed**.

**Refer Screenshot**:
![387](https://user-images.githubusercontent.com/60252716/104013664-c5021a80-51d7-11eb-8c6b-b8818461ae0c.PNG)

Thanks!
