### ISSUE TITLE
[BUG] Old naming is showing for policy i.e. configuration at many places

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#388]
**Description**: Old naming is showing for policy i.e. configuration at many places

**URL link or topic name**: [Adminstration page](https://www.elastic.co/guide/en/security/current/admin-page-ov.html#admin-page-ov)

**Screenshot**:
![Configuration_Policy](https://user-images.githubusercontent.com/60252716/100862911-cdb94f80-34b9-11eb-8708-7742e72f6f1c.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @jmikell821

**Comment by jmikell821** [comment]
Note: @muskangulati-qasource in the proper context, `configuration` is okay to use (e.g., `"view configuration details..."`) but will go through the highlighted areas. Thanks!

**Comment by jmikell821** [comment]
Fixed in #411.

**Comment by muskangulati-qasource** [comment]
Hi @jmikell821,

We validated this issue again and found that issue now **fixed**.

**Refer Screenshot**:
![388](https://user-images.githubusercontent.com/60252716/104013470-7bb1cb00-51d7-11eb-9460-8d10f65ca6ae.PNG)

Thanks!
