### ISSUE TITLE
[BUG] Old screenshot is displayed for open a new case under the cases Tab.

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#389]
**Description:** Old screenshot is displayed for Open a new case under the cases Tab.

**Observation**: Edit option is not displaying under External Incident Management System 

**URL link or topic name**: [Cases Page](https://www.elastic.co/guide/en/security/current/cases-overview.html)

**Screenshots:**
**Doc Screenshot:**
![doc_screenshot](https://user-images.githubusercontent.com/61860752/100867193-d7de4c80-34bf-11eb-914f-1419b2643b32.png)

**UI Screenshot:**
![new_screenshot](https://user-images.githubusercontent.com/61860752/100867198-da40a680-34bf-11eb-9b22-bfd7ad0ee564.jpg)

**Comment by deepikakeshav-qasource** [comment]
@manishgupta-qasource Please Review

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @jmikell821
