### ISSUE TITLE
Add link to 8.10 Elastic Defend document field documentation

### ISSUE THREAD

**Issue by ferullo** [elastic/security-docs#3891]
## Description 

The Endpoint team has started documenting which ECS fields can appear in each Endpoint document type. Can we please get a link to this documentation hosted on github.com from somewhere in the documentation hosted on elastic.co? I think this request has been informally made in the past so there's already a plan in place.

The 8.10 documentation is [here](https://github.com/elastic/endpoint-package/tree/2451b3ec8c62ec30d8372b3823482c984f13140a/package/endpoint/docs/custom_documentation). That link will need to be updated in the future. However, if we just want to link to the latest documentation and not update it per major/minor version then I can follow up with a link should always work going forward.

cc @roxana-gheorghe

**Comment by joepeeples** [comment]
Latest location to link to: https://github.com/elastic/endpoint-package/tree/main/custom_documentation/doc/endpoint
