### ISSUE TITLE
[Question] Information about Settings per case per connector is not mention in docs under the cases section

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#390]
**Description:** Information about Settings per case per connector is not mention in docs under the cases section

**Observation:** Information about different connector Like issue types , severity drop downs not mentioned. 

**URL link or topic name:** [Cases Page](https://www.elastic.co/guide/en/security/current/cases-overview.html)
[Configuring external connections](https://www.elastic.co/guide/en/security/current/cases-ui-integrations.html)

**Reference Ticket:** https://github.com/elastic/kibana/pull/77327

**Screenshots:**

**Jira: issue type, priority.**
<img width="2046" alt="Screenshot 2020-10-06 at 8 04 32 PM" src="https://user-images.githubusercontent.com/7871006/95236459-9eff5f80-080f-11eb-8f98-4d7a1113dd34.png">

**IBM Resilient: issue types and severity.**
<img width="2047" alt="Screenshot 2020-10-06 at 8 04 56 PM" src="https://user-images.githubusercontent.com/7871006/95236419-9444ca80-080f-11eb-8374-3925724bdcfc.png">

**ServiceNow: urgency, severity and impact.**
<img width="2045" alt="Screenshot 2020-10-06 at 8 05 05 PM" src="https://user-images.githubusercontent.com/7871006/95236435-9870e800-080f-11eb-8313-f6ca426cdf7a.png">

**Comment by deepikakeshav-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @jmikell821

**Comment by jmikell821** [comment]
@DonNateR trying to update and close out old bugs; please provide a status update.

**Comment by DonNateR** [comment]
Hi Janeen. After talking to Cristos about this, it's probably better if we don't document each issue type of severity since those are different across different versions of each of the three apps.
