### ISSUE TITLE
[Known Issue] Prevalence table in expanded alerts detail flyout showing no data if query runs long

### ISSUE THREAD

**Issue by christineweng** [elastic/security-docs#3904]
## Description

In the new alerts detail flyout, prevalence table in the left section, prevalence tab, shows "No prevalence data available" instead of the prevalence table. This is often observed in bigger clusters and when data streaming is enabled.

![image](https://github.com/elastic/security-docs/assets/18648970/0ffd6c2d-2802-400a-87a7-0c88b144e2b7)

## Area/Engineering team

Threat Hunting

## Stack release 

8.10

## Release fixed

8.10.1

## Workaround

No workaround

**Comment by nastasha-solomon** [comment]
Using the high-level description @paulewing suggested via Slack:
The alert prevalence feature behaves inconsistently and may not produce accurate results.

cc: @PhilippeOberti @christineweng

**Comment by nastasha-solomon** [comment]
Added in [3c69c70](https://github.com/elastic/security-docs/pull/3781/commits/3c69c70ae7f9f1116450c4cdc4b03fea5542b128).
