### ISSUE TITLE
[BUG] Old screenshot and naming 'Elastic Endpoint Security' is displayed at many places

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/security-docs#391]
**Description**: Old screenshot and naming 'Elastic Endpoint Security' is displayed at many places

**Observation**: Elastic Endpoint Security is renamed to Endpoint Security in 7.10.0 as per [#186](https://github.com/elastic/security-team/issues/186) 

**URL link or topic name**: [Configure and install Elastic Endpoint Integration (beta) page](https://www.elastic.co/guide/en/security/current/install-endpoint.html)

**Screenshots**:
- **Screenshot in doc:**
1. Under Integrations tab:-
![Screenshot1](https://user-images.githubusercontent.com/59917944/100872099-4c68b980-34c7-11eb-8cf9-b8f57557b700.jpg)

2. On adding Integration:-
![Screenshot2](https://user-images.githubusercontent.com/59917944/100872113-525e9a80-34c7-11eb-93cc-9e93f1a811c9.jpg)

3. Under Add Agent flyout :-
![Screenshot3](https://user-images.githubusercontent.com/59917944/100872119-55f22180-34c7-11eb-8c85-4ca99d8beb10.jpg)

- **UI screenshot under Integrations tab**:
![UI_screenshot](https://user-images.githubusercontent.com/59917944/100872134-5b4f6c00-34c7-11eb-83f8-0f4f11ae6985.jpg)

**Comment by rahulgupta-qasource** [comment]
@manishgupta-qasource Please review the bug.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821
