### ISSUE TITLE
[BUG] Add Exception is displaying instead of Add Rule Exception under Add exception to a Rule section.

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#392]
**Description:** Add Exception is displaying instead of Add rule exception under add exception to a Rule section. 

**Observation:** Add Exception is displaying instead of Add rule exception under add exception to a Rule section. Moreover, old screenshots are displayed for add rule exception

**URL link or topic name:** [Rule exceptions and value lists](https://www.elastic.co/guide/en/security/current/detections-ui-exceptions.html)

**Screenshots:**
**Doc Screenshot:**

![Doc_rule_exception1](https://user-images.githubusercontent.com/61860752/100875499-1d087b80-34cc-11eb-99e4-06a6a596a567.jpg)

**UI Screenshot:**

![UI_rule_exception](https://user-images.githubusercontent.com/61860752/100875530-298cd400-34cc-11eb-913d-9a6c56cfe3b7.jpg)

**Comment by deepikakeshav-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by jmikell821** [comment]
Fixed in #411.
