### ISSUE TITLE
Add note about ingest pipeline compatibility when upgrading from `7.x` -> `8.x`

### ISSUE THREAD

**Issue by spong** [elastic/security-docs#3920]
## Description 

As surfaced in this support ticket (https://github.com/elastic/sdh-security-team/issues/720) any ingest pipelines that are configured against the signals/alerts index may no longer function when upgrading from `7.x` -> `8.x` as the user that writes the alerts was changed from the `current user` to the `kibana_system` user, whose privileges are immutable and may not have write access to the destination index configured by the ingest pipeline. This issue is for adding a note/section to the [upgrade documentation](https://www.elastic.co/guide/en/security/current/upgrade-intro.html#upgrade-7.17-8x) detailing this behavior.

## Acceptance Test Criteria

As a user, I should know that if I have an ingest pipeline configured against the signals/alerts index that writes documents to an index that the `kibana_system` does not have privileges for, that the enabled Rules in my cluster will be in a failure state until the ingest pipeline is removed. 
 

## Notes

Please see [this comment](https://github.com/elastic/sdh-security-team/issues/720#issuecomment-1709092405) for further details, but feel free to reach out to me if there are any additional questions.

**Comment by nastasha-solomon** [comment]
Chatted with @spong about this briefly over Slack, and he provided the following language that we can add to our upgrade to 8.x [docs](https://www.elastic.co/guide/en/security/current/upgrade-intro.html).

> Alerts are now written using the `kibana_system` user instead of the `current user`, so any ingest pipelines configured against the alert index will use the `kibana_system` user privileges which may break your ingest pipeline

cc: @elastic/security-docs

**Comment by nastasha-solomon** [comment]
Note for self: since this applies to users upgrading from 7.x to 8.x, we should make this change to the latest branch (8.11/main) and then backport to 8.0.

**Comment by gboitano** [comment]
Some background: this alert index redirection was set up by elastic consulting (me), not a third party. more than a 18 months ago, I redirected some alerts from .siem-signals to another index  to replicate some ArcSight functionality which Bell absolutely required. They then ran with this idea and now have pipelines that redirect alerts to six or seven different indices.

**Comment by gboitano** [comment]
As for my fix, the kibana_system role has access to a number of index patterns, including .alerts-*. So I just set up an alias (.alerts-alternate-alias) for one of their custom alert indices (indicators-alerts). This works. So now they'll have to set up about 7 such aliases and modify seven pipelines to point to these aliases, Then they should be OK. They seemed happy with the solution.

For now.

Creating an alias starting with a . produced a warning message that this will be disallowed in a future major release. If this happens, this workaround won't work any more. A better long-term solution would be to allow users to add permissions to kibana-system. Or maybe add a new parameter in the rule definition GUI allowing an override to the destination index for alerts.

**Comment by jmikell821** [comment]
This was mentioned and merged in #5186.
