### ISSUE TITLE
Old Inspect modal options for Alert Trend 

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#3928]
## Description 
Old Inspect modal options for Alert Trend 

## Steps

- Navigate to https://www.elastic.co/guide/en/security/8.10/es-ui-overview.html#visualization-actions
- Scroll down and observed the listed action showing in screenshot of Alert Trend are out dated

## Expected:

![image](https://github.com/elastic/security-docs/assets/59917825/d5934644-da50-4982-83da-8d533e1d1c0e)

## Screen-Shot

<img width="957" alt="viz-options-menu-open" src="https://github.com/elastic/security-docs/assets/59917825/d920e0f3-d0fe-43c4-a1b5-3372d13ad2e0">

**Comment by nastasha-solomon** [comment]
Thanks for filing this @karanbirsingh-qasource! The docs are ready for review at https://github.com/elastic/staging-serverless-security-docs/pull/273 when you have a chance. Thanks!

**Comment by karanbirsingh-qasource** [comment]
Hi @nastasha-solomon thanks for the update.

the requested changes has been fixed now in shared preview so we are moving and closing this issue.
