### ISSUE TITLE
wrong internal side navigation in finding

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#3933]
## Description 

wrong internal side navigation in finding

## Screen-Shot

- Navigate to https://www.elastic.co/guide/en/security/8.10/es-ui-overview.html#_findings
- Observed that internal navigation showing behind the Finding screen-shot

## Screen-Shot

![image](https://github.com/elastic/security-docs/assets/59917825/a65fed35-585e-45a9-adc0-b27f90e2d12b)

**Comment by joepeeples** [comment]
Screenshots should not include side navigation or top header/toolbars. Please crop these UI elements out of the image.
