### ISSUE TITLE
Old Alert flyout in Suppress Alert Documentation

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#3936]
## Description 
Old Alert fly out in Suppress Alert Documentation

## Steps

- Navigate to https://www.elastic.co/guide/en/security/8.10/alert-suppression.html#_confirm_suppressed_alerts
- Scroll Down and check the Alert Flyout of insight section and observed that old alert fly out is showing

## Screen-Shot

![image](https://github.com/elastic/security-docs/assets/59917825/024ce073-f2ab-4a98-90ab-31ed281397dc)

**Comment by natasha-moore-elastic** [comment]
Closing this issue as it was resolved in https://github.com/elastic/security-docs/pull/3854.
