### ISSUE TITLE
[BUG] Only 03 types of the rule are showing under Define Rule for 'Create new rule tab'

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#394]
**Description**: Only 03 types of the rule are showing under Define Rule for 'Create new rule tab'

**Observation**: Old screenshot is displayed in the docs.

**URL link or topic name**: 
- [About building-block rules](https://www.elastic.co/guide/en/security/current/building-block-rule.html)

**Screenshots**:
- Screenshot in the doc:
![Doc_rules](https://user-images.githubusercontent.com/60252716/101127993-bb0f5980-3624-11eb-86ba-a2459d6c5f54.PNG)

- UI screenshot:
![UI_rules](https://user-images.githubusercontent.com/60252716/101128002-bc408680-3624-11eb-9724-ec2d8e9f3323.PNG)

**Comment by muskangulati-qasource** [comment]
@karanbirsingh-qasource, please review!!

**Comment by karanbirsingh-qasource** [comment]
Reviewed and assigned to @jmikell821

**Comment by jmikell821** [comment]
Fixed in #411.

**Comment by muskangulati-qasource** [comment]
Hi @jmikell821,

We validated this issue again and found that issue now **fixed**.

**Refer Screenshot**:
![394](https://user-images.githubusercontent.com/60252716/104013848-11e5f100-51d8-11eb-84a4-607f55d688b3.PNG)

Thanks!
