### ISSUE TITLE
[BUG] Old data sources drop-down information is displaying in doc under the Timeline schema

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#395]
**Description**: Old data sources drop-down information is displaying in doc under the Timeline schema

**Observation:** Old data sources drop-down information and old screenshot displayed in the docs.

**URL link or topic name:**
[Timeline schema](https://www.elastic.co/guide/en/security/current/timeline-object-schema.html#timeline-object-eventtype)

**Screenshots:**
**Doc Screenshots:**
![doc_screenshot](https://user-images.githubusercontent.com/61860752/101128965-b9469580-3626-11eb-9fd8-fb2367dc3b7a.png)

![event_type](https://user-images.githubusercontent.com/61860752/101129044-e1ce8f80-3626-11eb-9c00-4e8f9ebb05b5.jpg)

**UI Screenshot:**
![all_data_sources](https://user-images.githubusercontent.com/61860752/101129060-ea26ca80-3626-11eb-979c-4f000fb87176.jpg)

**Comment by deepikakeshav-qasource** [comment]
@karanbirsingh-qasource Please review

**Comment by karanbirsingh-qasource** [comment]
Reviewed and assigned to @jmikell821
