### ISSUE TITLE
Users can view documentation of the new Entity Risk Scoring engine within Elastic Security Solution documentation page

### ISSUE THREAD

**Issue by SourinPaul** [elastic/security-docs#3957]
## Description 

Elastic SIEM is releasing a new [Entity Risk Scoring engine](https://github.com/elastic/security-team/issues/4211) in 8.11. This will replace the current risk-scoring capabilities available to our users. 

This issue will reconcile and give structure to all related Entity Risk Scoring within [Elastic Security Solution documentation](https://www.elastic.co/guide/en/security/current/index.html).

## Existing Documentation References:
[Legacy Host docs:](https://www.elastic.co/guide/en/security/8.9/host-risk-score.html)
[Legacy User docs:](https://www.elastic.co/guide/en/security/8.9/user-risk-score.html)

### Related Issues:
- [Master Epic for 8.11](https://github.com/elastic/security-team/issues/4211)
- [In product Documentation Epic](https://github.com/elastic/security-team/issues/5604)

## Acceptance Test Criteria

As an end user, I want to:
- View and navigate all related Advanced Entity Analytics capabilities in a centralized place so that I can familiarize myself with the various features available. 
- Learn the latest Entity Risk Scoring features like User and Host Risk Scoring
  - Learn how to enable the feature in my environment
- (Optional for 8.11) Learn of Advanced Analytics capability
- View current (aka. legacy) risk scoring capabilities.
- Learn how to migrate from the legacy scoring feature to the new risk scoring engine.
- View FAQs

## Documentation Tasks:

- [x] Build a new navigation and structure for Advanced Entity Analytics -TBD @SourinPaul will share the initial draft
- [x] Build new documentation pages to cover ACs (see above)
~~Move legacy documentation pages (see existing documentation references above) from the `Technical Preview` section to this new navigation~~

# Engineering Resources:

## Collaborators:
- @nkhristinin 
- @rylnd 
- @machadoum 

## Related PRs:
- TBD

## Notes (TBD)
- Be sure to add any necessary screenshots, code text or console commands for clarity. 
- Include any conditions or caveats that may affect customers.

```[tasklist]
### Documentation Index
- [x] Prerequisites - Recommendation for ESS Cluster Configuration
- [x] Prerequisites - Required Roles and Privileges - ESS & Serverless
- [ ] Entity Risk Scoring Algorithm
- [x] Getting Started - How to Enable Risk Scoring
- [x] Getting Started - Migrating from Legacy Risk Scoring Engine
- [x] Viewing Entity Risk - Triage & Entity Pages
- [x] Viewing Entity Risk (Subsection) - Who can view risk score (kibana_system user constraints)
- [x] Internal (Not Public) - KB to update Risk Engine configurations in 8.11
- [ ] Restructuring advanced analytics https://github.com/elastic/security-docs/issues/4227
```

**Comment by nastasha-solomon** [comment]
Notes from 8.11 Detection Engine feature sync: https://docs.google.com/document/d/1RCZLW28YKfcrAWUkJKaQVsnNqmQlFprijvR4VQ0nwH8/edit?usp=sharing

**Comment by nastasha-solomon** [comment]
@benironside is leading the copy review for this feature. https://github.com/elastic/security-docs/issues/4032 is tracking the copy review.

**Comment by oatkiller** [comment]
cc: @SourinPaul 

Are we planning to document the limitation where we calculate risk scores using the Kibana internal users?

**Comment by SourinPaul** [comment]
> Are we planning to document the limitation where we calculate risk scores using the Kibana internal users?

Yes, @oatkiller. 

My current proposal is to capture this under `Viewing Entity Risk (Subsection) - Who can view risk score (kibana_system user constraints)`

**Comment by SourinPaul** [comment]
I am closing this issue to mark the completion of the 8.11 work. 

We will continue working on restructuring anomaly detection pages in https://github.com/elastic/security-docs/issues/4227
