### ISSUE TITLE
[BUG] 'Ingest Management' link is displayed in Docs on 'Fleet settings in Kibana' page

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/security-docs#396]
**Description**: 'Ingest Management' link is displayed on 'Fleet settings in Kibana' page

**Observation**: Ingest Management is renamed to Fleet in 7.10.1 as per [#83358](https://github.com/elastic/kibana/pull/83358) ticket

**URL link or topic name**: [Fleet settings in Kibana](https://www.elastic.co/guide/en/kibana/current/fleet-settings-kb.html)

**Screenshot in doc:** 
![Link_rename_issue](https://user-images.githubusercontent.com/72375798/101148868-287eb280-3644-11eb-86cd-00674c6b7444.jpg)

**Comment by rahulgupta-qasource** [comment]
Reviewed and assigned to @EricDavisX and @dedemorton

**Comment by EricDavisX** [comment]
nice find, thanks team.

**Comment by dedemorton** [comment]
Thanks for catching this. Fixed in https://github.com/elastic/kibana/pull/85083.

**Comment by dikshachauhan-qasource** [comment]
Hi @dedemorton 

Thank you for the update.
We have re-validated the same and added our observation comments to [#85083](https://github.com/elastic/kibana/pull/85083).

Please let us know if anything else is required from our side.
