### ISSUE TITLE
[DOCS] Update Rule Details page screenshots in the docs

### ISSUE THREAD

**Issue by nikitaindik** [elastic/security-docs#3970]
**Related PR: https://github.com/elastic/kibana/pull/166158**

## Description 
We are a going to merge a [PR](https://github.com/elastic/kibana/pull/166158) that would: 
 - rename "Data view" to "Data view ID" on the Rule Details page and in prebuilt rule flyout ([issue](https://github.com/elastic/kibana/issues/166650))
 - rename "Custom query" to "EQL query" for EQL rules on the Rule Details page and in prebuilt rule flyout ([issue](https://github.com/elastic/kibana/issues/164962))

We might want to sync screenshots in the docs.

### Data view changes
**Before (custom ID specified)**
<img width="656" alt="Screenshot 2023-09-19 at 17 12 08" src="https://github.com/elastic/security-docs/assets/15949146/2ad2c6c7-0f95-48a0-bb48-797395b71a82">

**After (custom ID specified)**
<img width="654" alt="Screenshot 2023-09-19 at 17 06 27" src="https://github.com/elastic/security-docs/assets/15949146/99b2aaf4-d175-476b-9327-783e81db2788">

**After (default auto-generated ID)**
<img width="659" alt="Screenshot 2023-09-19 at 17 06 06" src="https://github.com/elastic/security-docs/assets/15949146/2527648c-2446-4364-86ac-c0f459ca5a1f">

### EQL query changes
**Before**
<img width="654" alt="Screenshot 2023-09-19 at 17 31 20" src="https://github.com/elastic/security-docs/assets/15949146/62f038f9-2adc-4d8b-899b-2123bbec4f04">

**After**
<img width="653" alt="Screenshot 2023-09-19 at 17 30 49" src="https://github.com/elastic/security-docs/assets/15949146/a7688264-419f-42c5-98c4-823aeaa99673">

**Comment by banderror** [comment]
@elastic/security-docs Should we close this one?

**Comment by nastasha-solomon** [comment]
Thanks for following up on this, @banderror! 

Related question: do you want https://github.com/elastic/kibana/pull/166158 release-noted for 8.11? It's currently labeled to be skipped for release notes, so just double-checking here.

**Comment by nastasha-solomon** [comment]
@banderror we're good to close this for now because it doesn't require any immediate doc updates in 8.11.

**Comment by banderror** [comment]
> Related question: do you want https://github.com/elastic/kibana/pull/166158 release-noted for 8.11? It's currently labeled to be skipped for release notes, so just double-checking here.

@nastasha-solomon I'm fine with skipping and not mentioning this one in the release notes, because mainly it's a refactoring PR. It fixed two super-minor bugs, which were about changing some UI labels, and I'm not sure adding such small adjustments to the release notes would be useful for our users. Not a strong opinion though.

> we're good to close this for now because it doesn't require any immediate doc updates in 8.11.

Great! Thank you for your response!
