### ISSUE TITLE
Expandable alerts flyout new empty state messages

### ISSUE THREAD

**Issue by christineweng** [elastic/security-docs#3986]
## Description 

A few sections in the new expandable alerts flyout were missing empty state.error messages. Requesting a copy review on the following:

## Right section
1. **Overview -> About -> Rule description**: "There is no rule description for this rule."

![image](https://github.com/elastic/security-docs/assets/18648970/6a8341a6-4a1d-49d7-8b77-f717671b8f38)

2. **Overview -> About -> Alert Reason**: "There is no alert reason for this alert."

![image](https://github.com/elastic/security-docs/assets/18648970/b558da3c-9bbd-4efe-9445-30c3cc36f4a0)

3. **Overview -> About -> Investigation -> Highlighted Fields**: "There are no highlighted fields for this alert."

![image](https://github.com/elastic/security-docs/assets/18648970/1e1dbdb0-abed-46de-aa7b-7b05c0461137)

https://github.com/elastic/kibana/pull/166939

**Comment by nastasha-solomon** [comment]
Thanks for filing this, @christineweng! I'll take a look at this today or tomorrow and return suggestions ASAP.

**Comment by christineweng** [comment]
@nastasha-solomon here is one more, I added a error message for analyzer preview to stay consistent with analyzer graph.

@PhilippeOberti suggested "Error loading analyzer data". wdyt?

![image](https://github.com/elastic/security-docs/assets/18648970/8aa89f69-5b3e-4499-9f3a-4919919f6fc9)

**Comment by nastasha-solomon** [comment]
Hey, @christineweng - couple questions to help me better understand the context of these UI messages (and apologies if any of these are ignorant questions):

- Is it possible for users to create a rule without a description? AFAIK, the description is mandatory for all rule types and users can't complete the rule creation flow without filling out mandatory fields.  
- Are there scenarios where alerts wouldn't have a reason/source event or any sort of highlighted fields? The current messages look ok, but I'm wondering if we need to be more descriptive about the "why".
- In what scenario would users see the error message for analyzer?

**Comment by PhilippeOberti** [comment]
Answer for the first 2 points:
> * Is it possible for users to create a rule without a description? AFAIK, the description is mandatory for all rule types and users can't complete the rule creation flow without filling out mandatory fields.
Like you said, this should never happen, but we're putting safeguards in the code just in case something goes wrong as good practice.

> * Are there scenarios where alerts wouldn't have a reason/source event or any sort of highlighted fields? The current messages look ok, but I'm wondering if we need to be more descriptive about the "why".
Same here, I feel like these situations should never (or extremely rarely) happen, but just safeguarding the code just in case...

**Comment by christineweng** [comment]
Like @PhilippeOberti said this is mostly for safeguarding, if a user creates the rule in kibana, an alert should always have description and highlighted fields etc.

The only case I can think of is perhaps corruption in the data, or migrating from old alerts? i was able to recreate some edge cases by manually injecting alerts

![image](https://github.com/elastic/security-docs/assets/18648970/d22ec92a-eee0-4c5f-b782-969f67b24f25)

**Comment by nastasha-solomon** [comment]
@christineweng the current messages look great! Just made some minor adjustments to cut down on repetitiveness. 

1. Overview -> About -> Rule description: There's no description for this rule. 

2. Overview -> About -> Alert Reason: There's no source event information for this alert.    
 
3. Overview -> About -> Investigation -> Highlighted Fields: There's no highlighted fields for this alert. 

4. Error message for analyzer preview -> An error is preventing this alert from being analyzed.

**Comment by nastasha-solomon** [comment]
@christineweng feel free to close this doc issue if you've implemented the copy. Ty!
