### ISSUE TITLE
[DE][Exceptions] Allow duplicate case sensitive values for match_any

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#3992]
## Description 

Exceptions are evaluated by the detection engine as case sensitive. This means that if a user is trying to match a value `FOO` and `foo`, they must add both cases in the exception for it to catch all scenarios. While this has been possible in the API, it has not been possible from the UI. The UI would show an error saying that that value had already been added and was a duplicate. 

## Acceptance Test Criteria

Update existing [docs](https://www.elastic.co/guide/en/security/master/add-exceptions.html) to note the UI change.

## Notes

- PR - https://github.com/elastic/kibana/pull/167208

**Comment by nastasha-solomon** [comment]
Verified with @yctercero that this change applies to both types of exceptions (regular and Endpoint) in classic and in Serverless. 

Serverless doc updates are at: https://github.com/elastic/staging-serverless-security-docs/pull/197.
