### ISSUE TITLE
[7.9] Elastic Endpoint - Onboarding

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#40]
## Description 
Elastic Endpoint Onboarding META ticket: https://github.com/elastic/endpoint-app-team/issues/16

This will outline the process of getting a user started with the Elastic Endpoint (installing Endpoint on the agent to get events flowing in the Security app). 

(It would be good to have "get started"/quick guide for this process as I think we'll want to link the user to the docs in the onboarding flow.)

Prerequisites
* An Elasticsearch cluster and Kibana (running version 7.9) with a basic license. 
* A user with the superuser role.
* Ingest Manager (and Fleet) enabled (ingest docs [here](https://www.elastic.co/guide/en/ingest-management/current/ingest-management-getting-started.html#enable-ingest-management ))
* OS support: [See Column B](https://docs.google.com/spreadsheets/d/1PuHAQFyUGvukfbGc_gRN-p9gaHvQ1bMWiP2pmp66jNc/edit#gid=0)

**Ingest Concepts:**

**Integration:** Ingest Manager provides integrations that bundle various assets needed to ingest and visualize data. See[ ingest docs](https://www.elastic.co/guide/en/ingest-management/7.8/ingest-management-overview.html#configuring-integrations) for more information. Note: this documention still references Data Source, which is a concept that will be removed in 7.9. Instead users will just see the word "Integration".

**Agent Configuration:** The Elastic Agent configuration allows you to add and use any number of integrations. You can apply the Elastic Agent configuration to multiple Agents, making it even easier to manage configuration at scale. Users may only add one instance of the Endpoint Security Integration to an Agent Configuration (so, if an Agent Configuration already has the Endpoint Integration associated with it, it cannot be added again). There is also one policy associated with an Endpoint Security integration (think of the Agent Configuration as an extension of Policy). 

Our onboarding flow takes users through the process of adding the Elastic Endpoint Integration to an Agent Configuration (the default, or one they create). These steps can be done in a different order if they go through Ingest directly (if you create an Agent Configuration first, you can add the Endpoint Security integration later. Or, if you start with the Endpoint Security integration, it will ask you which Agent Configuration to associate it with.)

After the integration is associated with the Agent Configuration, we automatically create a Policy for them. The policy is configured with "recommended" settings (Malware turned on and set to Prevent, and all event collection set to Yes).

The next step is to enroll the elastic agent on their hosts. We show the instructions in the UI for this (also, instructions are in ingest docs, see [here](https://www.elastic.co/guide/en/ingest-management/7.8/ingest-management-getting-started.html#install-run-elastic-agent)).

**Comment by jmikell821** [comment]
@caitlinbetz this onboarding process will likely be under a `Getting Started` menu option in our TOC.

**Comment by jmikell821** [comment]
Related to: https://github.com/elastic/endpoint-app-team/issues/586. Let's make sure we include the caveats and notes listed on this issue.
