### ISSUE TITLE
Malware User Notification & Customization[DOCS]

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#403]
## Description 

*Background*
A policy administrator may want to configure their security policy to alert an end-user (or user of the host) that malware has been detected or prevented on their workstation.

The policy admin should be able to configure the policy to 1.) inform the end host-user that malware has been detected/prevented 2.) if desired, configure the notification to provide user with next steps.

## Acceptance Test Criteria
**Licensing**
Malware notification
* The "Notify User" checkbox is available to all users regardless of tier 

Notification customization:
* If users are at the Basic or Gold tiers, additional malware customization options will not be visible
* If the user is at the correct tier (Platinum or Enterprise), then the feature will be enabled/visible as normal

AC:
Notification:
* If Malware is set to Prevent: User notification is selected by default. User is able to deselect if desired.
* If Malware is set to Detect: User notification is deselected by default. User is able to select if desired.
* If Malware is turned off entirely, notification option is disabled (User notification will be false when sent to Endpoint)

Customization:
* Under the Malware section of policy, users can see a text box when the "Notify User" checkbox is selected
* If Notify User is deselected, the text box is no longer available
* The default text for the notification is: "Elastic Security { action } { filename }"
* Bracketed tags can be used to dynamically populate the applicable action (prevented or detected) and the filename that has been prevented or detected. For example, Elastic Security detected malwarefile.exe (where _detected_ is the {action} and _malwarefile.exe_ is the {filename})

Example notification on host:
![image (35)](https://user-images.githubusercontent.com/26076500/101818793-5bb4bc00-3af2-11eb-8f04-044f322a90c5.png)

**Comment by jmikell821** [comment]
#465 merged.
