### ISSUE TITLE
Rename AI connector from "Generative AI" to "OpenAI"

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#4040]
## Description 

The existing "Generative AI" connector is now called "OpenAI" and is specific to that particular provider. There is also now a connector type for "Generative AI," which includes OpenAI and Amazon Bedrock (refer to #4031 for this new connector).

## Notes

- Since we don't typically document the connectors themselves, we'll just need to update any references to them and screenshots in the AI Assistant docs.

**Comment by benironside** [comment]
task complete
