### ISSUE TITLE
Trusted Apps by Signer[DOCS]

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#406]
## Description 

In addition to Path and Hash (already documented), we've added the ability to add Trusted Applications by Signer.

## Acceptance Test Criteria

- Signer is an available field in Trusted apps create flow
- Signer is only available when Windows is selected
- Signer is a text field
- If user changes to a different OS from Windows and they have a Signer field, it is removed and NOT preserved
- If user changes to a different OS from Windows, signer is no longer available in the dropdowns
- If user changes to Windows from another OS, signer is added to available fields in dropdowns

**Comment by jmikell821** [comment]
Merged #484.
