### ISSUE TITLE
Setting up references to and release-noting ES|QL features in Security

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#4066]
## Description 

One or two weeks before 8.11 GA's, we'll need to revisit the following topics with @abdonpijpelink:
- **Linking to ES|QL Security docs from the core ES|QL docs**: In 8.11, the Security docs team is documenting new ES|QL functionality in Timeline, rules, and the Elastic AI Assistant. We might need to set up references to this content from the core ES|QL docs. The linking strategy is TBD. 
- **Release-noting ES|QL functionality in ES and Security**: How, and where, do we want to release-note ES|QL features, bug fixes, etc. for 8.11 and onward?

## Notes

- We can discuss these topics over Zoom or meet asynchronously in Slack/GH.

**Comment by nastasha-solomon** [comment]
Decisions from today's meeting:

- **Linking to ES|QL Security docs from the core ES|QL docs:** @abdonpijpelink will add another overview page to the Using ES|QL section for Security. The new page will briefly describe ES|QL functionality in Security and then link off to the appropriate Security docs. @benironside and @nastasha-solomon will give Abdon our ES|QL doc PRs and review the new page once it's ready.
- **Release-noting ES|QL functionality in ES and Security:** 
  - For **8.11**, @abdonpijpelink will summarize Security's ES|QL functionality in Elasticsearch's [What's new in 8.11](https://www.elastic.co/guide/en/elasticsearch/reference/8.11/release-highlights.html#es_ql_new_query_language_for_flexible_iterative_analytics_in_technical_preview). The summary will provide a link to Security's [What's new in 8.11](https://www.elastic.co/guide/en/security/master/whats-new.html) page, which will offer more detail about ES|QL features in 8.11. 
  - If Ben or Nastasha come across any ES|QL known issues or limitations, they should ping Abdon so he can add the necessary info to the [ES|QL limitations](https://www.elastic.co/guide/en/elasticsearch/reference/8.11/esql-limitations.html) page. 
  - For release highlights in 8.12 and onward, it might be less vital to mention ES|QL Security functionality in the ES release highlights. We can revisit this topic come 8.12. 
  
cc: @elastic/security-docs

**Comment by abdonpijpelink** [comment]
PR to add a summary of ES|QL functionality in Security to the Elasticsearch docs: https://github.com/elastic/elasticsearch/pull/101677

**Comment by nastasha-solomon** [comment]
PR that references Elastic Security's "What's new" page: https://github.com/elastic/elasticsearch/pull/101818
