### ISSUE TITLE
Register as AntiVirus [DOCS]

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#407]
## Description 
Users can toggle on the "Registered AntiVirus" option in their policy. 

## Acceptance Test Criteria

- Users can set Registered as AV via Policy
- Registered as AV is supported by 7.10+ Agents
- Windows only
- This config option is Basic license, NOT a tiered feature
- Turning this on will register Elastic Security as the AV solution in windows OS, and will disable windows defender

![image](https://user-images.githubusercontent.com/26076500/101825988-62e0c780-3afc-11eb-81ce-05422a9ac829.png)

**Comment by DonNateR** [comment]
PR merged. Closing this issue now.
