### ISSUE TITLE
[Docs][Rules] Remove custom highlighted fields params from Rule Creation API Docs in 8.10

### ISSUE THREAD

**Issue by peluja1012** [elastic/security-docs#4082]
## Description 

In https://github.com/elastic/security-docs/pull/3852, we added an API param (`investigation_fields`) to the docs to configure rule custom highlighted fields. We recently realized that we introduced a [breaking change](https://github.com/elastic/dev/issues/2385) upon upgrade to 8.11 related to this new parameter. In order to avoid more users being exposed to this issue, we would like to remove API docs referencing this new param. I believe this documentation is only present [here](https://www.elastic.co/guide/en/security/current/rules-api-create.html#opt-fields-all) (screenshot below). The request is to remove it from the **8.10** public user docs. Other docs related to custom highlighted fields usage in the UI can remain.

<img width="870" alt="image" src="https://github.com/elastic/security-docs/assets/616158/4ffe81c1-20be-4a85-a18e-e58250073136">

**Comment by nastasha-solomon** [comment]
Thanks for filing this, @peluja1012! Docs are updated at https://github.com/elastic/security-docs/pull/4085.

@yctercero @peluja1012 - if this issue with the `investigation_fields` needs to be doc'd as a breaking change in 8.11, can one of you drop the release notes summary as as comment in https://github.com/elastic/security-docs/issues/4015? TY!

**Comment by nastasha-solomon** [comment]
Closing this since merged https://github.com/elastic/security-docs/pull/4085.
