### ISSUE TITLE
[Doc] Incorrect EQL Query in Elastic Guide for Event Correlation Detection Rules

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#410]
**Describe the bug**
Incorrect EQL Query in Elastic Guide for Event Correlation Detection Rules

**Build Details:**
Version: 7.10

**Steps to Reproduce**
1. Navigate to Elastic Guide and go to Detection Rules > Event Correlation or navigate to this link
2. Observed that incorrect EQl query there in the Elastic Guide for Event Correlation Detection Rules. 

**Test-Data:**
https://www.elastic.co/guide/en/security/current/rules-ui-create.html#create-eql-rule

**Impacted Test case(s)**
N/A

**Actual Result**
back-quote **`** is there in end of EQL Query 
```
sequence by process.entity_id
  [process
    where event.type in ("start", "process_started")
    and process.name == "msxsl.exe"]
  [network
    where event.type == "connection"
    and process.name == "msxsl.exe"
    and network.direction == "outgoing"`
```

**Expected Result**
Square bracket  **]**   should be there in end of EQL Query
```
sequence by process.entity_id
  [process
    where event.type in ("start", "process_started")
    and process.name == "msxsl.exe"]
  [network
    where event.type == "connection"
    and process.name == "msxsl.exe"
    and network.direction == "outgoing"]

```
**What's Working**
- N/A

**What's not Working**
- N/A

**Screenshots**
- Actual : 
![image](https://user-images.githubusercontent.com/59917825/102209250-81790100-3ef6-11eb-9b1a-4ea9e434c74e.png)
- Expected:
![image](https://user-images.githubusercontent.com/59917825/102210004-a326b800-3ef7-11eb-9eec-4ddb58ed6e73.png)

**Logs**
N/A

**Comment by karanbirsingh-qasource** [comment]
@manishgupta-qasource Please review the issue.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by karanbirsingh-qasource** [comment]
Thanks for the Update . 

Issue is Fixed now .
![image](https://user-images.githubusercontent.com/59917825/103608467-6facdb80-4f41-11eb-8f0f-da645d376e4c.png)

thanks !!
