### ISSUE TITLE
Entity Analytics release notes

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#4109]
Using this issue to track release notes for Entity Analytics' new features, enhancements, or bug fixes for `8.11`.

**Comment by jmikell821** [comment]
@SourinPaul please add EA release notes here. Thanks!

**Comment by SourinPaul** [comment]
8.11.0:

- Introduces the New Entity Risk Scoring engine leveraging the SIEM Detection Engine to calculate host and user risk scores from the last 30 days. (readme [link to Docs])

8.11.1:
@machadoum @nikitaindik please list the bug fixes.

**Comment by jmikell821** [comment]
@SourinPaul we would need the relative Kibana PR link(s) -- we don't usually link to `readme` files in release notes. We'll also add this to what's new highlights.

**Comment by SourinPaul** [comment]
> we would need the relative Kibana PR link(s)

The new risk engine capability is spread over multiple PRs in 8.11. 

@jmikell821 What is your recommendation?
- Be comprehensive, and list the most relevant PRs
- List the top 3 PRs
- Not link any PRs

cc: @jaredburgettelastic

**Comment by nastasha-solomon** [comment]
Closing since the release notes were merged earlier this week: https://github.com/elastic/security-docs/pull/4095
