### ISSUE TITLE
[8.11.1] Entity Analytics dashboard updates 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#4118]
New EA dashboard updates in `8.11` include: 

- Time filter will work on risk panels (no direct UI updates)
- New column added to risk panels to capture when the entity risk was calculated last

@machadoum @SourinPaul can you please provide a server URL where we can see the changes as well as a PR link. If there are any other changes, please let us know.

**Comment by natasha-moore-elastic** [comment]
Screenshots to update:
- On [Entity Analytics dashboard](https://www.elastic.co/guide/en/security/current/detection-entity-dashboard.html):
    - [ ] https://www.elastic.co/guide/en/security/current/images/entity-dashboard.png
    - [ ] https://www.elastic.co/guide/en/security/current/images/host-score-data.png
    - [ ] https://www.elastic.co/guide/en/security/current/images/user-score-data.png 
		 
- On [View and analyze risk score data](https://www.elastic.co/guide/en/security/current/analyze-risk-score-data.html):
    - [ ] https://www.elastic.co/guide/en/security/current/images/ea-dashboard.png
    - [ ] https://www.elastic.co/guide/en/security/current/images/hosts-hr-data.png 

- On [Host risk score](https://www.elastic.co/guide/en/security/current/host-risk-score.html): 
    - [ ] https://www.elastic.co/guide/en/security/current/images/hosts-by-risk-tab.png
- On [User risk score](https://www.elastic.co/guide/en/security/current/user-risk-score.html):
    - [ ] https://www.elastic.co/guide/en/security/current/images/users-by-risk-details-page.png
