### ISSUE TITLE
[BUG] Document unsupported field types for threshold rule type `Group by` feature

### ISSUE THREAD

**Issue by dplumlee** [elastic/security-docs#4119]
Related tickets: https://github.com/elastic/kibana/issues/170168, https://github.com/elastic/sdh-security-team/issues/758 (internal)

We currently don't support nested field types for our threshold rule type's Group by feature but don't specify this in the UI or in the [documentation for threshold rules](https://www.elastic.co/guide/en/security/current/rules-ui-create.html#create-threshold-rule). We should add a clarification of this limitation until an enhancement is ever implemented down the line.

**Comment by 111andre111** [comment]
Not sure but would the syntax that is already built into Kibana help on the Threshold rules?
https://www.elastic.co/guide/en/kibana/8.10/kuery-query.html#_querying_nested_fields

Or would there be needed special work for that?
@dplumlee
