### ISSUE TITLE
Timeline autosave removed in favor of manual save

### ISSUE THREAD

**Issue by michaelolo24** [elastic/security-docs#4200]
## Description 

The auto-save feature in timeline was removed in favor of allowing users to manually save their timeline. Autosave, while useful, also led to users accidentally persisting changes to the timeline that they never wished to persist.

https://github.com/elastic/kibana/pull/169239

## Acceptance Test Criteria

- A guided tour should present notifying users of the change on initial load of timeline
- As a user when making changes in timeline it should no longer auto save. You can identify this by:
  - Open a new timeline
  - Save the timeline by clicking the save button
  - Make changes to the timeline
  - Note the `unsaved` label beside the title
  - Create a new timeline
  - Re-open the timeline that was previously saved
  - Note the final changes you made were not saved

- When a change is made within timeline the label of the timeline should change to 'unsaved'

- When a timeline is saved and re-opened the final saved changes should persist.

- Currently refreshing the page of an unsaved timeline will not keep your active changes. This is due to a bug surrounding localStorage, but will be fixed by: https://github.com/elastic/kibana/pull/170542
 

## Notes

- Add all appropriate labels to the issue, especially the version number label. 
- Be sure to add any necessary screenshots, code text or console commands for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by nastasha-solomon** [comment]
Update from talking to @michaelolo24 during today's TH sync: manual saving for Timeline will be pushed to the prod server next Wednesday (Nov. 15).

**Comment by nastasha-solomon** [comment]
Quick update: will need access to a Serverless project that has this feature available for testing and screenshots. 

The following pages need screenshot refreshes:
- https://docs.elastic.co/serverless/security/timelines-ui
- https://docs.elastic.co/serverless/security/timeline-templates-ui

**Comment by nastasha-solomon** [comment]
Notes to self:
- Still need to create a PR for the classic docs. 
- Once I create the classic docs PR, it might be prudent to wait til the 8.12 docs branch is created before merging the PR.

**Comment by nastasha-solomon** [comment]
Update from today's Timeline sync: Jatin's work doesn't present any functionality changes, but will require copy review. The associated issue and PR are incoming.

**Comment by nastasha-solomon** [comment]
Classic and serverless docs are done! 🏃🏼🏃🏼🏃🏼
