### ISSUE TITLE
[BUG] No mention of the new features for EDR for 8.11.0 under the docs of 8.11 release

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#4216]
**Description**: 
No mention of the new features for EDR for 8.11.0 under the docs of 8.11 release

**URL link or topic name**: 
https://www.elastic.co/guide/en/security/current/whats-new.html

**Screenshots**:
![image](https://github.com/elastic/security-docs/assets/60252716/cf0f3493-d25a-4126-bc58-2b5bdb40dde3)

**Feature ticket**
https://github.com/elastic/security-team/issues/3593
https://github.com/elastic/security-team/issues/6096

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821
