### ISSUE TITLE
[BUG] Screenshot needs to be updated to add 'Protection updates' tab under policy setting

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#4217]
**Description**: 
Screenshot needs to be updated to add 'Protection updates' tab under policy setting

**URL link or topic name**: 
https://www.elastic.co/guide/en/security/current/admin-page-ov.html#integration-policy-details

**Screenshots**:
- Actual
![2_Actual](https://github.com/elastic/security-docs/assets/60252716/2e11bd3a-cbbd-431a-a8d8-dde72754b0f4)

- Expected
![2_Expected](https://github.com/elastic/security-docs/assets/60252716/4beb0738-da91-4631-8c24-e80ff000fa20)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821
