### ISSUE TITLE
[BUG] Missing deployed version column under the Policy tab

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#4218]
**Description**: 
Missing deployed version column under the Policy tab

**URL link or topic name**: 
https://www.elastic.co/guide/en/security/8.11/policies-page-ov.html

**Screenshots**:
- Actual
![3_Actual](https://github.com/elastic/security-docs/assets/60252716/5187218d-85de-4f03-b59a-e7d15aba5e37)

- Expected
![3_Expected](https://github.com/elastic/security-docs/assets/60252716/ebe21562-4bd4-4094-8813-05d54cc38662)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821
