### ISSUE TITLE
[BUG] Field heading for the filter name should be consistent in the Event Filters fly out

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#4219]
**Description**: 
Field heading for the filter name should be consistent in the Event Filters fly out

**URL link or topic name**: 
https://www.elastic.co/guide/en/security/8.11/event-filters.html

**Screenshots**:
- Actual
![4_Actual](https://github.com/elastic/security-docs/assets/60252716/7542f9d3-465b-4aa3-bc6a-42218ed35184)

- Expected
![4_Expected](https://github.com/elastic/security-docs/assets/60252716/93252cd3-d193-44d5-9d75-59afe68a8481)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821
