### ISSUE TITLE
[Bug] API events information is not mentioned in the Docs

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#4220]
**Description**:
API events information is not mentioned in the Docs

**URL link or topic name**:
https://www.elastic.co/guide/en/security/8.11/es-overview.html#_elastic_security_components_and_workflow

**Screenshots**:
- Actual:

![image (7)](https://github.com/elastic/security-docs/assets/60252716/1eb4a2fe-7353-4a32-8c51-b9acbcdbec7f)

- Expected:

![image (6)](https://github.com/elastic/security-docs/assets/60252716/4e376294-839a-4152-9a19-70db86b1287d)

**Comment by natasha-moore-elastic** [comment]
Also to be updated: `event-collection.png` screenshot in [Event collection](https://www.elastic.co/guide/en/security/8.11/configure-endpoint-integration-policy.html#event-collection).
