### ISSUE TITLE
[Bug]Missing ES|QL query rule type in the screenshot

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#4222]
**Description**:
Missing ES|QL query rule type in the screenshot

**URL link or topic name**:
https://www.elastic.co/guide/en/security/8.11/rules-ui-create.html#preview-rules

**Screenshots**:
- Actual:

![image (7)](https://github.com/elastic/endgame-platform/assets/60252716/be465be7-f5ed-45c9-b6eb-1ac01991bf53)

- Expected:

![Expected](https://github.com/elastic/endgame-platform/assets/60252716/7ed6e5e6-2f2c-4daf-b2ee-5fb2a0f3ec49)

**Comment by nastasha-solomon** [comment]
Thanks for filing this, @karanbirsingh-qasource! The fix is ready at https://github.com/elastic/security-docs/pull/4497 when you have a chance to validate it.
