### ISSUE TITLE
What's new fixes

### ISSUE THREAD

**Issue by natasha-moore-elastic** [elastic/security-docs#4224]
Add a link to the [new risk engine docs](https://www.elastic.co/guide/en/security/current/advanced-entity-analytics-overview.html#entity-risk-scoring) from the [What's new in 8.11](https://www.elastic.co/guide/en/security/current/whats-new.html) page.

**Comment by jmikell821** [comment]
A few other things to fix:

- [ ] Update [Latest risk scoring engine](https://www.elastic.co/guide/en/security/current/whats-new.html#_latest_risk_scoring_engine) title to something more informative, e.g., `Latest entity risk scoring engine provides greater scalability and performance`
- [ ] Change [ES|QL rule type](https://www.elastic.co/guide/en/security/current/whats-new.html#_esql_rule_type) title to `Create ES|QL query detection rules with new ES|QL rule type`
- [ ] Change `ES|QL knowledge base` title to -> `New ES|QL knowledge base`. 
- [ ] Change [Exceptions enhancements](https://www.elastic.co/guide/en/security/current/whats-new.html#_exceptions_enhancements) title to -> `Case-sensitive values supported in rule exceptions`
- [ ] Delete the **[Access to host and user prevalence](https://www.elastic.co/guide/en/security/current/whats-new.html#_access_to_host_and_user_prevalence)** snippet - this isn't really an enhancement. 
- [ ] Change `ES|QL in Timeline` -> `Use ES|QL in Timeline`. There's also an extra `the` there. "To start using ES|QL, open the the ES|QL tab."
- [ ] Change `Cloud Security enhancements` -> `Expanded support for Cloud security posture management (CSPM)`
- [ ] In the [Connectors page renamed](https://www.elastic.co/guide/en/security/current/whats-new.html#_connectors_page_renamed) section, bold "Settings." 

Please resubmit for PR review when you're done, thanks!
