### ISSUE TITLE
[BUG] 8.11.0 release notes include links to private repository

### ISSUE THREAD

**Issue by ferullo** [elastic/security-docs#4247]
The last four 8.11.0 "New Features" release notes include links to the private endpoint-dev repo. Can we get those links removed? They aren't accessible by users so including them just adds confusion.

https://www.elastic.co/guide/en/security/current/release-notes-header-8.11.0.html#features-8.11.0

**Comment by nastasha-solomon** [comment]
Not a problem, @ferullo. I've filed https://github.com/elastic/security-docs/pull/4248 to remove the links.

**Comment by ferullo** [comment]
Thanks!
