### ISSUE TITLE
[Serverless][Advanced Settings] Document new serverless index validations

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#4266]
## Description 

In serverless, advanced settings will be restricted as follows:

- securitySolution:defaultIndex is limited to 50 
- securitySolution:defaultThreatIndex to 10 

The PR that applies this logic is here and does a great job describing the details and linking to the issue with even further details around the motivations for the change https://github.com/elastic/kibana/pull/170234

**Comment by joepeeples** [comment]
This is being documented as part of:
- meta — https://github.com/elastic/staging-serverless-security-docs/issues/95
- PR — https://github.com/elastic/security-docs/pull/4362

**Comment by joepeeples** [comment]
Documented in https://github.com/elastic/staging-serverless-security-docs/pull/213
