### ISSUE TITLE
[DOCS] Self protection overview

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#428]
Document an overview topic about self protection. Might be a good idea to place it in this [ES Overview section](https://www.elastic.co/guide/en/security/current/es-overview.html#_additional_elastic_endpoint_security_information) and expand. 

Summary and related issue is here: https://github.com/elastic/endpoint-dev/issues/8195

**Comment by jmikell821** [comment]
@DonNateR what are your thoughts on where to place this? See my initial comment above.

**Comment by DonNateR** [comment]
@jmikell821: I think this makes sense for now... Though it might be smart to have a general "Protections Overview" that also covers malware protection. To that end, what is the distinction between malware protection and "self" protection? Is malware a more specific type of protection?

**Comment by jmikell821** [comment]
> @jmikell821: I think this makes sense for now... Though it might be smart to have a general "Protections Overview" that also covers malware protection. To that end, what is the distinction between malware protection and "self" protection? Is malware a more specific type of protection?

Great question! Dan answered my question about having a Protections Overview in [this comment](https://github.com/elastic/endpoint-dev/issues/8195#issuecomment-754171689). There is a difference between the two. Self protection is described as this: 

> "Self Protection means that Endpoint has guards against users and attackers interfering with Endpoint's functionality. Over time we'll build these guards out to further prevent users/attackers from interfering with Endpoint. This is a never ending task; there's always another thing to protect against."

**Comment by jmikell821** [comment]
Merged #476.
