### ISSUE TITLE
[DOCS] Detections Migration API

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#430]
[This topic](https://www.elastic.co/guide/en/security/current/post-upgrade-req.html) needs to be updated to include new reqs. 

Related issue: https://github.com/elastic/security-team/issues/204

**Comment by DonNateR** [comment]
I believe this card will be taken care of by resolving issue #408, @jmikell821. Would you like me to assign this to myself?

**Comment by jmikell821** [comment]
@DonNateR we have PR #435 open, but let me double check to make sure there's nothing else that needs to be added regarding this topic. We probably also need to move this to "System Reqs" - it hanging out at the bottom like that is kind of strange.
