### ISSUE TITLE
[Detection Engine][AI Assistant] Add documentation for new AI Assistant prompt on DE errors

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#4300]
## Description 

Issue - https://github.com/elastic/security-team/issues/7666
PR - https://github.com/elastic/kibana/pull/166778  

A button will now appear when a rule warning or error is displayed in the rule details page allowing users to prompt the AI Assistant for help in resolving or understanding the problem.

## Notes

- All the same requirements that hold for the AI Assistant exist here as well:
  - Assistant needs to be enabled in order for users to see this
  - Feature is in beta (I believe overall AI features remain in beta in security?)

**Comment by benironside** [comment]
Planned for release notes only
