### ISSUE TITLE
[Entity Analytics] Update Risk Scoring Prerequisites documentation

### ISSUE THREAD

**Issue by hop-dev** [elastic/security-docs#4307]
## Description 

There are a couple of changes we need to the documentation at https://www.elastic.co/guide/en/security/current/ers-requirements.html

### 1. Remove the bullet point  "All for the Saved Objects Management feature under Management" 

We have found that this privilege is not required for the risk engine so can be removed from the docs 

<img width="673" alt="Screenshot 2023-11-21 at 15 02 27" src="https://github.com/elastic/security-docs/assets/3315046/5140b084-b1e2-45e2-9ca3-48a9903cf4ce">

### 2. Tell users the serverless roles needed for risk scoring.

We now have a new privileges callout which will tell users if they do not have privileges for risk scoring, it links to these docs:

<img width="804" alt="Screenshot 2023-11-21 at 12 52 21" src="https://github.com/elastic/security-docs/assets/3315046/68cce4e8-7c35-40f3-8c50-5f35d418539f">

We want to help serverless users to know which roles will give them these privileges, this is the situation as the roles stand today:

| Role               | Can enable the risk engine?  | Can view risk scores? | Can Disable the risk engine? |
|--------------------|------------------------------|-----------------------|------------------------------|
| Platform engineer  | ✅                       | ✅               | ✅                      |
| Detections admin   | ✅                      | ✅               | ✅                      |
| Admin              |✅                      |✅              | ✅                      |
| all roles          | :x:                          | ✅               | :x:                          |

I'm not saying this is the best way to present the information in the docs, just that we need to inform the user that they need to grant one of the 3 roles in order to enable/disable the risk engine.

I am also not sure if the current page is the right place for this information? If it was put in a different place we would add another link to the UI callout.

**Comment by SourinPaul** [comment]
@natasha-moore-elastic, let's account for this as part of the post-8.11 EA documentation updates #4227. 

Thanks!

**Comment by natasha-moore-elastic** [comment]
Hi @hop-dev & @SourinPaul, thanks for raising this! 
Point 1 is an easy fix – I'll add that to the post-8.11 work.
Regarding the 2nd point (Tell users the serverless roles needed for risk scoring): We have separate documentation sets for ESS docs and serverless docs. We currently have the new risk scoring documentation published only in the ESS docs set. The plan was to complete all the 8.11 work in ESS docs, then publish everything in serverless docs. That's where we will then define all the serverless-specific requirements.
cc @jmikell821

**Comment by hop-dev** [comment]
Great thanks @natasha-moore-elastic, let me know if you need anything more from me. 

@SourinPaul the callout is behind a feature flag at the moment, would we only want to enable it once this documentation is added?

**Comment by hop-dev** [comment]
> @SourinPaul the callout is behind a feature flag at the moment, would we only want to enable it once this documentation is added?

Just re-raising this

**Comment by SourinPaul** [comment]
> @SourinPaul the callout is behind a feature flag at the moment, would we only want to enable it once this documentation is added?

@hop-dev, we do not gate features that are pending documentation. Rather track a documentation task to complete the pending work, which we have here. Please remove the feature flag.

🙏 for reflagging.

**Comment by hop-dev** [comment]
Awesome thanks for the quick reply 👍
