### ISSUE TITLE
[DOCS] Updates to rule actions API 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#434]
Hey there @cnasikas! I have a feeling the [Rules API page](https://www.elastic.co/guide/en/security/current/rules-api-create.html#rules-api-create) is extremely outdated and I wanted to check with you to ensure we get whatever new API updates and fixes to the existing get pulled in for 7.11. I'll start making syntax changes (updating the language, e.g., `threat match` > `indicator match`) but I'd appreciate your help with this one. Let's sync if you have a moment. Thank you!

**Comment by cnasikas** [comment]
Hey @jmikell821! I think is better to reach out the @elastic/security-detections-response team for that as my knowledge around detection engine is limited.

**Comment by jmikell821** [comment]
PR #522.
