### ISSUE TITLE
[DOCS] List of API changes for 7.11 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#440]
**Cases**

https://github.com/elastic/kibana/pull/82715 - Create comment types. 
https://github.com/elastic/kibana/pull/84731 - Sync cases with alerts. 
https://github.com/elastic/kibana/pull/84321 - A new status was added for cases called in-progress.
https://github.com/elastic/kibana/pull/84587 - Move mappings from actions to cases.
https://github.com/elastic/kibana/pull/82519 - New action subactions.

UI changes:
https://github.com/elastic/kibana/pull/82996 - You can attach an alert to a case from the detections page
https://github.com/elastic/kibana/pull/84731 - Sync alerts toggle switch.
https://github.com/elastic/kibana/pull/84450 - Alerts comment UI

**Comment by DonNateR** [comment]
- [ ] Update screenshots in the cases documentation.
- [ ] Ensure that the cases documentation covers how comments work.
