### ISSUE TITLE
[enhancement]: Cloud Security 8.12 documentation 

### ISSUE THREAD

**Issue by tinnytintin10** [elastic/security-docs#4440]
### Description

The cloud security team is introducing several additions/changes in the 8.12 release. We want our documentation to reflect these additions and updates. Here are epics that track the work done:

1. https://github.com/elastic/security-team/issues/7621
2. https://github.com/elastic/security-team/issues/7352
3. https://github.com/elastic/security-team/issues/7616

### Related links / assets

Please include each of the following, if applicable:
Doc URL: https://www.elastic.co/guide/en/security/current/cspm.html
Subject matter expert: @tinnytintin10 @smriti0321 
Figma link(s): (within epic links below)
Github epic link(s): 1) https://github.com/elastic/security-team/issues/7621 2) https://github.com/elastic/security-team/issues/7352 3) https://github.com/elastic/security-team/issues/7616
Github issue link(s):

### Which documentation set needs improvement?

ESS and serverless

### Software version

8.12+

### Collaborators

PM: @tinnytintin10 
Designer: @r4zr32d3k1l @einatjacoby 
Developer: @tehilashn @oren-zohar @kfirpeled 
Others (if applicable): @snehsach19 @nick-alayil @smriti0321 

### Timeline / deliverables

Ideally, these updates should be ready for the 8.12 release.

**Comment by tinnytintin10** [comment]
Here ya go @benironside! I have added you to the relevant channels for the work above. Will begin working with the relevant devs to start generating some content for ya.

**Comment by tinnytintin10** [comment]
cc @smriti0321

**Comment by orestisfl** [comment]
# Additional instructions for deploying to Azure Management Groups

Prerequisites: To setup CSPM for an Azure Management Group, you'll need admin access to that group. Specifically, you need to have the `Microsoft.Authorization/roleAssignments/write` permission to create `Reader` role assignments at the Management Group scope. You additionally need to [Elevate access to manage all Azure subscriptions and management groups](https://learn.microsoft.com/en-us/azure/role-based-access-control/elevate-access-global-admin).

## Add your CSPM integration

Make sure to select the `Azure Organization` option in the setup steps.

## ARM template setup (recommended)

Prerequisites: To deploy the ARM template, you need additional admin privileges for the subscription you'll use to deploy the Elastic Agent to.

Open the ARM template when prompted. There, select the management group you want to scan on the drop-down element. For the Subscription Id field go to the [Subscriptions](https://portal.azure.com/#view/Microsoft_Azure_Billing/SubscriptionsBladeV2) page and select the subscription ID that you want to deploy to. This subscription will be used to deploy a VM with the Elastic Agent.

**Comment by moukoublen** [comment]
# Azure Manual onboarding flow

## Add your CSPM integration
In **Setup Access** make sure you select **Manual** then you will have three options in **Preferred manual method** drop box. 
  * Managed Identity
  * Service principal with Client Secret
  * Service principal with Client Certificate

### Managed Identity
For this option, you must ensure the agent is deployed on a resource supporting managed identities (e.g., Azure Virtual Machines). No explicit credentials need to be provided; Azure handles the authentication.

Read the [documentation](https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/) for more details

### Service principal with Client Secret
For this option, you must fill in three pieces of information: client ID, tenant ID, and client secret. 

To retrieve these pieces of information, you need to create an **App Registration** on Azure. You can get client ID and tenant ID from the **Overview > Essentials** tab.
<img width="592" alt="Screenshot 2023-12-22 at 12 17 03 PM" src="https://github.com/elastic/security-docs/assets/1380039/e9208ad3-60c7-4b25-aab5-88eb1fc42a1d">

To create a client secret you have to navigate to **Certificates & Secrets** tab, then, on **Client secrets** tab you can click on **New client secret**, 
<img width="1160" alt="Screenshot 2023-12-22 at 12 45 28 PM" src="https://github.com/elastic/security-docs/assets/1380039/b69fd78e-9ec9-4129-ae52-7aa6a5aec597">

Read the [documentation](https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-register-app) for more details. 

### Service principal with Client Certificate
For this option, you must fill in three pieces of information and an optional one: client ID, tenant ID, client certificate path, and client certificate password (optional).

The **Client Certificate Path** must be the path inside the vm that Cloudbeat should find the certificate. 

To retrieve these pieces of information, you need to create an **App Registration** on Azure. You can get client ID and tenant ID from the **Overview > Essentials** tab.

To upload a client certificate you have to navigate to **Certificates & Secrets** tab, then, on **Certificates** tab you can click on **Upload certificate**, 
<img width="1113" alt="Screenshot 2023-12-22 at 12 45 20 PM" src="https://github.com/elastic/security-docs/assets/1380039/49facf32-3752-450e-b6bc-6958b7d5d333">


**Note about certificate formats**: The **PEM** format must be used for password-free certificates. For password-protected certificates, the **PKCS12** format must be used. 

Example of creating certificates (but not limited to):
**PEM password-free format**
```bash
# Generate csr and key
openssl req -new -newkey rsa:4096 -nodes -keyout cert.key -out cert.csr

# generate PEM and self-sign with key
openssl x509 -req -sha256 -days 365 -in cert.csr -signkey cert.key -out signed.pem

# crete bundle
cat cert.key > bundle.pem
cat signed.pem >> bundle.pem
```
Upload to azure: `signed.pem` 
Upload to VM that hosts Cloudbeat: `bundle.pem`

**PKCS12 password-protected format**
```bash
# create pem
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes

# create pkcs12 bundle using legacy flag (cli will ask for export password)
openssl pkcs12 -legacy -export -out bundle.p12 -inkey key.pem -in cert.pem
```
Upload to azure: `cert.pem` 
Upload to VM that hosts Cloudbeat: `bundle.p12`

**Comment by benironside** [comment]
complete
