### ISSUE TITLE
[DOCS] Document Detection Engine compatibility with Cold Tier storage and Searchable Snapshots

### ISSUE THREAD

**Issue by peluja1012** [elastic/security-docs#446]
Cold tier storage is also going GA in 7.11. Our users may end up running Detection Engine rules with data stored in this tier. We need to provide documentation that summarizes the Detection Engine's compatibility with Cold Tier storage. More details in this [ticket](https://github.com/elastic/security-team/issues/672).

The guidance we would like to document is below (more background [here](https://github.com/elastic/security-team/issues/672#issuecomment-756387528)):
- The security solution supports cold-tier data for the following Elasticsearch indices:

  - index patterns specified in securitySolution:defaultIndex
  - index patterns specified in the definitions of detection rules
  - index patterns specified in the data sources selector on the various security app pages

- The security solution does NOT support cold-tier data for the following Elasticsearch indices:
  - index patterns controlled by the Security solution, including signals and list indices
  - index patterns specified in Indicator Match rules as indicator index patterns

**Comment by jmikell821** [comment]
Merged #487.
