### ISSUE TITLE
[enhancement]: `elastic-endpoint top` command section to troubleshooting

### ISSUE THREAD

**Issue by 111andre111** [elastic/security-docs#4478]
### Description

What: we could move `elastic-endpoint top` command to troubleshooting section

### Related links / assets

Please include each of the following, if applicable:
Doc URL: https://www.elastic.co/guide/en/security/8.11/ts-management.html
Github source URL: https://github.com/elastic/endpoint/blob/main/EndpointTopCommand.md

### Which documentation set needs improvement?

ESS and serverless

### Software version

The functionality has been introduced in 8.10 I think so I would opt for a backport.

### Collaborators

PM: @nfritts 

### Timeline / deliverables

It would be good to get this into the docs middle priority. It would help us mitigate probably some SDHes.

**Comment by natasha-moore-elastic** [comment]
Hi @111andre111 , @caitlinbetz 
There's a related issue that @nfritts raised [here](https://github.com/elastic/security-docs/issues/5097).  @jmikell821 and I discussed both issues with @roxana-gheorghe and decided to move forward with the suggestion made [here](https://github.com/elastic/endpoint-dev/issues/13771#issuecomment-2022673190) – work with @intxgo to create new documentation similar to [Elastic Agent command reference](https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html) for all public endpoint commands, including the `top` command. 

I'll close this issue as a duplicate, and we'll track the work in #5097.
