### ISSUE TITLE
Palo Alto elastic agent integration[enhancement]: 

### ISSUE THREAD

**Issue by rachitakumar** [elastic/security-docs#4535]
### Description

Hello team! I have seen multiple inquiries around this part of the docs where the customer is confused on what the setting "syslog host" should be when setting up the integration. In particular for my case # 01536525, the customer mentioned our [palo alto elastic integration doc](https://docs.elastic.co/en/integrations/panw#configurations) is vague:

> The doc you sent is vague and doesn't cover most of the configuration on the Elastic side.
> 
> Yes the PANW integration does default to "localhost" however this would never be the case as the Elastic agent cannot be installed on a Palo Alto devices. In the case of Palo Alto the syslog host will always be remote to the agent. Since the "syslog host" setting affects the listening for the syslog service is it meant to be set to only the IP of the device sending the logs to the agent? Is 0.0.0.0 correct setting if you expect syslog from multiple devices?

I did see when [sifting through slack ](https://elastic.slack.com/archives/C0D8SUKB2/p1582672485066100)that multiple users also asked about this particular setting in which we recommended 0.0.0.0 to have it bind to all interfaces however we don't discuss this in our docs. Could we have some improvement around this configuration?

Thank you!

### Related links / assets

Please include each of the following, if applicable:
Doc URL: https://docs.elastic.co/en/integrations/panw#configurations
Subject matter expert: palo alto elastic agent integration
Figma link(s):
Github epic link(s):
Github issue link(s):

### Software version

Probably N/A I guess for all versions.

### Collaborators

PM:
Designer: 
Developer:
Others (if applicable):

### Timeline / deliverables

At the earliest so customers can have a bit more guidance on this configuration.

**Comment by jmikell821** [comment]
Spoke to @jamiehynds, who said he'd chat with an engineer to get a sense of what's involved. 
> Even if we keep the integrations as-is, we can probably do a better job of explaining what the setting does and the supported values within our docs.

**Comment by natasha-moore-elastic** [comment]
Hi @jamiehynds, following up to see if there are any updates on this? Please let us know if there are any doc updates we can support with. Thanks!

**Comment by natasha-moore-elastic** [comment]
Update from @jamiehynds:

> After looking into it, we realised the usual labels we apply to that setting within our integration UI were not applied to the Palo integration. Rather than adjusting docs, we're going to update the integration to make it clearer in the UI.

Closing this ticket as there are no resulting docs updates.
