### ISSUE TITLE
[Known Issue][Security Solution][Threat Intelligence] - filter in/out not showing value in KQL bar

### ISSUE THREAD

**Issue by PhilippeOberti** [elastic/security-docs#4582]
### Description

There is a bug in the KQL bar for the Security Solution Intelligence page. When users try to filter in or out from the different places in the page (barchart legend, table cell actions...) the badge/chip added to the KQL bar will show the field name and the word `Warning` instead of showing the field value.

![Screenshot 2024-01-09 at 4 03 34 PM](https://github.com/elastic/security-docs/assets/17276605/297e13a3-a3a7-4e90-8799-4abcd02cfc26)

The filters are actually working correctly, meaning that the KQL bar does apply the correct field/value pair and the barchart and table are reflecting the filtered data correctly. The only issue is that the UI is showing `Warning` instead of the value.

### Area/Engineering team

Protections Experience & Threat Hunting Investigations

### Which documentation set does this known issue impact?

ESS and serverless

### Affected versions

The issue was introduced in `8.11.1` and is present in all following `8.11.x` versions, as well as `8.12.x`.

### Fix version

There is no fix in place yet.

### Workaround

There isn't any workaround none at the moment.

**Comment by nastasha-solomon** [comment]
The root cause of this is still unknown so removing this from release notes for now. 
cc: @PhilippeOberti @benironside
