### ISSUE TITLE
[BUG] Matches , Doesnot matches operator information is missing under endpoint exception details.

### ISSUE THREAD

**Issue by sukhwindersingh-qasource** [elastic/security-docs#4625]
### Documentation links

https://www.elastic.co/guide/en/security/current/add-exceptions.html

### Description

- Matches , Doesnot matches operator information is missing under endpoint exception details.
- As it is only mentioned under rules exception about new `Matches` operators it should be mentioned under Endpoint exception also
**Screenshot**
![image](https://github.com/elastic/security-docs/assets/108654988/43fb35bf-6db2-407f-b939-2ac23bcdcc30)

### Which documentation set(s) does this bug apply to?

ESS only

### Release version

This bug applies to the stack version 8.12.0

**Comment by muskangulati-qasource** [comment]
Reviewed and assigned to @jmikell821

**Comment by joepeeples** [comment]
No update needed. The "Add Elastic Endpoint exceptions" intentionally doesn't include details about configuring conditions because it's the same process with the same options as in "Add exceptions to a rule" above.
