### ISSUE TITLE
[BUG] Outdated information mentioned in the step 5 for Osquery.

### ISSUE THREAD

**Issue by sukhwindersingh-qasource** [elastic/security-docs#4626]
### Documentation links

https://www.elastic.co/guide/en/security/current/alerts-run-osquery.html

### Description

- Outdated information mentioned in the step 5 for Osquery timeout field, As for now it got timed out as per the value we fill in the timeout field.

**Screen
![image (1)](https://github.com/elastic/security-docs/assets/108654988/b0284d14-7d7a-4123-b6bf-344c3e0c9f50)
shot**

### Which documentation set(s) does this bug apply to?

ESS only

### Release version

This bug applies to the stack version 8.12.0

**Comment by muskangulati-qasource** [comment]
Reviewed and assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
@szwarckonrad do you happen to know if the 5-minute timeout period was the default and preset setting for Osquery live queries before 8.12? I checked the Kibana docs, and in versions 8.4-8.11, we tell users that queries will automatically timeout if there have been no responses after 5 minutes. For reference, see the second sentence in step 6 [here](https://www.elastic.co/guide/en/kibana/8.11/osquery.html#osquery-run-query).

**Comment by nastasha-solomon** [comment]
Thanks for the review, @sukhwindersingh-qasource! The docs are ready for review at https://github.com/elastic/security-docs/pull/4658 when you have a chance.

**Comment by nastasha-solomon** [comment]
Docs updated so closing this issue. Will follow up on [this](https://github.com/elastic/security-docs/issues/4626#issuecomment-1906992687) separately.
