### ISSUE TITLE
Elastic AI Assistant feature missing in Kibana Privilege

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#4627]
**Description**
Elastic AI Assistant feature missing in Kibana Privilege

Steps
- Navigate to https://www.elastic.co/guide/en/security/8.12/case-permissions.html
- Scroll Down to Kibana Privilege
- Observe that beneath the Case feature Elastic AI Assistant feature should be listed

**Expected:**

![image](https://github.com/elastic/security-docs/assets/59917825/0683b39a-6ea0-46b3-a46f-19802e9c37f2)

**Screen-Shot/Current Result:**

![image](https://github.com/elastic/security-docs/assets/59917825/daa3f3f8-055c-4b4a-b76f-deb931b59298)

**Comment by nastasha-solomon** [comment]
Hey there, @lisacaw! Is [this](https://www.elastic.co/guide/en/security/8.12/images/case-feature-privs.png) an automated an automated screenshot? I didn't see a comment in the asciidoc file indicating it was, so just wanted to check with you before I replace it.

**Comment by lcawl** [comment]
> Hey there, @lcawl ! Is [this](https://www.elastic.co/guide/en/security/8.12/images/case-feature-privs.png) an automated screenshot? I didn't see a comment in the asciidoc file indicating it was, so just wanted to check with you before I replace it.

No, it's not automated yet but if it needs to be prioritized, let me know!

**Comment by nastasha-solomon** [comment]
Will only be updating the [ESS docs](https://www.elastic.co/guide/en/security/8.12/case-permissions.html). The Serverless docs are not impacted at the moment.

**Comment by nastasha-solomon** [comment]
Thanks for the review @karanbirsingh-qasource! The docs are updated at https://github.com/elastic/security-docs/pull/4659 when you have a chance to review them.

**Comment by karanbirsingh-qasource** [comment]
https://github.com/elastic/security-docs/pull/4659#issuecomment-1908044589 @nastasha-solomon
