### ISSUE TITLE
[BUG] Sentinelone connector is missing under connector docs

### ISSUE THREAD

**Issue by sukhwindersingh-qasource** [elastic/security-docs#4628]
### Documentation links

https://www.elastic.co/guide/en/kibana/8.12/action-types.html

### Description

- Sentinel connector is not present under connector docs.

**Screenshot**

![image](https://github.com/elastic/security-docs/assets/108654988/2063cd88-64aa-4dd5-9e6f-f53c860ebbbd)

### Which documentation set(s) does this bug apply to?

ESS only

### Release version

This bug applies to the stack version 8.12.0

**Comment by muskangulati-qasource** [comment]
Reviewed and assigned to @jmikell821

**Comment by joepeeples** [comment]
Closing as duplicate; https://github.com/elastic/kibana/pull/174696 is in flight to add docs for the SentinelOne connector.
