### ISSUE TITLE
[BUG] Hyper link for endpoint exception is missing under whats new page for 8.12.0

### ISSUE THREAD

**Issue by sukhwindersingh-qasource** [elastic/security-docs#4629]
### Documentation links

https://www.elastic.co/guide/en/security/current/whats-new.html

### Description

- Hyper link for endpoint exception is missing under whats new page for 8.12.0 ❌ 
- And it is present for Event filters ✔️ 

**Screenshot**
![image (2)](https://github.com/elastic/security-docs/assets/108654988/eebc66da-c9ff-482e-9fca-aa8c14022a72)

### Which documentation set(s) does this bug apply to?

ESS only

### Release version

This bug applies to the stack version 8.12.0

**Comment by muskangulati-qasource** [comment]
Reviewed and assigned to @jmikell821
