### ISSUE TITLE
Timeline Result more action list incorrect ( missing assign unassign and alert tag)

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#4630]
**Description**
Timeline Result more action list incorrect ( missing assign unassign and alert tag)

**Steps**
- Navigate to https://www.elastic.co/guide/en/security/8.12/es-ui-overview.html#timeline-tab
- Observe that more action animation video and in that more action list in incorrect

**Expected:**

![image](https://github.com/elastic/security-docs/assets/59917825/cda807ed-78d2-4b93-937e-707906d98463)

-Apply alert tag
-Assign alert
-Unassign Alert

**Screen-Shot/Current Result:**

- Add to Existing Case
- Add to new Case
- Mark as acknowledged
- Mark as closed
- Add Endpoint Exception
- Add rule exception
- Run Osquery

https://www.elastic.co/guide/en/security/8.12/images/timeline-accessiblity-tab-keys.gif

**Comment by nastasha-solomon** [comment]
Thanks for checking on this @karanbirsingh-qasource! I've updated docs at https://github.com/elastic/security-docs/pull/4660 and they're ready for your review when you have a chance. Thanks!

**Comment by karanbirsingh-qasource** [comment]
Hi @nastasha-solomon thanks for the update.

the requested changes has been fixed now in shared preview so we are moving and closing this issue.
