### ISSUE TITLE
es|ql tab is missing in timeline investigation screen-shot

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#4631]
**Description**

es|ql tab is missing in timeline investigation screen-shot

**Steps**
- Navigate to https://www.elastic.co/guide/en/security/8.12/interactive-investigation-guides.html
- Observe the Timeline screen-shot in that ES|QL tab is missing 

**Expected:**
- ES|QL tab should be present in timeline screen-shot

**Screen-Shot/Current Result:**

![image](https://github.com/elastic/security-docs/assets/59917825/63a6a43a-d94c-4cb2-871f-ea827e7c169e)

**Comment by nastasha-solomon** [comment]
Thanks for checking on this @karanbirsingh-qasource! The corrected docs are ready for your review at https://github.com/elastic/security-docs/pull/4661

**Comment by karanbirsingh-qasource** [comment]
Hi @nastasha-solomon thanks for the update.

the requested  changes has been fixed now in shared preview so we are moving and closing this issue.
