### ISSUE TITLE
[UI copy]: Ad hoc rule runs copy review

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#4650]
### Description

Might need to provide a copy review for the ad hoc rule run feature once design is nearly complete.the 

### Related links / assets

Please include each of the following, if applicable:
Figma link(s): Potentially [this](https://www.figma.com/file/nZsOTIfxEbzi1KD7JUINrg/Ad-hoc-rule-runs-and-Gap-filler-%232840?type=design&node-id=1128-8772&mode=design&t=rvco2EZQUcvIrSE6-0)
Github epic link(s): https://github.com/elastic/security-team/issues/2840
Github issue link(s): TBD
How to find the text in a production environment: TBD
Testing environment information: TBD
NOTE: To keep sensitive information such as credentials secure, do not include it in this form.

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

N/A

### Software version

Possibly 8.14

### Collaborators

PM: @approksiu @paulewing 
Designer: @ARWNightingale 
Developer: TBD
Others (if applicable): TBD

### Timeline / deliverables

Submission date for the final copy is TBD

**Comment by ARWNightingale** [comment]
The only major change which I think we discussed before was to use "Manual runs" instead of ad hoc runs

**Comment by nastasha-solomon** [comment]
https://github.com/elastic/security-docs/issues/5265 contains updated information and screenshots.
