### ISSUE TITLE
[DOCS] Enhancements for ECS compatibility and Indicator Match rules

### ISSUE THREAD

**Issue by kostasb** [elastic/security-docs#468]
## Description 

- Rename the section title [Third-party collectors mapped to ECS](https://www.elastic.co/guide/en/security/current/es-overview.html#_third_party_collectors_mapped_to_ecs) (docs master branch link [here](https://github.com/elastic/security-docs/blob/master/docs/es-overview.asciidoc#third-party-collectors-mapped-to-ecs)) to `Elastic Security Requires Data that is Compliant with Elastic Common Schema`. Modify the content of the section as per the screenshot below:
![image](https://user-images.githubusercontent.com/15780449/105695842-385f9800-5f0b-11eb-9a9f-f858584f5610.png)

- In the [Create an Indicator Match rule](https://www.elastic.co/guide/en/security/current/rules-ui-create.html#create-indicator-rule) paragraph (docs master branch link [here](https://github.com/elastic/security-docs/blob/master/docs/detections/rules-ui-create.asciidoc#create-an-indicator-match-rule)) section, inside the `Indicator index patterns:` section add a Tip section with the following content:
> Data in Indicator indices must be [ECS compatible](link-to-the-updated-"Elastic Security Requires Data that is Compliant with Elastic Common Schema" section described above), and therefore must carry an `@timestamp` field.

## Notes
- @jmikell821 these clarifications are of significant importance for our users, as we've seen questions coming in which could be answered by the above changes. Should be relatively small docs changes to address this. Please could you help with this, hopefully to get it out with 7.11 docs?
- Affects: v7.10 and higher versions. If we can backport to 7.10 docs as well, it would be great. Otherwise merging with 7.11+ is fine, as that's the GA version of this feature.

**Comment by jmikell821** [comment]
@kostasb #476 has been merged and backported to 7.10, 7.11 and 7x. The other snippet about the indicator match rule will be merged in another PR.

**Comment by kostasb** [comment]
Thank you for handling this request so fast Janeen!
