### ISSUE TITLE
[Request] [Detection Engine] add Indicator match rule alert suppression docs 

### ISSUE THREAD

**Issue by vitaliidm** [elastic/security-docs#4715]
### Description

Introducing alert suppression for Indicator match rule

#### Notes from doc syncs and async comms

- When users create an indicator match (IM) rule, they can specify the fields they want to be grouped for suppression. For IM rules, the minimum number of field names that can be specified is 1. The max is 3.
- The maximum number of alerts that can be suppressed is tied to the [`max_signals`](https://www.elastic.co/guide/en/security/current/rules-api-create.html#opt-fields-all) setting and is five times the `max_signals` value. Since the default `max_signals` value is `100`, the maximum number of alerts that can be suppressed is `500`.  
- If enabling suppression causes the IM rule to timeout during the rule preview or when the rule is enabled and running, there are two possible ways to resolve this:
  - Turn off suppression on the rule.
  - Shorten the rule's [look-back time](https://www.elastic.co/guide/en/security/current/rules-ui-create.html#rule-schedule) to reduce the number of documents the rule analyzes. 
- Fields with an array of values are treated as a single group and suppressed together (i.e., they're treated as a single suppression value). When you check the `kibana.alert.suppression.terms` field,  you'll see an array of values for suppressed fields. An example provided by @WafaaNasr:

1. Imagine we have the below document:

````
{
          id,
          '@timestamp': timestamp,
          host: { name: ['host-a', 'host-b'] },
        };
````
2. We indexed this document 3 times with different timestamps
3. We have the below threat index
````
{
            host: {
                  name: 'host-a',
              },
 };
````
4. We enabled suppression for the IM rule
5. we will end up having 1 alert generated only and the suppression count will be 2 and the `suppression.terms` will be an array, not a single value as in the Query rule case
````
 kibana.alert.suppression.terms: [
            {
              field: 'host.name',
              value: ['host-a', 'host-b'],
            },
          ],
````

- The new `alert_supression` param for IM rules has the same functionality as the [query rule](https://www.elastic.co/guide/en/security/8.12/rules-api-update.html#opt-fields-alert-suppression-update).
- The default maximum number of alerts that can be suppressed for each rule type:
  - Custom query rule: indefinite number of alerts
  - Threshold: The `max_signals` value (100 by default) 
  - Indicator match rule: Five times the `max_signals` value (500 by default) 

### Background & resources

* PRs: 
https://github.com/elastic/kibana/pull/174241
* Issues/metas: 
https://github.com/elastic/security-team/issues/7773
https://github.com/elastic/security-team/issues/8360
* Point of contact: 
* @vitaliidm 
* Test environments: 

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.13

### Serverless release

around 8.13 release

### Feature differences

ESS: alert suppression is available for Platinum license
Serverless: available for Essentials and Complete tiers

### API docs impact

adds `alert_suppression` field to Indicator match rule create/update/patch rule APIs

### Prerequisites, privileges, feature flags

ESS: requires Platinum license
Feature Flag: `alertSuppressionForIndicatorMatchRuleEnabled`

**Comment by nastasha-solomon** [comment]
Docs merged for ESS and Serverless
