### ISSUE TITLE
[Request] Updates Vulnerabilities Findings Page

### ISSUE THREAD

**Issue by smriti0321** [elastic/security-docs#4746]
### Description

This is an extension of grouping and table customisation options introduced in 8.12 for CSPM/KSPM Findings. This is to introduce similar features in CNVM Findings Page.

### Background & resources

* PRs: 
* Issues/metas: 
- https://github.com/elastic/kibana/issues/165788
- https://github.com/elastic/kibana/issues/169050
- https://github.com/elastic/kibana/issues/172197
- https://github.com/elastic/kibana/issues/169052
- https://github.com/elastic/kibana/issues/169048
- https://github.com/elastic/kibana/issues/173405
- https://github.com/elastic/kibana/issues/175574

* Point of contact: @opauloh @Omolola-Akinleye 
* Test environments: 

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.13

### Serverless release

April 1, 2024

### Feature differences

Identical

### API docs impact

No

### Prerequisites, privileges, feature flags

- License subscription access to Cloud Security
- User with a Role with read privilege to the following indices: `logs-cloud_security_posture.scores-default`, `logs-cloud_security_posture.findings_latest-default`, `logs-cloud_security_posture.vulnerabilities_latest-default`

**Comment by opauloh** [comment]
@smriti0321, I added the missing issues and updated the pre-requisites, would you like us to hold until the remaining open tasks are completed to provide a test environment?
