### ISSUE TITLE
Prebuilt rule customization - per-field rule diffs

### ISSUE THREAD

**Issue by dplumlee** [elastic/security-docs#4783]
### Description

As part of Prebuilt Rule Customization, users will be able to view a per-field list of component diffs for updated prebuilt rules, giving them visibility into how each rule is changing when Elastic sends out updated rules. 

<img width="1538" alt="Screenshot 2024-02-08 at 1 35 05 AM" src="https://github.com/elastic/kibana/assets/56367316/37e25106-f4a5-47e6-9d93-beab8d0f90a4">

### Background & resources

* PRs: https://github.com/elastic/kibana/pull/174564
* Issues/metas: https://github.com/elastic/kibana/issues/166489
   * also related: https://github.com/elastic/kibana/issues/171520
* Epic: https://github.com/elastic/security-team/issues/1974
* Point of contact: @dplumlee 
* Test environments: N/A

### Condensed docs issue template info

- Which documentation set does this change impact?  ESS and serverless
- ESS release: `8.13.0`
- Serverless release:  March 4th
- Feature differences:  The feature is identical in ESS and serverless
- API docs impact:  No API impact
- Prerequisites, privileges, feature flags: Feature flag name: `perFieldPrebuiltRulesDiffingEnabled`

---
```[tasklist]
### Docs Pull Requests
- [x] Classic docs — https://github.com/elastic/security-docs/pull/4871
- [x] Serverless docs — https://github.com/elastic/staging-serverless-security-docs/pull/296
```

**Comment by joepeeples** [comment]
PRs merged for both classic and serverless
