### ISSUE TITLE
Enhancements to SentinelOne bidirectional actions - response console & history

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#4875]
### Description

Expands the sentinel one bidirectional capability (initially released in 8.12, tech preview) to make use of our response console and actions history views. (in 8.12, you could only isolate through the "Isolate" flyout UX).

* Users can take isolate/release actions on S1 hosts from the response console
* Actions submitted will be tracked through the response action history views. "Agent Type" drop down allows users to filter through Defend vs S1 agent. 

### Background & resources

* PRs: 
  * https://github.com/elastic/kibana/pull/173927 (console)
  * https://github.com/elastic/kibana/pull/175810 (actions history)
* Issues/metas: 
  * https://github.com/elastic/security-team/issues/7718
  * https://github.com/elastic/security-team/issues/7729
* Point of contact: 
  * @caitlinbetz @ashokaditya 
* Test environments: 

### Condensed docs issue template info

- Which documentation set does this change impact?  ESS and serverless
- ESS release:  8.13
- Serverless release:  week of March 26, 2024
- Feature differences:  N/A
- API docs impact:  https://github.com/elastic/security-docs/pull/4853

#### Prerequisites, privileges, feature flags

This is an Enterprise level feature - still in Tech Preview for 8.13.

@ashokaditya do we have any feature flag info to provide here?

Feature flag PRs:
- https://github.com/elastic/kibana/pull/179319
- https://github.com/elastic/kibana/pull/179316

---
```[tasklist]
### Docs Pull Requests
- [x] Classic docs — https://github.com/elastic/security-docs/pull/4885
- [ ] Serverless docs — https://github.com/elastic/staging-serverless-security-docs/pull/305
```

**Comment by joepeeples** [comment]
> @ashokaditya do we have any feature flag info to provide here?

Per https://github.com/elastic/kibana/pull/175810, it looks like `responseActionsSentinelOneV1Enabled` is a required feature flag, as of BC3. Will this flag be required for release versions (8.13.0 release AND serverless production release)?
