### ISSUE TITLE
[DOCS] Add additional case in Troubleshooting Missing Alerts  

### ISSUE THREAD

**Issue by MikePaquette** [elastic/security-docs#488]
## Description 

Add new material in https://www.elastic.co/guide/en/security/current/alerts-ui-monitor.html#troubleshoot-signals 

There would now be two cases to document  
1) when a rule fails to run close to its scheduled time  and you see gaps (existing) and 
2) Even if your rule runs at its scheduled time, there might still be missing alerts if your ingestion pipeline delay is greater than your rule interval + additional look-back time.

Please see slides 40-47 for a [slide-presentation](https://docs.google.com/presentation/d/1V71QdHdYzCEbKkFeAsz9P9bohA4absQ0ulnJgHdPsvU/edit?ts=600f618a#slide=id.gb94973f270_0_142) of what we want to add here for the documentation.

## Acceptance Test Criteria

A user who suspects they are missing alerts will find this section, read it, and be able to take steps to avoid missing further alerts.

## Notes

- Add the **"Team:Docs"** label to new issues. 
- Be sure to add the version number label. 
- Be sure to add any necessary screenshots for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by jmikell821** [comment]
Merged #507.
