### ISSUE TITLE
[UI copy]: Event details flyout title and tooltips

### ISSUE THREAD

**Issue by christineweng** [elastic/security-docs#4897]
### Description

In 8.10, we released the expanded details for alerts (alerts on Alerts Page). In 8.14, we are enabling the expandable details experience for events (events in Host and User pages). PR https://github.com/elastic/kibana/pull/176332 introduced the enhancement behind a feature flag.

1. Title for documents that has `event.kind=alert`

Per [ecs defintion](https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-kind.html), users can feed `alert` as event kind, which can come from their internal systems. This is different from the alerts generated from rules (for those we use `event.kind=signal`, which is reserved for security solution only).

![image](https://github.com/elastic/security-docs/assets/18648970/bdaec820-8270-422e-9a9e-dffbb3c5e7ac)

**Q: Since showing alert can be confusing, should we change it to `External alert details`? There is an option to show only external alerts so the concept exist in the app currently**

![image](https://github.com/elastic/security-docs/assets/18648970/9b1403f2-7f44-458b-b056-8799781e016b)

2. We are showing event categories as a subsection in about section. When a user hover on the field it will show a tooltip with the category description. In the case of we can't find the field in ecs, we show a fall back message.

This field is not an ecs field, description is not available.

![image](https://github.com/elastic/security-docs/assets/18648970/b8879e49-0515-47f1-9714-6e3295c0e4c3)

### Related links / assets

Please include each of the following, if applicable:
Figma link(s): https://www.figma.com/file/ubvhBGHee58diJNvSiy0GZ/%5B8.%2B%5D-%5BAlerts%5D-Expandable-Event-Flyout?type=design&node-id=4000-541651&mode=design&t=Ij7mRiM9jWPMOIKC-0
Github epic link(s):
Github issue link(s): https://github.com/elastic/security-team/issues/7759, https://github.com/elastic/kibana/pull/176332
How to find the text in a production environment: Host page -> Event table -> expand a row
Testing environment information:
NOTE: To keep sensitive information such as credentials secure, do not include it in this form.

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

No difference between ESS and serverless

### Software version

8.14

### Collaborators

PM: Paul Ewing
Designer: Fernanda Enrigue
Developer: Christine Weng
Others (if applicable):

### Timeline / deliverables

We need it reviewed before turning on the feature flag, ideally one week before 8.14 feature freeze (4/16). But if we need to go over via a call, I would like to get the conversation started earlier. Thanks!

**Comment by nastasha-solomon** [comment]
Hey, @christineweng! Here are the notes from our meeting earlier today:

- Title for event details flyout: For events of the `event.kind=alert` type, `External alert details` works. For all other types of events (minus the `event.kind=signal` types), `Event details` works.
- Additional action items for me:
   - Review tooltip copy for event category fields that aren't ECS-compliant.
   - Might need to write reference docs for the new expandable event flyout. Users will for sure need to know that toggling the `securitySolution:enableExpandableFlyout` advanced setting on turns on the new expandable event details flyout. It could also be helpful to explain the event details flyout title and areas on the **Overview** tab (right and left panels).

**Comment by nastasha-solomon** [comment]
@christineweng here are a few copy options for event category fields that aren't ECS-compliant:

- **Option 1:** Field descriptions are unavailable for non-ECS fields. 
- **Option 2:** Non-ECS fields don't have field descriptions.  
- **Option 3:** This field doesn't have a description because it's not part of ECS. 

Let me know if none of these work or if you'd like to tweak any of them.

**Comment by christineweng** [comment]
> Option 1: Field descriptions are unavailable for non-ECS fields.
> Option 2: Non-ECS fields don't have field descriptions.
> Option 3: This field doesn't have a description because it's not part of ECS.

I find option 3 to be plain and simple, @paulewing wdyt?

**Comment by nastasha-solomon** [comment]
Copy has been merged via https://github.com/elastic/kibana/pull/180750.
