### ISSUE TITLE
[Enhancement] Only open or acknowledged alerts are considered for alert suppression

### ISSUE THREAD

**Issue by marshallmain** [elastic/security-docs#4916]
We've gotten a couple of SDHs [like this](https://github.com/elastic/sdh-security-team/issues/907) where customers are confused about why their closed alerts are not suppressing new alerts from a rule. It would be helpful to update the [Alert suppression docs](https://www.elastic.co/guide/en/security/8.12/alert-suppression.html) to inform users that the suppression is only applied by open or acknowledged alerts.

**Comment by nastasha-solomon** [comment]
Thanks again for filing this, @marshallmain. I'm not sure I fully understand how alert suppression works for closed and open alerts. If we're telling users that alert suppression only works for `Open` or `Acknowledged` alerts, are we by extension advising them to _never_ close suppressed alerts? After reading through the examples in the linked SDH, it looks as though alert suppression is completely stopped if users close alerts that meet the suppression criteria. Am I understanding that correctly? If I am, can we make any other recommendations for managing alerts that have been investigated and are ready to be closed? For example, should we reccomend that users move these alerts to `Acknowledged` instead of `Closed`?

**Comment by marshallmain** [comment]
Once the suppression window has passed, users can close alerts and it won't have any effect on suppression. If the suppression window is 1 hour, closing an alert that's more than 1 hour old makes no difference. What seems to be happening for these users is an alert comes in and they triage it quickly and close it, expecting similar alerts to be suppressed even though they closed the first alert already. We don't consider closed alerts for suppression logic because when we detect new alerts and suppress them because of an existing alert, we update the existing alert - so we thought it would be potentially confusing if closed alerts were updated by the system since we don't expect users to go back and look at closed alerts for updates regularly.

@paulewing do you have thoughts on what workflows we should recommend to users here? Using the `acknowledged` status seems reasonable to me. Perhaps alert tags would also be a good tool to manage alerts that have been triaged but not closed yet because they're being used for suppression.

**Comment by nastasha-solomon** [comment]
(Reposting from Slack and adding a bit more)

So it's not that users can never close alerts that are being used for suppression. It's that they should _avoid closing those alerts within an active suppression window_. In other words, users can close alerts being used for suppression, but only after the suppression window has ended.

I think it'd be helpful to explain this in the alert suppression docs, and then provide an example and some recommended workflows for handling alerts being used in an active suppression window. @paulewing let me know what you think about this approach and if you have any examples in mind.

Thanks, both!

**Comment by nastasha-solomon** [comment]
From Slack convo with @paulewing and @marshallmain:

Add the following lang to the docs, and include an example:

> We do not recommend closing alerts during an active suppression window as this will disable the current alert suppression and prevent future alerts from being suppressed.

**Comment by nastasha-solomon** [comment]
Confirmed via Slack that this update should be backported to 8.7.

**Comment by nastasha-solomon** [comment]
Serverless and ESS docs updated.
