### ISSUE TITLE
[Request] Ability to edit setup guide field for custom rules in UI and API

### ISSUE THREAD

**Issue by dplumlee** [elastic/security-docs#4917]
### Description

We need documentation for the setup guide field being added to the create/edit rule forms and the corresponding `setup` field being added to the related API schemas. Right now, the setup field is a prebuilt rules only field - this change will allow the field to be used in custom rules as well by adding a markdown container to the create/edit rule ui forms and adding the `setup` fields to the create/update/patch rules api schema - not just the response schema.

### Background & resources

* PRs: https://github.com/elastic/kibana/pull/178131
* Issues/metas: https://github.com/elastic/kibana/issues/173626
* Point of contact: @dplumlee 

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.14.0

### Serverless release

The week of April 15, 2024

### Feature differences

The feature is identical in ESS/serverless

### API docs impact

Right now the `setup` field is documented in our [response schema](https://elastic.co/guide/en/security/8.12/rules-api-create.html#_response_payload) (as a default empty string). This update will add the field to the create and update (POST/PUT/PATCH) schemas as a defaultable (optional) field. It will default to an empty string if not included.

---

```[tasklist]
### Pull requests
- [x] Serverless docs — https://github.com/elastic/staging-serverless-security-docs/pull/324
- [x] Classic docs — https://github.com/elastic/security-docs/pull/5091
- [x] API docs (classic) — https://github.com/elastic/security-docs/pull/5095
```

**Comment by joepeeples** [comment]
@dplumlee I don't think we can have docs ready in time for the serverless release of week of March 18th, since that's just a few days after this issue was opened, and that week we'll be working heavily on 8.13 features. I'll try to prioritize this soon after we get the 8.13 features covered.
