### ISSUE TITLE
[Known Issue] Please add docs for a known issue where users unable to create/edit/delete filters while creating/editing security rules

### ISSUE THREAD

**Issue by e40pud** [elastic/security-docs#4928]
### Description

In `8.12.1` security rules' filters were broken and users were not able to create, edit or delete them. That would happen when user selected data view as a source for the security rule.

Here is the bug ticket https://github.com/elastic/kibana/pull/178207

cc @yctercero 

### Area/Engineering team

Detections & Response

### Which documentation set does this known issue impact?

ESS and serverless

### Affected versions

`8.12.1`, `8.12.2`

### Fix version

`8.13.0+`

**Comment by e40pud** [comment]
@yctercero what do you think about the urgency for these docs? We had an SDH and this issue breaks filters experience inside rules in `8.12.1` and `8.13.0`

**Comment by yctercero** [comment]
@e40pud I'd say urgent. @nastasha-solomon let us know how we can help here to get this one out.

**Comment by nastasha-solomon** [comment]
@e40pud a couple of follow-up questions on this bug:

- Does it affect all rule types? The linked Kibana PR only describes an issue with custom query rules -- it doesn't look as though other rule types were impacted. 
- Is there a workaround for this bug or is upgrading to 8.13.1+ the only fix?

**Comment by e40pud** [comment]
@nastasha-solomon here are the answers

> Is this known issue also present in 8.12.2? Or does it only affect 8.12.1 and 8.13.0?

Yes it affects 8.12.2 as well. All versions between 8.12.1 and 8.13.0 (including those two) are affected.

> Does it affect all rule types? The linked Kibana PR only describes an issue with custom query rules -- it doesn't look as though other rule types were impacted.

It affects `Custom query`, `Indicator Match` and `New Terms` rules.

>Is there a workaround for this bug or is upgrading to 8.13.1+ the only fix?

There is no workaround for this issue. Users need to upgrade to 8.13.1+

**Comment by e40pud** [comment]
@nastasha-solomon, @banderror pointed out that there still will be a build candidate for `8.13.0`, so my changes will make it into it then. This means that affected versions are `8.12.1` and `8.12.2`, and users need to upgrade to `8.13.0`. I will update description accordingly.
