### ISSUE TITLE
[DOCS] Add known issue to 7.11 release notes for Elastic Endpoint rule initial failure status

### ISSUE THREAD

**Issue by peluja1012** [elastic/security-docs#493]
## Description 

The `Elastic Endpoint Security` rule will report a failure status until the Endpoint sends an alert for the first time, at which point the next rule execution will succeed. This is because the `logs-endpoint.alerts-*` index pattern doesn’t get created until the Endpoint sends the first alert. It may give users the impression that the rule is not running properly even after they install their Endpoint. But, in fact, it is and it’s reporting accurate status.

More info in this comment: https://github.com/elastic/kibana/issues/90401#issuecomment-774070671

**Comment by jmikell821** [comment]
Hi @DonNateR can you add this issue to the RN's PR please?
