### ISSUE TITLE
[Enhancement]: Add a note in  Manage detection alerts -> Edit drop-down filter controls

### ISSUE THREAD

**Issue by logeekal** [elastic/security-docs#4938]
### Description

Hello Team,

Currently, docs explain almost complete information about Fliter Controls on the alert page. 

We need to add one small `note` to make that information complete. Note is given below:

```
Saved changes are currenly stored in browsers storage and not in the user profile. In case you clear the storage or login into your profile in some other browser, you will see default page filter controls. 
```

![grafik](https://github.com/elastic/security-docs/assets/7485038/2a1ce3a7-2ea2-4f59-bc77-fab58f0b3129)

### Related links / assets

Please include each of the following, if applicable:
Doc URL: https://www.elastic.co/guide/en/security/8.9/alerts-ui-manage.html#drop-down-filter-controls
Subject matter expert: @logeekal ( Jatin Kathuria )
Figma link(s):
Github epic link(s):
Github issue link(s):

### Which documentation set needs improvement?

ESS and serverless

### Software version

All versions since 8.9

### Collaborators

PM:
Designer: 
Developer:
Others (if applicable):

### Timeline / deliverables

I am not sure of your timings but recently we got [SDH regarding this](https://github.com/elastic/sdh-security-team/issues/905). Hopefully, we would like to prevent more SDH like this.

**Comment by nastasha-solomon** [comment]
ESS and Serverless docs updated.
