### ISSUE TITLE
[Bug] Security Solution tagged dashboard cannot be deleted hence the bulk selection should be disabled not enabled

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#4992]
**Description**

Security Solution tagged dashboard cannot be deleted hence the bulk selection should be disabled not enabled

**URL**

https://www.elastic.co/guide/en/security/8.13/es-ui-overview.html#_dashboards

**Expected Result**

![image](https://github.com/elastic/security-docs/assets/59917825/bf74c60d-ed23-4ea3-baea-6a87ded7ed9c)

**Actual Result**

![image](https://github.com/elastic/security-docs/assets/59917825/95cb6a77-adfc-464b-ac88-a33c636f7806)

**Comment by joepeeples** [comment]
Wwe're probably OK with no update. We don't say anywhere that the dashboards can be deleted, and the checkbox in the screenshot is a very minor detail that typical users probably wouldn't notice.
