### ISSUE TITLE
[BUG] Information missing in Docs for trusted application new warning message added.

### ISSUE THREAD

**Issue by sukhwindersingh-qasource** [elastic/security-docs#4993]
### Documentation links

https://www.elastic.co/guide/en/security/8.13/trusted-apps-ov.html

### Description

- No information is present for the new warning message added in the 8.13.0 release under trusted application as per this feature ticket
- Feature ticket link : https://github.com/elastic/kibana/issues/172212

![image](https://github.com/elastic/security-docs/assets/108654988/45a2b01b-c339-4bbe-9fbe-bb2eac8f204d)

### Which documentation set(s) does this bug apply to?

ESS only

### Release version

This bug applies to the stack version 8.13.0

**Comment by muskangulati-qasource** [comment]
Reviewed and assigned to @jmikell821

**Comment by joepeeples** [comment]
The UI behavior and messaging seem adequate to inform the user about this limitation, but it wouldn't hurt to mention in docs too.
