### ISSUE TITLE
[Bug] assignees filter button along with manage rules missing

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#4994]
**Description**
assignee filter button along with manage rules missing

**URL**

https://www.elastic.co/guide/en/security/8.13/es-ui-overview.html

**Expected Result**
![image](https://github.com/elastic/security-docs/assets/59917825/766b62b6-5c74-408a-946a-b3bb46a108e1)

**Actual Result**

![image](https://github.com/elastic/security-docs/assets/59917825/e7668705-7f95-4c6f-9f8e-9583320b079b)

**Comment by nastasha-solomon** [comment]
Thanks for filing this, @karanbirsingh-qasource! The following PRs are ready for your review:

- https://github.com/elastic/security-docs/pull/5000
- https://github.com/elastic/staging-serverless-security-docs/pull/309

Thank you!

**Comment by karanbirsingh-qasource** [comment]
requested changes are now present in the above shared preview @nastasha-solomon 

so we are closing this ticket and adding "QA:Validated" ✔️
