### ISSUE TITLE
[BUG] Docs missing for Cases attachments will support comments from S1 actions

### ISSUE THREAD

**Issue by sukhwindersingh-qasource** [elastic/security-docs#4995]
### Documentation links

https://www.elastic.co/guide/en/security/8.13/cases-open-manage.html

### Description

- No information is present for the Cases attachments will support comments from S1 actions
- Feature ticket link :https://github.com/elastic/security-team/issues/8243
![image](https://github.com/elastic/security-docs/assets/108654988/6967afdd-6ebd-4116-9bdc-652236e22d23)

### Which documentation set(s) does this bug apply to?

ESS only

### Release version

This bug applies to the stack version 8.13.0

**Comment by muskangulati-qasource** [comment]
Reviewed and assigned to @jmikell821

**Comment by joepeeples** [comment]
We could mention this in the S1 docs. Our docs for cases are more general (some/most originate from outside of Security, in Response Ops).
