### ISSUE TITLE
[BUG] The Manage Endpoint protection does not specify all the tabs under the manage section

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#4996]
### Documentation links

https://www.elastic.co/guide/en/security/current/sec-manage-intro.html

### Description

The Manage Endpoint protection does not specify all the tabs under the manage section
 
**Screenshots**
- Actual:
![1_Actual](https://github.com/elastic/security-docs/assets/60252716/9ed02bf9-3fd6-4e6c-bcce-87af2dc1a14f)

- Expected:
![1_Expected](https://github.com/elastic/security-docs/assets/60252716/f4e06754-3c10-4cbe-9d05-114b29917bbd)

### Which documentation set(s) does this bug apply to?

ESS only

### Testing environment

VERSION: 8.13.0
BUILD: 72069
COMMIT: 2e3a5cd43e835baa1d596b1aa54735992259ecb9

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
We intentionally reorganized the "Manage endpoint protection" and "Endpoint response actions" sections to be more tasked based, not necessarily a 1-to-1 match of how the UI is organized. This section landing page covers the tasks within the section.
