### ISSUE TITLE
[BUG] The section for 'Endpoint response actions' should be nested under the 'Manage endpoint protection'.

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#4997]
### Documentation links

https://www.elastic.co/guide/en/security/current/index.html

### Description

The section for 'Endpoint response actions' should be nested under the 'Manage endpoint protection'.

**Screenshot**
![2](https://github.com/elastic/security-docs/assets/60252716/3d94a400-13d5-4b6a-84dd-360ac5ddddcd)

### Which documentation set(s) does this bug apply to?

ESS only

### Testing environment

VERSION: 8.13.0
BUILD: 72069
COMMIT: 2e3a5cd43e835baa1d596b1aa54735992259ecb9

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
This was an intentional reorganization of these sections.
