### ISSUE TITLE
[BUG] The protection message is not displayed for the policy configuration

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#4998]
### Documentation links

https://www.elastic.co/guide/en/security/current/admin-page-ov.html

### Description

The protection message is not displayed for the policy configuration

**Screenshots**
- Actual:
![3_Actual](https://github.com/elastic/security-docs/assets/60252716/7f49fa9a-726d-4ec2-99c5-f6e80ebe262f)

- Expected:
![3_Expected](https://github.com/elastic/security-docs/assets/60252716/a8e8f5e0-b6a0-4006-9558-d9ef3d92e5cd)

### Which documentation set(s) does this bug apply to?

ESS only

### Testing environment

VERSION: 8.13.0
BUILD: 72069
COMMIT: 2e3a5cd43e835baa1d596b1aa54735992259ecb9

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
Very minor detail, I think we're OK forgoing a screenshot update. The UI message (regarding the Endpoint Security rule) isn't related to what the image is illustrating (the general context of the integration policy page).
