### ISSUE TITLE
[BUG] The screenshot for policy config needs to be updated to show 'Response Actions'

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#4999]
### Documentation links

https://www.elastic.co/guide/en/security/current/admin-page-ov.html

### Description

The screenshot for policy config needs to be updated to show 'Response Actions'

**Screenshots**
- Actual:
![4_actual](https://github.com/elastic/security-docs/assets/60252716/a77ed912-5364-4c9f-845a-459ce229611c)

- Expected:
![4_Expected](https://github.com/elastic/security-docs/assets/60252716/4c70a231-2f6f-4ad6-8c4d-9eff4b7e434f)

### Which documentation set(s) does this bug apply to?

ESS only

### Testing environment

VERSION: 8.13.0
BUILD: 72069
COMMIT: 2e3a5cd43e835baa1d596b1aa54735992259ecb9

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
Very minor detail, I think we're OK with no update. The context around the image isn't focusing on specific status categories; it's just generally showing what the UI looks like.
