### ISSUE TITLE
[BUG] Docs missing for adding a sentinelOne alert to a case/timeline

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#5004]
### Documentation links

https://www.elastic.co/guide/en/security/current/response-actions-config.html

### Description

Docs missing for adding a sentinelOne alert to a case/timeline

### Which documentation set(s) does this bug apply to?

ESS only

### Testing environment

VERSION: 8.13.0
BUILD: 72069
COMMIT: 2e3a5cd43e835baa1d596b1aa54735992259ecb9

**Comment by manishgupta-qasource** [comment]
Reviewed and assigned to @jmikell821

**Comment by joepeeples** [comment]
No update needed. Adding a SentinelOne-originated alert to a case or Timeline is no different from any other type of alert.
