### ISSUE TITLE
[BUG] Isolation of SentinelOne alerts via cases/timelines is not mention

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#5005]
### Documentation links

https://www.elastic.co/guide/en/security/current/response-actions-config.html

### Description

Isolation of SentinelOne alerts via cases/timelines is not mention

### Which documentation set(s) does this bug apply to?

ESS only

### Testing environment

VERSION: 8.13.0
BUILD: 72069
COMMIT: 2e3a5cd43e835baa1d596b1aa54735992259ecb9

**Comment by manishgupta-qasource** [comment]
Reviewed and assigned to @jmikell821
