### ISSUE TITLE
[UI copy]: 3P Posture Workflows 

### ISSUE THREAD

**Issue by smriti0321** [elastic/security-docs#5006]
### Description

Requesting a UI Copy for 3p posture workflows

### Related links / assets

Please include each of the following, if applicable:
Figma link(s): https://www.figma.com/file/rERIzTNVuXscp5yZrDpqfz/3rd-Party-Posture-Posture-Workflows?type=design&node-id=226-7449&mode=design&t=k1cJIWnBX9kg1Swm-0
Github epic link(s): https://github.com/elastic/security-team/issues/8454
Github issue link(s):
How to find the text in a production environment:
Testing environment information:
NOTE: To keep sensitive information such as credentials secure, do not include it in this form.

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

Identical in ESS and Serverless

### Software version

8.14

### Collaborators

PM: @smriti0321 
Designer: @einatjacoby 
Developer: 
Others (if applicable):

### Timeline / deliverables

We need the UI Copy review by April 5, as engineering will pick up this for next sprint.

**Comment by benironside** [comment]
complete - provided two rounds of feedback
