### ISSUE TITLE
[Request] 8.13.1 release notes

### ISSUE THREAD

**Issue by benironside** [elastic/security-docs#5012]
### Description

we need release notes for 8.13.1

### Background & resources

* PRs: 
* Issues/metas: 
* Point of contact: 
* Test environments: 

### Which documentation set does this change impact?

ESS only

### ESS release

8.13

### Serverless release

-

### Feature differences

-

### API docs impact

-

**Comment by nastasha-solomon** [comment]
Confirmed with @roxana-gheorghe that there are no Endpoint PRs that need to be release-noted for this release.
