### ISSUE TITLE
[UI copy]: Guide tour in alerts flyout

### ISSUE THREAD

**Issue by christineweng** [elastic/security-docs#5045]
### Description

We are introducing a guided tour for the expandable alerts/event details in 8.14. Even though the initial feature was introduced in 8.10, we think it would still be good to have a tour for customers upgrading from earlier versions. We aim to show new functionalities (expand function, previews) and new insights available to users (entities, prevalence)

We would like to have docs team review the verbiage.

Current steps:

1. Overview
![image](https://github.com/elastic/security-docs/assets/18648970/92144210-04b7-4f96-9161-f4c91eb0deae)

2. Opening preview 
![image](https://github.com/elastic/security-docs/assets/18648970/34171ef8-eb0d-4b5a-a2e8-8831342cc081)

3. Expand 
![image](https://github.com/elastic/security-docs/assets/18648970/322363cf-052e-45ce-860d-5e4cb79bab2d)

4. Entities tab (left)
![image](https://github.com/elastic/security-docs/assets/18648970/dedf01e2-57dd-4717-8566-dc2d37be87b2)

5. Prevalence tab(left)
![image](https://github.com/elastic/security-docs/assets/18648970/890e45f9-4921-4729-a46d-5e6de2bed6d1)

**Note:**
We are waiting to hear back from product on if there are additional steps to be added. I will keep you updated.

### Related links / assets

Please include each of the following, if applicable:
Figma link(s):
Github epic link(s): 
Github issue link(s): https://github.com/elastic/security-team/issues/8134
How to find the text in a production environment:
Testing environment information:
NOTE: To keep sensitive information such as credentials secure, do not include it in this form.

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

no difference between ESS and serverless

### Software version

8.14

### Collaborators

PM: Paul Ewing
Designer: Fernanda Enrigue
Developer: Christine Weng
Others (if applicable):

### Timeline / deliverables

Before 8.14 feature freeze (April 16)

**Comment by nastasha-solomon** [comment]
Notes on tour: https://docs.google.com/document/d/1_UADFkAUcXDv2CCgnga8zzauyIkFi3DZwDeXCnrglUQ/edit?usp=drive_link

**Comment by PhilippeOberti** [comment]
work implemented in [this PR](https://github.com/elastic/kibana/pull/180318)

**Comment by nastasha-solomon** [comment]
Closing since we completed the review and the tour was added to the UI.
