### ISSUE TITLE
[Request]: Documentation for Value list modal

### ISSUE THREAD

**Issue by nkhristinin** [elastic/security-docs#5052]
### Description

https://github.com/elastic/kibana/assets/7609147/2aafe007-734f-4c0e-b542-5eca229e310d

Added a new modal window that lets users interact with value lists directly. This modal supports viewing, searching, adding, deleting, updating, and uploading items.

Where to find the modal window:
- Value list popup
- Exception editing and viewing on both the rule page and shared exceptions management page
Permissions:

Add, edit, delete, and upload buttons are hidden for read-only users.
The modal link is not shown to users without read permissions.

### Related links / assets

Please include each of the following, if applicable:
Doc URL: 
Subject matter expert:
Figma link(s):
Github epic link(s):
Github issue link(s): https://github.com/elastic/kibana/pull/179339

### Which documentation set needs improvement?

ESS and serverless

### Software version

8.14

### Collaborators

PM:
Designer: 
Developer:
Others (if applicable):

### Timeline / deliverables

8.14

**Comment by nastasha-solomon** [comment]
Additional Serverless docs that'll need to be updated to account for the changes being implemented in https://github.com/elastic/kibana/pull/180929:

**_NOTE: Do not update the docs below until 180929 is merged._**

- [Create and manage value lists](https://docs.elastic.co/serverless/security/value-lists-exceptions):
  - [ ] [Create value lists](https://docs.elastic.co/serverless/security/value-lists-exceptions#create-value-lists) - step 3
  - [ ] `-detections-upload-lists-ui.png`
  - [ ] Multiple areas/images in the [Manage value list](https://docs.elastic.co/serverless/security/value-lists-exceptions#manage-value-lists) section that I'm updating in https://github.com/elastic/staging-serverless-security-docs/pull/322.
- [About detection rules](https://docs.elastic.co/serverless/security/about-rules):
  - [ ] `-detections-all-rules.png` (under `docs/images/about-rules`)
- [Use Elastic prebuilt rules](https://docs.elastic.co/serverless/security/prebuilt-rules-management)
  - [ ] `-detections-prebuilt-rules-add-badge.png`
  - [ ] `-detections-prebuilt-rules-update.png`
- Manage detection rules
  - [ ] `-detections-all-rules.png` (under `docs/images/rules-ui-management`)
  - [ ] Third bullet under the [Export and import rules](https://docs.elastic.co/serverless/security/rules-ui-management#export-and-import-rules) section (update the reference to Import value list UI and instructions for finding it)
- [Create a detection rule | Use value lists with indicator match rules](https://docs.elastic.co/serverless/security/rules-create#use-value-lists-with-indicator-match-rules):
  - [ ] Update path in the tip (If you don't remember this information, go to **Rules** → **Detection rules (SIEM)** → **Import value lists**)
- [Elastic Security UI | Rules](https://docs.elastic.co/serverless/security/security-ui#rules):
  - [ ] `-detections-all-rules.png`
- [Rules](https://docs.elastic.co/serverless/security/about-rules)
  - [ ] `-detections-all-rules.png`
- [Monitor and troubleshoot rule executions | Rule Monitor tab](https://docs.elastic.co/serverless/security/alerts-ui-monitor#rule-monitoring-tab)
  - [ ] `-detections-monitor-table.png`

I'll need to update the ESS docs in the same way, but will also need to refresh several API docs:
- [Import rule](https://www.elastic.co/guide/en/security/current/rules-api-import.html)
  - [ ] Update third note in the intro - fix path in the third para 
- [Export rules](https://www.elastic.co/guide/en/security/current/rules-api-export.html)
  - [ ] Update first (and only) note in the intro - fix path in the third para
