### ISSUE TITLE
[Request] improved ES|QL investigation(highlighted) fields

### ISSUE THREAD

**Issue by vitaliidm** [elastic/security-docs#5054]
### Description

allows to select custom created fields in ES|QL query as investigation(highlighted) fields
shows only ES|QL fields for aggregating queries
shows ES|QL fields + index fields for non-aggregating queries. Since results are enriched with source documents in that case

### Background & resources

* PRs: 
https://github.com/elastic/kibana/pull/177746

* Issues/metas: 
[Meta] https://github.com/elastic/security-team/issues/7944
https://github.com/elastic/security-team/issues/8771

* Point of contact: 
@vitaliidm 

* Test environments: 

### Which documentation set does this change impact?

ESS only

### ESS release

8.14

### Serverless release

N/A

### Feature differences

Available only on ESS

### API docs impact

No impact on API

### Prerequisites, privileges, feature flags

N/A

**Comment by nastasha-solomon** [comment]
Note to self: I'll need to update the Serverless ES|QL rule docs once merge https://github.com/elastic/staging-serverless-security-docs/pull/340. Can re-use the ESS changes I'm adding in https://github.com/elastic/security-docs/pull/5182.

**Comment by nastasha-solomon** [comment]
ESS and Serverless docs are updated.
