### ISSUE TITLE
[Enhancement]: Add details about Serverless Downgrades from Complete to Essentials tier

### ISSUE THREAD

**Issue by MikePaquette** [elastic/security-docs#5067]
### Description

As described in https://github.com/elastic/security-team/issues/8827, we need to caution users that a downgrade from Complete to Essentials may incur data loss.

The modal in the Cloud UI will point to our docs for more details.  This enhancement request is to provide those additional details.

### Related links / assets

Please include each of the following, if applicable:
Doc URL:  https://docs.elastic.co/serverless/elasticsearch/manage-project#project-features-and-add-ons
Subject matter expert: @MikePaquette 
Figma link(s): https://www.figma.com/file/mrSTnZQZlYxIeXuKv00Rbf/Untitled?type=design&node-id=0%3A1&mode=design&t=rZ0rcAsiCMJQWSJ5-1
Github epic link(s): https://github.com/elastic/security-team/issues/8827
Github issue link(s): https://github.com/elastic/security-team/issues/8827

### Which documentation set needs improvement?

Serverless only

### Software version

Serverless 

### Collaborators

PM: @MikePaquette 
Designer: @semd 
Developer: @YulNaumenko 
Others (if applicable):

### Timeline / deliverables

- needed for Serverless Ungated Preview on 30-April.

**Comment by semd** [comment]
Here's the implementation [PR](https://github.com/elastic/cloud/pull/125977):

![image](https://github.com/elastic/security-docs/assets/17747913/7b11a9a5-6337-4062-8b93-3ef23aa53e86)

**Comment by jmikell821** [comment]
Hi @MikePaquette and @semd. I'm unsure of what I'm supposed to add to docs [here](https://docs.elastic.co/serverless/elasticsearch/manage-project#project-features-and-add-ons). It looks like the UI has the warning sign about downgrading -- should I just add a similar warning to this section in the serverless docs, or were there additional details we need to include here too?

**Comment by MikePaquette** [comment]
Hi @jmikell821 yes, there are additional details we should add here.  I'll share an internal doc with some details, but it may not be complete yet.
