### ISSUE TITLE
[UI copy]: Automate the asset classification process from an offline data source

### ISSUE THREAD

**Issue by r4zr32d3k1l** [elastic/security-docs#5070]
### Background 
This feature is an iteration of https://github.com/elastic/security-team/issues/4208. It allows users to automate the asset classification process from an offline data source.

### User outcome 
As an analyst:

- I want to upload a file from my local environment containing managed hosts and/or users with asset-criticality classifications (aka. Critical, High, Medium, Low, None) so that this business criticality classification is available within elastic for subsequent all detection and hunting workflows.

- I want to subsequently update this list so that I can conveniently update the assignments

### Description

Objective:
To ensure all instructional content, user interface text, and error messages related to the CSV Import feature are clear, concise, and free of errors. The copywriting team will be tasked with refining the language to enhance user comprehension and engagement.

Scope of Work:
- Review and proofread all written material associated with the CSV Import functionality.
- Check for grammatical accuracy, consistency in terminology, and adherence to the company's style guide.
- Simplify technical jargon where possible, ensuring accessibility for users of varying expertise levels.
- Validate the clarity and effectiveness of error messages and system notifications.
- Ensure all instructions are accurate and match the user interface elements and user flow.
- Provide recommendations for language improvements to enhance user experience.

### Related links / assets

Please include each of the following, if applicable:
Figma link(s): https://www.figma.com/file/IKQr6HbQPAdFws9i7Ikcx9/Entity-Analytics?type=design&node-id=988%3A14&mode=design&t=rHn89zTT2dctDDnR-1
Github epic link(s): https://github.com/elastic/security-team/issues/5261

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

No difference.

### Software version

Currently in development. 

### Collaborators

PM: Jared Burgett
Designer: Pavel Manko
Developer: Pablo Neves Machado, Mark Hopkin
Others (if applicable):

### Timeline / deliverables

Not sure.

**Comment by natasha-moore-elastic** [comment]
No critical UI copy issues were found, so the dev PR was approved by Docs due to feature freeze deadline.
Non-critical copy suggestions provided in [Google doc](https://docs.google.com/document/d/18Y5jCbDYEFYcgeLZ0WAfG0FA71SO4_B0gE4aHbMf11w/edit).
