### ISSUE TITLE
[UI copy]: for value list modal

### ISSUE THREAD

**Issue by nkhristinin** [elastic/security-docs#5072]
### Description

Value list modal window - more info in the docs issue: https://github.com/elastic/security-docs/issues/5052

### Related links / assets
<img width="1503" alt="Screenshot 2024-04-15 at 17 17 05" src="https://github.com/elastic/security-docs/assets/7609147/a30f6a37-5ec9-443a-9359-794adca87773">
<img width="1493" alt="Screenshot 2024-04-15 at 17 16 53" src="https://github.com/elastic/security-docs/assets/7609147/bb1fbd55-9659-46ec-a007-128b07efe532">
<img width="1505" alt="Screenshot 2024-04-15 at 17 16 47" src="https://github.com/elastic/security-docs/assets/7609147/f5b167ef-5a9c-46b2-bb83-e5c4d3e0cf27">
<img width="1493" alt="Screenshot 2024-04-15 at 17 16 42" src="https://github.com/elastic/security-docs/assets/7609147/5d21e64b-542a-42e6-9928-421158cea3e9">

PR: https://github.com/elastic/kibana/pull/179339

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

identical

### Software version

new from 8.14

### Collaborators

PM: @approksiu 
Designer: @ARWNightingale 
Developer: @nkhristinin 
Others (if applicable):

### Timeline / deliverables

8.14

**Comment by jmikell821** [comment]
Hi @nkhristinin, thanks for filing this. Can you please attach a screenshot of the value list modal that needs copy review? Is it just one modal that needs UI copy or are there other components in the Kibana PR you linked that we need to review as well?

**Comment by nkhristinin** [comment]
> #5052

In this issue, you will see a video - it's only a modal window is new

https://github.com/elastic/security-docs/issues/5052

**Comment by nastasha-solomon** [comment]
@nkhristinin @ARWNightingale, following up on @approksiu's question [here](https://github.com/elastic/security-team/issues/8964#issuecomment-2047697366):

Is the **Import value lists** button being renamed? If so, what's the new button name, and when will users be able to see this change in the value list UI? (Which Serverless and Stack release will users be able to see the renamed button?)

If the **Import value lists** button is renamed, I'll need to update additional docs. Multiple places throughout the UI and API docs reference the **Import value lists** button, so I'll need to update all of those instances. I'll also need to refresh screenshots that show the **Import value lists** button to ensure they're up-to-date and correct.

**Comment by nkhristinin** [comment]
> Is the Import value lists button being renamed?

I didn't change any old UI, all UI in modal window is new one

**Comment by approksiu** [comment]
@nastasha-solomon I am suggesting to rename "Import value lists" link to "Value lists". 
<img width="1423" alt="image" src="https://github.com/elastic/security-docs/assets/40713348/d9163467-f980-4268-8f3c-887a469ae64e">
Could you please take a look at the tooltip as well here:
<img width="720" alt="image" src="https://github.com/elastic/security-docs/assets/40713348/f2fadff3-da56-46a2-bde1-73352f67ee02">
cc @ARWNightingale @nkhristinin

**Comment by nastasha-solomon** [comment]
@approksiu and @nkhristinin here are my copy review notes: https://docs.google.com/document/d/1h255zqBSLZWpvJlFGUYqh5Sa6fjmzEL13uFlxDkATeE/edit?usp=sharing

**Comment by nastasha-solomon** [comment]
Copy has been merged via https://github.com/elastic/kibana/pull/180929.
