### ISSUE TITLE
[Request] Update docs for ability to unassign asset criticality for host or user

### ISSUE THREAD

**Issue by jaredburgettelastic** [elastic/security-docs#5084]
#### What

We're now giving users the ability to unassign a previously assigned asset criticality from a host or user. This capability will be available from within the existing asset criticality workflows (available within entity flyouts and entity detail pages).

This capability will require DELETE privileges on the associated index (`.asset-criticality.asset-criticality-<spaceId>`).

<img width="628" alt="Screenshot 2024-04-12 at 12 25 13 AM" src="https://github.com/elastic/security-docs/assets/147995946/acbe6de7-b64f-4d8d-bd11-a4243ad15690">

#### Why

Users may wish to unassign a criticality for a few reasons, such as:
- An error was made when previously assigning criticality for an entity
- The criticality for the entity is no longer known

### Background & resources

* PRs: https://github.com/elastic/kibana/pull/180603
* Issues/metas: https://github.com/elastic/security-team/issues/8597
* Point of contact: @jaredburgettelastic 
* Test environments: See [EA long-lived environments document](https://docs.google.com/document/d/1U4LPcDH9Jxa9US5h1uk9dvJJ3vlElhQaK19db0Pcycs/edit)

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.14

### Serverless release

The week of April 22nd

### Feature differences

N/A

### API docs impact

N/A

### Prerequisites, privileges, feature flags

As described above, this capability will require DELETE privileges on the associated index (`.asset-criticality.asset-criticality-<spaceId>`).

**Comment by natasha-moore-elastic** [comment]
Thanks for opening the docs issue, @jaredburgettelastic. For serverless privileges, is there any specific user role required for unassigning asset criticality, or is it the same roles as for viewing, assigning and changing criticality (listed [here](https://docs.elastic.co/serverless/security/ers-requirements#user-roles-1))?
