### ISSUE TITLE
[Request] Document new API support for AI Assistant

### ISSUE THREAD

**Issue by dhru42** [elastic/security-docs#5088]
### Description

What: We're introducing a way for users to interface with the AI Assistant & it's features via API
Why? This allows users to chain together workflows, embed the assistant wherever users find useful.

### Background & resources

* PRs: 
* Issues/metas: https://github.com/elastic/security-team/issues/8423
* Point of contact: 
* Test environments: 

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.14

### Serverless release

tbd

### Feature differences

N/A

### API docs impact

tbd

**Comment by dhru42** [comment]
@benironside is it possible to provide a URL path of where instructions for the AI Insights will be populated?

Reason for the ask: in the UI there is a "Learn More" button which we'd like to point to these docs so if users have questions they can click on it.

see Andrew's [comment](https://github.com/elastic/kibana/pull/180611#issuecomment-2052452877)

cc: @andrew-goldstein

**Comment by benironside** [comment]
@dhru42  Here's the link (it will 404 for now though): https://www.elastic.co/guide/en/security/master/ai-insights.html

It will probably change at some point but there should be a redirect so it shouldn't break.

**Comment by dhru42** [comment]
> @dhru42 Here's the link (it will 404 until the doc is published though): https://www.elastic.co/guide/en/security/master/ai-insights.html
> 
> It will probably change at some point but there should be a redirect so it shouldn't break.

Sorry Ben...the name of this feature was changed last minute to "Attack Discovery" from "AI Insights"
Could we get a new link that reflects this change?


cc: @andrew-goldstein @jamesspi

**Comment by benironside** [comment]
No prob, that's a much better name. Here you go: https://www.elastic.co/guide/en/security/master/attack-discovery.html

**Comment by dhru42** [comment]
oh no, i just realized that I commented the above messages on the wrong ticket - they should've been in the Attack Discovery (AI Assistant) ticket.. Sorry @benironside

**Comment by dhru42** [comment]
@benironside we won't need to create docs for API support in 8.14, but can we keep the ticket open/backlogged for future release?

**Comment by benironside** [comment]
complete
