### ISSUE TITLE
[Request][Serverless & ESS] Update docs to convey release state of AI Assistant's ES|QL-query-generating functionality 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#5098]
### Description

ES|QL is going GA in 8.14, but the functionality that generates ES|QL queries is still in tech preview, so the following warning that's in the [docs](https://www.elastic.co/guide/en/security/current/security-assistant.html#ai-assistant-knowledge-base) needs to be tweaked. 
<img width="984" alt="Screenshot 2024-04-16 at 1 55 51 PM" src="https://github.com/elastic/security-docs/assets/79124755/de91e9b9-b669-46ca-ba20-ef0e07cf73e9">

The following revision was suggested by @dhru42:

> ES|QL queries generated by the AI Assistant may not be 100% accurate, so please refer to the ES|QL documentation (link) to ensure accuracy. 

### Background & resources

* PRs: N/A
* Issues/metas: N/A 
* Point of contact: @dhru42 
* Test environments: N/A

### Which documentation set does this change impact?

ESS only

### ESS release

8.14

### Serverless release

N/A

### Feature differences

N/A

### API docs impact

N/A

### Prerequisites, privileges, feature flags

N/A

**Comment by dhru42** [comment]
@nastasha-solomon could we wordsmith this to sound more confident?

`ES|QL queries generated by the AI Assistant may not be 100% accurate, so please refer to the ES|QL documentation (link) to ensure accuracy.`

I proposed the above on chat just as a guide 😄

**Comment by nastasha-solomon** [comment]
Hey, @dhru42 - sorry for not getting back to you sooner. If the entire Knowledge Base feature is still in tech preview (i.e., the functionality that generates ES|QL queries and the functionality that answers questions about alerts), we should keep the tech preview warning in the [docs](https://www.elastic.co/guide/en/security/current/security-assistant.html#rag-for-esql) but remove the line that says "Do not use ES|QL on production environments." 

Then, in the [Knowledge base for ES|QL](https://www.elastic.co/guide/en/security/current/security-assistant.html#rag-for-esql) section, we can add a note or warning that encourages users to double-check ES|QL queries generated by AI Assistant. Placing the note here increases the information's visibility and targets users who are reading about that functionality.

Let me know if you're ok with that approach, and the following revision of the language you provided:

> ES|QL queries generated by AI Assistant might require additional validation. To ensure they're correct, refer to the [ES|QL documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-language.html). 

Also if it helps to visualize the changes I'm proposing, here's an example of what they'd look like in the docs:

![Image](https://github.com/elastic/security-docs/assets/79124755/9178db02-3b73-4cb0-a430-626bd8bd9206)

**Comment by nastasha-solomon** [comment]
Serverless and ESS docs updated.
