### ISSUE TITLE
[Request][Detection Engine] GA-ing alert suppression for custom query rule

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#5104]
### Description

Moving forward with removing technical preview for custom query alert suppression. There are 3 affected areas in the UI:
- Rule creation/edit flow - it appears next to suppression input
- Alert details - correlations section 
- Alert details expanded - correlations section

### Background & resources

* PRs: https://github.com/elastic/kibana/pull/181279
* Point of contact: @yctercero @approksiu @vitaliidm 
* Test environments: TBD

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.14

### Serverless release

April 29th

### Feature differences

No feature differences - just moving into GA.

### API docs impact

- [UI docs](https://www.elastic.co/guide/en/security/current/alert-suppression.html) - Note in suppression section needs updated to specify custom query is GA.
- [API docs](https://www.elastic.co/guide/en/security/current/rules-api-create.html#opt-fields-alert-suppression-create) - Note needs to be updated to specify custom query is GA.

### Prerequisites, privileges, feature flags

No feature flags. Coordinating PR merge directly. Once in it will go out to serverless next release so need to coordinate merging into main.

**Comment by nastasha-solomon** [comment]
ESS and Serverless docs are updated!
