### ISSUE TITLE
Defend Integration policy - Malware on-write now controllable

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#5127]
### Description

Until now (8.14) Malware was a on/off toggle, with the option to set to Detect and Prevent.
We've added a toggle that adds additional control allowing the user to disable scanning malware on-write - "scan files upon modification." We have not changed any of the default configurations; this new toggle will be enabled by default to stay consistent with current behavior (malware on-write enabled).

The reason this is added is that disabling on-write (and scanning files when they are executed) can be less resource-intensive compared to scanning every file modification, improving the performance of the endpoint. It should be understood that disabling this will mean malware is only detected on execution (and will only be identified when it attempts to run); however, execute detection still provides a robust level of protection.

![image](https://github.com/elastic/security-docs/assets/26076500/c5f77ea8-8a36-43d8-8b79-1d5d2d3f9791)

### Related links / assets

Please include each of the following, if applicable:
Doc URL: https://www.elastic.co/guide/en/security/current/configure-endpoint-integration-policy.html#malware-protection
Subject matter expert: @ferullo 
Figma link(s):
Github epic link(s): https://github.com/elastic/security-team/issues/8588
Github issue link(s): 

### Which documentation set needs improvement?

ESS and serverless

### Software version

8.14

### Collaborators

PM: @caitlinbetz 
Designer: 
Developer: @ferullo @dasansol92 
Others (if applicable):

### Timeline / deliverables

Along with 8.14 release

---

```[tasklist]
### Pull Requests
- [x] Classic/stateful docs — https://github.com/elastic/security-docs/pull/5196
- [x] Serverless docs — https://github.com/elastic/staging-serverless-security-docs/pull/351
```

**Comment by ferullo** [comment]
I'll add that disability malware detection on write isn't just something users should temporarily do when debugging performance. In some scenarios it may be an adequate solution to their problem; on execute detection still provides a robust level of protection.

**Comment by ferullo** [comment]
Sorry `@das` for the ping, @caitlinbetz meant to ping @dasansol92

**Comment by caitlinbetz** [comment]
Thanks @ferullo . Sorry about that 🤦‍♀️ 

Made some tweaks to the description per your comments. Thanks!
