### ISSUE TITLE
Defend Policy option added to sync windows anti-virus registration with Malware prevention

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#5128]
### Description

We have added a new toggle in the "Register as antivirus" section of the Defend integration policy that automatically enables/disables registration if Malware prevention is disabled/enabled (benefit being, users don't need two AV products scanning for malware).

We are likely going to enable this by default in 8.15 as this is fairly common behavior across endpiont/AV solutions. 

![image](https://github.com/elastic/security-docs/assets/26076500/050fd615-ffc7-42c0-9e14-58dbf192b2ed)
![image](https://github.com/elastic/security-docs/assets/26076500/bf1238f3-826d-4ae1-aa43-92c96e056e7a)

### Related links / assets

Please include each of the following, if applicable:
Doc URL:  
https://www.elastic.co/guide/en/security/current/configure-endpoint-integration-policy.html#malware-protection
https://www.elastic.co/guide/en/security/current/configure-endpoint-integration-policy.html#register-as-antivirus

Subject matter expert: @ferullo @caitlinbetz 
Figma link(s):
Github epic link(s): https://github.com/elastic/security-team/issues/8687
Github issue link(s):

### Which documentation set needs improvement?

ESS and serverless

### Software version

8.14

### Collaborators

PM: @caitlinbetz 
Designer: 
Developer: @ferullo @dasansol92 
Others (if applicable):

### Timeline / deliverables

8.14 release docs

---

```[tasklist]
### Tasks
- [x] Clasic/stateful docs — https://github.com/elastic/security-docs/pull/5197
- [x] Serverless docs — https://github.com/elastic/staging-serverless-security-docs/pull/350
```

**Comment by ferullo** [comment]
Oops, @caitlinbetz meant @dasansol92 nit `@dasa`

**Comment by caitlinbetz** [comment]
ahh thanks @ferullo
