### ISSUE TITLE
[UI copy]: Update to UX copy for the AI Insights feature -> Attack Discovery

### ISSUE THREAD

**Issue by bojanasan** [elastic/security-docs#5133]
### Description

There was a feature name change from AI Insights to Attack Discovery that is going out with the 8.14 release. We've done our best with the short turn around however, I'd like to request a review and an update for future releases on the UX Copy guidelines and alignment with the rest of the product. 

### Related links / assets

Please include each of the following, if applicable:
Figma link(s): https://www.figma.com/file/uYQARNegEP6iQeL3IG6gac/%5BSecurity%5D-Alerts-insights?type=design&node-id=1088%3A98448&mode=design&t=7WHMEceUOV2OMGVO-1
Github epic link(s):  https://github.com/elastic/security-team/issues/7933
Github issue link(s): 
How to find the text in a production environment:
Testing environment information:
NOTE: To keep sensitive information such as credentials secure, do not include it in this form.

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

No difference

### Software version

8.14

### Collaborators

PM: @jamesspi 
Designer: @bojanasan 
Developer: @andrew-goldstein 
Others (if applicable):

### Timeline / deliverables

Ideally any updates would go in the first upcoming release possible.

**Comment by benironside** [comment]
First round of suggestions added to the Figma

**Comment by benironside** [comment]
This is complete. Reviewed and handed off.
