### ISSUE TITLE
[UI copy]: Attack discovery tour component copy

### ISSUE THREAD

**Issue by bojanasan** [elastic/security-docs#5134]
### Description

We're adding a tour component to the left nav with the addition of Attack Discovery which needs copy. 

### Related links / assets

Please include each of the following, if applicable:
Figma link(s): https://www.figma.com/file/uYQARNegEP6iQeL3IG6gac/%5BSecurity%5D-Alerts-insights?type=design&node-id=2600%3A93167&mode=design&t=7WHMEceUOV2OMGVO-1
Github epic link(s): https://github.com/elastic/security-team/issues/7933
Github issue link(s):
How to find the text in a production environment:
Testing environment information:
NOTE: To keep sensitive information such as credentials secure, do not include it in this form.

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

None

### Software version

TBD, ideally part of 8.14 (currently under way but missing copy)

### Collaborators

PM: @jamesspi 
Designer: @bojanasan 
Developer: tbd
Others (if applicable):

### Timeline / deliverables

Ideally in the next week or so. If not, we'll create a placeholder and update down the road.

**Comment by benironside** [comment]
First round of suggestions added to the Figma

**Comment by benironside** [comment]
review complete. This is handed off.
