### ISSUE TITLE
[Request] [Detection Engine][Serverless] Expose ES|QL rule in serverless

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#5135]
### Description

With ES|QL becoming available in serverless, we can now move to remove the feature flag hiding it in serverless.

### Background & resources

* PRs: TBD
* Issues/metas: https://github.com/elastic/kibana/issues/181937
* Point of contact: @yctercero 
* Test environments: TBD

### Which documentation set does this change impact?

Serverless only

### ESS release

N/A

### Serverless release

The week of May 13th

### Feature differences

NA

### API docs impact

Need to expose same docs that exist for ES|QL rule in ESS, in serverless.

### Prerequisites, privileges, feature flags

Removing existing feature flag.

**Comment by nastasha-solomon** [comment]
Notes from meeting with @yctercero today:
- Dev is targeting the **Monday, May 13, 2024** Serverless release, so docs will need to be ready for publishing by then. 
- There's no need to update Servlers API docs for the ES|QL rule as Security API docs are not exposed/hosted on the Serverless docsite. 
- @nastasha-solomon to do the following:
   - [ ] Add the following content to the Serverless docs:
       - [ ] [ES|QL rule type](https://www.elastic.co/guide/en/security/current/about-rules.html)
       - [ ] [Create an ES|QL rule](https://www.elastic.co/guide/en/security/current/rules-ui-create.html#create-esql-rule) 
   - [ ] Figure out whether the ES|QL rule docs should reference ES|QL reference content in Servlerss (which doesn't currently exist) or ES|QL content in the [ESS docset](https://www.elastic.co/guide/en/elasticsearch/reference/current/esql.html). Will ping the ES writers to learn more.

**Comment by nastasha-solomon** [comment]
PR merged
