### ISSUE TITLE
[Request] Update ES|QL rule type metadata operator syntax

### ISSUE THREAD

**Issue by vitaliidm** [elastic/security-docs#5150]
### Description

ES|QL metadata operator has changed its syntax: https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-metadata-fields.html

from

```
FROM index [METADATA _index, _id]
```

to

```
FROM index METADATA _index, _id

```

All metadata operator mentions with square brackets need to be updated

### Background & resources

* PRs: 
https://github.com/elastic/kibana/pull/182114

* Issues/metas: 
* Point of contact: 
@vitaliidm 

* Test environments: 

### Which documentation set does this change impact?

ESS only

### ESS release

8.14

### Serverless release

n/a

### Feature differences

ES|QL not yet available on Serverless

### API docs impact

All ES|QL metadata operator mentions with square brackets need to be updated

**Comment by nastasha-solomon** [comment]
Serverless and 8.14 docs updated.
