### ISSUE TITLE
[Request] add ES|QL rule alert suppression docs 

### ISSUE THREAD

**Issue by vitaliidm** [elastic/security-docs#5156]
### Description

adds alert suppression to ES|QL rule

### Background & resources

* PRs: 
https://github.com/elastic/kibana/pull/180927

* Issues/metas: 
https://github.com/elastic/security-team/issues/9203

* Point of contact:  @vitaliidm 
* Test environments: 

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.15

### Serverless release

around 8.15 release

### Feature differences

ESS: alert suppression is available for Platinum license
Serverless: available for Essentials and Complete tiers

### API docs impact

adds alert_suppression field to ES|QL rule create/update/patch rule APIs

### Prerequisites, privileges, feature flags

ESS: requires Platinum license
Feature Flag: `alertSuppressionForEsqlRuleEnabled`

**Comment by nastasha-solomon** [comment]
ESS and 8.15 docs merged!
