### ISSUE TITLE
[Enhancement]: Update Attack Discovery screenshots & GIF

### ISSUE THREAD

**Issue by dhru42** [elastic/security-docs#5223]
### Description

What: Update Attack Discovery page's screenshots and GIF's pulling assets from [this](https://www.elastic.co/blog/ai-security-analytics-integrating-anthropic-claude) blog post.

GIF sent to Ben on Slack

### Related links / assets

Please include each of the following, if applicable:
Doc URL: 
Subject matter expert:
Figma link(s):
Github epic link(s):
Github issue link(s):

### Which documentation set needs improvement?

ESS and serverless

### Software version

8.14 ESS and Serverless docs need to be updated

### Collaborators

PM:
Designer: 
Developer:
Others (if applicable):

### Timeline / deliverables

Before 8.14 release

**Comment by benironside** [comment]
complete

**Comment by benironside** [comment]
* only complete on serverless, still applicable to ESS 8.14
