### ISSUE TITLE
[DOCS] Add Threshold Rules to the list of rule types compatible with exceptions

### ISSUE THREAD

**Issue by peluja1012** [elastic/security-docs#523]
## Description 

In 7.11, we [added](https://github.com/elastic/kibana/pull/85103) support for exceptions to Threshold Rules. We should add this rule type to the list [here](https://www.elastic.co/guide/en/security/current/detections-ui-exceptions.html).

![image](https://user-images.githubusercontent.com/616158/108695166-f73cb280-74cd-11eb-96a8-a05b01ce1582.png)

## Notes

- Add the **"Team:Docs"** label to new issues. 
- Be sure to add the version number label. 
- Be sure to add any necessary screenshots for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by jmikell821** [comment]
Merged #561.
