### ISSUE TITLE
[UI copy]: Manual rule runs

### ISSUE THREAD

**Issue by nkhristinin** [elastic/security-docs#5265]
### Description

Here is more information about future.

The main issue that we should come up with better name for Backfill group

1. It's filtering by execution type status + show source event data range column
There tooltip - when we can say that it' not include lookback time, which is not super clear. Idea that - is real source range can be different if lookback time configured = actual start range = start - lookback
<img width="1822" alt="Screenshot 2024-05-28 at 15 36 53" src="https://github.com/elastic/security-docs/assets/7609147/6aa1b12b-ed1f-4dbd-b4b9-9baca35c5840">

<img width="1822" alt="Screenshot 2024-05-28 at 15 36 46" src="https://github.com/elastic/security-docs/assets/7609147/5a3d83c6-a250-48d3-829b-4179cd9b0a46">

2. Backfill group and stop of the group run

<img width="1862" alt="Screenshot 2024-05-28 at 15 36 11" src="https://github.com/elastic/security-docs/assets/7609147/b7c289cd-852a-4d0a-85a0-2486f690872d">

<img width="1839" alt="Screenshot 2024-05-28 at 15 36 16" src="https://github.com/elastic/security-docs/assets/7609147/220d4018-2ebb-4eff-8b10-02b61a7f55b2">

success tooltip

<img width="1784" alt="Screenshot 2024-05-28 at 15 36 29" src="https://github.com/elastic/security-docs/assets/7609147/c821a309-f88d-4b10-8195-f083aabc9ebc">

### Related links / assets

Please include each of the following, if applicable:
Figma link(s): https://www.figma.com/design/nZsOTIfxEbzi1KD7JUINrg/Manual-rule-runs-and-Gap-filler-%232840?node-id=1128-8817&t=iGk1Zm0aaZxdxQd5-0
Github epic link(s): https://github.com/elastic/security-team/issues/2840
Github issue link(s):
How to find the text in a production environment:
Testing environment information:
NOTE: To keep sensitive information such as credentials secure, do not include it in this form.

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

identical

### Software version

plan to release 8.15

### Collaborators

PM: @approksiu 
Designer: @ARWNightingale 
Developer: @nkhristinin 
Others (if applicable):

### Timeline / deliverables

Couple of weeks before 8.15 feature freeze

**Comment by nastasha-solomon** [comment]
Hey, @nkhristinin. I dropped a few questions in Slack about the first set of screenshots that you provided in the description. 

Here are my suggestions for the copy that was added for the second set of items (Backfill group and stop of the group run):

1. I'd recommend changing "Stop" to "Stop run" or "Stop rule run". Making the command more descriptive helps our users understand what they're stopping. It's also helpful for those relying on screen readers to navigate the UI. 

   <img width="679" alt="Screenshot 2024-06-17 at 11 36 15 AM" src="https://github.com/elastic/security-docs/assets/79124755/6aa22139-606f-4251-965c-a72cf3615537">

2. Our [UI copy guidelines](https://eui.elastic.co/#/guidelines/writing/guidelines#messages) say to avoid using "Are you sure", and to be more direct when addressing users. Here's a few options for the title in the confirmation message:
   - **Option 1:** Stop running this rule
   - **Option 2:** Stop this rule run
   - **Option 3:** Stop the rule from running  
   
   I'm not quite sure what the text in the body explains. It sort of looks like a user manually ran a rule multiple times, and the first run, plus every subsequent run after that, is being stopped. If that's the case, here's some potential revisions:
   - **Option 1:** The current rule run, and any other that you set up, will be stopped. 
   - **Option 2:** This action stops the current rule run and any additional ones that you set up. 


     <img width="686" alt="Screenshot 2024-06-17 at 11 36 10 AM" src="https://github.com/elastic/security-docs/assets/79124755/80abfce0-7216-410e-ad62-ad888ef6f05f">


3. Just reccomend being a bit more descriptive here and changing "Run stopped" to "Rule run stopped". Also, does a different message display if the rule had more than one manual rule run in queue?  

   <img width="683" alt="Screenshot 2024-06-17 at 11 36 22 AM" src="https://github.com/elastic/security-docs/assets/79124755/24d2d4ba-9e80-41b5-83bb-14f9f1f3ac2a">

**Comment by nkhristinin** [comment]
> I'm not quite sure what the text in the body explains. It sort of looks like a user manually ran a rule multiple times, and the first run, plus every subsequent run after that, is being stopped. If that's the case, here's some potential revisions:


When user execute manual run - it create a group, which can contain several potenial rule execution

Let's say - 1 manual rule run group has 10 tasks:
- 6 completed
- 4 pending

We can stop only the whole group, so means 4 pending tasks will be canceled

**Comment by nkhristinin** [comment]
> Also, does a different message display if the rule had more than one manual rule run in queue?

No, as we always just stop the whole group

**Comment by nkhristinin** [comment]
@nastasha-solomon do you thinks it's clear from this UI, what total,completed,error etc means?

**Comment by nastasha-solomon** [comment]
> @nastasha-solomon do you thinks it's clear from this UI, what total,completed,error etc means?

I think all of the columns in the second table could use tooltips, similar to the Execution log table at the top of the tab. I can help with the wording, but I'll need explanations for what each column displays. @approksiu would you be able to help with that?

**Comment by nkhristinin** [comment]
>I think all of the columns in the second table could use tooltips, similar to the Execution log table at the top of the tab. I can help with the wording, but I'll need explanations for what each column displays. @approksiu would you be able to help with that?

I can also try to help with that:

Status - it's status of the whole Manual run group - can be Pending, Running,
Created at - when user execute manual rule run
Source event time range - it's the date range which user select when execute manual rule run

Also each Manual run can have multiple tasks/rule execution to cover this date range:

Total - total amount of tasks (rule executions) which this manual run has.
Completed - number of completed tasks/rule executions
Running - number of tasks/rule executions which is progress
Pending - number of tasks which wait to be queued by task manager
Error - Number of failed tasks/rule executions

**Comment by nastasha-solomon** [comment]
Thanks for providing a starting point, @nkhristinin. Here's my crack at the descriptions for the table columns:

_(Note that some of these descriptions are identical to the corresponding columns in the` Execution log` table.)_

- **Status**: Overall status of execution 
- **Created at**: When the manual run was started
- **Source event time range**: The date and time range selected for the manual run
- **Total**: The total number of times this manual run was executed
- **Completed**: The number of completed manual run executions
- **Running**: The number of manual runs that are executing
- **Pending**: The number of manual runs that are waiting to execute 
- **Error**: The number of failed manual run executions

**Comment by approksiu** [comment]
@nastasha-solomon I have the suggestions for the following:
>     * **Total**: The total number of times this manual run was executed
>     * **Completed**: The number of completed manual run executions
>     * **Running**: The number of manual runs that are executing
>     * **Pending**: The number of manual runs that are waiting to execute
>     * **Error**: The number of failed manual run executions

Total: The total number of tasks this manual run will execute
Completed: The number of completed manual run task executions
Running: The number of manual run tasks that are executing
Pending: The number of manual run tasks that are waiting to execute
Error: The number of failed manual run tasks executions

**Comment by approksiu** [comment]
![image](https://github.com/elastic/security-docs/assets/40713348/5f7f1158-1d23-4f5c-9f20-7569696cce1f)
Suggestion for the tooltip copy for the above screenshot:
"Applies to manual run rule executions. The actual time range will also include lookback time according to the rule settings."
 cc @nastasha-solomon @nkhristinin

**Comment by approksiu** [comment]
How about "View and manage active manual runs" for the info under "Manual runs" table header? cc @nastasha-solomon @nkhristinin

**Comment by approksiu** [comment]
>     1. I'd recommend changing "Stop" to "Stop run" or "Stop rule run". Making the command more descriptive helps our users understand what they're stopping. It's also helpful for those relying on screen readers to navigate the UI.

I vote for "Stop run" option. cc @nastasha-solomon @nkhristinin

**Comment by approksiu** [comment]
>     2. See notes below for the copy that appears in the confirmation modal:
>        #### Title
>        Our [UI copy guidelines](https://eui.elastic.co/#/guidelines/writing/guidelines#messages) say to avoid using "Are you sure", and to be more direct when addressing users. Here's a few options for the title in the confirmation message:
>        
>        * **Option 1:** Stop running this rule
>        * **Option 2:** Stop this rule run
>        * **Option 3:** Stop the rule from running
>        
>        #### Body text
>        ~I'm not quite sure what the text in the body explains. It sort of looks like a user manually ran a rule multiple times, and the first run, plus every subsequent run after that, is being stopped. If that's the case, here's some potential revisions:~
>        ~- **Option 1:** The current rule run, and any other that you set up, will be stopped.~
>        ~- **Option 2:** This action stops the current rule run and any additional ones that you set up.~
>        Updated copy options for the body text:
>        
>        * **Option 1:** The current rule run and pending ones will be stopped.
>        * **Option 2:** This action stops the current rule run and any pending ones.

For the **Title**, let's use **Option 2:** Stop this rule run
For the **Body**, I'd suggest to use something like: "All the pending rule executions for this manual rule run will be stopped".

@nastasha-solomon what do you think?
cc @nkhristinin

**Comment by nastasha-solomon** [comment]
Closing since no other changes are happening to the manual runs table for Servlerss/8.16.
