### ISSUE TITLE
[Request] Elastic Integrations Assistant 

### ISSUE THREAD

**Issue by jamiehynds** [elastic/security-docs#5272]
### Description

We're introducing a new AI-driven workflow to assist users with ingesting data from sources we don't have out of the box integrations for. Today, when a user has to ingest custom data, they are faced with steep learning curves in terms of building custom pipelines, getting familiar with the ECS schema - it's a very daunting and length process to get custom data in. 

This new workflow (we're calling it Integrations Assistant, but name TBD) will allow them to provide a set of sample logs, and use AI to build the pipeline with ECS mappings, so they can ingest their custom data in minutes. 

### Background & resources

* Issues/metas: https://github.com/elastic/security-team/issues/9570
* Demo: https://drive.google.com/file/d/1hw8E7qboLQ15nsfH5VYKB2f2KKNNvjWT/view?usp=sharing

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.15

### Serverless release

Sometime in October, inline with the 8.15 stack release 

### Feature differences

Feature will behave the same in both. 

### API docs impact

N/A

### Prerequisites, privileges, feature flags

Enterprise license will be required for ESS.
Complete licenses will be required for Serverless.

**Comment by benironside** [comment]
Complete - doc published
