### ISSUE TITLE
[BUG] Missing updates in 'What's new in 8.14'

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#5323]
### Documentation links

https://www.elastic.co/guide/en/security/8.14/whats-new.html

### Description

The What’s new in 8.14 section misses following updates:
- Wildcard warnings for event filters and endpoint exceptions
- S1 and response actions improvements
        - Isolate
        - Release

### Which documentation set(s) does this bug apply to?

ESS only

### Release version

8.14.0

### Testing environment

Cloud platform for 8.14.0

**Comment by manishgupta-qasource** [comment]
Reviewed and assigned to @jmikell821

**Comment by natasha-moore-elastic** [comment]
Hi @muskangulati-qasource, thanks for raising this! We've had a look and these sound like features that we've already documented in previous release highlights:

* https://www.elastic.co/guide/en/security/8.12/whats-new.html#_event_filters_and_endpoint_exceptions_support_for_matches_and_does_not_match_conditions
* https://www.elastic.co/guide/en/security/8.13/whats-new.html#_third_party_response_actions_sentinelone

If this isn't what you're referring to, feel free to re-open this issue and please provide more details about the features and/or any related development issues/PRs.
Thank you!
