### ISSUE TITLE
[BUG] Only 02 count is shown for agent type. It is updated to 04

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#5324]
### Documentation links

https://www.elastic.co/guide/en/security/8.14/response-actions-history.html

### Description

The agent types are added for SentinelOne and Endpoint type.

**Screenshots**
- Actual
![2_Actual](https://github.com/elastic/security-docs/assets/60252716/56915850-52fd-4706-8fbc-d10f8ce39328)

- Expected
![2_Expected](https://github.com/elastic/security-docs/assets/60252716/d6b72d46-9866-4cf6-a3c3-44c788acf0c0)

### Which documentation set(s) does this bug apply to?

ESS only

### Release version

8.14.0

### Testing environment

Cloud platform for 8.14.0

**Comment by joepeeples** [comment]
I think we're OK not fixing this for now. It's a very minor detail that most readers probably wouldn't notice, and is unlikely to confuse or mislead them even if they did notice it.
