### ISSUE TITLE
[BUG] Screenshot needs to be updated to show option added 'scan malware'

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#5325]
### Documentation links

https://www.elastic.co/guide/en/security/8.14/admin-page-ov.html

### Description

**Screenshots**:
- Actual
![3_Actual](https://github.com/elastic/security-docs/assets/60252716/7855af8c-b5cb-4bc1-b9c9-e8d06f6e812d)

- Expected
![3_Expected](https://github.com/elastic/security-docs/assets/60252716/cd5c20ac-c881-42c8-855d-4de8026f93f5)

### Which documentation set(s) does this bug apply to?

ESS only

### Release version

8.14.0

### Testing environment

Cloud platform for 8.14.0

**Comment by manishgupta-qasource** [comment]
Reviewed and assigned to @jmikell821
