### ISSUE TITLE
[BUG] No mention of SentinelOne agents supporting automated actions: isolate

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#5326]
### Documentation links

- https://www.elastic.co/guide/en/security/8.14/response-actions-config.html
- https://www.elastic.co/guide/en/security/8.14/third-party-actions.html
- https://www.elastic.co/guide/en/security/8.14/response-actions-history.html

### Description

The actions supported for SentinelOne agent are different from those supported by Endpoints

### Which documentation set(s) does this bug apply to?

ESS only

### Release version

8.14.0

### Testing environment

Cloud platform for 8.14.0

**Comment by joepeeples** [comment]
AFAIK SentinelOne _automated_ actions are not yet supported; https://github.com/elastic/security-team/issues/8053 is still open and actively being discussed. We already document the available manually-triggered actions for SentinelOne in https://www.elastic.co/guide/en/security/8.14/third-party-actions.html, including isolate. 

Currently that's the only place where we want to document S1-specific actions, to avoid having to update information throughout multiple other pages (such as [response-actions-config.html](https://www.elastic.co/guide/en/security/8.14/response-actions-config.html) and [response-actions-history.html](https://www.elastic.co/guide/en/security/8.14/response-actions-history.html)) as we add new supported S1 actions.
