### ISSUE TITLE
[Security Solution][Doc]Missing Dashboard and Incorrect Beta Tag

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#5327]
**Describe the bug:**
[Doc]Incorrect icon of beta instead it should be technical preview

**URL**
- https://www.elastic.co/getting-started/security/detect-threats-in-my-data-with-siem

**Steps to reproduce**
- Navigate to https://www.elastic.co/getting-started/security/detect-threats-in-my-data-with-siem.
- Scroll down to "Working with Elastic Security" topic.

**Expected Result**
- Beta tag should not show for "Kubernetes" dashboard.
- "Cloud Native Vulnerability Management" Dashboard should not be present.

**Screen-cast**

![image](https://github.com/elastic/kibana/assets/59917825/f8ecc9a7-0021-497e-82e7-929b548caa11)

**Comment by joepeeples** [comment]
The Docs team doesn't maintain the content at https://www.elastic.co/getting-started/security/detect-threats-in-my-data-with-siem.
