### ISSUE TITLE
[Security Solution][Doc]Text Content of asset criticality not matching

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#5329]
**Describe the bug:**
[Doc]Text Content of asset criticality not matching

**URL**
- https://www.elastic.co/guide/en/security/8.14/whats-new.html#_asset_criticality_file_upload

**Steps to reproduce**
- Navigate to https://www.elastic.co/guide/en/security/8.14/whats-new.html#_asset_criticality_file_upload
- scroll down to Asset Criticality
- Observed that text is not matching in documentation

**Expected Result**
- Asset Criticality content should match 

**Screen-cast**

![image](https://github.com/elastic/kibana/assets/59917825/d9508f63-0c05-4dca-ba74-f1e291aa493a)

**Comment by jaredburgettelastic** [comment]
Thanks for this @karanbirsingh-qasource !

@natasha-moore-elastic please let me know if you need any environment creation assistance in this effort.
