### ISSUE TITLE
[Security Solution][Doc]Elastic AI Assistant sub feature missing 

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#5330]
**Describe the bug:**
[Doc]Elastic AI Assistant sub feature missing 

**URL**
- https://www.elastic.co/guide/en/security/8.14/case-permissions.html

**Steps to reproduce**
- Navigate to https://www.elastic.co/guide/en/security/8.14/case-permissions.html
- scroll down and observe the kibana privileges
- Observed sub feature is missing for Elastic AI Assistant

**Expected Result**
- Elastic AI Assistant sub feature should be shown in screenshot

**Screen-cast**

![image](https://github.com/elastic/kibana/assets/59917825/6c9190bd-4d02-4e4d-a4e3-57c7e216de8b)

**Comment by joepeeples** [comment]
I think we're OK not fixing this for now. It's a very minor detail that's unrelated to what the image is actually illustrating (the Cases feature, not AI Assistant). Most readers probably wouldn't notice this, and it's unlikely to confuse or mislead them even if they did notice it.
