### ISSUE TITLE
[Security Solution][Doc]Up to keyboard missing for Attack Discovery

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#5331]
**Describe the bug:**
Up to keyboard missing for Attack Discovery

**URL**
- https://www.elastic.co/guide/en/security/8.14/attack-discovery.html

**Steps to reproduce**
- Navigate to https://www.elastic.co/guide/en/security/8.14/attack-discovery.html
- scroll down and observe the Attack Discovery
- Observed that text up to text is missing

**Expected Result**
- Up to 20 alerts will be analyzed

**Screen-cast**

![image](https://github.com/elastic/kibana/assets/59917825/01b2a7cf-7088-4beb-a3e5-1eb10e4b1844)

**Comment by joepeeples** [comment]
We're OK not updating the image. It's a very minor detail that shouldn't affect user experience.
