### ISSUE TITLE
[BUG] Information missing in Docs for Events Filter new warning message added.

### ISSUE THREAD

**Issue by sukhwindersingh-qasource** [elastic/security-docs#5332]
### Documentation links

https://www.elastic.co/guide/en/security/8.14/event-filters.html

### Description

- No information is present for the new warning message added in the 8.13.0 release under Events Filter as per this feature ticket
- Feature ticket link :  https://github.com/elastic/security-team/issues/8734

![image](https://github.com/elastic/security-docs/assets/108654988/2498edf0-9e9a-4d66-85c9-092839ae47cf)

### Which documentation set(s) does this bug apply to?

ESS only

### Release version

This bug applies to the stack version 8.14.0

### Testing environment

8.14.0 BC7

**Comment by sukhwindersingh-qasource** [comment]
@muskangulati-qasource Kindly review this

Thanks !

**Comment by muskangulati-qasource** [comment]
Reviewed and assigned to @jmikell821

**Comment by joepeeples** [comment]
The in-app warning messages convey everything the user needs to know. And the docs already indicate that the `?` and `*` wildcard characters are supported for the `matches` | `does not match` operators. We could try to be even more explicit and say something like "and wildcards are NOT supported for any other operators," but that seems like unnecessary over-explanation.
