### ISSUE TITLE
[Request][8.15 & Serverless] Update the Security Timeline Documentation in accordance with new Unified Timeline changes

### ISSUE THREAD

**Issue by logeekal** [elastic/security-docs#5341]
### Description

Recently, security team undertook a project to revamp timeline UI with a goal to give users a unified experience across Security.

With this project, we extended timeline experience to be very similar to Discover data viewing experience.

This does NOT changes the timeline functionality in anyway but only UI and how a user interacts with timeline.

### Background & resources

* PRs: 
   * https://github.com/elastic/security-team/issues/8726
   * https://github.com/elastic/security-team/issues/8727
   * https://github.com/elastic/security-team/issues/9091 
* Issues/metas: 
* Point of contact: @logeekal ( Jatin Kathuria ), @kqualters-elastic (Kevin Qualters)
* Test environments: 

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.15

### Serverless release

21 June 2024

### Feature differences

These changes only affect `Query` and `Correlation` tab hence there will screenshot updates needed in both places.

- https://www.elastic.co/guide/en/security/8.14/timelines-ui.html#timelines-ui
- https://www.elastic.co/guide/en/security/8.14/timelines-ui.html#conf-timeline-display
- https://www.elastic.co/guide/en/security/8.14/timelines-ui.html#filter-with-eql

#### Table

✅ Screenshot update needed in docs

Below you can see tables side by side.

|Pre 8.15| Post 8.15 |
|--|--|
|![grafik](https://github.com/elastic/security-docs/assets/7485038/284e72d8-f8ed-44b0-9cc7-de568af07840)| ![grafik](https://github.com/elastic/security-docs/assets/7485038/44ae61ce-cd88-4428-9f40-3f8ff7580ef9) |

1. Table Cells are no long draggable. But I could not find any docs where it was mentioned so I guess no changes are needed in docs. But please double check.
2. [Event Renderers](https://www.elastic.co/guide/en/security/8.14/timelines-ui.html#conf-timeline-display) remain as it is and there are no changes.
3. 💡 (Addition) Users are not able choose multiple records and perform below bulk actions on those rows. 
	1. Show selected Documents only
	2. Copy documents to Clipboard
	3. See below video : 
4. Records are not fetched page by page but we fetch 500 records in one go and then user has the option to load more 500 by going to the last page and clicking on load more. See below video where I changes `Sample size` to 20 to demonstrate the functionality. but by default it is 500.
     
https://github.com/elastic/security-docs/assets/7485038/a3e614d6-4b84-477f-aee6-be1529fb1f31

6. `Last updated` moved from bottom of the table to top of the table.

|Pre 8.15| Post 8.15 |
|--|--|
|![Bildschirmfoto 2024-06-07 um 09 54 30](https://github.com/elastic/security-docs/assets/7485038/66e41b32-0b8e-4548-a7fe-3dec313463f2)| ![Bildschirmfoto 2024-06-07 um 09 53 34](https://github.com/elastic/security-docs/assets/7485038/5387aa89-2da0-41ce-82c6-ecb32141486e) |

#### Field Browser

✅Screenshot update needed.

See below for comparison in using Field Browser in `Pre 8.15` v/s `Post 8.15` versions.

| Pre 8.15 | Post 8.15 |
| -------- | --------- |
|     <video src="https://github.com/elastic/security-docs/assets/7485038/620ee4c5-c200-4dc2-b8cd-914e2a45f358" />|           <video src="https://github.com/elastic/security-docs/assets/7485038/30a40141-9263-4715-ad00-0d066084ab68" />|
1. User are able to see the statistic pertaining to any field by clicking on any field as shown below:
2. Fields can be added to the table by simple dragging a field to the table.
3. Fields can also be added or removed from the table by clicking ⊕ or ❌ icon.

#### ESS (8.15)
The following areas in the [Investigate in Timeline](https://www.elastic.co/guide/en/security/current/timelines-ui.html) topic:

- [x] `timeline-ui-updated.png`
- [x] `timeline-ui-renderer.png`
- [x] `correlation-tab-eql-query.png`
- [x] See [notes](https://docs.google.com/document/d/1jKDZ7PXFqmPk82eXz5tGjKhYgzQ2phkLvvxtWR6CfvY/edit?usp=sharing) in the audit of the "Investigate in Timeline" topic.

The following areas in the [About Timeline templates](https://www.elastic.co/guide/en/security/current/timeline-templates-ui.html) topic:

- [x] `create-a-timeline-filter.png`
- [x] See [notes](https://docs.google.com/document/d/1jKDZ7PXFqmPk82eXz5tGjKhYgzQ2phkLvvxtWR6CfvY/edit?usp=sharing) in the audit of the "Investigate in Timeline" topic.

Images in the [Launch Timeline from investigation guides](https://www.elastic.co/guide/en/security/current/interactive-investigation-guides.html) topic will need to be refreshed as well. 
   - [x] `ig-timeline.png`
   - [x] `ig-timeline-query.png`
   - [x] `ig-timeline-template-fields.png`

Main image in the [Timeline schema](https://www.elastic.co/guide/en/security/current/timeline-object-schema.html) topic:
- [x] `timeline-object-ui.png` (just need to refresh parts 9 and 10 of the image)

#### Serverless
Update all the same topics and images. 

### API docs impact

No Impact

**Comment by nastasha-solomon** [comment]
Thanks for filing this, @logeekal! I've left some additional comments and questions below. 

> Table Cells are no long draggable. But I could not find any docs where it was mentioned so I guess no changes are needed in docs. But please double check.

The first sentence in the second paragraph [here](https://www.elastic.co/guide/en/security/current/timelines-ui.html) mentions draggable fields. Are those the draggable cells that you're referring to? If so, I'll also need to remove (or possibly update?) [these docs](https://www.elastic.co/guide/en/security/current/es-ui-overview.html#draggable-timeline-elements) that explain how to interact with draggable Timeline elements.

On a related note, have the changes to Timeline removed or updated any of the accessibility features listed [here](https://www.elastic.co/guide/en/security/current/es-ui-overview.html#timeline-accessibility-features)? If they have, we'll need to update the docs and screenshots in the section I linked.

> Users are able to see the statistics pertaining to any field by clicking on any field
 
Can you give an example of this? For instance, what does the following image tell users about the `agent.type` field and what can/should they do with that information? A general walk-through of the modal would be helpful too. At first glance, I'm not really sure what's all included and why.

<img width="400" alt="Screenshot 2024-06-07 at 12 34 16 PM" src="https://github.com/elastic/security-docs/assets/79124755/f6bec24c-f5f2-42ea-8f6b-46fba6629693">

**Comment by logeekal** [comment]
## New Additions


### Row Renderer Switch

Security has introduced a new switch which users can use to switch event renderers on/off. It is visible in the video below.

It also shows a tooltip which tells users that enabling row renderers may impact performance.

> [!NOTE]
> Please check if the content of the toop tip makes sense. 

https://github.com/elastic/security-docs/assets/7485038/7c10bae4-a1cf-4e35-9c8b-cc76f68aa2ee

### Notes in flyout

Notes are no longer part of even row. Below you can see the screenshot from before v/s new behaviour.

> [!NOTE]
>
> 
> Here we show 3 types of tooltips when user hover over Notes button. Please let me know if they makes sense from docs perspective.
> 
> 1. Add Note. ( When no notes are available )
> 2. 1 Note available. Click to view them & add more.
> 3. 2 Notes available. Click to view them & add more.


|Before|After|
|---|---|
||<video src="https://github.com/elastic/security-docs/assets/7485038/ca313ea0-dbe5-4951-b86b-34bb8bcb63dc" />|

**Comment by nastasha-solomon** [comment]
@logeekal here are a couple of suggestions about the tooltip for the new toggle that allows users to enable/disable the event renderer:
- In the [docs](https://www.elastic.co/guide/en/security/current/timelines-ui.html#conf-timeline-display) and UI, we call the row renderer feature the **event renderer**. It looks like we've been capitalizing "event renderer" in the UI and keeping it lowercase it in docs. I'm partial to keeping it lowercase in the docs and UI, but I'm not sure how easy it is to make that change in the tooltip that appears when users hover over the icon that allows them to customize event renderers (see image below). 

     <img width="315" alt="Screenshot 2024-07-02 at 11 30 32 PM" src="https://github.com/elastic/security-docs/assets/79124755/877452a2-75e1-4dc2-b3b2-03b112108532">

     I also don't know if there's a preference from other stakeholders (for example, Product) to capitalize the term. If it's not too difficult and there are no other asks to keep the capitalization as is, I'd suggest using lowercase in the UI and changing "row renderer" to "event renderer" in the tooltip.

- When possible, we try to avoid using ableist terms like "enable" or "disable" in the UI. Can we change the tooltip copy to the following instead:
Turning on event renderers might impact table performance.

**Comment by logeekal** [comment]
Thanks @nastasha-solomon for the feedback. I think changes suggested by you makes sense. Let me make those changes.

and it is a fairly quick change.
