### ISSUE TITLE
[SIEM] Update perm documentation for detections

### ISSUE THREAD

**Issue by elauqsap** [elastic/security-docs#536]
**Describe the feature:**
The [documentation](https://www.elastic.co/guide/en/security/7.9/detections-permissions-section.html) around permissions for CRUD operations in the detections of the SIEM app is confusing. Clearer guidance on how to achieve various combinations of CRUD with the individual index perms would be appreciated as well as warnings about index vs alias when assigning perms in the role.

**Describe a specific use case for the feature:**
As an administrator I would like to create a user that can read all of the rules in the SIEM app
As an administrator I would like to create a user that can create, read, and update all of the rules in the SIEM app
As an administrator I would like to create a user that can create, read, update, and delete all of the rules in the SIEM app

**Comment by jmikell821** [comment]
Hi @elauqsap, so sorry for the late reply! We merged this change some time ago and updated [this topic](https://www.elastic.co/guide/en/security/7.14/detections-permissions-section.html) with more explicit instructions. Would appreciate your feedback if you find it clearer. Thank you!
