### ISSUE TITLE
[DOCS]: Unified Detection Alerts View

### ISSUE THREAD

**Issue by dontcallmesherryli** [elastic/security-docs#54]
## Description 

**Meta Issue:** https://github.com/elastic/endpoint-app-team/issues/372
**Link to Mocks** https://www.figma.com/file/LsjbVEOGXX4iPHqoqQL8mc/Endpoint-Screens-and-Components?node-id=1269%3A125098

As an analyst, I want to be able to view all alerts on a page and search/filter/sort fields in the Detection Alerts view. As a user, I want to have a single unified place to see all alerts coming from Elastic Endpoints, 3rd party logs, and detection engine created so that I can have a holistic and uniformed triage process for all of my alerts.

## Acceptance Test Criteria

Documentation required to point out following changes to the Detection Alert page in 7.9:
1. Open, In Progress, and Closed Alerts filters on alert list
2. Action overflow menu (https://github.com/elastic/kibana/issues/65945)
   1. Actins not in overflow - Investigate in Timeline, Analyze Event
   2. Action in overflow - Mark In Progress, Close selected, Add Exceptions, Add Endpoint Exception, Edit Actions
3. Signals now called Detection Alerts (https://github.com/elastic/kibana/issues/65944)
4. Remove External Alerts tabs
5. Toast success and failed messages on status change of alerts to closed, in progress, reopen (https://github.com/elastic/kibana/pull/67406)
6. Sticky column preferences - Columns and row rendered preferences are stored per-user base (https://github.com/elastic/siem-team/issues/589)

## Notes

- Add the **"Team:Docs"** label to new issues. 
- Be sure to add any necessary screenshots for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by dontcallmesherryli** [comment]
@benskelker we need to add the ability for users to go full screen mode in the alert page, as well as in the timeline.

**Comment by benskelker** [comment]
Hi @dontcallmesherryli, @jmikell821 

As all event and alert tables in the app can be viewed in full screen, let's also add this to over overview/UI stuff. I'll include it as a tip in the Managing alerts section.

**Comment by benskelker** [comment]
Documented as part of #73
