### ISSUE TITLE
Documentation for filtering process descendants in Event Filters [Request]

### ISSUE THREAD

**Issue by gergoabraham** [elastic/security-docs#5402]
### Description

In the context of Security / Management / Event Filters, we're introducing a new option to not simply filter Events, but filter events from all descendants of a given process - while the events from the process itself are still ingested.

Expand below to see the new Events | Process Descendants button group on the screenshots.

<details>

<img width="1060" alt="image" src="https://github.com/elastic/security-docs/assets/39014407/d441c67b-f998-4e5a-8a7b-6653c75beae1">

<img width="902" alt="image" src="https://github.com/elastic/security-docs/assets/39014407/43b4dfab-1d6d-4152-a021-1844edd53ef3">

</details>

### Background & resources

* PRs: 
  * https://github.com/elastic/kibana/pull/184947
* Issues/metas: 
  * https://github.com/elastic/endpoint-dev/issues/14226
  * https://github.com/elastic/security-team/issues/9339
* Point of contact: @ferullo @dasansol92 @gabriellandau @gergoabraham 
* Test environments: Kibana side is still under development

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.15

### Serverless release

August - synced around 8.15 release

### Feature differences

They're the same.

### API docs impact

there should be no impact here

### Prerequisites, privileges, feature flags

Feature flag on Kibana:
`xpack.securitySolution.enableExperimental.filterProcessDescendantsForEventFiltersEnabled`

---

```[tasklist]
### Pull requests
- [x] ESS – https://github.com/elastic/security-docs/pull/5626
- [x] Serverless – https://github.com/elastic/security-docs/pull/5672
```

**Comment by joepeeples** [comment]
Release timeline means we can merge ESS docs to main now, but for serverless docs we need to wait until shortly after 8.15.0 release to merge.
