### ISSUE TITLE
[Request] Add criticality column to All Users table In Explore pages

### ISSUE THREAD

**Issue by jaredburgettelastic** [elastic/security-docs#5448]
### Description

What: We are introducing a new column to both the "All Hosts" and "All Users" pages within the Explore section of the Security solution, which shows the associated asset criticality value for that entity.
Why: In order to give analysts more contextual information as they explore their hosts and users
How: When the asset criticality feature is enabled, and an asset criticality value is assigned for a host or user, that value will be visible on these pages

**From a documentation standpoint, based on reading the current docs, there may be no changes required for this new feature,** as I was unable to find any documentation specific to the "All Hosts/Users" tabs. 

### Background & resources

* PRs: https://github.com/elastic/kibana/pull/186375 & https://github.com/elastic/kibana/pull/186456#event-13226246566
* Issues/metas: https://github.com/elastic/security-team/issues/9737
* Point of contact: @jaredburgettelastic or @tiansivive 
* Test environments: https://kibana.siem.estc.dev should have this available by June 24th

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.15

### Serverless release

July 1, 2024

### Feature differences

N/A

### API docs impact

N/A

**Comment by natasha-moore-elastic** [comment]
I think you're right @jaredburgettelastic – it doesn't look like any of the docs need updating, so I'll close this issue. Thanks for keeping us in the loop!
