### ISSUE TITLE
[DE Team][8.16 & Serverless] Case system action being added for rules

### ISSUE THREAD

**Issue by dhurley14** [elastic/security-docs#5457]
## Description 

Ticket for docs updates that will be required for new system actions feature.

Related:
- @dhurley14 add draft PR
- Epic: https://github.com/elastic/security-team/issues/9263

## Notes
To keep in mind:
- UI changes (new Cases action icon within rule actions section)
- Will be tech preview

### Serverless docs
[Create a detection rule | Set up alert notifications (optional)](https://www.elastic.co/guide/en/security/master/rules-ui-create.html#rule-notifications): 
- [x] Tweak the title so that it shows users can set up rule actions or notifications. Will also need to make the same change the the fifth step in the list at the start of the "Create a detection rule" page.
- [x] In the section that describes rule actions, add [this info](https://www.elastic.co/guide/en/kibana/current/create-and-manage-rules.html#defining-rules-actions-details). 

### 8.16 docs
- [x] Same changes as above

**Comment by nastasha-solomon** [comment]
Plan for Serverless and 8.16 docs:

- Serverless doc updates are outlined in the first list item above. Should aim to have docs published by next Tuesday (July 30), or Wednesday morning (July 31) at the latest. 
- 8.16 docs updates can be made post-8.15. They'll consist of the following: 
  - [ ] Doc updates outlined in this issue's description
  - [ ] Release notes 
 
 cc: @dhurley14 @yctercero

**Comment by nastasha-solomon** [comment]
ESS and Serverless docs updated.
