### ISSUE TITLE
[UI copy]: Attack Discovery Notification

### ISSUE THREAD

**Issue by bojanasan** [elastic/security-docs#5461]
### Description

The Notification feature will let the user know when their Attack Discovery has finished analysing the alerts. The user will be notified via toast of a success or an error with the generation. Once they click on the link they will go to the relevant Attack Discovery. Each connector can run an Attack Discovery independently.  

### Related links / assets

Please include each of the following, if applicable:
Figma link(s): [mocks](https://www.figma.com/design/PRoCaFHvOv1JIWES3IN5wM/%5B8.15%5D-Attack-Discovery%3A-Notification-%26-Save?node-id=4556-14647&t=Om2aMGUKNfUXonQ3-1)
Github issue link(s): [Design issue](https://github.com/elastic/security-team/issues/9763)

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

None

### Software version

8.15

### Collaborators

PM: @jamesspi 
Designer: @bojanasan 
Developer: @stephmilovic 
Others (if applicable):

### Timeline / deliverables

in time for 8.15 release

**Comment by bojanasan** [comment]
In particular we need review of the toasts both for a Successful Attack Discovery and one that returns an error. These are the most relevant screens for that:

![image](https://github.com/elastic/security-docs/assets/1832102/21b4e275-48ba-4989-a829-86308b72a2ae)

![image](https://github.com/elastic/security-docs/assets/1832102/58823292-b16a-44a2-b959-d7259d59f6b7)

**Comment by benironside** [comment]
Review complete
