### ISSUE TITLE
[UI copy]: Stack Management Security AI Assistant Settings

### ISSUE THREAD

**Issue by bojanasan** [elastic/security-docs#5462]
### Description

We have moved the bulk of the Security AI Assistant Settings to the AI Assistant pages in Stack Management. I'd like to request a review of the UI copy for clarity. 

### Related links / assets

Please include each of the following, if applicable:
Figma link(s): [final mocks](https://www.figma.com/design/BMvpY9EhcPIaoOS7LSrkL0/%5B8.15%5D-GenAI-Security-Assistant-Settings%3A-Stack-Management-Pages?node-id=93-33273&t=HNfdsnBZTEJKOWMw-1)
Github epic link(s): https://github.com/elastic/security-team/issues/9222#issue-2249405144
Github design issue link(s): https://github.com/elastic/security-team/issues/9493

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

None

### Software version

8.15

### Collaborators

PM: @jamesspi 
Designer: @bojanasan 
Developer: @yichun0210 
Others (if applicable):

### Timeline / deliverables

Ideally 8.15

**Comment by bojanasan** [comment]
@benironside link updated

**Comment by benironside** [comment]
Review complete, sent comments to Bo
