### ISSUE TITLE
[UI copy]: [Security Solution] Flyout navigation copy

### ISSUE THREAD

**Issue by christineweng** [elastic/security-docs#5484]
### Description

We are introducing the preview navigation in the exiting alert flyout experience. In 8.15 (currently behind a feature flag), a user can click on a host name, and a preview of the host flyout will appear. This allows the user to see the host information without leaving the original alert context. The same is applied to user name (opens a user entity flyout in preview mode), and alerts (opens another alert in preview mode).

The preview mode disallows any expand capability, but there is a footer with a link to open an "actual" flyout. 

Requsting a copy review of the text added:

### Host preview
- preview banner: `Preview host`
- link in the footer: `Open host details flyout` (or `Replace with this flyout` from design)

![image](https://github.com/elastic/security-docs/assets/18648970/e021e7d7-6433-4742-88f7-87637816cfab)

### User preview
- preview banner: `Preview user`
- link in the footer: `Open user details flyout` (or `Replace with this flyout` from design)

![image](https://github.com/elastic/security-docs/assets/18648970/01081031-75ce-49cc-8f8e-ddf70966cdd0)

### Alert preview
- preview banner: `Preview alert`
- investigation guide (in normal flyout it is a button that opens the investigation section in left panel): 
`You are currently in preview mode. Switch to this flyout to access all expandable options.`
- Response action (in normal flyout it is a button that opens the response section in left panel): 
`You are currently in preview mode. Switch to this flyout to access all expandable options.`
- link in the footer: `Open alert details flyout` (or `Replace with this flyout` from design)

![image](https://github.com/elastic/security-docs/assets/18648970/977aebc3-a0f0-405b-b704-09fe1dd8c823)

### Related links / assets

Please include each of the following, if applicable:
Figma link(s):
Github epic link(s): https://github.com/elastic/security-team/issues/9510
PRs:
https://github.com/elastic/kibana/pull/186850
https://github.com/elastic/kibana/pull/186857
Github issue link(s):
How to find the text in a production environment:
Testing environment information:
NOTE: To keep sensitive information such as credentials secure, do not include it in this form.

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

Same

### Software version

kibana 8.15

### Collaborators

PM: Paul Ewing
Designer: Sergei Sivukhin, Pavel Manko
Developer: Christine Weng
Others (if applicable):

### Timeline / deliverables

This feature goes in 8.15 (FF is July 2), but I can update just the copy during the BCs, ideally before July 12.

**Comment by nastasha-solomon** [comment]
Thanks for filing this, @christineweng! Please find my suggestions and questions below.

> Host preview
preview banner: `Preview host`
link in the footer: `Open host details flyout` (or `Replace with this flyout from design`)

> User preview
> preview banner: `Preview user`
> link in the footer: `Open user details flyout` (or `Replace with this flyout from design`)

I think it'd be a good idea to follow what's in the rule details flyout (see image below). On a related note, would this be a good opportunity to tweak the existing copy for the rule details preview? If so, here's what I'm thinking:

#### Rule preview
preview banner: `Preview rule details`  
link in the footer: `Show full rule details` or `Show more rule details` (this is more descriptive of what users will find when they click on the link)

<img width="500" alt="Screenshot 2024-06-28 at 12 37 59 PM" src="https://github.com/elastic/security-docs/assets/79124755/1376caec-6865-4515-b0c2-7b0686b0c78f">

If you were ok with tweaking the existing rule preview copy, you should apply that to the user and host details flyout copy like so:

#### Host preview
preview banner: `Preview host details`
link in the footer: `Show full host details` or `Show more host details` 

#### User preview
preview banner: `Preview user details`
link in the footer: `Show full user details` or `Show more user details` 

If it's not possible to tweak the rule preview copy, here's what I'd suggest instead for the host and user preview flyouts:

#### Host preview
preview banner: `Preview host details`
link in the footer: `Show host details`  

### User preview
preview banner: `Preview user details`
link in the footer: `Show user details` 

> #### Alert preview
> - preview banner: `Preview alert`

This just needs a minor change: `Preview alert details`

> - investigation guide (in normal flyout it is a button that opens the investigation section in left panel): 
> `You are currently in preview mode. Switch to this flyout to access all expandable options.`

In the current copy, what does "this flyout" refer to?

> - Response action (in normal flyout it is a button that opens the response section in left panel): 
> `You are currently in preview mode. Switch to this flyout to access all expandable options.`

Same question about "this flyout".

> - link in the footer: `Open alert details flyout` (or `Replace with this flyout` from design)
Even though users are technically opening another flyout, it's more useful for them to understand what they'll find in the newly-opened flyout. In other words, we should describe the result of the action (they'll find more details on the alert), not the action itself (they're opening a new flyout). In case you're interested, you can find more info on writing linked text [here](https://docs.elastic.dev/content-design/accessibility#guidelines).

I recommend changing the footer copy to one of the following:
- `Show alert details` (if you're following the existing copy from the rule preview copy)
- `Show full alert details` or `Show more alert details` (if you're updating the rule preview copy)

**Comment by christineweng** [comment]
> In the current copy, what does "this flyout" refer to?

i think it is referencing to this preview's full flyout - distinguishing what you are seeing is a preview, but you can also see an actual/full form flyout by clicking this link

**Comment by nastasha-solomon** [comment]
Gotcha, and thanks for the example recording in Slack, @christineweng. Instead of telling users to switch to another flyout, can we provide them with a way to do it? For example, in your example video [here](https://github.com/elastic/kibana/pull/186857#issue-2371209391), the copy tells users to open the alert details flyout to view investigation guides. Is it possible to make the text `open the alert details` clickable and link it directly to alert details? That way, instead of telling users to go somewhere, we give them a way to actually do it. If that's a feasible option, here's a slightly modified version of the copy for the  investigation guides and response action sections in preview mode:

- `Open alert details to find investigation guides.` (`Open alert details` would be linked text.)
- `Open alert details to find response actions.` (Same)

Access is another option if you don't like "find" as the action users would take.

If you'd prefer to go with plain text because it's easier to set up and maintain, here are my suggestions for the copy:

- `Open alert details to access investigation guides.`
- `Open alert details to access response actions.`

I'm not a fan of using "open" in the preview copy and "show" in the footer copy, but they're close enough that it shouldn't be too much of a stretch for users to make that connection. Let me know your thoughts and if you still want to workshop the text.

**Comment by christineweng** [comment]
Great, thanks @nastasha-solomon!

The interaction (include a link and then it opens the full flyout) was suggested by UIUX, but there were considerations around maintenance and the flow. We will have more time to investigate and improve the flow in 8.16, so I'm going with plain text to keep it simple for 8.15.

**Comment by christineweng** [comment]
@nastasha-solomon the new copy are reflected in 
- https://github.com/elastic/kibana/pull/187430 - I've added you as a reviewer
- https://github.com/elastic/kibana/pull/186857 is already merged but here is a screenshot
![image](https://github.com/elastic/security-docs/assets/18648970/b2c21cad-c6c2-4868-a539-e3d99308655b)

**Comment by nastasha-solomon** [comment]
Changes merged, so closing this issue.
