### ISSUE TITLE
[Enhancement]: Entity Analytics troubleshooting guide is outdated should be removed

### ISSUE THREAD

**Issue by hop-dev** [elastic/security-docs#5489]
### Description

We have recieved two SDHs this week from users following these guides for the legacy risk engine when they are on the "new" risk engine:

https://www.elastic.co/guide/en/security/8.11/host-risk-score.html#troubleshoot-host-risk-score
https://www.elastic.co/guide/en/security/8.11/user-risk-score.html#troubleshoot-user-risk-score

They are still available in the latest docs. There is a warning at the very top of the page saying it is for the legacy risk engine but I think we can now safely delete the pages to be safer. 

As for the 8.11 docs is changing them to make it even more obvious an option now? Just because it has caused the SDHs I wouldnt like more 😅 

I think we should also consider a troubleshooting guide for the new risk engine to replace these?

### Related links / assets

The whole of:
https://www.elastic.co/guide/en/security/8.11/host-risk-score.html
https://www.elastic.co/guide/en/security/8.11/user-risk-score.html

But these are the bits which caused the SDH:
https://www.elastic.co/guide/en/security/8.11/host-risk-score.html#troubleshoot-host-risk-score
https://www.elastic.co/guide/en/security/8.11/user-risk-score.html#troubleshoot-user-risk-score

### Which documentation set needs improvement?

ESS and serverless

### Software version

8.11 onwards

### Collaborators

PM:
Designer: 
Developer:
Others (if applicable):

### Timeline / deliverables

it feels high priority but not sure what a reasonable time scale to ask for would be

**Comment by natasha-moore-elastic** [comment]
After discussing with @jmikell821 and @jaredburgettelastic, we decided to move forward with the following approach:

1. Remove the legacy docs from 8.12+.
2. Link to the 8.11 legacy docs from the new risk engine docs in 8.12+.

**Comment by natasha-moore-elastic** [comment]
> 👍 Thank you @natasha-moore-elastic !
> 
> Could we also add a note to the top of the "Troubleshooting" section within 8.11, explicitly stating that the troubleshooting steps are for the legacy risk engine? As the new engine was introduced in 8.11, it is still likely to confuse users (and cause SDH's) who may have been linked directly to the troubleshooting section, but have already migrated to the new risk engine in 8.11

Sure @jaredburgettelastic – this will be in a separate PR since it will only target the `8.11` branch.
Also, if there are any troubleshooting steps relevant to the new risk engine, feel free to share those and we can add them to the docs.

**Comment by jaredburgettelastic** [comment]
@natasha-moore-elastic that's great, and similarly I think we can create a separate docs request to add troubleshooting steps for the new risk engine. 

@hop-dev If you already have some ideas for such troubleshooting steps, feel free to create a new docs request, and if not, let's discuss!

**Comment by natasha-moore-elastic** [comment]
As discussed in the EA sync today, we're reverting back to the original approach described in the issue description. Legacy risk engine docs can't be removed from docs v.8.12–8.14, since the Kibana UI has [links to those docs](https://github.com/elastic/security-docs/pull/5497#issuecomment-2206103214). The links can be removed from 8.15+ but can't be easily backported to previous versions.
Dev PR that removes the links in Kibana `main`: https://github.com/elastic/kibana/pull/187585
