### ISSUE TITLE
Update Host isolation exceptions document

### ISSUE THREAD

**Issue by Trinity2019** [elastic/security-docs#5547]
### Documentation links

https://www.elastic.co/guide/en/security/current/host-isolation-exceptions.html

Slack question: https://elastic.slack.com/archives/CNW9Y42KV/p1720539349919699

### Description

Host isolation exceptions document mentions:

>You can configure host isolation exceptions for specific IP addresses that [isolated hosts](https://www.elastic.co/guide/en/security/current/host-isolation-ov.html) are still allowed to communicate with, even when blocked from the rest of your network.

Can we update the document to indicate: If that communication is depending on VPN(s), then the IP address(es) of the VPN server(s) should be exception listed.

### Testing environment

https://www.elastic.co/guide/en/security/current/host-isolation-exceptions.html

**Comment by joepeeples** [comment]
@Trinity2019 Thanks for this request; please take a look at the fix in PR https://github.com/elastic/security-docs/pull/5579.

**Comment by Trinity2019** [comment]
HI @joepeeples 
The fix in PR https://github.com/elastic/security-docs/pull/5579 looks great!. Thanks for fixing!
