### ISSUE TITLE
[DOCS] Doc required for 7.11 release notes for wrong migration version tag

### ISSUE THREAD

**Issue by dontcallmesherryli** [elastic/security-docs#555]
## Description 

A jira connector failed the migration between 7.11.0 to 7.11.2. We know why this is happening because when we fixed our last blocker for 7.11.2, we did not tag the migration to the right version. We should have used 7.11.0 and not 7.11.2 or we should have added more logic to avoid this problem. 

A current work around for this user: https://github.com/elastic/sdh-kibana/issues/1320#issuecomment-799771073.

## Acceptance Test Criteria

Doc for 7.11 release notes need to add to Known Issues:

Jira connector migration between 7.11.0 to 7.11.2 will fail to due a missing tag for the right version.

## Notes

- Add the **"Team:Docs"** label to new issues. 
- Be sure to add the version number label. 
- Be sure to add any necessary screenshots for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by MikePaquette** [comment]
Proposed DRAFT of "known issue" release notes to be added to:
https://www.elastic.co/guide/en/security/current/release-notes.html#known-issues-7.11.0


> When upgrading from 7.11.0 or 7.11.1 to 7.11.2, certain connectors, including those that connect to Jira, ServiceNow, and IBM Resilient, are not properly migrated during the upgrade process, causing them to be deleted.  
>
>Impacts include:
> 
> - Security detection rules that have been configured to use the affected connectors as part of their rule actions will no longer create these actions.
> - Kibana Alerting and Action alerts that have been configured to use the affected connectors will no longer create these actions.
> - Security Case workflow users will need to recreate external connectors before cases can be pushed our updated via the affected connectors.
> - Open cases that were previously connected to third-party systems via the affected connectors will need to be re-connected after the connector(s) are recreated.
> 
> Users are advised to consider delaying the upgrade to 7.11.2, and instead using 7.12.0 once it is released. 

cc: @asnehalb @oatkiller @jmikell821

**Comment by jmikell821** [comment]
Merged #558.
