### ISSUE TITLE
[Request] Attack Discovery - Background Checks

### ISSUE THREAD

**Issue by dhru42** [elastic/security-docs#5561]
### Description

**What:** Document - 8.15 Attack Discovery update which allows Attack Discoveries to run as background tasks

### Background & resources

* PRs: 
* Issues/metas: https://github.com/elastic/security-team/issues/9486
* Point of contact: @stephmilovic 
* Test environments: 

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.15

### Serverless release

tbd

### Feature differences

n/a

### API docs impact

n/a

**Comment by dhru42** [comment]
cc: @Charelzard

**Comment by Charelzard** [comment]
Any update on this one @benironside ?

**Comment by benironside** [comment]
Resolved - background checks are documented in attack discovery docs and in the release notes
