### ISSUE TITLE
[Request] Documentation for AI Assistant API

### ISSUE THREAD

**Issue by dhru42** [elastic/security-docs#5562]
### Description

What: We're introducing an AI Assistant API

### Background & resources

* PRs: 
* Issues/metas: https://github.com/elastic/security-team/issues/8423
* Point of contact: @YulNaumenko 
* Test environments: 

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.15

### Serverless release

TBD

### Feature differences

N/A

### API docs impact

What: we're introducing a way for users to call on the AI Assistant using an API so they can embed AI Assistant into security workflows (orchestration/Tines playbooks)

**Comment by dhru42** [comment]
cc: @Charelzard

**Comment by Charelzard** [comment]
Any update on this one @benironside ?
