### ISSUE TITLE
[BUG] Documentation Defend for Cloud doesn't show itself as in beta stage

### ISSUE THREAD

**Issue by 111andre111** [elastic/security-docs#5583]
### Documentation links

https://www.elastic.co/docs/current/integrations/all_integrations
https://www.elastic.co/docs/current/integrations/cloud_defend

### Description

At the moment Defend for Containers is at beta stage, however this is now reflected in our documentation.
Our serverless documentation has it correctly:
https://www.elastic.co/docs/current/serverless/security/d4c-overview
as well as
https://www.elastic.co/guide/en/security/current/d4c-overview.html

So I think that's because `release` tag is missing in
https://github.com/elastic/integrations/blob/main/packages/cloud_defend/manifest.yml

similar to e,g, this integration:
https://github.com/elastic/integrations/blob/main/packages/linux/manifest.yml#L10

### Which documentation set(s) does this bug apply to?

ESS and serverless

### Testing environment

At the end on both pages integration should show in beta stage

**Comment by jmikell821** [comment]
@111andre111 - I opened https://github.com/elastic/integrations/pull/10541. Can you review please?

**Comment by jrmolin** [comment]
@111andre111 I'm not sure that adding `release: beta` is the correct response, given the documentation in `elastic-package` that identifies the `release` property as an unsupported (but common) one. Ref: https://github.com/elastic/elastic-package/blob/09d372c994f47d12528977a7788f0e313112f84b/docs/howto/update_major_package_spec.md?plain=1#L160-L171

That blob is useful for explaining why the very simple PR is failing linting, but not how to resolve it cleanly.

**Comment by 111andre111** [comment]
Ah, ok, so I learnt from the linked kibana issue https://github.com/elastic/kibana/issues/122973 that rather not the `release` tag, but rather the `version` tag moving it from `1.2.5` to `1.2.6-beta` would make it beta. Was not aware of that change...
