### ISSUE TITLE
[Request] 3P Integrations data in native Posture workflows

### ISSUE THREAD

**Issue by smriti0321** [elastic/security-docs#5607]
### Description

In order to enable CDR workflows, we are planning to extend our native posture workflows to support 3P data from vendors/products like Wiz, AWS Security Hub, Prisma Cloud etc.,  mored etails in the ticket- https://github.com/elastic/security-team/issues/8454

We need a documentation plan to consider redirection for users from our workflows.

### Background & resources

* PRs: 
* Issues/metas: https://github.com/elastic/security-team/issues/8454
* Point of contact: 
* Test environments: 
* Figma- https://www.figma.com/design/rERIzTNVuXscp5yZrDpqfz/3rd-Party-Posture-Workflows?node-id=226-7449&t=ZbGNB2U7K70SvzmL-0

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.16

### Serverless release

November 2024

### Feature differences

No differences

### API docs impact

TBD

**Comment by smriti0321** [comment]
Content draft:
Now you can start using native cloud security workflows by ingesting misconfigurations and vulnerability findings from 3rd party security tools like Wiz, AWS Security Hub and more to follow in future. Elastic Security supports out of the box workflows like findings table for misconfigurations and vulnerabilities from 3rd party tools (starting 8.16). Users can now ingest the data from Wiz, AWS Security Hub and start reviewing and investigating these findings in the native findings table. Contextualization of these findings is also available from alerts flyout, users and hosts flyout from explore page.

Steps to ingest 3p data:
1. Set up the Wiz or AWS Security Hub integration follow the integration step by step guide- link to integration guide for Wiz and AWS Security Hub.
2. Make sure the integration version is <check with engineering and get back>
3. Recommended data retention:
- For better contextualisation of your security posture, we recommend setting the initial interval for misconfiguration findings and vulnerabilities findings to be set to 90d or 2160h

**Comment by maxcold** [comment]
> For better contextualisation of your security posture, we recommend setting the initial interval for misconfiguration findings and vulnerabilities findings to be set to 90d or 2160h

the value should be `2160h`, the setting doesn't support `d`. We can rephrase to smth like `For better contextualisation of your security posture, we recommend setting the initial interval for misconfiguration findings and vulnerabilities findings to be set to 90 days by using 2160h as the value`

**Comment by smriti0321** [comment]
@benironside As per feedback from @maxcold in direct slack thread, we need to talk about the Elasticsearch indices which user needs to provide read permissions for in order to see the 3p data in native workflows

Read privileges for the following Elasticsearch indices:

security_solution-*.misconfiguration_latest 
security_solution-*.vulnerability_latest
