### ISSUE TITLE
[UI copy]: Agentless designs review

### ISSUE THREAD

**Issue by smriti0321** [elastic/security-docs#5608]
### Description

Agentless onboarding experience has considerable changes in the flow and needs a UI copy review. Here is the high level flow prototype- https://www.figma.com/proto/jmdsEtaqB6im6T0Y08Vais/Agentless-CSPM-for-serverless?page-id=5320%3A5426&node-id=5364-19656&viewport=5831%2C-1320%2C0.56&t=QNy0aXnqxKigjU2w-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=5364%3A19656

 @einatjacoby to give a go ahead when design is ready for copy review

### Related links / assets

Please include each of the following, if applicable:
Figma link(s):https://www.figma.com/design/jmdsEtaqB6im6T0Y08Vais/Agentless-CSPM-for-serverless?node-id=5320-5426&t=Uh8vvz6H9DXlyjqS-0
Github epic link(s): https://www.figma.com/design/jmdsEtaqB6im6T0Y08Vais/Agentless-CSPM-for-serverless?node-id=5320-5426&t=Uh8vvz6H9DXlyjqS-0
Github issue link(s):
How to find the text in a production environment:
Testing environment information:
NOTE: To keep sensitive information such as credentials secure, do not include it in this form.

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

Identical in ESS and Serverless

### Software version

8.16

### Collaborators

PM: @smriti0321 
Designer: @einatjacoby 
Developer: @Omolola-Akinleye 
Others (if applicable): @seanrathier @paulo

### Timeline / deliverables

Due by Aug 15, 2024

**Comment by benironside** [comment]
reviewed
