### ISSUE TITLE
[Request] Document behavior of AI Assistant prompts upon upgrade to 8.15

### ISSUE THREAD

**Issue by peluja1012** [elastic/security-docs#5623]
### Description

Upon upgrade to 8.15, AI Assistant user quick prompts and system prompts, which are currently stored in browser localStorage, will no longer be available to users. The reason is that in 8.15 we decided to store quick prompts an system prompts in Elasticsearch and make the globally available across all users. This brings a couple of benefits. First, by storing them in Elasticsearch, prompts will be available anywhere the user logs into the app (i.e. a new browser, a new laptop, etc). Additionally, by making them globally available, teams of security analysts will be able to share common system and quick prompts.

The fact that users will effectively lose access to any quick prompts or system prompts they've created upon upgrade should be documented in the "Upgrade to Elastic Security 8.15" page and anywhere else the Security Docs team deems appropriate. We should also document the new "global" nature of the prompts. We should recommend that, if users want to continue to use these prompts after upgrade, they should copy the prompt text prior to upgrade.

Relevant screenshots of where quick prompts and system prompts appear in the UI, for reference.

<img width="765" alt="image" src="https://github.com/user-attachments/assets/28e6a266-4b97-4ab4-9cf5-998f733ad67d">

<img width="861" alt="image" src="https://github.com/user-attachments/assets/1e6cc5c6-f16c-445f-8bc0-60d2aa33eb8b">

<img width="865" alt="image" src="https://github.com/user-attachments/assets/9170a480-7878-41e0-b507-1ae974b5e8ec">

### Background & resources

* PRs: https://github.com/elastic/kibana/pull/187040/
* Point of contact: The GenAI team

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.15

### Serverless release

Next serverless release

### Feature differences

The feature is identical in both ESS and Serverless

### API docs impact

These two APIs should be documented.
POST "/api/security_ai_assistant/prompts/_bulk_action"
GET "/api/security_ai_assistant/prompts/_find"

**Comment by benironside** [comment]
Closing because we added this to the release notes
