### ISSUE TITLE
[DOCS] [Security Solution] Remove Beta Warning(s) from Generally Available functions

### ISSUE THREAD

**Issue by MikePaquette** [elastic/security-docs#563]
## Description 

Beta Warning need to be removed from Generally Available functions, starting with the Detection Engine, which became generally available in 7.11.0.

- [ ] Remove Beta warning from [Detections and Alerts page](https://www.elastic.co/guide/en/security/7.12/detection-engine-overview.html)

![image](https://user-images.githubusercontent.com/22619280/111990284-8fd44b80-8ae9-11eb-89e2-428a38f7242c.png)

## Acceptance Test Criteria

Users viewing Elastic Security documentation for 7.11 or 7.12 should not see the Beta Warning 

Possible other mentions of "Beta" in Security Documents:

![image](https://user-images.githubusercontent.com/22619280/111990739-f22d4c00-8ae9-11eb-8d92-5de0bfe96673.png)

cc: @jmikell821

**Comment by jmikell821** [comment]
Hi @MikePaquette I want to confirm that we don't currently have any features in `beta` before we nix all of these. Thanks!

**Comment by MikePaquette** [comment]
@paulewing @dontcallmesherryli  Can you please confirm for Janeen?

**Comment by dontcallmesherryli** [comment]
@jmikell821 @MikePaquette will work on confirming that with Detection team and Threat hunting team today

**Comment by dontcallmesherryli** [comment]
Confirmed with Xavier and Garrett that there are no other betas from their teams.

**Comment by dontcallmesherryli** [comment]
@jmikell821 Nevermind, Xavier did some more digging, looks like Cases is still in Beta in the docs. 
https://www.elastic.co/guide/en/security/current/cases-overview.html

The question is, do we take that out of beta? @MikePaquette @paulewing

**Comment by MikePaquette** [comment]
@dontcallmesherryli 

> @jmikell821 Nevermind, Xavier did some more digging, looks like Cases is still in Beta in the docs.
> https://www.elastic.co/guide/en/security/current/cases-overview.html
> 
> The question is, do we take that out of beta? @MikePaquette @paulewing

Yes.  This issue is to remove all the incorrect "Beta" warnings from the docs.
There should be no beta warnings for detection engine or cases.

cc: @jmikell821

**Comment by lcawl** [comment]
We have "beta" indicators on the use of the Elastic Endpoint integration with pre-built machine learning jobs in https://www.elastic.co/guide/en/security/master/prebuilt-ml-jobs.html. Should that be removed there too?

**Comment by dontcallmesherryli** [comment]
Thank you!
