### ISSUE TITLE
[Request] AI Performance Matrix Changes for 8.15

### ISSUE THREAD

**Issue by dhru42** [elastic/security-docs#5661]
### Description

What: We need to update the AI Matrix for 8.15 to include Google's Gemini models
Why: We added support for new models and want to include them as part of the matrix

### Background & resources

* PRs: 
* Issues/metas: 
* Point of contact: @dhru42 @Charelzard 
* Test environments: 
Link: [Google Doc](https://docs.google.com/spreadsheets/d/1V6Qofsf2sjyYR6dgkfcS56lVGQXKEIW9seaMasbSd3A/edit?usp=sharing) 

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.15

### Serverless release

TBD

### Feature differences

Add Google's models to the matrix

### API docs impact

N/A

**Comment by dhru42** [comment]
![image](https://github.com/user-attachments/assets/66e9cf9c-4e6e-4021-9f07-62f7a17eb0f2)
updated matrix

**Comment by benironside** [comment]
Closing because these changes are in

**Comment by Charelzard** [comment]
FYI @benironside @dhru42

**Comment by Charelzard** [comment]
This can be closed I reviewed the table and its correct.
