### ISSUE TITLE
[Enhancement]: Add AI Assistant basic custom knowledge feature to 8.15 release notes

### ISSUE THREAD

**Issue by peluja1012** [elastic/security-docs#5670]
### Description

In 8.15, we added functionality that enables users to add custom knowledge to the AI Assistant Knowledge Base. This is done by asking the assistant, via a message in a conversation, to remember specific information for later use. We should document this in our release notes and/or in the "What's new in 8.15" section of our security docs.

For example, you could ask the assistant that a server in your organization is located in New York:

> When answering any question about server-xyz, or any attack discovery or alert that references it, mention that this host lives in the New York data center.

In future conversations, the AI Assistant will remember this detail and mention it in subsequent messages whenever relevant.

![image (46)](https://github.com/user-attachments/assets/634973a4-c036-48be-84bd-dfb8861170e5)
![image (47)](https://github.com/user-attachments/assets/c87e3909-29cd-472c-8222-f435f100ebae)

### Related links / assets

Please include each of the following, if applicable:
Doc URL: 
Subject matter expert:
Figma link(s):
Github epic link(s):
Github issue link(s):

### Which documentation set needs improvement?

ESS and serverless

### Software version

8.15
Serverless

### Collaborators

PM:
Designer: 
Developer:
Others (if applicable):

### Timeline / deliverables

It would ideal to document it by the 8.15 release.

**Comment by benironside** [comment]
added to RNs, added to AI Assistant doc
