### ISSUE TITLE
[Security Solution] Missing Attack Discovery under Navigation Menu Doc

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#5691]
**URL**
https://www.elastic.co/guide/en/security/8.15/es-ui-overview.html#navigation-menu-overview

**Actual Result**

- missing mention of Attack Discovery after the Alert Navigation

![image](https://github.com/user-attachments/assets/8464bb0d-fc3d-4fe5-bc27-9211724e0362)

**Expected Result**

- Mention of Attack Discovery in Navigation Menu

![image](https://github.com/user-attachments/assets/7b1ee9d4-f10f-4e17-a7a7-17c8428415e4)

**Comment by amolnater-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by joepeeples** [comment]
I think we're OK not updating this for now, as the image still accomplishes main goal of illustrating how the menus work. Also Attack Discovery is still in tech preview and subject to change, and we might have overall nav updates coming soonish anyway.
