### ISSUE TITLE
[Bug] No mention of AVC banner under Defend integration

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#5693]
### Description:
The AVC banner should be visible under Defend integration

### URL link or topic name:
https://www.elastic.co/guide/en/security/current/install-endpoint.html

### Screenshots:
- Expected
![image](https://github.com/user-attachments/assets/9dc757a2-16c0-4baf-a86c-a33990f60b81)

- Actual
![image](https://github.com/user-attachments/assets/c6a15daa-9464-416c-ae3c-a2a80753166f)

**Comment by muskangulati-qasource** [comment]
@karanbirsingh-qasource please review!

**Comment by joepeeples** [comment]
The banner is an in-app announcement, not functionality that needs to be documented.
