### ISSUE TITLE
[UI copy]: Data Quality Dashboard tooltip texts review

### ISSUE THREAD

**Issue by einatjacoby** [elastic/security-docs#5699]
### Description

We're making a change to the Data Quality dashboard UI, replacing some table expansions with flyouts,
and want to make sure that tooltips aren't redundant or repeating themselves(some of them were already there and need editing, some of them newly added).
![data quality tooltip](https://github.com/user-attachments/assets/2cd09a2f-e579-44b8-a661-3dde78d4f7a3)

### Related links / assets

**Figma link:** https://www.figma.com/design/Cgp9p09QcFGjbhzSmpPIFU/Retrieval-of-Historic-Data-Quality-Results?node-id=3455-21203&t=BXwRzobGfrHpMJnu-1
**How to find the text in a production environment:** some are already in production- Dashboards-> Data Quality

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

The feature is the same in both.

### Software version

This feature is in production but the flyout part is only in 8.16.X

### Collaborators

PM: @dhru42 
Designer: @einatjacoby 
Developer: @kapral18 
CC @andrew-goldstein @semd @angela

### Timeline / deliverables

We'd love it if the edit is ready this week, figma comments welcome, or whatever works for you @benironside 
Thank you!

**Comment by kapral18** [comment]
thanks @einatjacoby this ticket is related to https://github.com/elastic/security-docs/issues/5701

**Comment by kapral18** [comment]
as promised this is the full set of tooltips, if some element is not in these screenshots, most likely it doesn't have tooltips and needs to be added. Looking for your feedback. Thanks

![SCR-20240813-bgsp](https://github.com/user-attachments/assets/a4c62567-30dc-484a-8f14-637f57abad5e)
![SCR-20240813-bgqb](https://github.com/user-attachments/assets/ee4c78ef-7cce-44ef-a377-32434bf2361d)
![SCR-20240813-bgob](https://github.com/user-attachments/assets/89c3e286-cc23-4952-ae4a-8e3e187d0b9b)
![SCR-20240813-bglq](https://github.com/user-attachments/assets/1db0a820-fc7f-40bb-acf5-841bd95000c2)
![SCR-20240813-bghk](https://github.com/user-attachments/assets/6446c3ed-2f4b-44e8-baee-f4b941d5b270)
![SCR-20240813-bgfs](https://github.com/user-attachments/assets/ef9490f9-f3bd-4f73-8ae7-69e80c04826b)
![SCR-20240813-bgdz](https://github.com/user-attachments/assets/25364da3-17d3-426e-bc71-46aac229ed0f)
![SCR-20240813-bgcm](https://github.com/user-attachments/assets/ee5cb6de-c2e0-4743-a3ca-ed2101d0dcd6)
![SCR-20240813-bgbi](https://github.com/user-attachments/assets/8a483492-396d-4ff0-a7d0-57d2c4cde3dd)
![SCR-20240813-bfzh](https://github.com/user-attachments/assets/b0f0af28-2f5f-47e9-b1f0-7c988473c5e6)
![SCR-20240813-bfxz](https://github.com/user-attachments/assets/6cde0edb-64b2-4e8f-b8b4-408aa5467915)
![SCR-20240813-bfwx](https://github.com/user-attachments/assets/373ce0dd-e1e6-4bf6-a5c4-3aee3d36464d)
![SCR-20240813-bfwa](https://github.com/user-attachments/assets/e09d1c78-fea7-44be-975b-09e0da47fad0)
![SCR-20240813-bfui](https://github.com/user-attachments/assets/18203d36-6fc8-4284-b1b4-4dac7214e937)
![SCR-20240813-bfqj](https://github.com/user-attachments/assets/2255d8f8-790d-4253-9e33-a3ae9dd39f22)
![SCR-20240813-bfoj](https://github.com/user-attachments/assets/b004cfb8-e315-4ae4-b5b7-4c81b900ad78)
![SCR-20240813-bfmu](https://github.com/user-attachments/assets/c41a1876-b50d-4b02-95ca-ec7dcae474c0)
![SCR-20240813-bffo](https://github.com/user-attachments/assets/2211529c-c5d2-4436-8fd8-7f1f6e385879)
![SCR-20240813-bfeg](https://github.com/user-attachments/assets/73d1ab2e-27f3-4798-b07f-4d1f106c7407)
![SCR-20240813-bfcv](https://github.com/user-attachments/assets/b31e371c-1fe1-41bb-9d16-0878dbdeec36)
![SCR-20240813-bfbp](https://github.com/user-attachments/assets/9df32f49-7c83-40be-a6a7-c295fe11d61c)
![SCR-20240813-bfao](https://github.com/user-attachments/assets/11352707-d836-42a8-baff-c33171aa8834)
![SCR-20240813-beqb](https://github.com/user-attachments/assets/cdceec4f-f86c-46a4-8b04-7cad93e71356)
![SCR-20240813-beod](https://github.com/user-attachments/assets/8e254b21-94f6-4f5b-863c-c8c0e27ea392)
![SCR-20240813-bely](https://github.com/user-attachments/assets/beb09c63-249d-43fe-88f0-e08734b34fac)
![SCR-20240813-bekd](https://github.com/user-attachments/assets/33a9d57a-1000-4eef-954f-de104c093433)
![SCR-20240813-beew](https://github.com/user-attachments/assets/e0d3a4d7-4033-4a34-b0e1-01078b48bbb9)
![SCR-20240813-beca](https://github.com/user-attachments/assets/b8b09385-9ac8-4a1d-bbf7-826e0725e8d2)
![SCR-20240813-bdul](https://github.com/user-attachments/assets/2562e2c2-7c9d-4ecc-8336-53bc748c0051)

**Comment by benironside** [comment]
I added my suggestions in the Figma. Please let me know if you have any questions or want further copy review on any part of the design!

**Comment by kapral18** [comment]
we decided with @einatjacoby 
that this ticket is no longer a blocker for #5701 

#5701 has higher prio vs this

cc: @benironside @nastasha-solomon

**Comment by benironside** [comment]
Reviewed ✅
