### ISSUE TITLE
[Request] DataQuality Dashboard New ListView and Flyout UI

### ISSUE THREAD

**Issue by kapral18** [elastic/security-docs#5701]
### Description

We have revised DataQuality Dashboard UI to improve UX by making it more visually outlined and structured, simplifying color scheme and most importantly preparing it for addition of Historical Checks UI which will come next.

Please take a look at the PR https://github.com/elastic/kibana/pull/188468 description for exact diff of changes with screenshots.

### Background & resources

* PRs: https://github.com/elastic/kibana/pull/188468
* Issue: https://github.com/elastic/kibana/issues/185881
* Story: https://github.com/elastic/kibana/issues/184158
* Epic: https://github.com/elastic/security-team/issues/8527
* Point of contact: @kapral18

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.16

### Serverless release

As soon as possible

### Feature differences

No difference

### API docs impact

This is purely a frontend change

**Comment by kapral18** [comment]
@benironside there is a tiny last minute update. I was asked to remove the tabline of flyout because the disabled tab is confusing so it looks like this now

![image](https://github.com/user-attachments/assets/119cdad5-ea5e-494b-b217-606e8fdd7e14)

**Comment by benironside** [comment]
complete
