### ISSUE TITLE
[Known Issue] Doc Elastic Defend bug that stopped security events from populating the `user.name` field

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#5765]
### Description

We need to add a known issue to the `8.13.1`-`8.15.0` release notes that describes the following:
An Elastic Defend regression was introduced in 8.13.1, where security events did not populate the `user.name` field. This bug affected Windows endpoints only.

To do:

- [x] Work with @gabriellandau to validate the known issue description and get the workaround (might just be to upgrade to `8.15.1`)

### Area/Engineering team

Endpoint 

### Which documentation set does this known issue impact?

ESS only

### Affected versions

8.13.1-8.15.0

### Fix version

8.15.1

### Workaround

TBD

**Comment by gabriellandau** [comment]
Sorry I misread https://github.com/elastic/endpoint-dev/issues/14686.  It was [introduced in 8.14.0](https://github.com/elastic/endpoint-dev/issues/14686#issuecomment-2234343004).

Here is a concise, accurate description:

> Elastic Defend for Windows versions 8.14.0 through 8.15.0 will not properly populate `user.name`.  Affected users should upgrade to 8.15.1 or later.  There is no known workaround.
