### ISSUE TITLE
[Request][Serverless][ESS] EQL Sequence alert suppression

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#5886]
### Description

Alert suppression is now supported for EQL rules using sequence queries. 

### Background & resources

* PRs: https://github.com/elastic/kibana/pull/189725
* Issues/metas: https://github.com/elastic/security-team/issues/9608
* Point of contact: @dhurley14 
* Test environments: N/A

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.16

### Serverless release

TBD

### Feature differences

N/A

### API docs impact

- https://www.elastic.co/guide/en/security/master/rules-api-create.html#opt-fields-alert-suppression-create: Update title 
- https://www.elastic.co/guide/en/security/master/rules-api-update.html#opt-fields-alert-suppression-update: Update title

### Prerequisites, privileges, feature flags

N/A

**Comment by dhurley14** [comment]
Part of the "Notes" section should include the following:

1. Suppression happens on values from sequence alerts, not from building block alerts.
2. If the suppression field is an array of values, the suppressed alert will only suppress on values that are an exact match. The values must be equivalent and be in the same position. e.g. if suppressing on a field `myips` and one sequence alert has [1.1.1.1, 0.0.0.0] and another sequence alert has [1.1.1.1, 192.168.0.1], neither of those alerts will be suppressed, despite sharing an array element.
