### ISSUE TITLE
[UI copy]: DQ Dashboard Historical Results

### ISSUE THREAD

**Issue by kapral18** [elastic/security-docs#5899]
### Description

What: historical results tab + minor fixes is in listview and index check flyout of DataQualityDashboard
When: 8.16
How: improves UX of consumers

Additionally a tour guide copy needs to be reviewed:
![Image](https://github.com/user-attachments/assets/e5f70b67-b9ec-41da-a7a6-18c2f44c2b70)

### Related links / assets

PR: https://github.com/elastic/kibana/pull/191898

Testing environment information: will add later...

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

- index phase labels are not available in serverless
- some specific UI fixes have been done that affect only serverless (more details in the screenshots in PR)

### Software version

8.16.0

### Collaborators

PM: @dhru42 
Designer: @einatjacoby 
Developer: @kapral18 
Others (if applicable):

### Timeline / deliverables

Urgent, highest prio, asap.

**Comment by benironside** [comment]
UI copy review complete
