### ISSUE TITLE
[Request] [Draft] AI Performance Matrix Update

### ISSUE THREAD

**Issue by Charelzard** [elastic/security-docs#5950]
### Description

We are updating the model matrix testing and need the main page updated here to reflect performance tests: https://www.elastic.co/guide/en/security/current/llm-performance-matrix.html

### Background & resources

* PRs: 
* Issues/metas: 
* Point of contact: 
* Test environments: 

### Which documentation set does this change impact?

ESS and serverless

### ESS release

N/A

### Serverless release

N/A

### Feature differences

N/A

### API docs impact

N/A

### Prerequisites, privileges, feature flags

N/A

**Comment by Charelzard** [comment]
FYI @jamesspi

**Comment by Charelzard** [comment]
Link will be provided once testing is complete.

**Comment by dhru42** [comment]
![Image](https://github.com/user-attachments/assets/ed0e4082-9bb2-4d45-bd8e-a8e6103ace5d)
Please update the AI Matrix to reflect the changes in this image.

**Comment by jamesspi** [comment]
@dhru42 I believe Sonnet 3.5 v2 should also have ES|QL generation down as excellent.
