### ISSUE TITLE
[UI copy]: DataQuality Dashboard descriptions and callouts

### ISSUE THREAD

**Issue by kapral18** [elastic/security-docs#5964]
### Description

![Image](https://github.com/user-attachments/assets/4e3d3a73-6709-4cdf-b1b3-8e9e8a025c27)

### Related links / assets

Testing environment information: SIEM dev

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

None

### Software version

8.16.0

### Collaborators

PM: @dhru42 
Designer: @einatjacoby 
Developer: @kapral18 
Others (if applicable):

### Timeline / deliverables

Asap

**Comment by benironside** [comment]
complete
