### ISSUE TITLE
[Request] New KB Section in Docs

### ISSUE THREAD

**Issue by Charelzard** [elastic/security-docs#5994]
### Description

Use the following document and video links (in document) to create a new section:

AI for security
AI Assistant
Knowledge Base

Please note that on the AI Assistant page about halfway down all items regarding the KB should be removed. 

https://docs.google.com/document/d/1QOtUy7ya1q2cSIu19QjY36XLcQ3St_Ppqw6Tngrd3O0/edit?usp=sharing

### Background & resources

N/A

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.16

### Serverless release

N/A

### Feature differences

N/A

### API docs impact

N/A

### Prerequisites, privileges, feature flags

N/A

**Comment by Charelzard** [comment]
FYI @benironside and @jamesspi

**Comment by jamesspi** [comment]
Sorry for the last minute change, can we add this demo video? https://ela.st/seckb
