### ISSUE TITLE
[Docs][Endpoint]: Add instructions for enabling full disk access, mac

### ISSUE THREAD

**Issue by DonNateR** [elastic/security-docs#6]
## Description 

According to bug https://github.com/elastic/endpoint-dev/issues/6635, any macOS 10.15 endpoint must enable full disk access in order to be protected by the Endpoint app. Write a set of instructions about how to enable this access, and document how the Endpoint app sensor checks for this access. 

## Notes

- Add the **"Team:Docs"** label to new issues. 
- Be sure to add any necessary screenshots for clarity. 
- Include any conditions or caveats that may affect customers. 

### Example Issue: 
**Issue Name:** Document the ability for users to disable artifact updates. 

**Description:** Many organizations have major events where they lock down updates to their systems. They lock down the updates because the systems are highly tuned and they don't want to introduce error or risk during the major event (think World Series or All Star Game or a state government just before elections.) This feature will give admin users the ability to stop artifact updates until that event is over and then re-enable after.

**Acceptance Test Criteria:** Ensure the user is logged into the platform as an admin. 
1. On the Left Navigation toolbar, click the Administration button, then select the **PLATFORM** tab.
2. In the "ARTIFACT UPDATE CONFIGURATION" section, click **Disable artifact updates**.
3. In the dialog box that says, "You are about to DISABLE artifact updates. This will prevent you from receiving updated artifacts..." click **Disable**. A 'Successfully updated configuration" confirmation appears.
4. Click **Finish**.

**Note:** To re-enable cloud updates, follow the aforementioned steps, except in Step 2, click **Enable artifact updates**.

**Comment by willyu-elastic** [comment]
Hello @DonNateR, is there any way we can push this up in priority and knock it out within a week? Thanks!

@DanielFerullo is the manager on the endpoint team if you have any questions regarding timelines and priorities.

**Comment by DonNateR** [comment]
@willyu-elastic: You've got it.

**Comment by ferullo** [comment]
For what it's worth, an example documentation from Sophos is here https://support.home.sophos.com/hc/en-us/articles/360032989852-Additional-steps-for-Sophos-Home-installations-on-MacOS-10-15-Catalina-

**Comment by DonNateR** [comment]
Posting Will Yu's instructions here: https://docs.google.com/document/d/1JM5i_SFvVMWCVA64GPTFpcv7DfBQzWtiiwfyemloqK0/edit?usp=sharing

**Comment by jmikell821** [comment]
Posted and live for primetime! 
https://www.elastic.co/guide/en/endpoint/master/sensor-full-disk-access.html
