### ISSUE TITLE
[DOC] Rule fields Override and Rule Building blocks

### ISSUE THREAD

**Issue by dontcallmesherryli** [elastic/security-docs#60]
## Description 
**Meta issue: ** https://github.com/elastic/kibana/issues/65941

User has the ability to map source fields to values of severity and risk score when they create a detection rule. 

![image](https://user-images.githubusercontent.com/52211561/86955171-2b24bc80-c125-11ea-8417-bd75bb836dde.png)

In advanced settings for rules creation, user also has the ability to override Rule Name and Timestamp, as well as check that the rule is a Building Block.
![image (47)](https://user-images.githubusercontent.com/52211561/86968890-e146d100-c13a-11ea-9c0e-85a2d828a4da.png)

## Acceptance Test Criteria

Documentation is required to instruct user to use Severity and Risk score override if they wish to use certain fields to map their rule severity and risk score to.

Use case example: User is using a data source where he wants to use a field called `Priority Ranking` (with the values of 1, 2, 3, 4, 5 as rank) is used for the SIEM Detection Rule Severity. He would select `Priority Ranking` as source field, and map severity value `1` to Critical, `2` to High, and so on. Now the user can use the source data to standardize into the SIEM severity mapping.

## Notes

- Add the **"Team:Docs"** label to new issues. 
- Be sure to add any necessary screenshots for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by benskelker** [comment]
Related API PR: #70
