### ISSUE TITLE
[CloudSecurity][Docs] Streamlined CNCF Falco ingestion documentation

### ISSUE THREAD

**Issue by nick-alayil** [elastic/security-docs#6004]
## Background

https://github.com/elastic/security-team/issues/9873
https://github.com/elastic/security-team/issues/9980
https://github.com/elastic/security-team/issues/10379

## Documentation Content

Detailed technical setup has been captured [here](https://docs.google.com/document/d/1ufaJTH4Ou-U28Np2Ul4J_EJCQ3iTJ9evTdCnpO68udU/edit?usp=sharing).

### Background & resources

* PRs: 
* Issues/metas: 
* Point of contact: @nick-alayil 
* Test environments: 

### Which documentation set does this change impact?

ESS only

### ESS release

8.16

### Serverless release

N/A

### Feature differences

N/A

### API docs impact

 N/A

### Prerequisites, privileges, feature flags

 N/A

**Comment by benironside** [comment]
complete in #6027
