### ISSUE TITLE
[Serverless]: Security - Cases nav steps are slightly incorrect

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#6015]
### Serverless Docs

Elastic Security

### Description

Nav nits! A few of the procedures on the [Create and manage cases](https://www.elastic.co/docs/current/serverless/security/cases-open-manage) include nav steps that are _just slightly_ incorrect. Fussy stuff like capitalization and UI label differences:

Docs say: **Project settings** → **Management** → **etc**
UI says: **Project Settings** → **Stack Management** → **etc**

### Resources and additional context

n/a

**Comment by nastasha-solomon** [comment]
Will address this when I update the Serverless nav instructions to align with the ESS nav updates.
