### ISSUE TITLE
[Serverless]: Security - Visual event analyzer advanced setting not in serverless

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#6017]
### Serverless Docs

Elastic Security

### Description

This tip on the [Visual event analyzer](https://www.elastic.co/docs/current/serverless/security/visual-event-analyzer) page mentions and links to an advanced setting that doesn't appear to be available in serverless:

<img width="700" src="https://github.com/user-attachments/assets/cefeebce-92c5-4134-a20a-b13147c82155"  /><br />

The link points to this section on the [Advanced settings](https://www.elastic.co/docs/current/serverless/security/advanced-settings#exclude-cold-and-frozen-tier-data-from-analyzer-queries) page:

<img width="700" src="https://github.com/user-attachments/assets/28766315-cc43-4b50-b4c3-a7b6439b40f3"  /><br />

As far as I can tell, the `excludeColdAndFrozenTiersInAnalyzer` advanced setting isn't available in serverless, probably because serverless doesn't provide direct access to data tiers. We'll need to verify this, but if so then _both_ of these sections should be removed from the serverless docs. Also double-check to make sure the serverless docs don't have any other references to this setting.

### Resources and additional context

n/a

**Comment by nastasha-solomon** [comment]
Followed up with @christineweng to check whether this setting is available in Serverless. Also searched the Serverless docs for mentions of/references to the `securitySolution:excludeColdAndFrozenTiersInAnalyzer` setting and didn't find any outside of what's already identified in the doc issue.

**Comment by nastasha-solomon** [comment]
Doc issue that added the Serverless docs: https://github.com/elastic/security-docs/issues/4387

Will need to follow up with @lgestc instead.

**Comment by nastasha-solomon** [comment]
Validated that this should be removed from the ESS docs since it only shows up in ESS.
