### ISSUE TITLE
[Serverless]: Security - Embedded videos require refresh to use

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#6029]
### Serverless Docs

Elastic Security

### Description

Similar to https://github.com/elastic/security-docs/issues/6030, but instead of looping, the embedded videos on [Connect to Google Vertex](https://www.elastic.co/docs/current/serverless/security/connect-to-google-vertex) just look like static images upon first loading the page. You have to refresh the page to get the play button to appear.

Note: Following the link above might not fully reproduce the issue. The problem seems to happen when you're navigating from another page in the serverless docs, so once you follow the link, click to a different page in the nav and then click back to the Vertex one.

### Resources and additional context

More Docsmobile limitations with videos?

**Comment by benironside** [comment]
Closing. This appears not to be an issue after the recent docs infrastructure update for serverless docs.
