### ISSUE TITLE
[Serverless]: Security - Video looping with no way to play

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#6030]
### Serverless Docs

Elastic Security

### Description

The embedded video on the [Attack Discovery](https://www.elastic.co/docs/current/serverless/security/attack-discovery) page loops for about 1 second and doesn't allow you to interact with it to stop or start it. Refreshing the page seems to resolve the issue, but users might not think of that.

### Resources and additional context

I remember this coming up earlier, maybe for this page or another one. It's probably a known/semi-known issue with Docsmobile but figured I'd mention it here just in case.

**Comment by benironside** [comment]
Fixed — no longer an issue after docs infra update
