### ISSUE TITLE
[Serverless]: Security – broken link on Enable threat intelligence integrations page

### ISSUE THREAD

**Issue by natasha-moore-elastic** [elastic/security-docs#6032]
### Serverless Docs

Elastic Security

### Description

On the Enable threat intelligence integrations page, the [Elastic Agent integration](https://www.elastic.co/docs/current/serverless/security/threat-intelligence#add-an-elastic-agent-integration) anchor link doesn't work.

### Resources and additional context

https://www.elastic.co/docs/current/serverless/security/threat-intelligence

**Comment by jmikell821** [comment]
Confirmed this works as expected after migration.
