### ISSUE TITLE
[Request] Add Signer option to Mac trusted apps field condition

### ISSUE THREAD

**Issue by szwarckonrad** [elastic/security-docs#6035]
### Description

https://www.elastic.co/guide/en/security/7.17/trusted-apps-ov.html

This changes target 8.17 release.

We’ve updated the field options for macOS Trusted Apps conditions to include “Signer” alongside “Path” and “Hash.” Previously, only Windows supported all three options. With these changes, Linux remains the only operating system limited to “Hash” and “Path” options.

https://github.com/user-attachments/assets/e3a60622-db48-4e40-b88a-44b54b741f46

### Background & resources

* PRs: https://github.com/elastic/kibana/pull/197821
* Issues/metas: https://github.com/elastic/security-team/issues/9580
* Point of contact: @szwarckonrad 
* Test environments: https://p.elstc.co/paste/l5IZvTAl#1Un4u4pkjB7LUg5p2IhzyBL8nfeLfQ4OjlAgcqZ5lY1

### Which documentation set does this change impact?

ESS and serverless

### ESS release

N/A

### Serverless release

The week of Nov 4th

### Feature differences

The feature is identical in ESS and Serverless

### API docs impact

https://www.elastic.co/docs/api/doc/kibana/operation/operation-createendpointlistitem

These changes address the validation of the `entries` field as defined in the [Elastic API documentation](https://www.elastic.co/docs/api/doc/kibana/operation/operation-createexceptionlistitem#operation-createexceptionlistitem-body-application-json-elastic-api-version-2023-10-31-entries), which, to my knowledge, currently lacks coverage in the docs. Specifically, we modified the validation behavior for `os_types=["mac"]` to allow `entries.field = process.code_signature`, aligning it with the Windows pattern that supports “Signer,” “Hash,” and “Path” `entries.field` values. In contrast, Linux still supports only “Hash” and “Path.” Since this doesn’t appear in the documentation, I don’t believe any doc updates are necessary.

### Prerequisites, privileges, feature flags

This change does not affect the existing RBAC or Serverless Tier requirements for Trusted Apps.
This is not gated behind a feature flag.

**Comment by natasha-moore-elastic** [comment]
Hey @szwarckonrad, does this also apply to the Blocklist workflow? We have the `Signature: (Windows only)` field mentioned in those docs as well: https://www.elastic.co/guide/en/security/8.16/blocklist.html

**Comment by szwarckonrad** [comment]
@natasha-moore-elastic 
This is for Trusted Apps only and has no effect on Blocklist.
