### ISSUE TITLE
[Serverless]: Security - Embedded videos unavailable for AI assistant setup docs

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#6036]
### Serverless Docs

Elastic Security

### Description

Several embedded videos are unavailable on multiple pages. This appears to be due to access permissions for Google Drive, where the videos are hosted.

<img width="600" src="https://github.com/user-attachments/assets/aff9df52-bc8f-4ece-bc9b-b67da9856f88"  /> 

Affected docs:
- https://www.elastic.co/docs/current/serverless/security/connect-to-azure-openai
- https://www.elastic.co/docs/current/serverless/security/connect-to-bedrock
- https://www.elastic.co/docs/current/serverless/security/connect-to-openai

### Resources and additional context

This isn't a problem in ESS docs, because their videos are hosted by Vidyard. I seem to remember something about Docsmobile having trouble with Vidyard, and now it looks like it might have trouble with Google Drive, too?

**Comment by benironside** [comment]
Fixed
