### ISSUE TITLE
[Serverless]: Security – Alerts section bugs

### ISSUE THREAD

**Issue by natasha-moore-elastic** [elastic/security-docs#6038]
### Serverless Docs

Elastic Security

### [Manage detection alerts](https://www.elastic.co/docs/current/serverless/security/alerts-manage)
- "Click a name in the Rule column to open the rule's details page" – it opens the rule details flyout, not details page
- "_x_ fields sorted" – should be "Sort fields _x_"

### [Reduce notifications and alerts](https://www.elastic.co/docs/current/serverless/security/reduce-notifications-alerts)
- Maintenance window link should link to https://www.elastic.co/docs/current/serverless/maintenance-windows instead of ESS docs
- Notification actions link should link to https://www.elastic.co/docs/current/serverless/security/rules-create#set-up-rule-actions-optional 

### [View detection alert details](https://www.elastic.co/docs/current/serverless/security/view-alert-details)
- **Last Alert Status Change** and **MITRE ATT&CK** are documented in the About section but not shown in the UI:
![Image](https://github.com/user-attachments/assets/142d9fb0-6a01-4469-ad5e-fde7913218ce)

### Resources and additional context

N/A

**Comment by nastasha-solomon** [comment]
[Pinged](https://elastic.slack.com/archives/C02EDDT1M35/p1732643971237509) TH and Rules Management folks on Slack for the last item.

**Comment by nastasha-solomon** [comment]
Confirmed that the **Last Alert Status Change** field was removed from the "About" section in `8.12` by https://github.com/elastic/kibana/pull/172888. I'll need to remove the field description from the Serverless docs and the ESS docs (`8.1`2 - `main`).
