### ISSUE TITLE
Create breaking changes and deprecations placeholder for `9.0.`

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#6039]
We need a place to start adding breaking changes and deprecations for `9.0` (currently `main`). In a separate PR, we'll remove `8.x` references from the `main` branch. 

Note: Don't forget to add the `coming [9.0.0]` tag.

**Comment by nastasha-solomon** [comment]
Docs for `coming` tag: https://github.com/elastic/docs#additions-and-deprecations
