### ISSUE TITLE
[Request] Add agentless troubleshooting steps to Agentless doc

### ISSUE THREAD

**Issue by benironside** [elastic/security-docs#6044]
### Description
We need to create a new section for Agentless integration troubleshooting/FAQ. The Q/A we have come up with so far are:

When you make a new integration, how long until the agent appears on the CSPM integration policies page?
- The integration on the integration policies but it will have an “Add agent” button for up to a couple minutes. No action is needed, the agent enrolment is happening automatically but you may have to refresh the page to see the agent

Can I create an agentless integration if I changed my Fleet server host value?
- Fleet Server Host must be the default value
- [ ]  Need to find out how the user can tell whether the default value was changed, and what the error that appears would be

How can I delete the agentless integration?
- warn the customer that deletion will remove resources and stop data ingestion
- When we create agentless integration, new agent policy appears on the Fleet >Agent policies page — can’t use the “Delete integration” here. They should delete it from the CSPM Integration policies page

How do I troubleshoot an unhealthy or offline agent?
- If agent is unhealthy — refer to existing troubleshooting steps for unhealthy agent
- User would have to figure out which agent is associated with the agentless integration
- To identify which agent is related to the agentless integration, go to CSPM Integration page -> Integration policies page, then click agents for the "agentless" policies, then click the agent’s Host link > Logs tab

What if I enter the wrong credentials:
- If the user enters the wrong credentials agent will show as unhealthy -> User should then delete the agentless integration and set up again 
- [ ] Need to clarify - what is agent status in this case, and what would the logs show?

Romulo's related ticket: https://github.com/elastic/kibana/issues/198151

### Background & resources

* PRs: 
* Issues/metas: 
* Point of contact: 
* Test environments: 

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.16

### Serverless release

Dec 2

### Feature differences

-

### API docs impact

-

**Comment by smriti0321** [comment]
@benironside please review this comment and plan to add it in known limitations- https://github.com/elastic/kibana/issues/198151#issuecomment-2450114463 cc @Omolola-Akinleye
