### ISSUE TITLE
[Serverless]: Minor punctuation and link issues in "Manage Elastic Defend" topics

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#6054]
### Serverless Docs

Elastic Security

### Description

- [Event filters](https://www.elastic.co/docs/current/serverless/security/event-filters): In the sentence before the procedures, the page names (Hosts and Event filters pages) aren’t bolded.
- [Optimize Elastic Defend](https://www.elastic.co/docs/current/serverless/security/optimize-edr): The ref to the [Endpoint alert exception](https://www.elastic.co/docs/current/serverless/security/add-exceptions#add-Elastic%20Endpoint-exceptions) page doesn’t fully work, likely because it includes the Elastic Defend attribute at the end in the syntax. 
- [Allowlist Elastic Endpoint in third-party antivirus apps](https://www.elastic.co/docs/current/serverless/security/allowlist-endpoint): The first sentence has spaces missing before and after the em dashes.
- [Elastic Endpoint command reference](https://www.elastic.co/docs/current/serverless/security/endpoint-command-ref): The second bullet in the note is missing spaces before and after the em dash.

### Resources and additional context

N/A

**Comment by natasha-moore-elastic** [comment]
Bullet 1: Fixed in https://github.com/elastic/security-docs/pull/6162.
Bullet 2: No longer seems to be an issue after migrating serverless docs to asciidoc.
Bullets 3 & 4: Per our style guide, em dashes are used without spaces.
