### ISSUE TITLE
[Serverless]: Missing hyphen in note

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#6055]
### Serverless Docs

Elastic Security

### Description

**Content reviewed:** [Self-healing rollback (Windows)](https://www.elastic.co/current/serverless/security/self-healing-rollback)

**Issue:** In the first sentence of the cautionary note, “recently added” should be hyphenated.

### Resources and additional context

N/A

**Comment by jmikell821** [comment]
Confirmed this doesn't need a hyphen. Closing.
