### ISSUE TITLE
[Serverless]: Various content and editorial notes for "Enable access for macOS Ventura and higher" page

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#6058]
### Serverless Docs

Elastic Security

### Description

**Content reviewed:** [Enable access for macOS Ventura and higher](https://www.elastic.co/docs/current/serverless/security/deploy-elastic-endpoint-ven) 

**Issues:**
- The three links at the start of the page don’t work if you click on them. The Elastic Endpoint attribute in the link syntax isn’t resolving correctly. For example, if you click on the first link, the page URL is: https://www.elastic.co/docs/current/serverless/security/install-endpoint-manually#approve-the-system-extension-for-Elastic%20Endpoint 
- In the note directly beneath the intro para, the reference to the docs for enrolling the agent isn’t working correctly. The URL for that section has the Elastic Agent attribute at the end: https://www.elastic.co/docs/current/serverless/security/install-edr#configure-and-enroll-the-((agent)) 
- [Enable Full Disk Access for Elastic Endpoint](https://www.elastic.co/docs/current/serverless/security/install-endpoint-manually#enable-full-disk-access-for-elastic-endpoint): A couple of notes for the content before the main steps:
  - In the first sentence of the intro para, I recommend swapping `via` with `using`.
  - Does the first sentence in the note apply to Serverless?

### Resources and additional context

N/A

**Comment by natasha-moore-elastic** [comment]
Bullets 1 & 2 are no longer an issue after migration of serverless docs to asciidoc.
Bullet 3 addressed in https://github.com/elastic/security-docs/pull/6216.
