### ISSUE TITLE
[BUG] Screenshot should be updated for the Register as Antivirus

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#611]
**Description**: Screenshot should be updated for the Register as Antivirus

**Observation**: Restrictions tooltip is not displayed

**URL link or topic name**:
- https://www.elastic.co/guide/en/security/7.12/install-endpoint.html#register-as-antivirus

**Screenshots**:
- Actual:
![1_1](https://user-images.githubusercontent.com/60252716/114021971-e8983800-988e-11eb-977a-402602310966.PNG)

- Expected:
![1_2](https://user-images.githubusercontent.com/60252716/114021975-ea61fb80-988e-11eb-9e7d-b96345db340a.PNG)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @jmikell821

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

The docs are correctly updated for this issue as per [Configure and install Elastic Endpoint integration](https://security-docs_617.docs-preview.app.elstc.co/guide/en/security/master/install-endpoint.html#register-as-antivirus).

**Refer Screenshot**:
![RegisterAsAV](https://user-images.githubusercontent.com/60252716/114669348-65a82f00-9d1f-11eb-8599-d9751d17d4c4.PNG)

Hence, closing this issue!!

Thanks!
