### ISSUE TITLE
[BUG] Endpoint Security inconsistently written as Elastic Endpoint Security or Elastic Security

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#613]
**Description**: Endpoint Security inconsistently written as Elastic Endpoint Security or Elastic Security

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/7.12/es-overview.html
- https://www.elastic.co/guide/en/security/7.12/install-endpoint.html
- https://www.elastic.co/guide/en/security/7.12/ingest-data.html

**Screenshots**:
![3](https://user-images.githubusercontent.com/60252716/114022386-53e20a00-988f-11eb-87f8-a6c8c8e91d34.PNG)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
@muskangulati-qasource thanks for finding these! Current guidelines from Marketing state that Elastic Security should be used when referencing the SIEM and endpoint security capabilities that make up Elastic's security solution. This means I'll need to replace any mentions of Endgame Security, Endpoint Security, and Elastic Endpoint Security in our docs. That said, there are few spots in the Kibana UI that still use the term "Endpoint Security" (see docs [here](https://www.elastic.co/guide/en/security/7.12/install-endpoint.html)) so I'll be leaving those instances intact to ensure they remain in-sync with the actual UI. 
cc: @jmikell821

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

Thank you for providing the information.

Since it is expected as of now, we are closing the ticket.

Thanks!!
