### ISSUE TITLE
[BUG] Screenshot should be updated for the Integration as Ransomware is also added now:

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#614]
**Description**: Screenshot should be updated for the Integration as Ransomware is also added now:

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/7.12/admin-page-ov.html

**Screenshots**:
- Actual:
![4_1](https://user-images.githubusercontent.com/60252716/114022514-7a07aa00-988f-11eb-961d-a4f986bce1c9.PNG)

- Expected:
![4_2](https://user-images.githubusercontent.com/60252716/114022524-7bd16d80-988f-11eb-9eb6-a54c6dfe6110.PNG)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
@muskangulati-qasource thanks for finding this! Doc updates are available for review at #643.

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

This is now fixed as per #643. Hence closing this issue!!

Thanks!
