### ISSUE TITLE
[BUG] Screenshot should be updated for timeline preview flyout:

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#615]
**Description**: Screenshot should be updated for timeline preview flyout:

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/7.12/hosts-overview.html
- https://www.elastic.co/guide/en/security/7.12/detection-engine-overview.html
- https://www.elastic.co/guide/en/security/7.12/rules-ui-create.html
- https://www.elastic.co/guide/en/security/7.12/timelines-ui.html

**Screenshots**:
- Actual:
![5_1](https://user-images.githubusercontent.com/60252716/114022632-9acfff80-988f-11eb-9c82-f7ab824de6d4.PNG)

- Expected:
![5_2](https://user-images.githubusercontent.com/60252716/114022635-9c012c80-988f-11eb-824d-fa27aa1a1260.PNG)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
@manishgupta-qasource and @muskangulati-qasource just wanted to verify whether you're asking for a specific screenshot to be updated across the topics you linked, or if you're asking that _all_ outdated Timeline screenshots are fixed across these topics.

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

> @manishgupta-qasource and @muskangulati-qasource just wanted to verify whether you're asking for a specific screenshot to be updated across the topics you linked, or if you're asking that all outdated Timeline screenshots are fixed across these topics.

All the links mentioned above are having outdated (different) screenshots for the Timeline tab that needs to be updated.

Please let us know if anything is required from our end.

Thanks!!

**Comment by nastasha-solomon** [comment]
@muskangulati-qasource just have one more ask: would you mind specifying which Timeline screenshots are outdated in the [Detections and alerts](https://www.elastic.co/guide/en/security/7.12/detection-engine-overview.html) topic and the [Create a detection rule](https://www.elastic.co/guide/en/security/7.12/rules-ui-create.html) topic? I'm not seeing Timeline-based screenshots in either, but might just be overlooking something, so please correct me if I'm wrong!

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

Sorry for the confusions.

Please find below the screenshots for both the pages that are outdated:

- [Detections and alerts topic](https://www.elastic.co/guide/en/security/7.12/detection-engine-overview.html) 
![Detection Alert](https://user-images.githubusercontent.com/60252716/114507617-fa902700-9c50-11eb-971c-43228086e1e1.png)

- [Create a detection rule](https://www.elastic.co/guide/en/security/7.12/rules-ui-create.html)
![CreateANewRule](https://user-images.githubusercontent.com/60252716/114507621-fc59ea80-9c50-11eb-97bf-d95248110930.png)

Please let us know if anything else is missing from our end.

Thanks!!

**Comment by nastasha-solomon** [comment]
@muskangulati-qasource ah, ok! No worries and thank you for clearing that up!

I'm having some trouble viewing Detections data in my dev environment at the moment, so will need some time to grab an updated version of those images. That said, if you have screenshots ready, I will gladly use those instead and insert them into the docs. In the meantime, #617 has updated docs that are available for review so I'll add you as a reviewer. Thanks again for all your help!

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

Sure, please find attached the screenshots as per the updated UI for both pages:

- [Detections and alerts topic](https://www.elastic.co/guide/en/security/7.12/detection-engine-overview.html)
![1](https://user-images.githubusercontent.com/60252716/114670241-69888100-9d20-11eb-89a9-885e6e6f4ad6.PNG)

- [Create a detection rule](https://www.elastic.co/guide/en/security/7.12/rules-ui-create.html)
![2](https://user-images.githubusercontent.com/60252716/114670246-6ab9ae00-9d20-11eb-94cf-cdbcda582539.PNG)

However, the screenshot for [Investigate events in Timeline](https://www.elastic.co/guide/en/security/7.12/timelines-ui.html) also needs to be updated for the Timeline flyout. The link for the updated doc is not provided on the PR linked: [#617](https://github.com/elastic/security-docs/pull/617). We will approve the PR afterwards. Or if you are going to have another PR for the same, please let us know.

Please let us know if anything else is required from our end.

Thanks!!

**Comment by nastasha-solomon** [comment]
Thanks @muskangulati-qasource! Just added these into the docs so you should see those changes in the doc build shortly.

**Comment by nastasha-solomon** [comment]
Closing issue since changes in #617 have been merged.
