### ISSUE TITLE
[Request] 8.16 Knowledge Base Update

### ISSUE THREAD

**Issue by Charelzard** [elastic/security-docs#6157]
### Description

Update the Knowledge Base to include the following section at the bottom:

Add Knowledge with a Connector or Web Crawler

Connectors and the Web Crawler can continually add knowledge via the various connectors show. Connectors like Github can be setup by navigating in Search to Content>Connectors. Go to the drop down to find the source your looking for to sync data. 

![Image](https://github.com/user-attachments/assets/a3177c79-8ff9-4e0e-9df2-cd9f7dea491a)

The web-crawler can also be used see the video below for a detailed setup. 

https://videos.elastic.co/watch/eYo1e1ZRwT2mjfM7Yr9MuZ?

Per @jamesspi the image and the video link are must haves, let me know if you have any questions. 

### Background & resources

N/A

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.16

### Serverless release

N/A

### Feature differences

N/A

### API docs impact

N/A

### Prerequisites, privileges, feature flags

N/A

**Comment by jamesspi** [comment]
Thanks @Charelzard !

FYI @serenachou @leemthompo
