### ISSUE TITLE
[BUG] Screenshot should be updated for the inline options available when user hovers over the hostname

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#616]
**Description**: Screenshot should be updated for the inline options available when user hovers over the hostname

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/7.12/hosts-overview.html

**Screenshots**:
- Actual:
![7_1](https://user-images.githubusercontent.com/60252716/114022808-c3f09000-988f-11eb-8942-f8f729b5119f.PNG)

- Expected:
![7_2](https://user-images.githubusercontent.com/60252716/114022804-c357f980-988f-11eb-9b6e-7f37ace1af11.png)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @jmikell821

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

The docs are correctly updated for this issue as per [Hosts page overview](https://www.elastic.co/guide/en/security/7.12/hosts-overview.html)

**Refer Screenshot**:
![3](https://user-images.githubusercontent.com/60252716/114671397-b02aab00-9d21-11eb-8222-3372181eaf5a.PNG)

Hence, closing this issue!!

Thanks!
