### ISSUE TITLE
[BUG] The screenshots for events tab should be updated since more options are now available

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#618]
**Description**: The screenshots for events tab should be updated since more options are now available

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/current/visual-event-analyzer.html

**Screenshots**:
![4_1 NewoptionsAvailable](https://user-images.githubusercontent.com/60252716/114383686-75066b80-9bab-11eb-8a9e-5a81d654c9cb.PNG)
![4_1_1](https://user-images.githubusercontent.com/60252716/114383690-759f0200-9bab-11eb-8aee-d347858bb5b2.PNG)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigend to @jmikell821

**Comment by nastasha-solomon** [comment]
@muskangulati-qasource would you mind clarifying what additional options you're seeing on the Events tab? When I checked my test environment, I didn't see any noticeable differences between the current UI and the screenshots you included in this issue. I know it's possible to customize the columns that display in the Events table, but don't believe that impacts the four columns to the far left of the table. Also, the red arrow in the current screenshot covers up the **Sort fields** button, but it's there in the image (just barely!).

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

Sorry for the confusions. We by mistake compared the events tab with the Detections tab and hence reported the issue.

Everything is expected. And hence, closing this issue!!

Thanks!
