### ISSUE TITLE
[BUG] The screenshot for Alerts tab needs to be updated since UI is updated for the same

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#619]
**Description**: The screenshot for Alerts tab needs to be updated since UI is updated for the same

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/current/visual-event-analyzer.html

**Screenshots**:
![5 AlertResolverUIUpdated](https://user-images.githubusercontent.com/60252716/114383757-8bacc280-9bab-11eb-83c7-ed8d3acac326.PNG)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigend to @jmikell821

**Comment by nastasha-solomon** [comment]
@muskangulati-qasource hi! Would you mind sharing what you'd expect to see for this page? I'm having some issues with my data's field mapping so I can't open most of my events in the analyzer at the moment. Thanks in advance for your help!

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

Please find below the screenshot for the alert Resolver UI:
![AlertsResolver](https://user-images.githubusercontent.com/60252716/115663199-c8bc4600-a35d-11eb-83a4-02f9a4f124ca.JPG)

Let us know in case anything else is required from our end.

Thanks!!

**Comment by nastasha-solomon** [comment]
@muskangulati-qasource thanks! Just to clarify, the updated portion of the UI that you initially alluded to is the placement of the Timeline feature?

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

> Just to clarify, are the updated UI portions that you initially alluded to the:
> - Placement of the Timeline feature
> - Two icons to the left of the scale/move buttons

Yes, that's correct.

Please let us know if anything else is required from our end.

Thanks!!

**Comment by nastasha-solomon** [comment]
@muskangulati-qasource appreciate you clarifying! I also updated several screenshots in the "Visual event analyzer" topic that were showing the Timeline feature to the right side of the UI. You can see those and the changes you initially requested when you filed this issue at #643. Thanks again for all your help!

**Comment by muskangulati-qasource** [comment]
@nastasha-solomon,

Thank you for looking into our issues. This is now fixed as per #643.
Hence closing this issue!!

Thanks!
