### ISSUE TITLE
[BUG] The screenshot for Templates Tab needs to be updated since UI is updated for the same

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#620]
**Description**: The screenshot for Templates Tab needs to be updated since UI is updated for the same

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/current/timeline-templates-ui.html

**Screenshots**:
![6_1TemplatesUIUpdated](https://user-images.githubusercontent.com/60252716/114383875-a7b06400-9bab-11eb-93b3-4f042cd02333.PNG)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigend to @jmikell821

**Comment by nastasha-solomon** [comment]
@muskangulati-qasource thanks for finding this. Doc updates are available for review at #633.

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

This issue is now fixed. Hence closing this issue!!

Thanks!
