### ISSUE TITLE
[BUG] Only 03 types of connectors are provided in the screenshot & text

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#621]
**Description**: Only 03 types of connectors are provided in the screenshot & text

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/current/cases-overview.html
- https://www.elastic.co/guide/en/security/current/cases-ui-integrations.html

**Screenshots**:
- Actual:
![7Only03typesOfConnectorsGiven](https://user-images.githubusercontent.com/60252716/114383998-cdd60400-9bab-11eb-8969-ff7ba1d77dbc.PNG)

- Expected:
![7_2Only03typesOfConnectorsGiven](https://user-images.githubusercontent.com/60252716/114384004-cf9fc780-9bab-11eb-80c1-61e1e2c6bcdc.PNG)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigend to @jmikell821

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

ServiceNow ITSM & ServiceNow SecOps are successfully added to the list but the explanation text is missing for both under the 'Create a new connector' section.

Thanks!!

**Comment by nastasha-solomon** [comment]
@muskangulati-qasource thanks for the follow-up! Would you mind clarifying which step under that section is incorrect? If you're referring to step 4, that information should be correct as I verified it with dev (and tested it on my end) post 7.12 release. Thanks in advance for your help!

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

> If you're referring to step 4, that information should be correct as I verified it with dev (and tested it on my end) post 7.12 release.

Thank you for sharing the information for the same. 

We are talking about the following section for the [Configuring external connections](https://www.elastic.co/guide/en/security/current/cases-ui-integrations.html) page: 
![1](https://user-images.githubusercontent.com/60252716/116198024-13213680-a753-11eb-8eb7-1bbc8afca99c.JPG)
If it is expected, please let us know!!

Also, it is not yet updated on the [Cases](https://www.elastic.co/guide/en/security/current/cases-overview.html) page:
![2](https://user-images.githubusercontent.com/60252716/116198190-4bc11000-a753-11eb-8160-1e94d582eb4e.JPG)

Thank you!

**Comment by nastasha-solomon** [comment]
Hi @muskangulati-qasource I believe the information under that section is still correct, but I can verify with dev. The Cases topic should be corrected now and is available for review at #643.

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

This issue is fixed & hence closing this ticket!

Also, we have approved the #643 PR since all the related bugs are fixed.

Thanks!!
