### ISSUE TITLE
[BUG] Wrong screenshot for Rule exception is there under the Endpoint Exception section

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#622]
**Description**: Wrong screenshot for Rule exception is there under the Endpoint Exception section

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/current/detections-ui-exceptions.html#endpoint-rule-exceptions

**Screenshots**:
- Actual:
![9_1RuleExceptionInsteadOfEndpointExeption](https://user-images.githubusercontent.com/60252716/114384226-12619f80-9bac-11eb-8544-baa5974f8ff0.PNG)

- Expected:
![9_2RuleExceptionInsteadOfEndpointExeption](https://user-images.githubusercontent.com/60252716/114384232-1392cc80-9bac-11eb-8461-5ff3a5fc29de.PNG)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigend to @jmikell821

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

This issue is now fixed. Hence closing this issue!!

Thanks!
