### ISSUE TITLE
[BUG] The newly added arguments : 'Integration', 'Policy status' & 'Sensor version' are missing

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#623]
**Description**: The newly added arguments : 'Integration', 'Policy status' & 'Sensor version' are missing

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/7.12/hosts-overview.html

**Screenshots**:
![6_1](https://user-images.githubusercontent.com/60252716/114384323-30c79b00-9bac-11eb-8e8c-5d6a06638838.PNG)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigend to @jmikell821

**Comment by nastasha-solomon** [comment]
@muskangulati-qasource would you mind sharing an example screenshot of what you expect the page to show? I don't see these details available in the UI on my end. Attached a screenshot for reference. Thanks in advance for your help!

<img width="1325" alt="host-details" src="https://user-images.githubusercontent.com/79124755/115618067-2d28c800-a2c0-11eb-9f7f-8a46946839ba.png">

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

Please find below the screenshot for updated UI arguments:
![HostTab](https://user-images.githubusercontent.com/60252716/115663129-a0cce280-a35d-11eb-80e5-41479f75e143.JPG)

Let us know in case anything else is required from our end.

Thanks!!

**Comment by nastasha-solomon** [comment]
Thanks, @muskangulati-qasource! Now that I can see that we're viewing slightly different versions of the host's details page, I'm wondering whether we're using the same build version of the Security app. For reference, my dev environment is a self-hosted cluster that's running a snapshot of the latest build (8.0.0-SNAPSHOT).

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

We are using the 7.12.1 build. And we tested all docs for the same build.

Please let us know if anything else is required from our end.

Thanks!!

**Comment by nastasha-solomon** [comment]
@manishgupta-qasource thanks for the additional info! I checked with the Detections dev team and it looks as though these fields were introduced in 7.13, which means the 7.12 docs won't need to be updated.

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

The changes were present in the 7.12.1 build & hence we logged a bug for the same.

Since it is expected, we are closing this issue.

Thanks!
