### ISSUE TITLE
[BUG] Screenshot contains incomplete logs info for the Integration under Admin tab

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#624]
**Description**: Screenshot contains incomplete logs info for the Integration under Admin tab

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/7.12/admin-page-ov.html#trusted-apps-ov

**Screenshots**:
- Actual:
![1_1 Policy Logs in Admin Tab](https://user-images.githubusercontent.com/60252716/114384404-4a68e280-9bac-11eb-943f-be911d2447eb.PNG)

- Expected:
![1_2 Policy Logs in Admin Tab](https://user-images.githubusercontent.com/60252716/114384408-4b9a0f80-9bac-11eb-84e0-4ed24b8ea942.PNG)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigend to @jmikell821

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

This issue is now fixed. Hence closing this issue!!

Thanks!
