### ISSUE TITLE
[BUG]  Cases is no more a beta feature

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#625]
**Description**:  Cases is no more a beta feature

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/7.12/cases-overview.html

**Screenshots**:
- Actual:
![2_1Cases is not a beta](https://user-images.githubusercontent.com/60252716/114384482-65d3ed80-9bac-11eb-9102-b3bf0c24f352.PNG)
![2_1Cases is not a beta_1](https://user-images.githubusercontent.com/60252716/114384487-67051a80-9bac-11eb-8c62-3193f8984597.PNG)

- Expected:
![2_2 Cases is not a beta](https://user-images.githubusercontent.com/60252716/114384493-68364780-9bac-11eb-8cda-6d91b31a0991.PNG)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigend to @jmikell821

**Comment by jmikell821** [comment]
Closing because this is a duplicate of #563.
