### ISSUE TITLE
[BUG] Screenshot contains old terminology used for Exceptions

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#626]
**Description**: Screenshot contains old terminology used for Exceptions

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/current/detections-ui-exceptions.html
- https://www.elastic.co/guide/en/security/current/tuning-detection-signals.html

**Screenshots**:
- Actual:
![3_1AddException instead ofAddRuleException](https://user-images.githubusercontent.com/60252716/114384580-83a15280-9bac-11eb-9487-7211d88944fb.PNG)
![3_1AddException instead ofAddRuleException_1](https://user-images.githubusercontent.com/60252716/114384587-84d27f80-9bac-11eb-9d4e-8542a5658bb8.PNG)

- Expected:
![3_2AddException instead ofAddRuleException](https://user-images.githubusercontent.com/60252716/114384593-8603ac80-9bac-11eb-813d-637a489b7674.PNG)
![9_2RuleExceptionInsteadOfEndpointExeption](https://user-images.githubusercontent.com/60252716/114384600-8ac86080-9bac-11eb-943b-5a88be255bfd.PNG)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigend to @jmikell821

**Comment by nastasha-solomon** [comment]
@muskangulati-qasource hi again! When you have a chance, I was hoping you could specify the location of the outdated screenshot for the Add Endpoint Exception page. Is it only under the "Nest condition example" section [here](https://www.elastic.co/guide/en/security/current/detections-ui-exceptions.html#ex-nested-conditions), or in other places as well?

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

The same issue is observed under the [Filter out uncommon application alerts](https://www.elastic.co/guide/en/security/current/tuning-detection-signals.html#filter-rule-process) section too in step 4.

Please let us know if anything else is required from our end.

Thanks!

**Comment by nastasha-solomon** [comment]
@muskangulati-qasource thanks for clarifying! Doc updates are available for review at #633.

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

This issue is now fixed. Hence closing this issue!!

Thanks!
