### ISSUE TITLE
[BUG] Incorrect LInk to pricing details on Serverless Create Project docs

### ISSUE THREAD

**Issue by MikePaquette** [elastic/security-docs#6262]
### Documentation links

https://www.elastic.co/guide/en/serverless/current/security-create-project.html

### Description

The link to the pricing details takes users to the ESS pricing page - should point to the Serverless pricing details once this goes live:  
.../cloud-pricing-table?productType=serverless&project=security

![Image](https://github.com/user-attachments/assets/67871e78-ea33-4a41-bd2c-657921f24f53)

### Which documentation set(s) does this bug apply to?

Serverless only

### Release version

Needs to be fixed for GA.

### Testing environment

Staging link for the correct serverless docs.

https://console.qa.cld.elstc.co/cloud-pricing-table?productType=serverless&project=security

**Comment by jmikell821** [comment]
Hi @MikePaquette is this not the correct website we're pointing users to? https://www.elastic.co/pricing/serverless-security.
