### ISSUE TITLE
[UI copy]: Legacy risk scoring module deprecation  in upgrade assistant

### ISSUE THREAD

**Issue by hop-dev** [elastic/security-docs#6270]
### What

UI copy review of this PR: https://github.com/elastic/kibana/pull/202775

In 9.0 the Entity Analytics team will be removing support for the legacy risk scoring modules (Or legacy risk engine as it is sometimes called internally).

As part of this we need to add a section to the Kibana upgrade assistant which informs users that they need to upgrade their risk scoring to use the new risk engine, this can be done in the entity risk scoring management page, and will uninstall the legacy risk engine.

Once all engines in all spaces have been upgraded, this warning will disappear. 

### Related links / assets

PR: https://github.com/elastic/kibana/pull/202775
9.0.0 breaking change (this has the most background): https://github.com/elastic/dev/issues/2822
Task for this specific work: https://github.com/elastic/security-team/issues/11254
Parent implementation task for removing the legacy code: https://github.com/elastic/security-team/issues/11253

### Which documentation set does this change impact?

ESS and serverless

### Feature differences

We could consider adding a documentation page for this, we have the option to add a documentation link to the deprecation warning.

### Software version

8.18

### Collaborators

PM: @joedatlive 
Developer: @hop-dev 
Others (if applicable): @jaredburgettelastic 

### Timeline / deliverables

Before 8.18 Feature freeze 15th Jan 2025

**Comment by natasha-moore-elastic** [comment]
Closing as completed – copy review provided in dev PR.
