### ISSUE TITLE
[BUG]Wrong text for Register as Antivirus: It shows Windows 10 and above, instead it should say, agent version 7.10+

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#631]
**Description**: Wrong text for Register as Antivirus: It shows Windows 10 and above, instead it should say, agent version 7.10+

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/7.12/install-endpoint.html#register-as-antivirus

**Screenshots**:
![RegisterAsAV](https://user-images.githubusercontent.com/60252716/114856662-fe64aa80-9e04-11eb-9d7c-648e8852eacb.PNG)

**Comment by muskangulati-qasource** [comment]
@karanbirsingh-qasource please review!

**Comment by karanbirsingh-qasource** [comment]
reviewed and assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
@muskangulati-qasource quick question! Are you suggesting changing the sentence "If you download the Elastic Agent on Windows 10 or above, you can configure Elastic Security as your antivirus software switching the Register as antivirus toggle on." to "If you download the Elastic Agent version 7.10+ on Windows 10+, you can configure Elastic Security as your antivirus software switching the Register as antivirus toggle on."

@jmikell821 if the above change is correct, what are your thoughts on this phrasing:
If you download version 7.10 or a newer version of the Elastic Agent on Windows 10 or above, you can configure Elastic Security as your antivirus software by switching the Register as antivirus toggle on.

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

> "If you download the Elastic Agent version 7.10+ on Windows 10+, you can configure Elastic Security as your antivirus software switching the Register as antivirus toggle on."

Everything is correct except for the text should not say Windows 10+. The Register as Antivirus is supported by Windows 7 & 8 too. So it is just the endpoint version that needs to be 7.10+ and no constraint on the Windows version.

Please let us know if anything else is required from our end,

Thanks!!

**Comment by nastasha-solomon** [comment]
Thanks for the additional clarification @muskangulati-qasource! When you have a moment, the doc update is ready for review at #643.

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

The link added in the #643 is having the text as: "If you download the Elastic Agent version 7.10 or later on **Windows 10 or above**, you can configure Elastic Security as your antivirus software switching the Register as antivirus toggle on"

Windows 7, 8 also support the Register as Antivirus'. So the constraint for the same should be removed. It should state: "If you download the Elastic Agent version 7.10 or later on Windows, you can configure Elastic Security as your antivirus software switching the Register as antivirus toggle on"

Thanks!

**Comment by nastasha-solomon** [comment]
@muskangulati-qasource ah yes, sorry about that! Updated text is available at #643.

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

The changes are correctly updated. Hence closing this issue!

Thanks!
