### ISSUE TITLE
[BUG] 'Show top host.name' option should be added to the text as per screenshot for the options available for a hostname

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#632]
**Description**: 'Show top host.name' option should be added to the text as per screenshot for the options available for a hostname

**URL link or topic name**: 
- https://security-docs_617.docs-preview.app.elstc.co/guide/en/security/master/hosts-overview.html

**Screenshots**:
![Bug_AddOneMoreOptionInText](https://user-images.githubusercontent.com/60252716/114856970-5a2f3380-9e05-11eb-8b31-f1672ec423b1.PNG)

**Comment by muskangulati-qasource** [comment]
@karanbirsingh-qasource please review!

**Comment by karanbirsingh-qasource** [comment]
reviewed and assigned to @jmikell821

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

This issue is now fixed. Hence closing this issue!!

Thanks!
