### ISSUE TITLE
[DOCS] Detections team 7.13 release

### ISSUE THREAD

**Issue by dontcallmesherryli** [elastic/security-docs#650]
## Description 

The only feature that will show up in 7.13 from the Detections team is the Out Of Cycle Rules update. The feature is still under "Beta" label.

Pre-built rules from Elastic can now be updated outside of Elastic releases, which means users will always be armed with the latest and the greatest of the pre-built rules.

To activate this capability, user just has to visit the fleet page or the endpoint package page. And that is it.

## Acceptance Test Criteria
In the documentation for Pre-built rules page, please add a note that users wishing to have out of cycle rules update should visit the Fleet page to activate that feature.

## Notes

- Add the **"Team:Docs"** label to new issues. 
- Be sure to add the version number label. 
- Be sure to add any necessary screenshots for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by dontcallmesherryli** [comment]
@jmikell821 updated the AC to specify where to put the docs

> ## Acceptance Test Criteria
In the documentation for Pre-built rules page, please add a note that users wishing to have out of cycle rules update should visit the Fleet page to activate that feature.

**Comment by dontcallmesherryli** [comment]
**prebuilt rule reference page notes:**

If rules are updated between now and 7.14 release (right now it's 7.13), then the rule version belong to the current release - 7.13.

**Blurb for the pre-built rule reference page about the new feature:**

"Pre-built rules can now update out of regular release schedule, visit the Fleet Integrations page to add the 'Prebuilt Security Detection Rules' integration to enable the feature."

**Requirements out of Protections meeting:**

1. Ross to reverse last PR to make users manually go into fleet and select "install integration". This is more in line with Beta status of the feature.
2. For 7.13, single source of truth is needed for pre-built rules reference; every time rule package updates, updates are shown in change log of rules between versions; within integration page, "for change log, go to this URL" point URL to change log between versions.

**Comment by rw-access** [comment]
* Pre-built rule reference (rules that came with the stack)
  * Adobe Hijack .... (all of the versions of the rule)
* Pre-built rule updates
  * Update #1 (summary of all the changes with links) 
  * Update #2 (summary of all the changes with links)
  * Update #3 (summary of all the changes with links)

**Comment by jmikell821** [comment]
Merged #666.
