### ISSUE TITLE
[DOCS] Endpoint package mapping change release notes

### ISSUE THREAD

**Issue by jonathan-buttner** [elastic/security-docs#670]
## Description 

In 7.13 we released a new version of the endpoint package (https://github.com/elastic/endpoint-package). This package contains mappings and other entities to setup the Security Solution app before users interact with some of the Fleet and endpoint features. The mappings dictate how we represent pieces of data in Elasticsearch. The 7.13 version of the endpoint package changed a few fields from keyword (basically a string entity) to an unsigned long (a number).

This change technically causes a breaking change for the following behavior. If a user clicks on the histogram icon
![image](https://user-images.githubusercontent.com/56361221/117147938-bbeb1980-ad83-11eb-82bd-b4eff4798d84.png)
for these changed fields, it's likely that the user will see an error. I chatted with @paulewing and @bradenlpreston and we decided that this behavior is ok because the fields are generally for diagnostic information and users will most likely not be creating histograms on them.

We'd like to document in the release notes that the data type for the fields in the mapping changed though just to make users aware. We decided not to include _breaking_ wording in the description or steps to fix the histogram errors at this time since we don't think it'll impact users.

The following fields changed:

| Field | Original Type | New Type | Field Description |
| - | - | - | - |
|`dll.Ext.mapped_address`| `keyword` | `unsigned_long` | The base address where this dll module is loaded. |
|`dll.Ext.mapped_size`|`long`|`unsigned_long`| The size of this dll module's memory mapping, in bytes. |
|`process.thread.Ext.start_address`|`keyword`|`unsigned_long`| Memory address where the thread began execution. |

For the release notes here's a rough draft of something to add:

_The following fields types were changed to `unsigned_long` to better align them with the actual representation of the data: `dll.Ext.mapped_address`, `dll.Ext.mapped_size`, `process.thread.Ext.start_address`._

If you think it'd be good to include the descriptions with the fields that's fine too, so I included them in the table.

## Acceptance Test Criteria

Just a sentence or two in the release notes about the fields that had their type change in this release.

**Comment by nastasha-solomon** [comment]
@jonathan-buttner really appreciate you providing the release notes summary and additional context! Because users might see an error if they click on the histogram icon for these updated fields, should these changes be documented as a known issue in 7.13? Normally, I'd check the dev PR to see how it was flagged for release notes before asking this question, but don't see a PR in this issue's description and am not sure whether it's one of the merged PRs here: https://github.com/elastic/endpoint-package

**Comment by jonathan-buttner** [comment]
> @jonathan-buttner really appreciate you providing the release notes summary and additional context! Because users might see an error if they click on the histogram icon for these updated fields, should these changes be documented as a known issue in 7.13? Normally, I'd check the dev PR to see how it was flagged for release notes before asking this question, but don't see a PR in this issue's description and am not sure whether it's one of the merged PRs here: https://github.com/elastic/endpoint-package

Yeah the endpoint package repo doesn't generate release notes (or have flags) like the kibana repos does. @paulewing @bradenlpreston do we want to document this as a known issue in 7.13?

**Comment by nastasha-solomon** [comment]
Documented this in the known issues section of the 7.13 release notes as per @paulewing @bradenlpreston 's request. Release notes summary is available in the draft at #671. Thanks all for the assistance!
