### ISSUE TITLE
[Docs]Add a what's new/breaking changes sections

### ISSUE THREAD

**Issue by benskelker** [elastic/security-docs#69]
We need a section that tells users what's new in each release. We also need a breaking changes section, as a Cases API call has changed. I've added the breaking changes section in this PR: #64. 

Since we now own the release notes for the Security app, I'd like to see if we can use the RNs section to highlight what's new (including terminology changes requested by @MikePaquette). @DonNateR - I think this is your decision as you're doing the RNs. Whatever we decide, we need to make sure users can easily find a (very :)) high-level list of changes.

Related to: #12, #53  

cc @jmikell821

**Comment by jmikell821** [comment]
@benskelker this also relates to #58. I'll update the TOC, as we'll want to put this in the beginning.
