### ISSUE TITLE
[DOCS] New expection_lists/summary endpoint on lists API

### ISSUE THREAD

**Issue by dasansol92** [elastic/security-docs#729]
## Description 

New route to retrieve summary for exception lists has ben added to the lists API in this pr https://github.com/elastic/kibana/pull/100668

Route: `/api/exception_lists/summary`
Params: `id, list_id, namespace_type`
Response: 
```
{
    windows: PositiveInteger,
    linux: PositiveInteger,
    macos: PositiveInteger,
    total: PositiveInteger,
}
```

There is no label for 7.14, so this is for 7.14

Please let me know if you need more information about this new route.

**Comment by jmikell821** [comment]
Merged #824.
