### ISSUE TITLE
[DOCS] Old screenshot of Case Tab is mentioned in elastic guide

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#731]
## Description 
Old screenshot of Case Tab is mentioned in elastic guide

## Guide URL
https://www.elastic.co/guide/en/security/current/cases-overview.html

## Actual
![image](https://user-images.githubusercontent.com/59917825/120306930-06fb3c80-c2f0-11eb-952c-12e86f7c5592.png)

## Expected
![image](https://user-images.githubusercontent.com/59917825/120306940-09f62d00-c2f0-11eb-9c35-6256b2ae4eed.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @nastasha-solomon

**Comment by nastasha-solomon** [comment]
Merged #746.
