### ISSUE TITLE
[DOCS] Missing ALert Case Sync Functionality in Elastic Guide

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#732]
## Description 
missing Alert Case Sync Functionality in Elastic Guide

## Guide URL
https://www.elastic.co/guide/en/security/current/cases-overview.html

## Actual
![image](https://user-images.githubusercontent.com/59917825/120307345-7ffa9400-c2f0-11eb-928f-fe556d80c62c.png)

## Expected
![image](https://user-images.githubusercontent.com/59917825/120307417-986aae80-c2f0-11eb-9149-974fb4fbbc95.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @nastasha-solomon

**Comment by nastasha-solomon** [comment]
Merged #757.
