### ISSUE TITLE
[DOCS]Missing documentation for Newly added Field under Host details page in Elastic Guide

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#733]
## Description 
Missing documentation for Newly added Field under Host details page in Elastic Guide

- Integration
- Policy status
- Sensor Version

## Guide URL
https://www.elastic.co/guide/en/security/current/hosts-overview.html

## Actual
![image](https://user-images.githubusercontent.com/59917825/120307785-02835380-c2f1-11eb-99da-a16ce0279571.png)

## Expected
![image](https://user-images.githubusercontent.com/59917825/120307841-10d16f80-c2f1-11eb-8159-553ce2bc43f6.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @nastasha-solomon

**Comment by nastasha-solomon** [comment]
@jmikell821 believe this screenshot shows the host details of a host with an integration installed, but am not sure whether it's the Security integration or a Beats one.

**Comment by karanbirsingh-qasource** [comment]
yes @nastasha-solomon  you are correct. 

Please find below details observations:

- If Only Beats are installed to our Kibana environment
![image](https://user-images.githubusercontent.com/59917825/121308560-cff3df00-c91e-11eb-8d96-00dcce93ff30.png)
![image](https://user-images.githubusercontent.com/59917825/121308542-ccf8ee80-c91e-11eb-91e8-9693661d977b.png)

- If Endpoint Security integration is installed to our Kibana environment then only we are seeing the newly added field
![image](https://user-images.githubusercontent.com/59917825/121308438-b0f54d00-c91e-11eb-8c44-66eb3d60ce64.png)
![image](https://user-images.githubusercontent.com/59917825/121308498-bfdbff80-c91e-11eb-8125-e2eafa923cf2.png)

Hence we are closing this issue.

thanks !!
