### ISSUE TITLE
[BUG]  Newly added alert notification place holders like {{rule.type}} are missing under placeholders to rule action fields for 7.13.0

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#735]
**Description**: Newly added alert notification place holders like {{rule.type}} are missing under placeholders to rule action fields for 7.13.0

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/current/rules-ui-create.html#rule-action-variables

**Screenshots**:
![rules_variables](https://user-images.githubusercontent.com/61860752/120311751-7c1d4080-c2f5-11eb-940a-6308ba33082c.jpg)

![rules_variable_kibana](https://user-images.githubusercontent.com/61860752/120311745-7aec1380-c2f5-11eb-8efe-0624e98a5d4e.jpg)

**Comment by deepikakeshav-qasource** [comment]
@manishgupta-qasource Please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @nastasha-solomon

**Comment by joepeeples** [comment]
Resolved in PR #881.
