### ISSUE TITLE
[BUG] Incorrect Type of value list name are displayed in value list

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#737]
**Description**: Incorrect Type of value list name are displayed in value list

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/current/detections-ui-exceptions.html

**Screenshots**:
![Exception_doc](https://user-images.githubusercontent.com/61860752/120317007-b984cc80-c2fb-11eb-8608-2d6ea232dce4.jpg)

**Expected:**
![Values_kibana](https://user-images.githubusercontent.com/61860752/120316896-922dff80-c2fb-11eb-8cab-b6bf10154ba8.jpg)

**Comment by deepikakeshav-qasource** [comment]
@manishgupta-qasource Please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @nastasha-solomon

**Comment by jmikell821** [comment]
@manishgupta-qasource please assign all issues to me, then I'll reassign to my staff as appropriate. Thank you.

**Comment by manishgupta-qasource** [comment]
Thank you for the update @jmikell821 

Sure Moving forward, I will assigning all doc issues to you

I will update all Doc issue reported in last 2 days

**Comment by nastasha-solomon** [comment]
@deepikakeshav-qasource docs are ready for your review at #880.

**Comment by deepikakeshav-qasource** [comment]
Hi @nastasha-solomon ,

We have validated this issue and observed that issue is **fixed**

![image](https://user-images.githubusercontent.com/61860752/128842098-bd8dc06f-2183-43aa-a770-53593540039d.png)

Hence, we are closing this issue

Thanks!!
