### ISSUE TITLE
[BUG] Screenshot for the Agent status on the Policy tab should be updated

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#738]
**Description**: Screenshot for the Agent status on the Policy tab should be updated

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/current/admin-page-ov.html

**Screenshots**:
- Actual:
![1_Ac](https://user-images.githubusercontent.com/60252716/120475035-822f2200-c3c6-11eb-85c5-50a86f97ad2c.JPG)

- Expected:
![1_E](https://user-images.githubusercontent.com/60252716/120475044-84917c00-c3c6-11eb-849f-df3dfc6cb20d.JPG)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @nastasha-solomon

**Comment by nastasha-solomon** [comment]
Thanks for finding this @muskangulati-qasource! After checking for similarly outdated screenshots in our docset, I found that the screenshot under the [Verify the Elastic Endpoint enrollment](https://www.elastic.co/guide/en/security/7.x/install-endpoint.html#verify-endpoint-enrollment) section needs to be updated as well. I'll be taking care of that, and the error you described, on Monday.

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

This ticket is fixed and also we have approved the PR https://github.com/elastic/security-docs/pull/743

Hence, we are closing this ticket.

Thanks!
