### ISSUE TITLE
Event Filtering [7.14][DOCS]

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#741]
## Description 
Epic: https://github.com/elastic/security-team/issues/881

Users have events that are high volume/noisy and not helpful or useful to them (for example, metricbeat process events, or the same process making a network connection over and over to the same IP/port on a busy network server). We want to give users the ability to filter out events that they no longer want stored. We could do this similar to the way we do exceptions; drop events that match a given rule. This will make a user's storage in ES last longer.

## License
Basic

## Acceptance Test Criteria

**Users can add event filters two ways:**

1. Administration: Users can go to the "Event filters" tab in the Admin section and "Add Endpoint Event filter". This path will present the user with a blank form that they can fill out. 
![image](https://user-images.githubusercontent.com/26076500/120815849-38594f80-c51e-11eb-9fe0-7b0c691f9151.png)

![image](https://user-images.githubusercontent.com/26076500/120816055-663e9400-c51e-11eb-87f2-0516c0177d8a.png)

<br />

2. Hosts tab > Events (sub-tab). Users can add an event filter directly from an Event. The "Add Endpoint Event Filter" option will be available on events that are from the Endpoint.  Doing this will populate the form automatically with fields/values related to the event. (Note: text currently says "event exception", this will be updated)

![image](https://user-images.githubusercontent.com/26076500/120816286-9b4ae680-c51e-11eb-8301-17aeffc5a839.png)

![image](https://user-images.githubusercontent.com/26076500/120816440-bcabd280-c51e-11eb-82b4-523815e0b76b.png)

![image](https://user-images.githubusercontent.com/26076500/120816790-144a3e00-c51f-11eb-981a-3311d2fa1ee1.png)

**Comment by jmikell821** [comment]
@caitlinbetz @kevinlog hi - qq. Like exceptions, there are nested condition options with event filters and I was wondering if they had the same requirements as exceptions? The [docs say:](https://www.elastic.co/guide/en/security/current/detections-ui-exceptions.html#ex-nested-conditions) 
> Some Endpoint objects contain nested fields, and the only way to ensure you are excluding the correct fields is with nested conditions. One example is the process.Ext object:.....

> Only these objects require nested conditions to ensure the exception functions correctly:

![2021-07-26_18-01-17](https://user-images.githubusercontent.com/57149392/127064861-cd3e6d00-fb82-43fe-8b62-80c2dffc08a1.png)

I just want to make sure there aren't any caveats about nested conditions that I need to document here.
