### ISSUE TITLE
[REVISION] Refreshing Sections in the Cases Topic 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#748]
Update procedures for opening new cases and managing existing ones. 

[Google doc](https://docs.google.com/document/d/1kJfU1aAF4f4LHUeUTcfeh-xIL9cMlHpKcuVkLhy0hUI/edit?usp=sharing) tracking suggested edits.

**Comment by jmikell821** [comment]
Closing; revisions in new topic.
