### ISSUE TITLE
[DOCS] Event Filters block Endpoint events from being streamed, so some custom Detection rules may not fire

### ISSUE THREAD

**Issue by kevinlog** [elastic/security-docs#770]
## Description 

TODO for now, scenarios is described here: https://github.com/elastic/kibana/issues/102619

## Acceptance Test Criteria

List all the ATC of each action and its intended result. 
For example: As a user, when [action (e.g., viewing, clicking, selecting, etc.)] I should [insert the expected result]. 

If the enhancement requires a procedure, include the steps.  

## Notes

- Add all appropriate labels to the issue, especially the version number label. 
- Be sure to add any necessary screenshots, code text or console commands for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by jmikell821** [comment]
Merged #837.
