### ISSUE TITLE
[DOCS] CTI enhancements to the alert details pane 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#773]
The following enhancements to the Summary and Threat Intel tabs need to be documented in the [Manage detection alerts](https://www.elastic.co/guide/en/security/master/alerts-ui-manage.html#view-alert-details) topic.

- The **Summary** tab used to have two separate sections: one displayed a compilation of alert details, and the other showed threat indicator data. In 7.14, those two sections have been combined into the **alert summary** section, which displays Indicator Match Enrichment (IME) data and Investigation Time Match (ITM) data. Refer to [this comment](https://github.com/elastic/security-team/issues/1002#issuecomment-875047904) for more details about IME and ITM data on this tab and the Threat Intel tab. 
- ITM data on the Summary tab is usually placed at the bottom of the **alert summary** section on the **Summary** tab and appended with text describing the indicator match source. 
  - Will need to keep an eye on https://github.com/elastic/security-team/issues/1457 as this might change. 
-  The **Threat Intel** tab now has descriptive headers that follow this structure: which field matched (`matched.field`), the value matched (`matched.atomic`), and the provider of the indicator. See the third screenshot at https://github.com/elastic/kibana/pull/103383 for an example.  
- Users can click on the magnifying glass icon on the **Threat Intel** tab to inspect the query used to pull in ITM data. More information about the query and fields is [here](https://github.com/elastic/security-team/issues/1002#issuecomment-875047904).

**Comment by rylnd** [comment]
@nastasha-solomon I added some documentation-focused [comments](https://github.com/elastic/security-team/issues/1002#issuecomment-875047904) on the linked issue.

**Comment by nastasha-solomon** [comment]
Merged #808.
