### ISSUE TITLE
[DOCS] Tooltips needed for the timeline action dropdown and next to “add value list” button 

### ISSUE THREAD

**Issue by dontcallmesherryli** [elastic/security-docs#78]
## Description 

To help users use the new features, we need hoverover tooltips for when timeline action dropdown items are greyed out and for the "add value list" button in the Detection Rules page.:

## Acceptance Test Criteria

Tooltips for:

1. timeline action dropdown menu when actions are greyed out - things are greyed out because user didn’t name their Timeline yet
2. next to “add value list” button on Detection Rules page to let users know what value lists are

## Notes

- Add the **"Team:Docs"** label to new issues. 
- Be sure to add the version number label. 
- Be sure to add any necessary screenshots for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by benskelker** [comment]
Upload value list tooltip:
Upload a file with values used for defining rule exceptions, such as IP addresses or `host.name` keywords.

Timeline tooltip:
To perform these actions, you must add a name to the _Untitled timeline_ field. 
Note: Timelines are automatically saved when a name is provided.

@dontcallmesherryli - let me know if these are okay or changes are needed.

**Comment by dontcallmesherryli** [comment]
This looks good, thanks @benskelker
