### ISSUE TITLE
[BUG] Cases connector docs need to specify one-way communication to the third party

### ISSUE THREAD

**Issue by stephmilovic** [elastic/security-docs#802]
**Description**: 
The issue keeps coming up that users expect updates made on the third party system to be made in Kibana Cases. However, we do not currently support bidirectional communication. We need to specify in the docs to only expect Cases to push updates to third parties, and that it will not relieve updates

**URL link or topic name**:
UI docs:
https://www.elastic.co/guide/en/security/master/cases-overview.html
https://www.elastic.co/guide/en/security/master/cases-ui-integrations.html
These API docs might need to the info too:
https://www.elastic.co/guide/en/security/master/register-connector.html
https://www.elastic.co/guide/en/security/master/update-connector.html
https://www.elastic.co/guide/en/security/master/cases-api-create.html
https://www.elastic.co/guide/en/security/master/actions-api-overview.html

**Comment by nastasha-solomon** [comment]
Merged #795.
