### ISSUE TITLE
[DOCS] Cases API Docs

### ISSUE THREAD

**Issue by jonathan-buttner** [elastic/security-docs#809]
## Description 

This issue is to track the work to update the Cases API docs for the 7.14.0 release. This isn't a request for the docs team but  mainly a reminder for myself to update the docs and a place to track that work.

## Acceptance Test Criteria

There are four main changes that need to be included:
- [x] Get all alerts attached to a case (https://github.com/elastic/kibana/pull/101878)
- [x] Get all Case IDs that have a specific alert attached to them (https://github.com/elastic/kibana/pull/98702)
- [x] Addition of the `owner` field (https://github.com/elastic/kibana/pull/95058)
- [x] Changes to the configuration API (https://github.com/elastic/kibana/pull/95058)

PR: https://github.com/elastic/security-docs/pull/835

**Comment by jmikell821** [comment]
Merged #835.
