### ISSUE TITLE
[7.15] Behavior Protection - Policy[DOCS]

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#828]
## Description 
Allow users to configure behavioral protection in their policy

Issues:
https://github.com/elastic/security-team/issues/1272
https://github.com/elastic/security-team/issues/1086
Allow users to configure behavioral protection in their policy

## Acceptance Test Criteria

- Users can successfully configure behavior protection in policy
- Users can view alerts associated with behavior protection rule
- Users can add exceptions based on behavioral protection alerts

**Comment by joepeeples** [comment]
Merged #994.
