### ISSUE TITLE
[7.15] Endpoint List refactor - tech debt[DOCS]

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#829]
## Description 

This issue **may not require any docs related effort.** Creating ticket for awareness.

Issue:
https://github.com/elastic/security-team/issues/1419

**Comment by caitlinbetz** [comment]
@kevinlog will the endpoint list refactor require any documentation/updates?

**Comment by kevinlog** [comment]
@caitlinbetz no, I don't think so.  It will look different so @jmikell821 may want updated screenshots, but no additional documentation is needed.

**Comment by jmikell821** [comment]
#1010 merged.
