### ISSUE TITLE
[7.16] Trusted Applications by Policy[DOCS]

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#832]
## Description 

Allow users to configure their set of trusted apps on a global _or_ per policy basis 

Issue:
https://github.com/elastic/security-team/issues/122

As a security solution user, I need to be able to target a set of hosts with certain configurations and and settings (like exceptions and trusted applications). The settings may need to be unique to that group, and not applied to any other hosts in my organization.

**Comment by caitlinbetz** [comment]
Updated, this will _not_ ship in 7.15.

**Comment by joepeeples** [comment]
Closing this issue as duplicate of #1102, which has more details and link to mock UI.
