### ISSUE TITLE
[DOCS] Troubleshooting guide for Endpoint list when Transform stops running

### ISSUE THREAD

**Issue by kevinlog** [elastic/security-docs#855]
## Description 
A common problem when users run Endpoint security is when a particular component, called a transform, stops running for different reasons.  We've taken action to address the root cause of the problem, but we'd like to add a troubleshooting guide for users that they can access in app so that they can resolve the issue themselves without the need to contact support.

Relevant PR for where this guide will be referenced in app: https://github.com/elastic/kibana/pull/107248

## Acceptance Test Criteria

In the event that users are not seeing Endpoint list data update, they should check the transform:

1. Instruct users to navigate to "Stack Management > Transforms"

![image](https://user-images.githubusercontent.com/56395104/127665921-78f322a8-fffa-441e-b76e-f75643359501.png)

2. Enter `endpoint.metadata_current-default` into the search bar

3. If the transform with the prefix `endpoint.metadata_current-default` is stopped, open up actions and click "Start"

![image](https://user-images.githubusercontent.com/56395104/127666362-5d93651b-df88-4173-8c03-2939a2fce791.png)

![image](https://user-images.githubusercontent.com/56395104/127666435-497686f8-b46a-40e2-81fb-e24c0256e393.png)

4. You should eventually see the transform return to a running state.  You may need to reload the page to see the state change.

![image](https://user-images.githubusercontent.com/56395104/127666655-dde793df-9d93-415c-b863-8197bf2fa1a4.png)

5. If the transform with the prefix `endpoint.metadata_current-default` is failed, open up the actions and click "Stop".  The transform should enter the "Stopped" state.  Then open up the actions again and click "Start".

![image](https://user-images.githubusercontent.com/56395104/127666894-f1d30631-983a-43d3-a309-9c7fab297b3e.png)

![image](https://user-images.githubusercontent.com/56395104/127666435-497686f8-b46a-40e2-81fb-e24c0256e393.png)

6. You should eventually see the transform return to a running state.  You may need to reload the page to see the state change.

![image](https://user-images.githubusercontent.com/56395104/127666655-dde793df-9d93-415c-b863-8197bf2fa1a4.png)

7. After the transform is running again, the warning on the Endpoints list should clear and you will start to get updated data in your list.

## Notes

- Add all appropriate labels to the issue, especially the version number label. 
- Be sure to add any necessary screenshots, code text or console commands for clarity. 
- Include any conditions or caveats that may affect customers.

**Comment by joepeeples** [comment]
Merged #1043.
