### ISSUE TITLE
[DOCS]Round Closing bracket missing for under Create Case Doc

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#894]
## Description 
Round Closing bracket missing for under Create Case Doc

## Guide URL
- https://www.elastic.co/guide/en/security/current/cases-api-create.html

## Actual
![image](https://user-images.githubusercontent.com/59917825/128298222-3da3f244-8aeb-4394-b026-c40bf6d579de.png)

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource docs are ready for your review at #921.

**Comment by karanbirsingh-qasource** [comment]
**Issue is Fixed :** 
![image](https://user-images.githubusercontent.com/59917825/128988451-cb6ee120-305b-42ef-bbd0-66c5eb80363e.png)

Hence closing this issue .
