### ISSUE TITLE
[DOCS]Breadcrumb information not matching with the case name under Cases doc

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#895]
## Description 
Breadcrumb information not matching with the case name under Open a new Cases doc

## Guide URL
https://www.elastic.co/guide/en/security/current/cases-overview.html

## Actual
![image](https://user-images.githubusercontent.com/59917825/128298366-a471d2a3-dd01-4364-9498-1828af53aaa2.png)

## Expected
![image](https://user-images.githubusercontent.com/59917825/128298411-e5056fa0-487f-453e-a8fb-24de19afe1d7.png)

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource docs are ready for your review at #918.

**Comment by karanbirsingh-qasource** [comment]
**Issue Fixed:** 
![image](https://user-images.githubusercontent.com/59917825/128825009-27f260f1-8ca4-435c-96cf-53b31ef54d7d.png)

Hence Closing this issue.
