### ISSUE TITLE
[DOCS]Comment is mentioned to be overwritten however expected it to be append under Swimlane mapping doc

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#896]
## Description 
Comment is mentioned to be overwritten however expected it to be append under Swimlane mapping doc

## Guide URL
- https://www.elastic.co/guide/en/security/current/cases-ui-integrations.html

## Actual
![image](https://user-images.githubusercontent.com/59917825/128298664-36b03cc4-920c-4a24-bca8-3b486a25c433.png)

## Expected
![image](https://user-images.githubusercontent.com/59917825/128298697-5037ba46-c55b-4c91-ae5b-9ec2dfaef5e2.png)

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource docs are ready for your review at #917.

**Comment by karanbirsingh-qasource** [comment]
**Issue Fixed:** 
![image](https://user-images.githubusercontent.com/59917825/128825311-7ae057d7-6511-4812-971f-b93cc268ed45.png)
Hence Closing this issue.
