### ISSUE TITLE
[DOCS]Incorrect Service Now Mapping to Comment Field under ServiceNow mapping doc

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#897]
## Description 
Incorrect Service Now Mapping to Comment Field under ServiceNow mapping doc

## Guide URL
- https://www.elastic.co/guide/en/security/current/cases-ui-integrations.html

## Actual
![image](https://user-images.githubusercontent.com/59917825/128298814-5e3d4fde-a915-4504-b11c-4097c2767570.png)

## Expected
- Service Now ITSM
![image](https://user-images.githubusercontent.com/59917825/128298862-491e384d-30cd-40bb-a592-34b58c059cae.png)
 
- Service Now SecOps
![image](https://user-images.githubusercontent.com/59917825/128298881-31ec9a11-fb0e-4b0e-beff-5a596e8b944b.png)

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource docs are ready for your review at #925.

**Comment by karanbirsingh-qasource** [comment]
Hi Team,

Issue is now fixed as required changes are now available in the docs.
![image](https://user-images.githubusercontent.com/59917825/129140697-31c2316a-93c8-4459-bb29-f33b06abec60.png)

Hence Closing this issue .
