### ISSUE TITLE
[DOCS]New Security Solution Detect Group changes are mismatching in Doc

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#898]
## Description 
New Security Solution Detect Group changes are mismatching in Doc

## Guide URL
- https://www.elastic.co/guide/en/security/current/index.html

## Actual
![image](https://user-images.githubusercontent.com/59917825/128299391-0dacc5ca-3938-4bb2-8aae-f8317f9e20aa.png)

## Expected

As we can see in the doc index page , all new security groups introduced [ that is Explore , investigate & Manage] are showing correctly expect Detect , Old naming Detection and Alert is showing currently , which need to be updated to Detect

![image](https://user-images.githubusercontent.com/59917825/128299352-2704488a-2940-4e9b-bee7-22a4a9b5dc6c.png)

**Comment by jmikell821** [comment]
Hi @karanbirsingh-qasource - I purposely did not label this section `Detect` because `Detections and alerts` is a pretty lengthy intro topic. However, I will ping the Detections & Response team to see if they feel strongly about having this match exactly.

**Comment by karanbirsingh-qasource** [comment]
> 
> 
> Hi @karanbirsingh-qasource - I purposely did not label this section `Detect` because `Detections and alerts` is a pretty lengthy intro topic. However, I will ping the Detections & Response team to see if they feel strongly about having this match exactly.

Yes @jmikell821 thanks for sharing the update and point of view for the current doc
