### ISSUE TITLE
[DOCS]Alert Page under 7.14.0 Doc is showing future changes of 7.15.0 under Elastic Security UI Doc

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#901]
## Description 
Alert Page under 7.14.0 Doc is showing future changes of 7.15.0 under Elastic Security UI Doc

## Guide URL
- https://www.elastic.co/guide/en/security/current/es-ui-overview.html

## Actual
![image](https://user-images.githubusercontent.com/59917825/128300281-d0064119-9768-4357-90ed-90dcfd23a7be.png)
![image](https://user-images.githubusercontent.com/59917825/128300301-f2ff024f-953a-4b87-9c08-e33dc6017563.png)

## Expected
- 7.14.0 Alert Page UI
![image](https://user-images.githubusercontent.com/59917825/128300334-6a8f98d3-1ed2-4c65-baea-d1316fda58ce.png)

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource docs are ready for review at #926.

**Comment by karanbirsingh-qasource** [comment]
Hi Team,

This issue is now fixed as required changes are now there in docs.
![image](https://user-images.githubusercontent.com/59917825/129140883-6da39ac6-11d5-41ef-a80f-e072027a085d.png)

Hence Closing this issue.
