### ISSUE TITLE
[DOCS]Incorrect reference of Trusted App under Event Filter Section Doc

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#902]
## Description 
Incorrect reference of Trusted App under Event Filter Section Doc even though we have separate doc page dedicate for Event Filters

## Guide URL
- https://www.elastic.co/guide/en/security/current/es-ui-overview.html

## Actual
![image](https://user-images.githubusercontent.com/59917825/128300511-d3cc4f1e-c566-4f0c-84ee-22b4ea51c1b9.png)

## Expected
Reference should be of Event Filter instead of Trusted Application for more information under Event Filter Section as we have page available for it
https://www.elastic.co/guide/en/security/current/event-filters.html

**Comment by jmikell821** [comment]
@nastasha-solomon change the `Page tabs` heading to `Page navigation` as well.

**Comment by nastasha-solomon** [comment]
Merged #914.
