### ISSUE TITLE
[DOCS]Old Host Page Navigation Screen-Shoot under Host Page Overview Doc

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#903]
## Description 
Old Host Page Navigation Screen-Shoot under Host Page Overview Doc

## Guide URL
- https://www.elastic.co/guide/en/security/current/hosts-overview.html

## Actual
![image](https://user-images.githubusercontent.com/59917825/128300878-c7d7ac81-3762-400b-b86a-6de7ae9ccc33.png)
![image](https://user-images.githubusercontent.com/59917825/128300892-a5dc3713-72cf-4522-897c-d4d7a0c76979.png)

## Expected
![image](https://user-images.githubusercontent.com/59917825/128300905-a709d66b-4a31-4d07-9c10-85715fc667ab.png)

**Comment by joepeeples** [comment]
@karanbirsingh-qasource docs are ready to review at #948. Thank you!

**Comment by karanbirsingh-qasource** [comment]
Hi Team,

The issue has been fixed now , required changed are now available in the doc.

![image](https://user-images.githubusercontent.com/59917825/129668435-57340a8e-b137-456a-8d71-04fec85963bc.png)
![image](https://user-images.githubusercontent.com/59917825/129668422-e13665cc-2b18-4859-b08e-427d9e1fdab6.png)

Hence closing this issue.
