### ISSUE TITLE
[DOCS]Export option missing for Timeline and Template All action 

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#907]
## Description 
Export option missing for Timeline and Template All action 

## Guide URL
- https://www.elastic.co/guide/en/security/current/timelines-ui.html#import-export-timelines
- https://www.elastic.co/guide/en/security/current/timeline-templates-ui.html

## Actual
- - Timeline All Actions
![image](https://user-images.githubusercontent.com/59917825/128301794-46410a39-1d69-4bba-afd4-ba7ef33e2d53.png)
- Timeline Template All Actions
![image](https://user-images.githubusercontent.com/59917825/128301858-f9f9f3de-de2c-49d0-93b7-b3396eef7b61.png)

## Expected
- Timeline All Actions
![image](https://user-images.githubusercontent.com/59917825/128301841-ff0d8728-61d6-4a8a-9a1e-bbd71263a303.png)
- Timeline Template All Actions
![image](https://user-images.githubusercontent.com/59917825/128301871-f7b3e189-0efa-465d-a88c-e728601333f5.png)

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource just so I have a better idea of what's being described in this doc issue, would you mind elaborating on what the doc bug is? Docs for [exporting Timelines](https://www.elastic.co/guide/en/security/current/timelines-ui.html#import-export-timelines) and [Timeline templates](https://www.elastic.co/guide/en/security/7.14/timeline-templates-ui.html#_export_and_import_timeline_templates) are currently available, they're just provided as a separate set of procedures.

**Comment by karanbirsingh-qasource** [comment]
> 
> 
> @karanbirsingh-qasource just so I have a better idea of what's being described in this doc issue, would you mind elaborating on what the doc bug is? Docs for [exporting Timelines](https://www.elastic.co/guide/en/security/current/timelines-ui.html#import-export-timelines) and [Timeline templates](https://www.elastic.co/guide/en/security/7.14/timeline-templates-ui.html#_export_and_import_timeline_templates) are currently available, they're just provided as a separate set of procedures.

Yes @nastasha-solomon  please find below detailed explanation of the issue

Currently under the doc for the all action ( specifically )for timeline and timeline template , **export** action is missing . if we see the kibana UI if we click on ... against the timeline and Timeline template export is present there in both bulk and single item all actions.

**_Updated html and highlighted the expected change to show in doc_**
![image](https://user-images.githubusercontent.com/59917825/128823891-b820364f-2aa9-4a1c-9fa2-3ad8d561b97c.png)
![image](https://user-images.githubusercontent.com/59917825/128824244-87fe1cfa-e219-416a-be3a-121c9abe0050.png)

please let us known if something more is required from our end

**Comment by nastasha-solomon** [comment]
Appreciate you providing this additional feedback @karanbirsingh-qasource. When you have a chance, the updates are ready for your review at #943. Thanks as always for the help!

**Comment by karanbirsingh-qasource** [comment]
Thanks @nastasha-solomon for approving the suggestions .

Issue is fixed now , Required changes for doc are now available.
- timeline
![image](https://user-images.githubusercontent.com/59917825/129667960-15e20c59-fbc7-47cb-bc34-a6b24018a210.png)

- timeline template
![image](https://user-images.githubusercontent.com/59917825/129667942-47bad527-5389-4860-b913-ad92ead88437.png)

Hence closing this issue
