### ISSUE TITLE
[DOCS] Expand Rule Monitoring docs with links to Alerting Monitoring resources

### ISSUE THREAD

**Issue by spong** [elastic/security-docs#932]
The Alerting team has extensive resources on monitoring and troubleshooting ([here](https://www.elastic.co/guide/en/kibana/master/task-manager-health-monitoring.html#task-manager-health-monitoring) and [here](https://www.elastic.co/guide/en/kibana/master/task-manager-troubleshooting.html#task-manager-health-tasks-run-late)), and would be good resources to link off to from our existing [Monitoring and Troubleshooting guide](https://www.elastic.co/guide/en/security/current/alerts-ui-monitor.html) as next/additional steps for users to try when debugging gaps/scaling.

**Comment by joepeeples** [comment]
Addressed in #970.
