### ISSUE TITLE
[DOCS] 7.14.1 Release Notes 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#969]
For this release, which is publishing on Aug. 31:

- Check out the `7.x` branch
   - run a `git fetch origin` then `git pull` to pull in latest changes 
- Merge to `7.x` (not `main`)
- Backport to `7.14` and `7.15`

(Do anytime the week of Aug. 23rd)

**Comment by nastasha-solomon** [comment]
Merged #987.
