### ISSUE TITLE
[DOCS] Alerts table updates (RAC) 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#991]
Google doc notes [here](https://docs.google.com/document/d/1r_XEahxgx7MWZmexdQP4ueiQmG3pTpHR36sSYXP3yrI/edit?usp=sharing). 

![2021-08-25_11-08-25](https://user-images.githubusercontent.com/57149392/130869101-4f50937f-bf0b-4e98-be4d-e95c8022024e.png)

Alert statuses are now:

- Open 
- Acknowledged
- Closed 

These have moved from the Alerts table to the Trend histogram. Select a status to update the histogram and the Alerts table. 

**Note:** Check for references of “In Progress” alert statuses, since that’s been replaced w/ “Acknowledged.” 

- Update status via Actions menu (...) or by expanding Alert details flyout. 
![2021-08-25_16-35-23](https://user-images.githubusercontent.com/57149392/130869243-17c023ed-b36f-4b27-9eef-9daa4fa25774.png)
![2021-08-25_16-36-57](https://user-images.githubusercontent.com/57149392/130869257-37e14512-54bf-47a8-bb9c-e8f3415ec701.png)

**Remember:** Click “Filter out value” to filter by that field, which updates the Alerts table view
![2021-08-25_17-02-56](https://user-images.githubusercontent.com/57149392/130869362-825b2bb4-db59-4a4c-a1fe-314a1a922499.png)

- Select **Columns** to drag and reorder visible columns in Alerts table 
![2021-08-25_16-48-25](https://user-images.githubusercontent.com/57149392/130869455-5d6faeaa-e630-4bef-a396-206fce502f86.png). You can also order columns A-Z, move left, right, etc. 

- Grid view vs. Rendered view
   - Grid view: tabular data, can group/sort by fields 
   - Event rendered view: event rendering for each event

![2021-08-25_16-57-46](https://user-images.githubusercontent.com/57149392/130870124-1540c715-bf1d-4116-83dd-a80d3a39244f.png)

- "Reason" column by defaults shows reason the alert was generated. Can select "event rendered view" to view all event renders.
![2021-08-25_18-00-14](https://user-images.githubusercontent.com/57149392/130871837-ed6d2e55-f905-4f1a-891d-d25086c9b9ce.png)

**Comment by joepeeples** [comment]
Also remember to update the screenshot of the Alerts page on the "Elastic Security UI" overview page:

![image](https://user-images.githubusercontent.com/87339667/132065251-7344f7ef-6e13-4e29-b799-a1ad237da876.png)

**Comment by joepeeples** [comment]
Merged #1028.
