### ISSUE TITLE
Discrepancy in Detections API Documentation [DOCS]

### ISSUE THREAD

**Issue by MakoWish** [elastic/security-docs#992]
## Description 

The URI's listed on the page [Detection API](https://www.elastic.co/guide/en/security/current/rule-api-overview.html#rule-api-overview) are incorrect and result in a 404. They are all listed as:

`<kibana host>:<port>/api/detection_engine/<endpoint>`

but on the page [Export rules](https://www.elastic.co/guide/en/security/current/rules-api-export.html#_request_url_15), it lists the `_export` endpoint as including `/rules/` in the URI:

`<kibana host>:<port>/api/detection_engine/rules/_export`

This does result in a successful export of the rules. It seems the [Detection API](https://www.elastic.co/guide/en/security/current/rule-api-overview.html#rule-api-overview) page needs to be updated to include `/rules/` in the URI.

**Comment by jmikell821** [comment]
Hi - can someone on the @elastic/security-detections-response team confirm the correct [Detection API](https://www.elastic.co/guide/en/security/current/rule-api-overview.html#rule-api-overview) parameters please? 

cc: @peluja1012 @spong

**Comment by spong** [comment]
Looks like these three need to be updated to include `/rules/` on the main [Detections API](https://www.elastic.co/guide/en/security/current/rule-api-overview.html#rule-api-overview) docs page:

- [ ] <kibana host>:<port>/api/detection_engine/_import - Imports rules from an .ndjson file ([source](https://github.com/elastic/kibana/blob/5e2511fc4335470cd86f7a433435fb37b5c92dbf/x-pack/plugins/security_solution/server/lib/detection_engine/routes/rules/import_rules_route.ts#L61)) ([details page correct](https://www.elastic.co/guide/en/security/current/rules-api-import.html#_request_url_14))
- [ ] <kibana host>:<port>/api/detection_engine/_export - Exports rules to an .ndjson file ([source](https://github.com/elastic/kibana/blob/5e2511fc4335470cd86f7a433435fb37b5c92dbf/x-pack/plugins/security_solution/server/lib/detection_engine/routes/rules/export_rules_route.ts#L31)) ([details page correct](https://www.elastic.co/guide/en/security/current/rules-api-export.html#_request_url_15))
- [ ] <kibana host>:<port>/api/detection_engine/prepackaged - Loads and retrieves the status of Elastic prebuilt rules ([source](https://github.com/elastic/kibana/blob/5e2511fc4335470cd86f7a433435fb37b5c92dbf/x-pack/plugins/security_solution/common/constants.ts#L222)) ([details page correct](https://www.elastic.co/guide/en/security/current/prebuilt-rules-api.html#_request_url_19))

Details page for each of the above has been verified to be correct and include `/rules/` as @MakoWish pointed out. [Postman definition](https://github.com/elastic/examples/blob/master/Security%20Analytics/SIEM-examples/Detections-API/Kibana.postman_collection.v2.json) appears to contain the correct routes as well, so looks like we're good there too 👍
