### ISSUE TITLE
[DOCS] Clarify wildcard functionality within exception & value lists

### ISSUE THREAD

**Issue by spong** [elastic/security-docs#995]
## Description 

Currently wildcards are not supported in Detection Exception or Value Lists. This has come up a few times both in the community channels and internally, and would make for a nice clarification/info callout on my main [Exceptions Doc page](https://www.elastic.co/guide/en/security/current/detections-ui-exceptions.html).

Enhancement request for adding wildcard support: https://github.com/elastic/kibana/issues/86560

**Comment by joepeeples** [comment]
Merged #1065.
